### ISSUE TITLE
Elasticsearch lock before dump

### ISSUE THREAD

**Issue by Nurza** [taskrabbit/elasticsearch-dump#104]
Hello, I use elasticdump for a while and I was wondering if it locks elasticsearch before the dump to prevent concurrency errors.

Thanks a lot!

**Comment by evantahler** [comment]
It doesn't "lock" the index or anything like that.  We use the ["Scan + Scroll"](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#scroll-search-context) technique to keep a search context alive throughout the dump, which can be thought of like a `transaction` from an RDMS, which keeps data in a consistent state over the export.
