### ISSUE TITLE
Error when dumping from local to remote

### ISSUE THREAD

**Issue by cristiboariu** [taskrabbit/elasticsearch-dump#106]
I am dumping from local to remote using existing local bloom-v2 index. (ES local and remote now is 1.5.2). If I don't create the index remotely elasticdump creates it but later when creating the mappings throws an exception:
```
{"error":"RemoteTransportException[[dwalin-2][inet[/10.0.24.13:9300]][indices:admin/create]]; nested: IndexAlreadyExistsException[[bloom-v2] already exists]; ","status":400}
```

Does anybody know why?

Command is:
```
elasticdump --input=http://localhost:9200/bloom-v2 --output=http://searchly_box/bloom-v2 --type=mapping --debug=true
```

**Comment by evantahler** [comment]
Always create the mappings first, then import your data (2 commands).  If you don't, elasticsearch will just 'guess' what type of data you are inserting, and that usually just ends up being a normal string.

**Comment by cristiboariu** [comment]
Thanks but not sure if you noticed that the command above is with type=mapping. So the above error happens when I manually create the index (bloom-v2) in my case and after that trying to export mappings from local to remote searchly box.
