### ISSUE TITLE
Improve readme doc

### ISSUE THREAD

**Issue by cristiboariu** [taskrabbit/elasticsearch-dump#107]
I spent at least 3 hours trying to understand why when trying to export from LOCAL to an AWS shared ES instance I was receiving:
```
Error Emitted => connect ETIMEDOUT
```
Basically in the end I found that if you try to export using default elasticsearch-dump infinite sockets, Amazon will block your ip immediately for a specific period of time (30 mins for my case).

The importing was starting like:
```
got 10 objects from source elasticsearch
```
but no response received so it ended with timeout.

In the end it worked if I specify:
```
--maxSockets=1
```

I think we should improve readme file because there is no clear reason for others if it happens the same.

**Comment by evantahler** [comment]
I think that's more of a specific setting based your firewall or application configuration more than a default AWS setting.  It seems that you are only allowing, perhaps, 1 request per IP?

**Comment by cristiboariu** [comment]
Yeah I think so...Basically searchly.com created my shared instance on request so I don't have too much info (like the aws admin) that's why I had so much struggle...
