### ISSUE TITLE
Bug - RoutingMissingException

### ISSUE THREAD

**Issue by cristiboariu** [taskrabbit/elasticsearch-dump#108]
When importing from LOCAL to a REMOTE output I have some children which depends on a specific type: "activities". Importing of all parents (activities) work fine but none of the children can be imported. Error:
```
{"error":"RoutingMissingException[routing is required for [bloom-v2]/[affinity]/[1592221]]","status":400}
```

I see that elasticdump nicely exported children, in my case:
```
{
   "_index":"bloom-v2",
   "_type":"affinity",
   "_id":"1592221",
   "_score":0,
   "_source":{
      "details":[
         {
            "level":3,
            "users":[
               12791
            ]
         }
      ]
   },
   "fields":{
      "_parent":"1592221",
      "_routing":"1592221"
   }
}
```

but it seems that elasticdump doesn't correctly inserts this. I suppose elasticdump use this url:
```
http://localhost:9200/bloom-v2/affinity/1592221
```
but in order for children importing to work it should also specify parent in these cases. (this works)

```
http://localhost:9200/bloom-v2/affinity/1592221?parent=1592221
```
Can you confirm that is a known bug?

**Comment by evantahler** [comment]
This will probably be solved by https://github.com/taskrabbit/elasticsearch-dump/pull/90
