### ISSUE TITLE
Export to gzip appends status line

### ISSUE THREAD

**Issue by falkorichter** [taskrabbit/elasticsearch-dump#109]
When using the documented way to export data and compress it with gzip the status line is added which makes the output file no valid JSON

```
Thu, 27 Aug 2015 13:36:24 GMT | Total Writes: 2177
```

**Comment by e100** [comment]
I see the same problem.

**Comment by evantahler** [comment]
Will be solved by https://github.com/taskrabbit/elasticsearch-dump/pull/112.  Thanks for reporting!
