### ISSUE TITLE
Transferring mappings from indices with multiple types quashes all but last type mapping

### ISSUE THREAD

**Issue by mieubrisse** [taskrabbit/elasticsearch-dump#113]
## Issue
I have several indices with multiple types per index. When I try to transfer them to another ES cluster, only the last mapping gets uploaded. This issue happens even if I dump to an intermediate file then try uploading that: the file seems to contain the mapping information for all the types, but only the mapping for the last type in the list ends up on the index.
**ES version:** 1.5.2 on both source and destination
**elasticdump version:** 0.14.4

## Repro
1. Create an index on the source ES cluster with two types, each with a mapping
2. Check the index has two mappings:
```
curl -XGET src:9200/test/_mapping
{
   "test": {
      "mappings": {
         "foo": {
            "properties": {
               "foo": {
                  "type": "string"
               }
            }
         },
         "fei": {
            "properties": {
               "first": {
                  "type": "string"
               },
               "last": {
                  "type": "string"
               },
               "middle": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```
3. Transfer the data across:
```
elasticdump --type=mapping --input=http://src:9200/test --output=http://dest:9200/test
```
4. Check the mapping on the destination:
```
curl -XGET dest:9200/test/_mapping
{
   "test": {
      "mappings": {
         "fei": {
            "properties": {
               "first": {
                  "type": "string"
               },
               "last": {
                  "type": "string"
               },
               "middle": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```

**Comment by evantahler** [comment]
Will be solved by https://github.com/taskrabbit/elasticsearch-dump/issues/113

**Comment by mieubrisse** [comment]
I'm using Elasticdump 0.16.0 and still experiencing this issue... is there a different release or something for the fix version?

**Comment by evantahler** [comment]
Can you please write a test case that fails (complete with commands to create the index)?

**Comment by evantahler** [comment]
Closing due to lack of communication
