### ISSUE TITLE
Compressing stdout

### ISSUE THREAD

**Issue by harvii** [taskrabbit/elasticsearch-dump#114]
Hello,
I'm trying to compress the console output of elasticsearch-dump directly instead of writing to a temp file and then compressing it; however, the resulting file is always incomplete.
I've tried piping the output to 7-zip and the gnuwin32 packages of gzip & bzip2, all with similar results.

I'm not sure if this is related to 'console.log' or a bigger Node issue, any help would be appreciated.

Edit: Nevermind, this is actually fixed in Node v0.12.7 (https://github.com/joyent/node/issues/3584).

Thanks

**Comment by evantahler** [comment]
Cool.  Thanks for checking.
