### ISSUE TITLE
make --bulk-use-output-index-name options default to true

### ISSUE THREAD

**Issue by 13leaf** [taskrabbit/elasticsearch-dump#116]
I've try to use elasticdump to reindex index A to index B.
But when use bulk mode,it won't work.
After read and debug code,I found this options "bulk-use-output-index-name",which not mentioned in document.
After turn on it,bulk works well.
Why this options default to false?In my opine,it should default to true.If I have specified out index,bulk use the original index is very strange.

**Comment by evantahler** [comment]
The reason it defaults to `false` is that we don't know what transport you are using.  If you are dumping to a file or stdout, you probably want to keep the original index names.  Also, when you use bulk, you are likley dumping more than one index.
