### ISSUE TITLE
Issues with console output

### ISSUE THREAD

**Issue by harvii** [taskrabbit/elasticsearch-dump#119]
A couple of issues in the console output:
1. When using the 'outputTransport' option, 'self.toLog' is not set to 'false' resulting in status logs being mixed with the data dump.
2. When using 'console.log()' in stdio.js to write to stdout, if the data has two consecutive percent chars '%%' then only one of them gets written to the console, which might have some data integrity issues; in my case, I solved this by using 'process.stdout.write([data] + '\n')' instead.

**Comment by evantahler** [comment]
I believe 1 is fixed by https://github.com/taskrabbit/elasticsearch-dump/pull/112.  If not, please provide an example. 

For 2, I'm happy changing the `console.log` calls in ["SET"](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/stdio.js#L70-L95) to `process.stdout.write`.  I'll do that in a new PR.

**Comment by evantahler** [comment]
BTW, the reason that you are losing some of the `%` chars, is that `console.log` is actually a wrapper around `process.stdout.write`, but with `util.format` in the mix.  `util.format` tries to parse strings like printf, so the `%` are getting absorbed.

- http://stackoverflow.com/questions/4976466/difference-between-process-stdout-write-and-console-log-in-node-js
- https://millermedeiros.github.io/mdoc/examples/node_api/doc/util.html#util.format

**Comment by evantahler** [comment]
solved by https://github.com/taskrabbit/elasticsearch-dump/pull/120

**Comment by harvii** [comment]
Thanks.

As for the first issue, I still get this:
```
elasticdump.cmd --input=http://localhost:9200/.kibana --type=data --limit=10000 --output=$ --outputTransport="stdio.js"

Thu, 03 Sep 2015 07:47:37 GMT | starting dump
Thu, 03 Sep 2015 07:47:37 GMT | got 2 objects from source elasticsearch (offset: 0)
[
{"_index":".kibana","_type":"config","_id":"4.0.0","_score":0,"_source":{"buildNum":5888,"defaultIndex":"[logstash-]YYYY.MM.DD"}}
,{"_index":".kibana","_type":"config","_id":"4.0.1","_score":0,"_source":{"buildNum":5930,"defaultIndex":"[logstash-]YYYY.MM.DD"}}
Thu, 03 Sep 2015 07:47:37 GMT | sent 2 objects to destination undefined, wrote 2
Thu, 03 Sep 2015 07:47:37 GMT | got 0 objects from source elasticsearch (offset: 2)
]
Thu, 03 Sep 2015 07:47:37 GMT | sent 0 objects to destination undefined, wrote 0
Thu, 03 Sep 2015 07:47:37 GMT | Total Writes: 2
Thu, 03 Sep 2015 07:47:37 GMT | dump complete
```

**Comment by evantahler** [comment]
I don't understand... where does `--outputTransport="stdio.js"` come from?  The stdio tool that ships with elasticdump is signaled with `$`

**Comment by harvii** [comment]
Actually I just used stdio.js as an example.

**Comment by evantahler** [comment]
Can you try the latest version with the proper transport, and confirm the issue remains?

**Comment by harvii** [comment]
Still there in v0.14.6; again this is only when the "custom" transport is outputting to the console, via a modified 'stdio.js'; I suppose this wouldn't be an issue if the transport was writing to a file or ES.

**Comment by evantahler** [comment]
Ahh! Yes, that makes sense now.
Will be solved by https://github.com/taskrabbit/elasticsearch-dump/pull/123
