### ISSUE TITLE
Url parsing error

### ISSUE THREAD

**Issue by ayserarmiti** [taskrabbit/elasticsearch-dump#121]
Hi All,

The package wrongly parse the elastic url in some cases. For example, if the url is like
https://127.0.0.1/prod/elasticsearch/indexname/ , then the function scrollResultSet@elasticsearch.js will assume that indexname is the field name and the string "elasticsearch" is the index name. The searchUrl in this case will be https://127.0.0.1/prod/ and not https://127.0.0.1/prod/elasticsearch/

Thanks
Ayser

**Comment by evantahler** [comment]
The tool as written assumes that we are connecting to a 'unmodified' elasticsearch server, where the root route is served by ES.  Rather then try to parse routes of arbitrary depths, I would suggest another collection of options, `--inputESRoute` and `--outputESRoute` (or similar) which default to "'`/`".

Please send in a pull request!

**Comment by kjvalencik** [comment]
Hi, I've also ran into this issue. I can provide  PR with a fix, but I was hoping for a little direction first on what you would like the arguments to look like. The two suggestions I can think of:

* Add a base route param like suggested above
* Add an --index field. If both --index and --type are provided, skip the parsing.

I think the second option would be a bit cleaner.

Cheers!

**Comment by evantahler** [comment]
`--type` is reserved for 'index' or 'mapping' right now, I think think that 'type' means the same thing in this context?

Either way, both options make sense to me... pick your flavor!

**Comment by kjvalencik** [comment]
Good call. Maybe just add `--index` which can be in the form `--index=index` or `--index=name/type`, since `--type` is already taken.

**Comment by evantahler** [comment]
I like that one!

**Comment by kjvalencik** [comment]
@evantahler Opened a PR (https://github.com/taskrabbit/elasticsearch-dump/pull/128) with the proposed flags.

The only thing that is a *little* weird is you still need to provide the `--input-index` flag even if you don't want to specify an `index` or `type`. But, using `--input-index=/` will do the trick.

**Comment by evantahler** [comment]
closing this in favor of the PR: https://github.com/taskrabbit/elasticsearch-dump/pull/128
