### ISSUE TITLE
Dump error

### ISSUE THREAD

**Issue by wbsimms** [taskrabbit/elasticsearch-dump#126]
I'm getting the following error when I dump data. (Dump of mapping works fine.)

Tue, 22 Sep 2015 19:52:43 GMT | starting dump
Tue, 22 Sep 2015 19:52:43 GMT | Error Emitted => {"_scroll_id":"c2NhbjswOzE7dG90YWxfaGl0czoxMzQyODs=","took":1,"timed_out":false,"_shards":{"total":5,"successful":0,"failed":0},"hits":{"total":13428,"max_score":0.0,"hits":[]}}
Tue, 22 Sep 2015 19:52:43 GMT | Total Writes: 0
Tue, 22 Sep 2015 19:52:43 GMT | dump ended with error (get phase) => Error: {"_scroll_id":"c2NhbjswOzE7dG90YWxfaGl0czoxMzQyODs=","took":1,"timed_out":false,"_shards":{"total":5,"successful":0,"failed":0},"hits":{"total":13428,"max_score":0.0,"hits":[]}}

Any suggestions?

**Comment by evantahler** [comment]
can you share the command you ran which caused the error?

**Comment by gsthakur** [comment]
Using the following command to input and output dump (same hostname, different index names)

elasticdump --input=http://hostname1:9200/index1 --delete --output=http://hostname1:9200/index2 --type=data --limit=100 --bulk=true --bulk-use-output-index-name

nodejs version:- v0.10.25, 
Ubuntu 15.04. 
Java build 1.8.0_45-b14
ElasticSearch version: 1.7.1

Any help? Thank you.

**Comment by evantahler** [comment]
Closing this one, no resonse from poster
