### ISSUE TITLE
dump ended with error (get phase)

### ISSUE THREAD

**Issue by gsthakur** [taskrabbit/elasticsearch-dump#129]
Trying to dump the data from one index to another (on same host). After some time, following error occurs. 

**Error Emitted => Cannot Parse: {"_scroll_id":"c2Nhbjs1OzI......**

followed by JSON text, and then ends with the following line...

**dump ended with error (get phase) => Error: Cannot Parse: {"_scroll_id":"c2Nh**

Using the following command to input and output dump (same hostname, different index names)

elasticdump --input=http://hostname1:9200/index1 --delete --output=http://hostname1:9200/index2 --type=data --limit=100 --bulk=true --bulk-use-output-index-name

nodejs version:- v0.10.25, 
Ubuntu 15.04. 
Java build 1.8.0_45-b14
ElasticSearch version: 1.7.1

Any help? Thank you.

**Comment by evantahler** [comment]
Can you share the whole error?

**Comment by evantahler** [comment]
I'm also pretty sure with bulk you don't want your base to haven an index route in the URL

**Comment by gsthakur** [comment]
Sorry, but I didn't get your second comment. The whole error

----------

Wed, 07 Oct 2015 23:28:12 GMT | starting dump
Wed, 07 Oct 2015 23:28:13 GMT | Error Emitted => Cannot Parse: {"_scroll_id":"c2Nhbjs1Ozg0NjIyOkZDNWV0bTdFU2VtbUQ2ZVMwNDQxMUE7Mjc0NTc6YkR3ZF8xMjRTeUszWHFZZktQcjJiQTsyNzQ1ODpiRHdkXzEyNFN5SzNYcVlmS1ByMmJBOzg0NjIzOkZDNWV0bTdFU2VtbUQ2ZVMwNDQxMUE7MTA1MjI5Okc3ZVdTVGJJVHNpc25fN1pSTDUyZ1E7MTt0b3RhbF9oaXRzOjQzNjY1MDExOw==","took":8,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":43665011,"max_score":0.0,"hits":[{"_index":"index1","_type":"

**followed by JSON data..  Finally,**

Wed, 07 Oct 2015 23:32:34 GMT | Total Writes: 0
Wed, 07 Oct 2015 23:32:34 GMT | dump ended with error (get phase) => Error: Cannot Parse: {"_scroll_id":"c2Nhbjs1OzI3NjE4OmJEd2RfMTI0U3lLM1hxWWZLUHIyYkE7MTA1MjMzOkc3ZVdTVGJJVHNpc25fN1pSTDUyZ1E7ODQ3ODU6RkM1ZXRtN0VTZW1tRDZlUzA0NDExQTsxMDUyMzQ6RzdlV1NUYklUc2lzbl83WlJMNTJnUTs4NDc4NDpGQzVldG03RVNlbW1ENmVTMDQ0MTFBOzE7dG90YWxfaGl0czo0MzY2NTAxMTs=","took":12,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":43665011,"max_score":0.0,"hits":[{"_index":"index1","_type":"

----------

**Comment by evantahler** [comment]
trying this locally, it works fine.  Is there perhaps a timeout hapening?  Do you have elasticsearch mounted under a sub-route?

```
> elasticdump --input=http://localhost:9200/source_index --delete --output=http://localhost:9200/new_index --type=data --limit=100 --bulk=true --bulk-use-output-index-name
Thu, 08 Oct 2015 00:26:10 GMT | starting dump
Thu, 08 Oct 2015 00:26:10 GMT | got 100 objects from source elasticsearch (offset: 0)
Thu, 08 Oct 2015 00:26:10 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 08 Oct 2015 00:26:11 GMT | got 100 objects from source elasticsearch (offset: 100)
Thu, 08 Oct 2015 00:26:11 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 08 Oct 2015 00:26:11 GMT | got 100 objects from source elasticsearch (offset: 200)
Thu, 08 Oct 2015 00:26:11 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 08 Oct 2015 00:26:11 GMT | got 100 objects from source elasticsearch (offset: 300)
Thu, 08 Oct 2015 00:26:11 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 08 Oct 2015 00:26:11 GMT | got 100 objects from source elasticsearch (offset: 400)
Thu, 08 Oct 2015 00:26:11 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 08 Oct 2015 00:26:11 GMT | got 0 objects from source elasticsearch (offset: 500)
Thu, 08 Oct 2015 00:26:11 GMT | sent 0 objects to destination elasticsearch, wrote 0
Thu, 08 Oct 2015 00:26:11 GMT | Total Writes: 500
Thu, 08 Oct 2015 00:26:11 GMT | dump complete
```

```
> elasticsearch -v
Version: 1.7.2, Build: e43676b/2015-09-14T09:49:53Z, JVM: 1.8.0_25
```

**Comment by gsthakur** [comment]
Tried with localhost also, as you had mentioned. No change in the error. 
```
> elasticsearch -v
Version: 1.7.1, Build: b88f43f/2015-07-29T09:54:16Z, JVM: 1.8.0_45
```
Thank you for your help.

**Comment by gsthakur** [comment]
I think the error occurs when elastic dump tries to input/output very large JSON document.

**Comment by evantahler** [comment]
Then try with a lower `--limit`.  In general I would expect any document over 1GB in size to be too big for this tool

**Comment by jama707** [comment]
I'm also having the same issue, I added the `--limit=10` but it is still giving the error. It's working for about 100 documents and then it's throwing parse error.

`Tue, 13 Oct 2015 21:57:44 GMT | got 0 objects from source elasticsearch (offset: 144)
Tue, 13 Oct 2015 21:57:44 GMT | dump ended with error (get phase) => Error: Cannot Parse: {"_scroll_id":"`

**Comment by evantahler** [comment]
Any data you can provide which would allow this to be reproduced would be helpful.

**Comment by gsthakur** [comment]
I will try sending some data in next 1-2 days. Basically it's tumblr blog
data collected based on a key words.

I was able to solve the problem by brute force. I.e. Extract source JSON
from elastic search and then index that document. More later. Thank you.
I'll send some data.

**Comment by jama707** [comment]
I cloned the project and tried to debug to see the error. So there is an error at lib/transports/elasticsearch.js:330 which is trying to parse an invalid JSON body.

At that line scan/scroll is retrieving documents from all indexes not from the index i specified as an input. And there are a lot of junk/invalid indexes which(I don't know how to get rid of them). 

Is there any way just look into the index which i specified as an input?

Thanks!

**Comment by evantahler** [comment]
JSON.parse *is* the fastest way to validate JSON :D

We should also be logging out the actual JSON payload that is invalid: https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L332.  Is that not the case?  Are you only getting back partial documents in the error message?   I'm not sure how to load in documents with invalid JSON to test this...

**Comment by jama707** [comment]
Yeah, right :) but it is logging whole responsebody, instead i wanted to see actual line of the JSON error.

I also don't know from where we got that invalid JSON entry in the index.

**Comment by evantahler** [comment]
To help a little bit, rather than come up with a new error message when JSON parsing fails, we can modify the actual PARSE error's `message` with the response payload, which should keep the parse information around.

https://github.com/taskrabbit/elasticsearch-dump/commit/d679213b85b40bcbc0fe573beb3d097d2505c702

**Comment by Alby1010** [comment]
Any idea regarding this errors:
1), [debug] | discovered elasticsearch output major version: 7

2), Unable to bulk upload the stats payload to the local cluster
