### ISSUE TITLE
Throttling / cluster status checking

### ISSUE THREAD

**Issue by kengruven** [taskrabbit/elasticsearch-dump#131]
I dumped my data from an ES cluster to a big JSON file, and now I'm having trouble loading it into a different cluster.  I'm told that the symptoms point to the new cluster simply not being able to keep up with the speed of the import.  (Elasticdump is too fast!)

It would be great, then, if elasticdump had the option to throttle its transfer speed.  This could either be a raw bandwidth threshold, or it could check the target cluster health between batches and wait until it's green again before sending the next batch.

**Comment by evantahler** [comment]
You have a proxy for this now with the `--limit` option.  When reading back from your file, `--limit` will control how many lines from your dump are attempted to be written to ES at once.

**Comment by kengruven** [comment]
Hi evantahler.  I'm not sure how that helps me.  I just spent several hours running an import with `--limit=10` (and giving my ES cluster way more resources than I think it ought to need), and it still can't keep up.

I could spend another day trying again with `--limit=1`, but I'm not convinced even that would be enough.  A smaller batch size is not the same thing as throttling.

**Comment by evantahler** [comment]
This tool only writes one "batch" of objects at a time.  It does no parallelization.  

Unless you want a sleep between writes (whose size is controller by the `--limit` argument), Speed is controller by disk and network I/O.  Writes are simple HTTP POST commands.  If ES takes time to ingest each write, it will be slower to respond to the POST request.  

How are you sure that ES "can't keep up"?

**Comment by kengruven** [comment]
That is literally the phrase that my host told me about my cluster.  I've pointed them to this thread, so maybe they can chime in on what exactly they mean by that.

**Comment by kengruven** [comment]
They have since told me that they don't think that is the cause of my trouble, after all.  Sorry about the confusion.
