### ISSUE TITLE
elasticdump not quite working

### ISSUE THREAD

**Issue by licral** [taskrabbit/elasticsearch-dump#134]
Hey there!

I tried installing elasticdump and it was fine after the first line, but wouldn't let me run './bin/elasticdump/'. I tried running 'elasticdump --all=true --input=...etc' but it said 'elasticdump: command not found'. Is there something I could have done wrong?

**Comment by evantahler** [comment]
Can you share your solution for future readers?

**Comment by licral** [comment]
Whoops, sorry, yup, will do now:
I ran the line 'ln -s /usr/bin/nodejs /usr/bin/node', as I am using a linux machine, so I think running this should make the shell script work. then i realised that whenever I wanted to executing something like 'elasticdump --all=true --input=...etc', i have to replace 'elasticdump' with './bin/elasticdump/', so that it would work! Hope this helps!
