### ISSUE TITLE
How to import raw JSON data to ElasticSearch using elasticsearch-dump?

### ISSUE THREAD

**Issue by xros** [taskrabbit/elasticsearch-dump#136]
For example, now I have a big raw JSON data file, **raw_data.json**. And it looks like:

> {"key1":"valueA_row_1","key2":"valueB_row_1","key3":"valueC_row_1"}
{"key1":"valueA_row_2","key2":"valueB_row_2","key3":"valueC_row_2"}
{"key1":"valueA_row_3","key2":"valueB_row_3","key3":"valueC_row_3"}
....
{"key1":"valueA_row_100","key2":"valueB_row_100","key3":"valueC_row_100"}

I want to import this file to index "myindex1", type "mytype1". 

But the schema of this raw data has not been read yet. 

Can elasticsearch-dump read this raw JSON data , generate its data schema and put it into ElasticSearch?

Thanks!

**Comment by evantahler** [comment]
Take a look at what a dumpfile looks like if you use the tool normally:

`./bin/elasticdump --input http://localhost:9200/another_index --output ~/Desktop/out.json`

```json
[
{"_index":"another_index","_type":"seeds","_id":"4","_score":0,"_source":{"key":"key4","_uuid":"4"}}
,{"_index":"another_index","_type":"seeds","_id":"11","_score":0,"_source":{"key":"key11","_uuid":"11"}}
,{"_index":"another_index","_type":"seeds","_id":"9","_score":0,"_source":{"key":"key9","_uuid":"9"}}
,{"_index":"another_index","_type":"seeds","_id":"16","_score":0,"_source":{"key":"key16","_uuid":"16"}}
,{"_index":"another_index","_type":"seeds","_id":"23","_score":0,"_source":{"key":"key23","_uuid":"23"}}

```

The data you have now would be the `"_source"` of the document.  At minimum, each document needs an `_id`, `_type`, and `_source`... IE: 

```json
[
  {"_type":"myObjectType","_id":"aaaaa","_source":{"key":"key4","_uuid":"4"}}
  , {"_type":"myObjectType","_id":"bbbb","_source":{"key":"key5","_uuid":"5"}}
]
```

Also note the array and comma syntax.

**Comment by xros** [comment]
@evantahler thank you. I dumped some docs in JSON before and it looked as  the scope of output above. But now I am looking for a tool which can automatically import my raw JSON data into elasticsearch. You referred that a text editor could add those data  `_id`, `_type`, `_source`, and I had thought that it would work. But I will have to do it by my hands. 

I was looking for a wheel before inventing a new one.

Thank you anyway!
