### ISSUE TITLE
What is the expected behavior for --ignore-errors=true

### ISSUE THREAD

**Issue by jama707** [taskrabbit/elasticsearch-dump#142]
I'm getting an error during set phase with below details:

```code = "ECONNRESET"
message = "socket hang up"```

Is that dataset won't be transferred because of that error during set phase? 
I've huge data, is there any way to configure so it won't throw that error?

Thanks!

**Comment by evantahler** [comment]
`--ignore-errors` only ignores errors in parsing or retrieval.  This kind of error, as you point out, happens at the initial connection... so I'm pretty sure the whole application will exit.
