### ISSUE TITLE
--output=/file/path ignored -- data sent to console?   

### ISSUE THREAD

**Issue by bwalsh** [taskrabbit/elasticsearch-dump#143]
## this works
```
elasticdump --all=true --input=http://192.168.99.100:9200  --input-index=/ --output=/data/mapping.json --type=mapping
```
data sent to file

## this fails
```
elasticdump --all=true --input=http://192.168.99.100:9200  --input-index=/ --output=/data/mapping.json --type=data
```
data sent to console

Am I missing something simple?

## if I redirect the output, I see this
```
Thu, 07 Jan 2016 01:40:05 GMT | Error Emitted => failed to parse json (message: "Unexpected token i")
```

**Comment by evantahler** [comment]
Looks like one of the documents in your index contains invalid JSON.  It's also unlikely that your index name is `/`, so elasticsearch is probably throwing an error.    Try dumping the data from just one index first (not the whole cluster), and see if you can narrow down the error.

**Comment by evantahler** [comment]
Closing due to lack of response
