### ISSUE TITLE
use Bulk API to populate another ES cluster --limit=10000 lost some data

### ISSUE THREAD

**Issue by sunyonggang** [taskrabbit/elasticsearch-dump#145]
These days, i want to use bulk to populate data to ES, data is about 10G, 1500w lines. When i set  --limit=10000, it shows me an error:
```
[sunyonggang@localhost ~/mygithub/elasticsearch-dump]$ bin/elasticdump --bulk=true --input=/Users/sunyonggang/mygithub/5w.json --output=http://localhost:9200/ --limit=10000
Thu, 07 Jan 2016 04:04:51 GMT | starting dump
Thu, 07 Jan 2016 04:04:51 GMT | got 10000 objects from source file (offset: 0)
Thu, 07 Jan 2016 04:04:55 GMT | sent 10000 objects to destination elasticsearch, wrote 7400
Thu, 07 Jan 2016 04:04:56 GMT | got 10000 objects from source file (offset: 10000)
Thu, 07 Jan 2016 04:04:57 GMT | sent 10000 objects to destination elasticsearch, wrote 5800
Thu, 07 Jan 2016 04:04:57 GMT | got 10000 objects from source file (offset: 20000)
Thu, 07 Jan 2016 04:04:59 GMT | sent 10000 objects to destination elasticsearch, wrote 5800
Thu, 07 Jan 2016 04:04:59 GMT | got 10000 objects from source file (offset: 30000)
Thu, 07 Jan 2016 04:05:00 GMT | sent 10000 objects to destination elasticsearch, wrote 5800
Thu, 07 Jan 2016 04:05:00 GMT | got 9999 objects from source file (offset: 40000)
Thu, 07 Jan 2016 04:05:01 GMT | sent 9999 objects to destination elasticsearch, wrote 5799
Thu, 07 Jan 2016 04:05:01 GMT | got 0 objects from source file (offset: 49999)
Thu, 07 Jan 2016 04:05:01 GMT | sent 0 objects to destination elasticsearch, wrote 0
Thu, 07 Jan 2016 04:05:01 GMT | Total Writes: 30599
Thu, 07 Jan 2016 04:05:01 GMT | dump complete
```
when i check the numbers of this index:
```
[sunyonggang@localhost ~/mygithub/elasticsearch-dump]$ curl -XGET 'http://localhost:9200/game@*/_search?pretty'
{
  "took" : 38,
  "timed_out" : false,
  "_shards" : {
    "total" : 150,
    "successful" : 150,
    "failed" : 0
  },
  "hits" : {
    "total" : 30599,
    "max_score" : 1.0,
```
infact the 5w.json should have 49999 messages instead of 30599.
Also when i set --limit=1000, it works.
so when my data is huge, how can i set this --limit properly? and does it looks a bug?

**Comment by evantahler** [comment]
Can you share that `5w.json` file?  The fact that the tool is counting the 49999 rows properly indicates that there is something wrong with the writer.  You may have an incompatible character encoding, weird line breaks, or something similar.

**Comment by sunyonggang** [comment]
yes, I'm sorry that i didn't point it 
```
[sunyonggang@localhost ~/mygithub]$ wc 5w.json
   50001  153747 33837426 5w.json

[
 {"_index":"game@2015-08-01","_type":"ufo_app","_id":"AU7m2_c481xLXMSreU-W","_score":0,"_source":{"message":"..."}}
]
```
so, you may want to know why 2 lines more, because there are '[' & ']'.

**Comment by evantahler** [comment]
I want to see the content of "message".  Are there line breaks?  Emoji?  characters that don't render on your host OS?

Try running the import with `--limit=1` and look for a line that throws an error

**Comment by sunyonggang** [comment]
there is only '\t', if you want to see it, it's ok.
```
"_source":{"message":"date=2015-08-01\ttime=01:24:11.734UTC\tloglevel=INFO \tlogger=c.z.t.Auth\tactor=akka://Titan/user/sharding/auth/669dfb1c-93b6-490e-b276-5a59662d97fe\tevent=CreateUserWithPlatformData\t\tPlatformAccount=PlatformName=Sevenga\tChannelId=1\tPlatformUID=655983\tUID=212\tctime=2015-08-01T09:24:11.713+08:00\tutime=2015-08-01T09:24:11.713+08:00","@version":"1","@timestamp":"201    5-08-01T01:24:12.143Z","host":"game1.ali","path":"/opt/game/log/server.log","type":"tyrion_app","date":"2015-08-01","time":"01:24:11.734UTC","loglevel":"INFO ","log      ger":"c.z.t.Auth","actor":"akka://Titan/user/sharding/auth/669dfb1c-93b6-490e-b276-5a59662d97fe","event":"CreateUserWithPlatformData","PlatformAccount":"PlatformNam      e=Sevenga","ChannelId":"1","PlatformUID":"655983","UID":"212","ctime":"2015-08-01T09:24:11.713+08:00","utime":"2015-08-01T09:24:11.713+08:00","_index":"logstash-2015.08.01"}}
```

**Comment by evantahler** [comment]
Fair enough.  Without seeing your data file in its entirety, there's not much help I can offer.  Good luck!

**Comment by sunyonggang** [comment]
sorry again, the file 5w.json means a file i truncate from the source file, it's about 50001 lines.
In my language, 5w means 50k, it's my fault, i thought you can understand it.
on the other hand, I just changed the '--limit' from 10k to 1k, then it works, so the error may not happened on data encoding or my OS.

**Comment by samcday** [comment]
I think this should be re-opened - pretty sure this tool is not handling rejection failures when the threadpool is exhausted. We ran into this issue today and observed that _cat/thread_pool was reporting many index threadpool rejections.

**Comment by evantahler** [comment]
If someone can provide a dataset where the error can be reproduced, I would be happy to open the issue again!

**Comment by samcday** [comment]
It's not about the dataset though, but more about the server. Bulk requests are processed in a bounded threadpool with a bounded queue. If all threads are busy working and the queue is also full, bulk requests will start getting knocked back with a rejected execution exception.

**Comment by evantahler** [comment]
Interesting. So even though we are waiting for the response to the HTTP call with the Bulk data, ES still might be processing it and reject the next request?  If that's the case, that seems like a failure of ES (normally great and strict) following of HTTP status codes... or are we forgetting to check a status code somewhere?

**Comment by sunyonggang** [comment]
maybe this can help you for these days i learned, when we upload data to ES, the response.statusCode is not so useful, you should check every 'status' is 201 to make sure all data upload to ES:
```
[sunyonggang@localhost ~]$ curl -XPOST http://localhost:9200/_bulk -T aggregation/aggtest.json -v
*   Trying ::1...
* Connected to localhost (::1) port 9200 (#0)
> POST /_bulk HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 2510
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 1433
<
* Connection #0 to host localhost left intact
{"took":126,"errors":false,"items":[{"index":{"_index":"aggtest","_type":"register","_id":"1101","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"register","_id":"1102","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"register","_id":"1201","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"register","_id":"1202","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"register","_id":"1203","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"register","_id":"1301","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1201","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1201a","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1301","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1302","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1401","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"login","_id":"1402a","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"topup","_id":"1501","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"topup","_id":"1502","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"topup","_id":"1503","_version":1,"status":201}},{"index":{"_index":"aggtest","_type":"topup","_id":"1504","_version":1,"status":201}}]}
```
also as @samcday said if you get "status":429, this can help: [Thread Pool](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html)
👻

**Comment by evantahler** [comment]
interesting @sunyonggang.  Please submit a patch to the tool so we can check for this type of thing!

**Comment by evantahler** [comment]
Anyone working on the patch?  If not, I'll close this issue

**Comment by sunyonggang** [comment]
you can close it, if i have time, maybe i will try to do it 
:smile:
