### ISSUE TITLE
File transport should not overwrite existing files

### ISSUE THREAD

**Issue by mariussoutier** [taskrabbit/elasticsearch-dump#147]
> the file transport will overwrite any existing files

This should be changed.

**Comment by evantahler** [comment]
pull requests (perhaps with new options) welcome!

**Comment by evantahler** [comment]
The current application has this behavior explicitly via: https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/file.js#L66-L67

**Comment by mariussoutier** [comment]
I don't know the first thing about Node, otherwise I'd have submitted a PR already ;)
