### ISSUE TITLE
Filter specific types?

### ISSUE THREAD

**Issue by asaf** [taskrabbit/elasticsearch-dump#154]
Hey,

It could be useful to avoid dumping a specific document type,

Thanks!

**Comment by evantahler** [comment]
I believe this already works in the simple (non-bulk) case. What version of ES do you have? Can you test it out?

**Comment by asaf** [comment]
@evantahler ES 2.1, by default I see chunks of 100 docs, so, what are the params for defining a non-bulk with filters set? thanks.
