### ISSUE TITLE
Unable to dump Index when Authentication is required

### ISSUE THREAD

**Issue by STeveShary** [taskrabbit/elasticsearch-dump#155]
We are now using Elastic's Shield plugin and it requires authentication to query the data.  I am unable to use the tool because there is no option to add username/password.

The documentation here has several examples including the Javascript one: https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_http_rest_clients_with_shield.html  There is also the ability to use basic auth.

**Comment by evantahler** [comment]
just use curl-style syntax: `elasticdump --input https://user:password@my.es.com/index ...`

**Comment by evantahler** [comment]
This is listed in the [`notes`](https://github.com/taskrabbit/elasticsearch-dump#notes) section of the readme.

**Comment by STeveShary** [comment]
Thanks.  Sorry that I missed that.

**Comment by UCSBGauchos** [comment]
My password is something like GDSDA3*0Wa99, curl can work while input will return 
undefined:1
<html>

**Comment by drizzersilverberg** [comment]
my password has '!' ,  so the comman has error `bash: !@exaditama: event not found`. how to solve this?

**Comment by djehutyy** [comment]
> My password is something like GDSDA3*0Wa99, curl can work while input will return undefined:1

Put in quotes or 'passw0rd'
