### ISSUE TITLE
Scan deprecation warning

### ISSUE THREAD

**Issue by galan** [taskrabbit/elasticsearch-dump#158]
As I can see from your generated request in `lib/transports/elasticsearch.js` you are using the `search_type=scan` which is [deprecated since elasticsearch 2.1](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_21_search_changes.html), and probably will not work in future versions (documentation says from 3.x on).

You might want to add a version check and switch the behaviour of the export for [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-request-scroll.html).

**Comment by evantahler** [comment]
Good catch!

Does anyone want to tackle this?

**Comment by slackboxster** [comment]
This is now definitely broken for elasticsearch 5.0.

**Comment by evantahler** [comment]
Great! 
Someone on this thread please fix it!   

Let me know if you need any help getting started.

**Comment by evantahler** [comment]
Closing in favor of the PR above
