### ISSUE TITLE
Index naming issue while using bulk

### ISSUE THREAD

**Issue by orweinberger** [taskrabbit/elasticsearch-dump#159]
When I try using the `--bulk=true` flag, I cannot import data to a different index name.

For example, running this:

```
elasticdump --input=http://localhost:9200/oldindex --output=http://otherhost:9200/newindex --type=data --bulk=true --limit=1000
```

Will create an `oldindex` index on `otherhost` instead of creating `newindex` on `otherhost`. However, if I remove the `--bulk=true` flag everything works correctly.

**Comment by evantahler** [comment]
That's the expected behavior.  The `bluk` action is meant to move documents as they are, keeping the index and type intact.  Without bulk, we can inspect and modify each document as we pass it to the output, and do things like modify the index.
