### ISSUE TITLE
process out of memory error during restore

### ISSUE THREAD

**Issue by pgraziano** [taskrabbit/elasticsearch-dump#163]
I have a backup which I created with ``elasticsearch-dump`` a couple of weeks ago.  The file is 114M in size with 19,644 lines.  When I try to restore I get an out of memory error (details below). 

**The command and error message:**

```
root@el:/tmp# elasticdump --input=elasticdump-data.json --output=http://el:9200/snag
Fri, 12 Feb 2016 20:08:04 GMT | starting dump

<--- Last few GCs --->

   17046 ms: Mark-sweep 1371.4 (1457.9) -> 1371.5 (1457.9) MB, 2295.5 / 0 ms [allocation failure] [GC in old space requested].
   19388 ms: Mark-sweep 1371.5 (1457.9) -> 1371.5 (1457.9) MB, 2341.1 / 0 ms [allocation failure] [GC in old space requested].
   21606 ms: Mark-sweep 1371.5 (1457.9) -> 1371.4 (1457.9) MB, 2217.9 / 0 ms [last resort gc].
   23809 ms: Mark-sweep 1371.4 (1457.9) -> 1371.4 (1457.9) MB, 2202.8 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3da753eb4629 <JS Object>
    2: write [/usr/lib/node_modules/elasticdump/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:92] [pc=0x17e4bdf0dc18] (this=0x3f608e8fe121 <a Parser with map 0x44dd658d3d9>,buffer=0x110980f3bb1 <an Uint8Array with map 0x44dd658c721>)
    3: /* anonymous */ [/usr/lib/node_modules/elasticdump/node_modules/JSONStream/index.js:~18] [pc=0x17e4bdf28026] (this=0x3f608e8fe299 <a Stream wi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

**My server's specs:**

* 16GB RAM
* 8-cores

**Version of elasticsearch:**

```
{
  "name" : "Pretty Persuasions",
  "cluster_name" : "production",
  "version" : {
    "number" : "2.2.0",
    "build_hash" : "8ff36d139e16f8720f2947ef62c8167a888992fe",
    "build_timestamp" : "2016-01-27T13:32:39Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Version of elasticdump:**

```
root@el:/tmp# npm view elasticdump version
1.0.1
```

**Comment by evantahler** [comment]
We did recently change the format of the dump files.  Can you confirm that your dump is using the new version?  (no starting `[` and lines don't start with `,`)

**Comment by pgraziano** [comment]
Changing the json to the new format as you described did the trick.  However, please consider throwing an invalid data exception rather than an "out of memory" exception.  I spent more time than I'd like to admit troubleshooting a lack of memory issue, which clearly was not the issue at all.

**Comment by evantahler** [comment]
It's not quite that simple... Node is actually tying to JSON parse your whole file in this case, which is a sync operation. 

If you want to test the file format in a non-JSON way, like checking for the first char or something, that might work.   Send in a PR!

**Comment by evantahler** [comment]
note added => https://github.com/taskrabbit/elasticsearch-dump/commit/f79ea40c0b1fe1701b2fe27921f3a96dbb5a5a8b

**Comment by ribbles** [comment]
I was able to import old backups that are 1GB+ by passing the files though [jq](https://stedolan.github.io/jq/), stripping the array braces and commas:

```bash
$ jq -cr '.[]' backup.json > backup2.json
```

**Comment by evantahler** [comment]
nice @ribbles

**Comment by kirantlr** [comment]
Thanks @ribbles, You saved my life!!
