### ISSUE TITLE
"Routing is required"

### ISSUE THREAD

**Issue by gnujeremie** [taskrabbit/elasticsearch-dump#166]
Hello,
I'm trying to import data from a file generated with elasticdump. There are parent-child relations, I can see the "_parent" and "_routing" fields in the generated json, but when I try to import them with
```
elasticdump  --input=data.json --output=http://elastic:9200/indexname
```
Nothing is written. In ES logs, I can see "routing is required". Did I miss something ? I saw several issues about parent/child and elasticdump, but it seemed like it worked.

Thanks.

**Comment by evantahler** [comment]
Do you have custom routing on your source index?  Did you export (and load in) the mapping first?

**Comment by gnujeremie** [comment]
What do you mean about custom routing ?
And yes, I exported and then imported the mapping first.

**Comment by gnujeremie** [comment]
Looking at line https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L264, it seems your are looking for "parent" and "routing" fields. The json generated by my dump (with elasticdump) has "_parent" and "_routing" fields, could it be the issue ?

**Comment by gnujeremie** [comment]
Maybe related to #108 ?

**Comment by evantahler** [comment]
good detective work!
Send in a pull request with your changes, so we can get this updated!

**Comment by evantahler** [comment]
I would also be useful if you could update the `.travis.yml` build matrix so we can test with elasticsearch v1.x and v2.x

**Comment by gnujeremie** [comment]
Ok, I'll see what I can do this week end (or sooner if I can)

Glad I could help :+1:

**Comment by evantahler** [comment]
any update?

**Comment by gnujeremie** [comment]
Sorry I didn't take the time to fix it and I didn't get the notifications for your message, I'll let you know as soon as it's done!
