### ISSUE TITLE
Will not overwrite file if it exists

### ISSUE THREAD

**Issue by bretd25** [taskrabbit/elasticsearch-dump#170]
My understanding is if a file already exists it should just overwrite.  I am receiving this error message when trying to overwrite a file.

Tue, 23 Feb 2016 20:46:57 GMT | starting dump
Tue, 23 Feb 2016 20:46:57 GMT | got 1 objects from source elasticsearch (offset: 0)
Tue, 23 Feb 2016 20:46:57 GMT | Error Emitted => File `/usr/data/car.json` already exists, quitting
Tue, 23 Feb 2016 20:46:57 GMT | Total Writes: 0
Tue, 23 Feb 2016 20:46:57 GMT | dump ended with error (set phase)  => Error: File `/usr/data/car.json` already exists, quitting

Thanks,

Bret

**Comment by evantahler** [comment]
We changed this behavior (safety++)  in v1 https://github.com/taskrabbit/elasticsearch-dump/releases/tag/v1.0.0

It looks like we forgot to update the README, which I've done here https://github.com/taskrabbit/elasticsearch-dump/commit/8aa9b7c37f579fc31c5997ff676873e17587f960

**Comment by bretd25** [comment]
Thank you
