### ISSUE TITLE
Part of index data lost while importing data

### ISSUE THREAD

**Issue by snowwolf007cn** [taskrabbit/elasticsearch-dump#175]
I export an index from cluster A to a file. I use _wc -l_ to caculate the lines exported, which is the same with docs stored in cluster A. After that, I import data from file to another cluster B and found that about 100 docs are missing.

How to trace the problem and have it fixed?

**Comment by evantahler** [comment]
Some thoughts: 
Do you have duplicate events?  Do you have un-serializable (binary) data?  Is the text-encoding of all systems involved the same?  Were there any errors?

**Comment by snowwolf007cn** [comment]
1、They are logs stored in ES, which may have duplicated entries, i.e, same error occurred in the same time. but I don't think it's the problem, because the dump file stored data in JSON.
2、We have binary data in some field, but they are imported into cluster B properly.
3、They are all properly encoded.
4、I don't see any errors occur.

**Comment by evantahler** [comment]
The only thing I can think of would be the duplicates.  If you have "fully" duplicated data (same `_id`), when its re-inserted, it would be an update, not a new document

**Comment by snowwolf007cn** [comment]
I dump the data to a file from origin cluster, there couldn't be duplicated data with same _id.

**Comment by evantahler** [comment]
Then I have no idea, sorry.
We'll leave this issue open if someone else has any thoughts.

**Comment by evantahler** [comment]
This looks to be related to https://github.com/taskrabbit/elasticsearch-dump/pull/194
