### ISSUE TITLE
reading and dumping to another index

### ISSUE THREAD

**Issue by jrots** [taskrabbit/elasticsearch-dump#176]
Hi, 
Would like to know what the best approach is to do the following:
if you have an index that has around 50M entries and you want to move the data to another index, 
you could start elasticdump as: 

> elasticdump --debug --input="http://localhost:9200/inputindex" --output="http://localhost:9200/outputindex" --bulk-mode="create" --bulk --bulk-use-output-index-name --limit 15000 

But there are some issues with this: 
Will take sometimes a few hours to complete and if the inputindex gets updates in the meanwhile you wont get the consistent state in the outputindex..

Is the best approach here to keep track of the changes happening in the inputindex when you start the dump and replay them afterwards? 

Would be nice if such functionality was built in in elasticdump or made very clear in the documentation that you will get inconsistent states if you don't take care of this

**Comment by evantahler** [comment]
Actually, you won't get inconsistent data, but you will preserve the snapshot of the data at the timestamp when you stated the dump.  Under the hood we use the [scan and scroll](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/scan-scroll.html) API to ensure this state is maintained.

**Comment by evantahler** [comment]
I've clarified the section in the readme about this
