### ISSUE TITLE
Bulk Data Transfer broken on ES 2.1.1?

### ISSUE THREAD

**Issue by booherbg** [taskrabbit/elasticsearch-dump#177]
I'm using the --bulk option, but it doesn't seem to work. When I don't use the bulk option, data transfers (but very slowly). With --bulk, I can see no documents get transferred (via Kibana), even though the elasticsearch-dump says it wrote them all. In my ES log I see: 

```
ElasticsearchParseException[failed to parse source for create index]; nested: JsonParseException[Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: [B@252a9595; line: 9, column: 18]];
```

Here is my ES version:
```
{
  "name" : "trakit-staging01",
  "cluster_name" : "trakit-staging",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

Thoughts?

**Comment by evantahler** [comment]
Can you please provide some sample documents and index to recreate this?

**Comment by giocaputo** [comment]
I have same problem.
elasticdump --bulk=true --input=./data/production_searchproduct_data.json --output=http://{ip_address}:9200/searchproduct/ --type=data

--I have this message 
Wed, 13 Apr 2016 07:24:47 GMT | starting dump
Wed, 13 Apr 2016 07:24:47 GMT | got 100 objects from source file (offset: 0)
Wed, 13 Apr 2016 07:24:49 GMT | sent 100 objects to destination elasticsearch, wrote 100
Wed, 13 Apr 2016 07:24:49 GMT | got 117 objects from source file (offset: 100)
Wed, 13 Apr 2016 07:24:53 GMT | sent 117 objects to destination elasticsearch, wrote 117

but the new index is empty

while with elasticdump --input=./data/production_searchproduct_data.json --output=http://{ip_address}/searchproduct/ --type=data
it works correctly

**Comment by evantahler** [comment]
Ok, I'm going to remove bulk mode entirely.  It's been buggy for a long time, and no one seems to have the time to fix it.  

Closed by https://github.com/taskrabbit/elasticsearch-dump/pull/191
