### ISSUE TITLE
Is there a upper limit for dump the index?

### ISSUE THREAD

**Issue by sunvssoongit** [taskrabbit/elasticsearch-dump#181]
I use the way like 
elasticdump --input=http://xxx/index1--output=http://xxx/index2 --maxSockets=5 --type=data --limit=300

it just quit around 85,000 docs dumped. And there is exceptions or errors, just like it normal completed the execution and exit. Actually, we have around 300,000 docs need to be dumped. 

Thanks for any advice!

**Comment by evantahler** [comment]
I think you are looking for the `skip` option? You can also write a `search` query about what to extract.

**Comment by sunvssoongit** [comment]
If use the skip option, does that mean I may not get 100% totally same data?

**Comment by evantahler** [comment]
Yes it does.  The sort order of the result set cannot be gaurnteed... unless you happen to have a field all documents have (like `created_at`) which you can sort by in a custom `search`

**Comment by sunvssoongit** [comment]
Thanks a lot, man.
