### ISSUE TITLE
support parent-child index

### ISSUE THREAD

**Issue by huangfushun** [taskrabbit/elasticsearch-dump#182]
backup data works fine, but only can restore parent data , if I try  to  restore the child data,
it did nothing:
`Thu, 24 Mar 2016 12:10:34 GMT | starting dump`
`Thu, 24 Mar 2016 12:10:34 GMT | got 5 objects from source file (offset: 0)`
`Thu, 24 Mar 2016 12:10:34 GMT | sent 5 objects to destination elasticsearch, wrote 0`
`Thu, 24 Mar 2016 12:10:34 GMT | got 0 objects from source file (offset: 5)`
`Thu, 24 Mar 2016 12:10:34 GMT | Total Writes: 0`
`Thu, 24 Mar 2016 12:10:34 GMT | dump complete`

to insert child data, elasticsearch (2.2.x)  need explicitly set child id and parent id on the uri path, this may need extra effort  to make it work.

**Comment by evantahler** [comment]
Added to the milestone https://github.com/taskrabbit/elasticsearch-dump/milestones/Elasticsearch%202.0%20compatibility

Pull requests welcome!

**Comment by gnujeremie** [comment]
Maybe related to #166 ?

**Comment by evantahler** [comment]
will be closed by https://github.com/taskrabbit/elasticsearch-dump/pull/202
