### ISSUE TITLE
Long Overflow

### ISSUE THREAD

**Issue by zeroly** [taskrabbit/elasticsearch-dump#184]
GenreRankID is long and equal _id
"_id":"-6078848508545849313","_score":0,"_source":{"GenreRankID":-6078848508545849000,
"_id":"7160458942796583043","_score":0,"_source":{"GenreRankID":7160458942796583000,

**Comment by evantahler** [comment]
so... what's the problem?  Please provide more details and some test data we can reproduce the problem with

**Comment by zeroly** [comment]
Sorry, my English is poor.
http://stackoverflow.com/a/17320771
