### ISSUE TITLE
`Error: unable to verify the first certificate` when trying to dump the data to another cluster

### ISSUE THREAD

**Issue by jpibarra1130** [taskrabbit/elasticsearch-dump#186]
Hello,

I'm getting this error when I try to copy from one host to another:

> Wed, 06 Apr 2016 05:15:26 GMT | starting dump
> Wed, 06 Apr 2016 05:15:28 GMT | Error Emitted => unable to verify the first certificate
> Wed, 06 Apr 2016 05:15:28 GMT | Total Writes: 0
> Wed, 06 Apr 2016 05:15:28 GMT | dump ended with error (get phase) => Error: unable to verify the first certificate

I reckon it's because of the certificate of the input cluster. Is there a way right now to bypass the certificate verification like the `-k` option in curl?

**Comment by evantahler** [comment]
try some of the options discussed here http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by jpibarra1130** [comment]
@evantahler cool, thanks. I was initially wondering whether there's a builtin option in here for that. 

If anyone ended up here looking for a solution for this, I ended up using this:

`export NODE_TLS_REJECT_UNAUTHORIZED=0`
