### ISSUE TITLE
Dumping a percolator index results in no data

### ISSUE THREAD

**Issue by infoprofs** [taskrabbit/elasticsearch-dump#187]
Hi,

I have a percolator index on my ES server. I can dump other indices fine without issues, but the percolator index not. No data gets dumped at all.

```
$ elasticdump --input=http://172.17.0.13:9200/percolator-index --output=/percolator-index_data.json --type=data

Fri, 08 Apr 2016 13:12:05 GMT | starting dump
Fri, 08 Apr 2016 13:12:05 GMT | got 0 objects from source elasticsearch (offset: 0)
Fri, 08 Apr 2016 13:12:05 GMT | Total Writes: 0
Fri, 08 Apr 2016 13:12:05 GMT | dump complete
```

I have 4200+ entries in the percolator index, i.e. when searching:
```
Searched 30 of 30 shards. 4238 hits. 0.005 seconds
```

Dumping of the mapping works fine:

```
$ elasticdump --input=http://172.17.0.13:9200/percolator-index --output=/percolator-index_data.json --type=mapping

Fri, 08 Apr 2016 13:12:06 GMT | starting dump
Fri, 08 Apr 2016 13:12:06 GMT | got 1 objects from source elasticsearch (offset: 0)
Fri, 08 Apr 2016 13:12:06 GMT | sent 1 objects to destination file, wrote 1
Fri, 08 Apr 2016 13:12:06 GMT | got 0 objects from source elasticsearch (offset: 1)
Fri, 08 Apr 2016 13:12:06 GMT | Total Writes: 1
Fri, 08 Apr 2016 13:12:06 GMT | dump complete
```

How can I dump percolator type indices? Or is this not supported?

**Comment by evantahler** [comment]
I haven't seen anyone try before! We certainly have no tests for it.  If you can create a failing test (in a pull request) that we can work off, that would be a good place to start.

**Comment by infoprofs** [comment]
I will when I have a little more time on my hands.

**Comment by kjvalencik** [comment]
Including `.percolator` in the `--input` line seemed to work for me. E.g.,

```bash
$ elasticdump --input=http://172.17.0.13:9200/percolator-index/.percolator --output=/percolator-index_data.json --type=data
```

You should *not* include the type as part of restore.

**Comment by evantahler** [comment]
@kjvalencik can you add a note about this to the readme?

**Comment by infoprofs** [comment]
Ah great. I just figured adding .percolator out myself after some searching in this index, but glad you found this out.

**Comment by evantahler** [comment]
Can one of you please create a pull request for adding a note about this to the README?
