### ISSUE TITLE
Compatible with ElasticSearch 2.2.0?

### ISSUE THREAD

**Issue by XUJiahua** [taskrabbit/elasticsearch-dump#188]
Hello,

I ran the command, but nothing happened. What would cause this issue?

**Comment by evantahler** [comment]
You'll need to share more detail than that... what was the command?   Were any messages logged?

**Comment by XUJiahua** [comment]
For example,

```
elasticdump --input=http://127.0.0.1:9200/cloudapp-2016.04.08 --output=/home/webapp/cloudapp_mapping.json --type=mapping
elasticdump --input=http://127.0.0.1:9200/cloudapp-2016.04.08 --output=/home/webapp/cloudapp_data.json --type=data

```

but nothing happened, no output, no err.

**Comment by evantahler** [comment]
are you sure you have elasticdump installed? `which elasticdump` should return the path...

**Comment by XUJiahua** [comment]
installed at /usr/local/bin/elasticdump

Below is how I install:
```
sudo apt-get install npm
sudo npm install elasticdump -g
sudo apt-get install node
```

**Comment by evantahler** [comment]
the version of node.js which ships with ubuntu (v0.10) is incompatible with this project.  Node v1.0.0 or higher is required. 

https://github.com/taskrabbit/elasticsearch-dump/blob/master/package.json#L13-L15
