### ISSUE TITLE
elasticdump: can't working throw linux pipes

### ISSUE THREAD

**Issue by vananiev** [taskrabbit/elasticsearch-dump#192]
Hello,

I have index with 210600 doc,
when i do
```
elasticdump --input=http://localhost:9200/test \
--output=$ | pv -l -s 210600 | wc -l
 211k 0:01:33 [2,24k/s] [===============================>] 100%
210600
```
i get all of the Docs, but when i set --limit
```
elasticdump --input=http://localhost:9200/test \
--limit=1000000 --output=$ | pv -l -s 210600 | wc -l
  24k 0:00:35 [ 684/s ] [============>               ] 11%
23998
```

i get only ~24kDocs, 89% of docs is lost .

Again when i set limit, but using redirecting
```
$elasticdump --input=http://localhost:9200/test \
 --limit=1000000 --output=$ > /tmp/1.json
$ wc -l /tmp/1.json
210600 /tmp/1
```
all docs was downloaded.
Now i test pipe, maybe deal goes wrong here
```
 cat /tmp/1.json | pv -l -s 210600 | wc -l
 211k 0:00:04 [  46k/s] [=====================>] 100%
210600
```
but all docs was go throw the pipe.

So, maybe elasticdump close pipe early (when one bit of data too big) before all docs is reading by reader util?

I need to use pipe for splitting output files.

**Comment by vananiev** [comment]
Write util do not need to exit() while all data is not read. Prove it.

```
time { echo {1..1000000} | tr ' ' '\n'; echo -e "end \n" >&2; } >/dev/null
end
real    0m1.989s
user    0m1.785s
sys     0m0.238s
```
No i set 15 seconds sleep before reader start, so all data write can already happen.
```
time { echo {1..1000000} | tr ' ' '\n'; echo -e "end writing\n" >&2; } | \
pv -N "       " | \
{ sleep 15; echo -e "go reading\n" >&2; while read l; do echo $l; done; } | wc -l

      :   64kB 0:00:14 [   0B/s ] [  <==>       ]
go reading
     : 6,31MB 0:00:30 [ 437kB/s] [     <=>                  ]
end writing
         : 6,57MB 0:00:30 [ 219kB/s] [       <=>                  ]
1000000
```
We can se what reader write 64 kB to pipe (this is pipe buffer size for linux), when blocked until reader start read data. So all data passed to reader.

Elasticdump instead of blokinf exiting.

**Comment by vananiev** [comment]
Also i get error occured to writing pipe
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:767:14)
```

**Comment by evantahler** [comment]
This is some great research... can you provide a pull request to fix this?   
The file write code is fairly simple: https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/file.js#L35-L82

You also may have identified a bug with [jsonstream](https://github.com/dominictarr/JSONStream).  Can you test upgrading this project to use the latest version, and see if that helps?

**Comment by evantahler** [comment]
https://github.com/taskrabbit/elasticsearch-dump/pull/195

**Comment by vananiev** [comment]
Yesterday I upgrade elasticdump to version 2.0.0, it loose docs too.

**Comment by evantahler** [comment]
v2.0.1 is the version with the above fix

**Comment by vananiev** [comment]
ok, i test it in my environment. Thanks)

**Comment by vananiev** [comment]
Test results in my env
```
# elasticdump --input=http://localhost:9200/test --limit=10000 --output=$ | pv -l -s 501278 | wc -l
 501k 0:00:28 [17,9k/s] [=================================================================>] 100%
501278

# elasticdump --input=http://localhost:9200/test --limit=100000 --output=$ | pv -l -s 501278 | wc -l
 259k 0:00:17 [14,8k/s] [================================================>                    ] 51%
258991

]# elasticdump --input=http://localhost:9200/test --limit=1000000 --output=$ | pv -l -s 501278 | wc -l
 2,3k 0:00:23 [97,1/s ] [>                                                                ]  0%
2301
```
So --limit yet lead to lose docs.

**Comment by evantahler** [comment]
Are you using elasticsearch version 2.x?  Is this related?  https://github.com/taskrabbit/elasticsearch-dump/pull/194

**Comment by evantahler** [comment]
Closing until we have more detail.
In the future, please provide your OS (name/version), elasticsearch version, etc.

**Comment by vananiev** [comment]
I'm using elasticsearch-2.0.1, CentOS 6.7.
