### ISSUE TITLE
Error: dump ended with error (set phase)  => Error: connect EMFILE

### ISSUE THREAD

**Issue by marianogg9** [taskrabbit/elasticsearch-dump#193]
Hi there.
I'm trying to upload a previous dump I got from another ES (production) cluster from a file to my staging ES. Thing is, I've run into this same error twice now using the following command:

`$ ./bin/elasticdump --all=true --limit=6000 --input=es-prod-dump.json --output=https://es-staging-cluster_url`

At certain point (let's say after several hours, still haven't found a pattern) the command will end and outputs the following error:

```
Thu, 14 Apr 2016 01:47:19 GMT | got 6140 objects from source file (offset: 12794094)
Thu, 14 Apr 2016 01:48:47 GMT | Error Emitted => connect EMFILE <IP>:443 - Local (undefined:undefined)
Thu, 14 Apr 2016 01:48:47 GMT | Total Writes: 9442347
Thu, 14 Apr 2016 01:48:47 GMT | dump ended with error (set phase)  => Error: connect EMFILE <IP>:443 - Local (undefined:undefined)
```

Any ideas why? EMFILE looks like a socket or ulimit error, but still not sure if this is the case.

More info:
- There're about 45 million records in the input json file (the prod cluster is about 5GB).
- I'm using "screen" to detach this huge upload process and avoid any session timeout.
- The dump process worked just fine with a limit=10000, the "upload" won't allow anything above 6000 (also, don't know how or why this happens).
- The instance I'm running elasticdump from is placed on the same region than staging ES.
- CentOS 7.
- First error was at ~2 million records, the second one (from the example before) around 9 millions.

Thanks!

**Comment by vananiev** [comment]
I yet get same error and want to make issue.

I run
`zcat test.json.gz | elasticdump         --output=http://hollywood1:9200/test  --input=$ --limit=10000`
and got
```
Thu, 14 Apr 2016 13:18:29 GMT | starting dump
Thu, 14 Apr 2016 13:18:30 GMT | got 10000 objects from source file (offset: 0)
Thu, 14 Apr 2016 13:18:38 GMT | Error Emitted => connect EMFILE 192.168.135.151:9200 - Local (undefined:undefined)
Thu, 14 Apr 2016 13:18:38 GMT | Total Writes: 0
Thu, 14 Apr 2016 13:18:38 GMT | dump ended with error (set phase)  => Error: connect EMFILE 192.168.135.151:9200 - Local (undefined:undefined)
parallel: Starting no more jobs. Waiting for 1 jobs to finish. This job failed:
```
When I decreasing --limit <= 1000 when elasticdump works fine.

Elasticdump is a best utility, hope it will be best in future too.

Thanks.

**Comment by evantahler** [comment]
yep `EMFILE ` is an error from your OS saying that node cannot get more sockets.   You can change your OS' ulimits or something to help with this.

**Comment by vananiev** [comment]
My ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 257452
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 257452
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
What parameter I shoukd change? (May by open files? Why elasticdup require so much open files?)

**Comment by marianogg9** [comment]
@vananiev what you can do is raise up your "open files" value by editing /etc/security/limits.conf. Check this link: https://easyengine.io/tutorials/linux/increase-open-files-limit/
You'll need to re-login and try again. Also you can try by using "--timeout" option for elasticdump command line. I've played around with those values to solve the issue.

Hope that helps.
Cheers!

**Comment by vananiev** [comment]
I run
`cat test.json | elasticdump --input=$ --output=http://localhost:9200/test --limit=10000`
limit
`ulimit -n 10000`
don't help. I set limit `ulimit -n 10100` and this limit helps.
When i running
`cat test.json | elasticdump --input=$ --output=http://localhost:9200/test --limit=20000`
And with limit 20000 I also get error EMFILE. When I increse it to 20100 and command end with success.

Looks like mote --limit you set, more `ulimit -n NUM` you should set, it's enough --limit be less smaller then ulimit -n.

**Comment by evantahler** [comment]
Are you running elasticdump on the same server as elasticsearch?  I'm still 90% sure that elasticdump shoudn't need any more open sockets regardless of the # files requested via the `limit`... it's still one HTTP call/response... it's just larger. However, Elasticsearch itself may be doing some work under the hood which increases linearly with the request response volume.

**Comment by vananiev** [comment]
Yes I do request on the same host as elasticsearch, but elasticsearch started by elasticsearch user, my limits.conf is
```
elasticsearch soft nofile 500000
elasticsearch hard nofile 500000
```

**Comment by evantahler** [comment]
I'm not sure what to say.  No one else has reported an issue like this, and I can't reproduce it.   Hopefully someone else can chime in with advice

**Comment by debovis** [comment]
I just ran into the same issue, due to the size of my ES documents. My solution was limiting the size of the dump, i.e. --limit 5, worked for me.
