### ISSUE TITLE
elasticdump nothing written

### ISSUE THREAD

**Issue by daranday** [taskrabbit/elasticsearch-dump#196]
Hi.
I started an elasticsearch server, then I tried to dump some data into the server from a file. But no matter what I have in the file, elasticdump always say found 1 object, writing 0.

Here's my file data.json:

[
{"_index":"destination_index","_type":"seeds","_id":"4","_score":0,"_source":{"key":"key4","_uuid":"4"}}
,{"_index":"destination_index","_type":"seeds","_id":"11","_score":0,"_source":{"key":"key1","_uuid":"1"}}
,{"_index":"destination_index","_type":"seeds","_id":"0","_score":0,"_source":{"key":"key0","_uuid":"0"}}
,{"_index":"destination_index","_type":"seeds","_id":"12","_score":0,"_source":{"key":"key2","_uuid":"2"}}
,{"_index":"destination_index","_type":"seeds","_id":"1","_score":0,"_source":{"key":"key1","_uuid":"1"}}
,{"_index":"destination_index","_type":"seeds","_id":"13","_score":0,"_source":{"key":"key3","_uuid":"3"}}
,{"_index":"destination_index","_type":"seeds","_id":"2","_score":0,"_source":{"key":"key2","_uuid":"2"}}
,{"_index":"destination_index","_type":"seeds","_id":"14","_score":0,"_source":{"key":"key4","_uuid":"4"}}
,{"_index":"destination_index","_type":"seeds","_id":"3","_score":0,"_source":{"key":"key3","_uuid":"3"}}
,{"_index":"destination_index","_type":"seeds","_id":"10","_score":0,"_source":{"key":"key0","_uuid":"0"}}
]

Here's my command:

elasticdump --input data.json --output "http://localhost:9200" --bulk

Here's the output:

{"acknowledged":true}{"acknowledged":true}Sat, 16 Apr 2016 04:08:46 GMT | starting dump
Sat, 16 Apr 2016 04:08:46 GMT | got 1 objects from source file (offset: 0)
Sat, 16 Apr 2016 04:08:46 GMT | sent 1 objects to destination elasticsearch, wrote 0
Sat, 16 Apr 2016 04:08:46 GMT | got 0 objects from source file (offset: 1)
Sat, 16 Apr 2016 04:08:46 GMT | Total Writes: 0
Sat, 16 Apr 2016 04:08:46 GMT | dump complete

Then I tried to query destination_index:

curl -XPOST 'http://localhost:9200/destination_index/_search?pretty'

Output:

{
  "took" : 47,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

**Comment by evantahler** [comment]
We have removed the `bulk` options, as they were buggy.  Please use the latest version.

We are also working though some problems with ES version 2, which you can follow here https://github.com/taskrabbit/elasticsearch-dump/milestones/Elasticsearch%202.0%20compatibility
