### ISSUE TITLE
Is there a default value for "timeout" option?

### ISSUE THREAD

**Issue by marianogg9** [taskrabbit/elasticsearch-dump#197]
Hi there.
I'm wondering if there's a default timeout for the connection?

running:
`./bin/elasticdump --all=true --limit=6000 --input=file.json --output=<new_es_url>`

output:
Sun, 17 Apr 2016 04:45:09 GMT | Error Emitted => read ETIMEDOUT
Sun, 17 Apr 2016 04:45:09 GMT | Total Writes: 18687
Sun, 17 Apr 2016 04:45:09 GMT | dump ended with error (set phase)  => Error: read ETIMEDOUT

The .json I'm using as input is around 9GB (yes, it's a pretty populated cluster). 

Also:
- Is there any limit for .json input file size?
- Is there a top value for "limit" for "upload" process (from json to ES)?

Thanks!

**Comment by evantahler** [comment]
There's a good explanation of this error here: http://stackoverflow.com/questions/23632914/how-to-handle-etimedout-error.  I think the default is something like 30s, and as you hint at, this timeout is per "batch"... so lowering your limit may help here.   The batch you get from the input is the same as passed to the output, we do this in serial. 

There are no file-size limits. 

You can also change the time limit for this timeout in the underlying request module.  It would be a simple addition... please submit a pull request with this change (and let me know if you need help getting started)

**Comment by evantahler** [comment]
Oh... We already have `--timeout` as an option!

That's what you would need to use :D

**Comment by marianogg9** [comment]
Thanks @evantahler that seems to do the trick!
