### ISSUE TITLE
Problem : data not wrote in elasticsearch

### ISSUE THREAD

**Issue by CerqueiraVictor** [taskrabbit/elasticsearch-dump#203]
Hey,
I'm trying to load a json file in elasticdump. 

I execute this command line
**elasticdump --bulk=true --input="/home/exploi/kibana/zips.json" --output=http://localhost:9200/zips --type=data**

The data is sent but not write on elasticsearch

**Tue, 19 Apr 2016 15:44:26 GMT | got 603 objects from source file (offset: 697)
Tue, 19 Apr 2016 15:44:43 GMT | sent 603 objects to destination elasticsearch, wrote 0**

Have you any idea

**Comment by evantahler** [comment]
`bulk` mode was just removed in recent versions, as it was known to be buggy.  We are also working on fixing some bugs with elasticsearch v2.   https://github.com/taskrabbit/elasticsearch-dump/pull/202

**Comment by KarimJedda** [comment]
Thanks a lot, this wasted 4 hours of my life. 👍

**Comment by axinlin** [comment]
maybe you shoud upgrade your elasticdump and upgrade your nodejs version
