### ISSUE TITLE
Bring back --bulk option

### ISSUE THREAD

**Issue by paullovessearch** [taskrabbit/elasticsearch-dump#205]
(removing `--bulk` options) Which renders it unusable for my application. Sorry.

**Comment by evantahler** [comment]
Now that we are operating from a place of stability, I'm open to the `bulk` options coming back.  Some changes will be needed from how it worked before, primarily around logging, ensure writes confirm before sending the next chunk, and ensuring it is only a "write" option.

Pull requests welcome! 

---
renamed title.

**Comment by paullovessearch** [comment]
No problem, I downgraded to elasticdump@1.1.4

Timing:
•	Without --bulk:  78 DPS
•	With --bulk:  286 DPS
•	With --bulk and --limit=500:  740 DPS

We have 9+ million records to upload, so you can see where the timing would be important. I'll look into do a pull request, but I'm a novice Node.JS programmer at this stage. Learning quickly, tho.

**Comment by cggaurav** [comment]
To tell how you slow it can be, it took a day to get to 10% of a 2.5 GB logging elasticsearch 1.5 single instance.

**Comment by evantahler** [comment]
I would actually argue that perhaps *all* writes to ES from this tool should use `bulk`.  Having the option is weird.  Anyone want to switch us to use the bulk API for all write operations?

**Comment by evantahler** [comment]
might be closed by https://github.com/taskrabbit/elasticsearch-dump/pull/221

**Comment by evantahler** [comment]
https://github.com/taskrabbit/elasticsearch-dump/releases/tag/v2.2.0 released!

**Comment by evantahler** [comment]
It's back! Closing.
