### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by nicodmf** [taskrabbit/elasticsearch-dump#207]
Hello, 

Is the build process automatical ? I think is it possible if you add this repository in your docker hub account. For now i don't find it but maybe it exists.

Best regards

**Comment by evantahler** [comment]
I've never built the docker container. 
@acaranta or @khanhicetea is this something you can set up?

**Comment by acaranta** [comment]
well, the problem, for my part is that I can not add an automatic build against this repo .... as it is not mine ;)

The only thing I can do is create an automatic build against a fork of this ... but it means I need to merge manually every new commit from here to mine .... sorry, I don't have time to do so ;)

Or I would require to be added as a "collaborator" to this repo .... but who am I to ask for admin privileges ;)

the best thing would be that @taskrabbit created an account on the hub (https://hub.docker.com) and created himself an automated build for this repo (easy, quick and FREE :p )  .... which then would build on every commit.

**Comment by evantahler** [comment]
neat! Thanks for the advice https://hub.docker.com/r/taskrabbit/elasticsearch-dump/

**Comment by acaranta** [comment]
you're welcome ;)

**Comment by khanhicetea** [comment]
Nice ! 👍

**Comment by davedash** [comment]
Thanks @acaranta and @evantahler .  The versions available now are 4.3 and older, can you resume building images again?

**Comment by ferronrsmith** [comment]
@davedash reached out to @evantahler and @bleonard about access to the docker container, but I haven't gotten a response. I might have to move the docker auto-build. Let me and I'll create one ASAP.

https://github.com/taskrabbit/elasticsearch-dump/issues/519

**Comment by ferronrsmith** [comment]
@evantahler is possible for you to create a new docker repo for elasticsearch-dump ? I don't have the necessary access to do this.

**Comment by ferronrsmith** [comment]
The latest version has been pushed. Thanks for your patience
