### ISSUE TITLE
Including type in --input or --input-index with --delete generates wrong delete URL

### ISSUE THREAD

**Issue by rthrfrd** [taskrabbit/elasticsearch-dump#209]
Type will appear twice in URL because `self.base.url` already includes it, therefore delete fails:
https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L376
In the same way write to output also fails if output has type specified.

**Comment by evantahler** [comment]
Great find! Please submit a pull request with the fix and matching test.

**Comment by evantahler** [comment]
Closing due to lack of progress/interest
