### ISSUE TITLE
What's the best practice to reindex a dump from multielasticdump?

### ISSUE THREAD

**Issue by cggaurav** [taskrabbit/elasticsearch-dump#213]
I have 1000+ indexes each with a mapping, analyzer and the data. Should't there be a multielastidump index command?

**Comment by evantahler** [comment]
Can you phrase this another way?  What doesn't `multielasticdump` do that you wish it would?  Do you want to `multielasticdump` from index A into index B?  If so, that's an easy pull request for you to write!  Let me know if you need help getting stated.

**Comment by cggaurav** [comment]
@evantahler I want multielasticdump to take all the files it has dumped to another elastic search instance. Yup, go through every index file, PUT the analyzer, mapper, then document?

**Comment by evantahler** [comment]
Makes sense to me! Let me know when you have a pull request ready.

**Comment by evantahler** [comment]
will be solved by https://github.com/taskrabbit/elasticsearch-dump/pull/216
