### ISSUE TITLE
Why is there a getaddrinfo NOT FOUND error even if the write succeeds?

### ISSUE THREAD

**Issue by cggaurav** [taskrabbit/elasticsearch-dump#214]
![](http://d.pr/i/10pN5+)

**Comment by evantahler** [comment]
This is a system-level networking error.  Your computer could no longer release the elasticsearch server.  Do you have networking timeouts, poor connectivity, etc?

**Comment by cggaurav** [comment]
@evantahler I keep getting it if I have large amounts of data. ```Wed, 18 May 2016 12:54:19 GMT | Error Emitted => connect ECONNRESET 127.0.0.1:9200
Wed, 18 May 2016 12:54:19 GMT | Total Writes: 4445
Wed, 18 May 2016 12:54:19 GMT | dump ended with error (set phase)  => Error: connect ECONNRESET 127.0.0.1:9200
Wed, 18 May 2016 12:54:19 GMT | Error: CHILD PROCESS EXITED WITH ERROR.  Stopping process```
How can I debug this?

**Comment by evantahler** [comment]
Look into the network settings of your OS?  Perhaps your router?

Try with a smaller `--limit` so there is less time between each request and hopefully you won't loose the connection if you are more active.
