### ISSUE TITLE
Does elasticsearch-dump copy settings blindly?

### ISSUE THREAD

**Issue by s1monw** [taskrabbit/elasticsearch-dump#215]
Hey folks,
I just ran into an [issue](https://github.com/elastic/elasticsearch/issues/18418#issuecomment-219811158) on the elasticsearch core project where somebody claims to use elasticsearch-dump and it seems that the user has carried over an index from 1.x to 2.x. That's all fine so far until you go to 5.x and suddenly es thinks the index was created with 1.x since the `index.version_created` setting seemed to be carried over from the old index. ES does accept that in 2.x still but in 5.x it will reject the index creation. This behavior is a pain and I fixed all the settings handling myself in the last couple of month but I think copying the index settings from the foreign index it trappy for users of elasticsearch-dump. Settings like
- `index.version.created`
- `index.version.upgraded`
- `index.creation_date` 
- `index.uuid`

should be filtered out - in 5.x they will be rejected anyhow.

if you folks do that already feel free to just close this. I didn't check too deep in your source but the references for settings seemed to no to, hence the issue.

thanks!

**Comment by evantahler** [comment]
Nope, that's not something the tool does.  Feel feel free to submit a pull request to filter those options out!

**Comment by s1monw** [comment]
> Nope, that's not something the tool does. Feel feel free to submit a pull request to filter those options out!

I guess I have to pass this on to somebody else, but I am sure it's a low hanging fruit for somebody who has the dev env set up.

**Comment by s1monw** [comment]
oh and btw. I think this is a bug not an enhancement.
