### ISSUE TITLE
--skip vs. --offset. Another limit option

### ISSUE THREAD

**Issue by jetnet** [taskrabbit/elasticsearch-dump#217]
Hi Evan,

first of all - thank you for the great tool, it's very useful and does save a lot of time!

What I was missing, is another "limit" option, which could control, how many records should be fetched from the source. E.g. I needed to extract N random samples from one index a put them into another one. Currently, it is not possible to "tell" the tool to stop after getting the first N documents.
So, another option was to use `--skip <total - N>` parameter and fetch N last docs (which is OK for a random query). But the skip function does not work as expected:
```
node elasticdump --input="http://localhost:9200/logstash-*" --output="http://localhost:9200/random" --searchBody '{"query":{"function_score":{"query":{"match_all":{}},"random_score":{}}}}' --skip 2447399 --limit 10000
Wed, 18 May 2016 16:32:03 GMT | starting dump
Wed, 18 May 2016 16:32:03 GMT | Warning: skipping 2447399 rows.
Wed, 18 May 2016 16:32:03 GMT |   * skipping doesn't guarantee that the skipped rows have already been written, please refer to the README.
Wed, 18 May 2016 16:32:04 GMT | got 10000 objects from source elasticsearch (offset: 0)
Wed, 18 May 2016 16:32:18 GMT | sent 10000 objects to destination elasticsearch, wrote 9241
Wed, 18 May 2016 16:33:46 GMT | got 2601 objects from source elasticsearch (offset: 20000)
Wed, 18 May 2016 16:33:48 GMT | sent 2601 objects to destination elasticsearch, wrote 2246
```
As you can see, it does not skip rows: it starts from the beginning and uses the doubled `limit` value for each iteration.

Fortunately, there is a hidden `--offset` parameter, which works like a charm:
```
node elasticdump --input="http://localhost:9200/logstash-*" --output="http://localhost:9200/random" --searchBody '{"query":{"function_score":{"query":{"match_all":{}},"random_score":{}}}}' --offset 2457399 --limit 100
Wed, 18 May 2016 17:14:50 GMT | starting dump
Wed, 18 May 2016 17:14:50 GMT | got 100 objects from source elasticsearch (offset: 2457399)
Wed, 18 May 2016 17:14:50 GMT | sent 100 objects to destination elasticsearch, wrote 100
Wed, 18 May 2016 17:14:50 GMT | got 100 objects from source elasticsearch (offset: 2457499)
Wed, 18 May 2016 17:14:51 GMT | sent 100 objects to destination elasticsearch, wrote 100
```
So, two questions:
1) what is the purpose of the `--skip` parameter, if there is a good working `--offset` (which is not documented yet)?
2) do you think it makes sense to implement a new limit option (e.g. `--stop-after N`), in order to get only the first N records from the source?

Thank you!

**Comment by jetnet** [comment]
it turned out, that neither of these parameters work correctly :(
`--offset` works with a random result set only.

**Comment by evantahler** [comment]
Great catch!
will be fixed via https://github.com/taskrabbit/elasticsearch-dump/pull/223
