### ISSUE TITLE
Why was the --bulk feature removed from your tool?

### ISSUE THREAD

**Issue by antonioaguilar** [taskrabbit/elasticsearch-dump#218]
I have been using elasticdump to mostly import/export indices from elasticsearch instances and it was the main reason why I started to use elasticdump. I don't understand why this feature is now removed? 

What is the latest version of elasticdump that I can revert to to have the bulk feature?

Thanks.

**Comment by evantahler** [comment]
Deleting in favor of https://github.com/taskrabbit/elasticsearch-dump/issues/205.  Please comment on the original story
