### ISSUE TITLE
Consider adding version info in elasticdump cli

### ISSUE THREAD

**Issue by antonioaguilar** [taskrabbit/elasticsearch-dump#219]
There is no version info displayed in the elasticdump cli which makes it difficult to know which version of elasticdump is installed. Consider adding a ```--version``` to the command line and displaying version info on program help:

```bash
elasticdump --help
elasticdump: Import and export tools for elasticsearch

Usage: elasticdump --input SOURCE --output DESTINATION [OPTIONS] ...
```

**Comment by evantahler** [comment]
great idea! 
https://github.com/taskrabbit/elasticsearch-dump/issues/219
