### ISSUE TITLE
Can't import Json

### ISSUE THREAD

**Issue by JaySWang** [taskrabbit/elasticsearch-dump#222]
Hi there,

It seems that the latest version doesn't support input Json like this : [{},{}....{} ],but {} {} works.

windows8
elasticdump --input export.json --output "http://localhost:9200/.kibana" --debug

 [debug] thisUrl: http://localhost:9200/.kibana/undefined/undefined, elem._source: undefined
Wed, 01 Jun 2016 13:10:19 GMT | sent 1 objects to destination elasticsearch, wrote 0
Wed, 01 Jun 2016 13:10:19 GMT | got 0 objects from source file (offset: 1)
Wed, 01 Jun 2016 13:10:19 GMT | Total Writes: 0
Wed, 01 Jun 2016 13:10:19 GMT | dump complete

thx for help

**Comment by evantahler** [comment]
That is correct.  V2.x changed the format of the dump files as you can see here: https://github.com/taskrabbit/elasticsearch-dump/releases/tag/v1.0.0
