### ISSUE TITLE
Feature request: add maxResults parameter

### ISSUE THREAD

**Issue by jetnet** [taskrabbit/elasticsearch-dump#224]
hi! I'd like to enhance the tool by adding a new parameter, that would limit the result set by a given number, e.g. `--maxResults`.

The code (`elasticdump.js`) could look like this:
```patch
***************
*** 132,137 ****
--- 132,141 ----
              }
            }

+           if (self.options['maxResults'] && total_writes >= self.options['maxResults']) {
+             data = [];
+           }
+
            if(data.length > 0 && toContinue){
              self.dump(callback, true, limit, offset, total_writes);
            }else if(toContinue){
```
Does it make sense?..
Thanks!

**Comment by evantahler** [comment]
keep in mind this result set would be ordered randomly.  You can currently achieve this functionality now by requesting an `--offset` which is the total of your data minus `maxResults `

**Comment by jetnet** [comment]
result sets are **not** ordered randomly. At least on my side :)
So, you idea - to take a random result set from the end - would work with function_score-random_score query only. It can be used in some cases, but not always.

**Comment by evantahler** [comment]
yep! 
So I think we don't need a new flag.

**Comment by jetnet** [comment]
It would be good, to enhance the tool for use cases, where an index needs to be split into chunks, with results sorted by a given sort method.
I would appreciate, if that feature could be implemented (officially ;))

**Comment by evantahler** [comment]
Pull requests welcome! 

Since there's a work-around, I'm not going to implement it, but if someone else wants to write it up (and test it), I'll merge it in!
