### ISSUE TITLE
"type":"security_exception","reason":"missing authentication token for REST request

### ISSUE THREAD

**Issue by abtpst** [taskrabbit/elasticsearch-dump#225]
I am trying to dump some data to a cluster that has shield authentication and i get

`"type":"security_exception","reason":"missing authentication token for REST request`

so i tried

elasticdump \
  --input=http://localhost:9200/my_index \
  --output=http://staging.es.com:9200/my_index \
  --type=data
  -u user/pass

as suggested on

`https://discuss.elastic.co/t/unable-to-check-elasticsearch-cluster-health-w-shield-plugin-installed/36686`

but i still get the exception. so next i tried

elasticdump \
  --input=http://localhost:9200/my_index \
  --output=https://user:password@staging.es.com:9200/my_index \
  --type=data

but now i get

`Error Emitted => tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:`

i have the proxy configured correctly in my .npmrc file. what should i do?

**Comment by evantahler** [comment]
We currently have no support for using token-based authentication.  let me know if you need any guidance on creating a pull request to add that feature!

**Comment by evantahler** [comment]
We have confirmed numerous times that using basic auth, as you describe via `https://user:password@staging.es.com:9200`, does work.  You may have a typo

**Comment by wangpengpeng** [comment]
you can mkdir httpAuthFile.txt  
content bellow: 
user=your-user
password=your-password

command bellow :

elasticdump \
  --input=http://crm-master1:9200/user_label_1 \
  --output=http://10.45.2.95:9200/user_label_1 \
  --type=data \
  --httpAuthFile=./httpAuthFile.txt

**Comment by nicopenaredondo** [comment]
@wangpengpeng upon trying that approach. i encountered this error.

![image](https://user-images.githubusercontent.com/3615451/80376186-082b9000-88cc-11ea-8d30-3abfcaaca1a6.png)

**Comment by ferronrsmith** [comment]
You’re using an outdated node version
