### ISSUE TITLE
IllegalArgumentException: can't add a _parent field that points to an already existing type

### ISSUE THREAD

**Issue by cah-ricksuggs** [taskrabbit/elasticsearch-dump#226]
I am using elasticdump to backup and restore an index with a parent child mapping, and it's causing an exception to be thrown by elasticsearch.

`java.lang.IllegalArgumentException: can't add a _parent field that points to an already existing type`

I noticed that the elasticsearch transport attempts to create the child mapping before the parent mapping by simply sorting the Array by the _parent field. https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L154

However, I believe this is causing the exception to be thrown, because all of the requests are sent in a loop, without waiting for the child mapping to be created and the successful response from elasticsearch.

Is there any way to use promises to control the requests, so that only one mapping is created at a time?

**Comment by evantahler** [comment]
Can you clarify?  

To copy an index properly, you need to export the `mapping`, the `settings` and the `data`.  If you export all 3 of those (3 separate files), and then load them into your new index in the proper order, does it not work?    This is what `multidump` does, and it seems to work for others.

**Comment by cah-ricksuggs** [comment]
I'm was using `multidump` to export the mapping, analyzer, and data json files, and using `elasticdump` command to import the three in order: 

```
elasticdump --input=./index1.analyzer.json --output=http://localhost:9200 --type=analyzer --output-index=index1
elasticdump --input=./index1.mapping.json --output=http://localhost:9200 --type=mapping --output-index=index1
elasticdump --input=./index1.json --output=http://localhost:9200 --type=data --output-index=index1
```

The problem is that in step 2, when the mapping is being imported, elasticdump splits the **mapping** json into chunks and sends separate requests for each mapping. An attempt is made to send the mapping requests in the correct order, however, in the manner implemented you really have no control over when the requests are processed on the other end by elasticsearch. For now, I have stopped using elasticdump for the mapping import, and started using the elasticsearch REST API directly. The elasticsearch REST API actually supports importing an entire mapping.json in one request, and automatically handling the parent/child relationships. I am not sure why this library is doing the extra work of splitting the mapping into separate requests.

**Comment by jhovell** [comment]
Experienced this issue at least once running the test suite for this project. Not surprisingly it doesn't happen every time 

```
.... (beginning of test output, normal)...
    ES to ES dump should maintain parent-child relationships
      1) "before all" hook
....
      ✓ works
    es to stdout
      - works
    stdin to es
      - works

  transform script should be executed for written documents
    ✓ documents should have the new field computed by transform script


  58 passing (4m)
  2 pending
  1 failing

  1) parent child ES to ES dump should maintain parent-child relationships "before all" hook:
     Error: the object {
  "reason": "can't add a _parent field that points to an already existing type, that isn't already a parent"
  "root_cause": [
    {
      "reason": "can't add a _parent field that points to an already existing type, that isn't already a parent"
      "type": "illegal_argument_exception"
    }
  ]
  "type": "illegal_argument_exception"
  "uncaught": true
} was thrown, throw an Error :)
      at process._fatalException (bootstrap_node.js:292:26)



npm ERR! Test failed.  See above for more details.
```
