### ISSUE TITLE
Return `lastScrollId` in debug mode, allow providing one via the command-line

### ISSUE THREAD

**Issue by bhurlow** [taskrabbit/elasticsearch-dump#227]
Hi!

Wondering if it would be possible to add some reconnection handling for instances when the `--output` target is unavailable. In my case specifically, I have an elasticsearch proxied via nginx which will sometimes drop a connection if it gets maxed out. Might be possible to buffer internally while waiting for the connection to come back up.

Thoughts?

**Comment by evantahler** [comment]
sorry, that's not something we can support.  Elasticsearch returns data in non-deterministic ways (see the notes on the `--offset` flag), so "resuming" your session isn't guaranteed to pick up where you left off.  

That said, we are using scroll, so if your scrollTime is long enough, you should be able to resume your session from where you left off (at the expense of Elastic search keeping your result set in RAM).  To that end, I've renamed the title of this pull request.

**Comment by bhurlow** [comment]
Thanks!

**Comment by leea** [comment]
+1 for this feature. I am also running long duration dumps which keep on failing midway.

Another way to implement this is to write the lastScrolLId to a file somewhere (like `/var/tmp/elasticdump/{input-index}/_scroll_id`) and have a `--resume` option that reads scroll id from file.

**Comment by ferronrsmith** [comment]
`--debug` emits `scrollRequest` which has the `scrollId`

**Comment by cjkoski** [comment]
Hi I was trying to find how this scroll ID gets emit.   I want to find a way to delete by scroll ID once I am done with it, but not seeing it emitted with --debug mode .

**Comment by ferronrsmith** [comment]
--debug emits **scrollRequest** which has the **scrollId**
****
