### ISSUE TITLE
Not copying analyzer  settings

### ISSUE THREAD

**Issue by fbarnard** [taskrabbit/elasticsearch-dump#231]
Hi

If i do a --type=analyzer from local to production it does not work. It creates the index but it does not have any analyzers. When i do it local to local with different name it works.

I have version 1.7.3 on local and 1.5.2 on production. Might be that

thanks

**Comment by evantahler** [comment]
Sorry, we are not interested in supporting `migrations` between versions.

**Comment by evantahler** [comment]
If you do learn what the changeset is between those versions, it would be useful to list them here for others to learn from.  Are you trying to dump from 1.7.3 -> 1.5.2 or the other way around?

**Comment by fbarnard** [comment]
Hi

I am going from 1.73 > 1.5.2. I will have a look at code and see what type=analyzer  uses and then see if any of the elastic  api changed.

thanks

**Comment by fbarnard** [comment]
Hi

had a quick look.

if you get a index settings the structure looks like this '[INDEXNAME]/settings/index/analysis' with 1.5 and 1.7

according to api when you put its at the 'index' level and not 'settings' level. Or am i looking wrong.

so instead of doing

> "analysis" :{
> }
> 

it looks like its doing

> "index" : {
> "analysis" :{
> }
> }

thanks
