### ISSUE TITLE
Elasticdump - wrote 0 

### ISSUE THREAD

**Issue by jkopparapu** [taskrabbit/elasticsearch-dump#232]
Objective: Move all the indexes dump from X server to Y server

STEP 1:
I extracted the dump from X server and following is the command i used:

elasticdump --all=true --type=data --limit=1000 --input=http://localhost:9200/ --output=dev.json

STEP 2:

moving the file from X server to Y server

STEP 3:

Now, i am trying to load the data to Y server and following is the command i used:

elasticdump --type=data --bulk=true --limit=1000 --input=dev.json --output=http://localhost:9200/

Please note: i removed --bulk=true and tried.. no luck... same result.

The problem is when i run the elasticdump in Y server: i am getting the below output

Wed, 22 Jun 2016 05:51:54 GMT | starting dump
Wed, 22 Jun 2016 05:51:54 GMT | got 1000 objects from source file (offset: 0)
Wed, 22 Jun 2016 05:51:55 GMT | sent 1000 objects to destination elasticsearch,wrote 0
Wed, 22 Jun 2016 05:51:55 GMT | got 1012 objects from source file (offset: 1000)

Wed, 22 Jun 2016 05:51:55 GMT | sent 1012 objects to destination elasticsearch,wrote 0
Wed, 22 Jun 2016 05:51:56 GMT | got 1007 objects from source file (offset: 2012)

Wed, 22 Jun 2016 05:51:56 GMT | sent 1007 objects to destination elasticsearch,wrote 0
Wed, 22 Jun 2016 05:51:56 GMT | got 1004 objects from source file (offset: 3019)

Both the places, elasticsearch is running version is also same

[vagrant@vagrant-testing ~]$ curl -XGET 'localhost:9200'
{
  "status" : 200,
  "name" : "XXXX", -- Different in Y server
  "cluster_name" : "XXXXX", -- Different in Y server
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by evantahler** [comment]
- Have you confirmed that your dumpfile contains data?
- can you try not using the `all` option, and going index-by-index?

**Comment by jkopparapu** [comment]
Yes, i checked the dumpfile having data in JSON format (by using the command head -10 dev.json)

I tried removing -all option.. no luck... However if i add a name in the url it works, for example
http://localhost:9200/my_index

But all the indexes are dumping at my_index. I want them separately, The separate indexes whatever is there in the source server (x) and i want the exact replica in the destination server

**Comment by evantahler** [comment]
The `-all` flag was actually removed a while ago.  Sadly it remained in the documentation.  This PR removed it entirely.  https://github.com/taskrabbit/elasticsearch-dump/pull/233

For help importing and exporting many indexes at once, check out the `multielasticdump` command: https://github.com/taskrabbit/elasticsearch-dump#multielasticdump

**Comment by jkopparapu** [comment]
-all has been removed in the X server and regenerated the data file. Still not working. Just want to make sure if there is a limitation in elasticdump for my requirement?

I will also definitely check the multielasticdump option.
