### ISSUE TITLE
response.filter is not a function

### ISSUE THREAD

**Issue by alexef** [taskrabbit/elasticsearch-dump#236]
Trying to get a full index dump with elasticdump@2.3.0, I'm getting:

```
/home/alexef/node_modules/elasticdump/bin/multielasticdump:80
    matchedIndexes = response.filter(function(index){
                              ^

TypeError: response.filter is not a function
    at Request._callback (/home/alexef/node_modules/elasticdump/bin/multielasticdump:80:31)
    at Request.self.callback (/home/alexef/node_modules/elasticdump/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/alexef/node_modules/elasticdump/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/alexef/node_modules/elasticdump/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by evantahler** [comment]
what node.js version are you using?  v4.0.0+ is required.

**Comment by alexef** [comment]
i have v4.4.7

**Comment by Ogniute** [comment]
i have the same issue and also the version 4.4.7

**Comment by evantahler** [comment]
Can you share the command you are running, a data set... something that can be used to reproduce this?

**Comment by jpablo** [comment]
I had the same problem while trying to use `multielasticdump`. The problem was that I'm using ES v1.7.2 and `response` is an object:
```
{"user_profile":{"aliases":{}},"haystack":{"aliases":{}}}
```
replacing 
`    matchedIndexes = response.filter(function(index){ `
by 
`    matchedIndexes = Object.keys(response).filter(function(index){`

fixed it.

**Comment by cah-ricksuggs** [comment]
I'm running into the same issue, the error is thrown here: https://github.com/taskrabbit/elasticsearch-dump/blob/master/bin/multielasticdump#L80

I use aliases when reindexing, so my response looks like the folowing:

```
{
    "l1-v1": {
        "aliases": {}
    },
    "latest": {
        "aliases": {
            "l1": {}
        }
    },
    "l2-v1": {
        "aliases": {
            "l2": {}
        }
    },
    "l3-v1": {
        "aliases": {
            "l3": {}
        }
    },
    "v1": {
        "aliases": {
            "l4": {}
        }
    }
}
```

**Comment by minhyeok4dev** [comment]
Work it! Thanks @jpablo

**Comment by richardfrost** [comment]
+1 :clap: @jpablo's suggestion

**Comment by evantahler** [comment]
Please submit a patch which either detects the ES version you are connecting too and handles the response properly, or try/catch that filter.

Thanks!

**Comment by adammichalik** [comment]
Why is this issue closed? I can't see that anybody provided a fix and the problem persists.

**Comment by bhurlow** [comment]
@jpablo thanks!

**Comment by evantahler** [comment]
Solved by https://github.com/taskrabbit/elasticsearch-dump/pull/249

**Comment by evantahler** [comment]
[v2.4.2](https://github.com/taskrabbit/elasticsearch-dump/releases/tag/v2.4.2) has been released to NPM

**Comment by ShrJoshi28** [comment]
data.filter is not a function
    at module.exports (custom-filters.js?641a:7

how to solve this error?
