### ISSUE TITLE
socket hang up error always

### ISSUE THREAD

**Issue by vivdev** [taskrabbit/elasticsearch-dump#237]
Tried it on a small index, it worked fine.

On larger index, it failed so:

$ elasticdump --input=http://localhost:9200/alias_bindoc --output alias_bindoc20160701_1852.json
Fri, 01 Jul 2016 13:25:51 GMT | starting dump
Fri, 01 Jul 2016 13:26:01 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 01 Jul 2016 13:26:02 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:26:12 GMT | got 100 objects from source elasticsearch (offset: 100)
Fri, 01 Jul 2016 13:26:12 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:26:26 GMT | got 100 objects from source elasticsearch (offset: 200)
Fri, 01 Jul 2016 13:26:27 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:26:48 GMT | got 100 objects from source elasticsearch (offset: 300)
Fri, 01 Jul 2016 13:26:48 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:27:10 GMT | got 100 objects from source elasticsearch (offset: 400)
Fri, 01 Jul 2016 13:27:10 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:27:17 GMT | got 100 objects from source elasticsearch (offset: 500)
Fri, 01 Jul 2016 13:27:17 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:27:32 GMT | got 100 objects from source elasticsearch (offset: 600)
Fri, 01 Jul 2016 13:27:32 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:28:37 GMT | Error Emitted => socket hang up
Fri, 01 Jul 2016 13:28:37 GMT | Total Writes: 700
Fri, 01 Jul 2016 13:28:37 GMT | dump ended with error (get phase) => Error: socket hang up

Tried offset of 700 this time:

$ elasticdump --input=http://localhost:9200/alias_bindoc --output alias_bindoc20160701_1852.json --offset 700
Fri, 01 Jul 2016 13:36:04 GMT | starting dump
Fri, 01 Jul 2016 13:36:04 GMT | Warning: offseting 700 rows.
Fri, 01 Jul 2016 13:36:04 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
Fri, 01 Jul 2016 13:36:17 GMT | Error Emitted => socket hang up
Fri, 01 Jul 2016 13:36:17 GMT | Total Writes: 0
Fri, 01 Jul 2016 13:36:17 GMT | dump ended with error (get phase) => Error: socket hang up

Then tried again full dump:

$ elasticdump --input=http://localhost:9200/alias_bindoc --output alias_bindoc20160701_1906.json
Fri, 01 Jul 2016 13:37:01 GMT | starting dump
Fri, 01 Jul 2016 13:37:02 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 01 Jul 2016 13:37:02 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:37:05 GMT | got 100 objects from source elasticsearch (offset: 100)
Fri, 01 Jul 2016 13:37:05 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:37:07 GMT | got 100 objects from source elasticsearch (offset: 200)
Fri, 01 Jul 2016 13:37:07 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:37:08 GMT | Error Emitted => socket hang up
Fri, 01 Jul 2016 13:37:08 GMT | Total Writes: 300
Fri, 01 Jul 2016 13:37:08 GMT | dump ended with error (get phase) => Error: socket hang up

Vivek@G5080-1TB MINGW64 /c/ec
$ elasticdump --input=http://localhost:9200/bindoc20160630 --output bindoc20160630_20160701_1906.json
Fri, 01 Jul 2016 13:39:36 GMT | starting dump
Fri, 01 Jul 2016 13:39:38 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 01 Jul 2016 13:39:39 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:39:41 GMT | got 100 objects from source elasticsearch (offset: 100)
Fri, 01 Jul 2016 13:39:41 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:39:43 GMT | got 100 objects from source elasticsearch (offset: 200)
Fri, 01 Jul 2016 13:39:43 GMT | sent 100 objects to destination file, wrote 100
Fri, 01 Jul 2016 13:39:43 GMT | Error Emitted => socket hang up
Fri, 01 Jul 2016 13:39:43 GMT | Total Writes: 300
Fri, 01 Jul 2016 13:39:43 GMT | dump ended with error (get phase) => Error: socket hang up

**Comment by evantahler** [comment]
This is a networking error.  

`Error: socket hang up` means that the elasticdump tool got either no or malformed data back over your network when waiting for data from Elasticsearch.

**Comment by sesibhushan121** [comment]
Hi @evantahler , can u suggest me any for my error

we are facing this issue on elastic dump, present in dev env environment, we have configure in my kubernetes cluster in Amazon EKS ,we have installed EFK in dev cluster and I want to dump elastic data to s3, so we have installed elastic dump in that env, After that when im giving the command to before that we are generating the file ,...facing the issue
command:

elasticdump \ --input=http://biden:MaralTNIJefffgrtuy@http/://ggtbtgtacc87d1vrvrg1968grgr-vrgtg26555vgrvrvr.us-east-1.elb.amazonaws.com:9200/data-source \ --output=/data/vfef33ddrf.json \ --type=data
Tue, 23 Aug 2022 09:31:56 GMT | starting dump
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Total Writes: 0
Tue, 23 Aug 2022 09:32:16 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND http

**Comment by evantahler** [comment]
You need to quote your URLs.  Also, you just shared your password - you should change it.

**Comment by sesibhushan121** [comment]
Ok, actually it was not original password, np for that

But the matter is my error , can u share any docs to follow
