### ISSUE TITLE
Debugging Incomplete Writers

### ISSUE THREAD

**Issue by haydenth** [taskrabbit/elasticsearch-dump#245]
Hello, running version 2.4 and copying records from one AWS ES cluster to another. I'm getting the following output

```
Wed, 10 Aug 2016 16:21:36 GMT | got 50 objects from source elasticsearch (offset: 0)
Wed, 10 Aug 2016 16:21:37 GMT | sent 50 objects to destination elasticsearch, wrote 48
Wed, 10 Aug 2016 16:21:38 GMT | got 50 objects from source elasticsearch (offset: 50)
Wed, 10 Aug 2016 16:21:39 GMT | sent 50 objects to destination elasticsearch, wrote 49
Wed, 10 Aug 2016 16:21:39 GMT | got 50 objects from source elasticsearch (offset: 100)
Wed, 10 Aug 2016 16:21:39 GMT | sent 50 objects to destination elasticsearch, wrote 47
Wed, 10 Aug 2016 16:21:40 GMT | got 50 objects from source elasticsearch (offset: 150)
Wed, 10 Aug 2016 16:21:40 GMT | sent 50 objects to destination elasticsearch, wrote 48
Wed, 10 Aug 2016 16:21:41 GMT | got 50 objects from source elasticsearch (offset: 200)
Wed, 10 Aug 2016 16:21:41 GMT | sent 50 objects to destination elasticsearch, wrote 47
Wed, 10 Aug 2016 16:21:41 GMT | got 50 objects from source elasticsearch (offset: 250)
Wed, 10 Aug 2016 16:21:42 GMT | sent 50 objects to destination elasticsearch, wrote 49
Wed, 10 Aug 2016 16:21:43 GMT | got 50 objects from source elasticsearch (offset: 300)
Wed, 10 Aug 2016 16:21:44 GMT | sent 50 objects to destination elasticsearch, wrote 50
Wed, 10 Aug 2016 16:21:44 GMT | got 50 objects from source elasticsearch (offset: 350)
Wed, 10 Aug 2016 16:21:45 GMT | sent 50 objects to destination elasticsearch, wrote 48
Wed, 10 Aug 2016 16:21:45 GMT | got 50 objects from source elasticsearch (offset: 400)
Wed, 10 Aug 2016 16:21:46 GMT | sent 50 objects to destination elasticsearch, wrote 49
Wed, 10 Aug 2016 16:21:46 GMT | got 50 objects from source elasticsearch (offset: 450)
Wed, 10 Aug 2016 16:21:47 GMT | sent 50 objects to destination elasticsearch, wrote 42
```

Using the following command
```
./elasticdump --input=$INPUT --input-index=$INDEX --output=$OUTPUT --output-index=$INDEX --type=data --limit=50 --bulk=true
```

Tried with different permutations of limits and bulk setting. No luck. Is there a good way to debug the rows that it's not writing? When it fetches 50 and writes 49, i'd love to see why it's not writing that one row.

**Comment by jcajkovic** [comment]
+1

**Comment by drajcan** [comment]
+1

**Comment by pivno** [comment]
+1

**Comment by kyblik** [comment]
+1

**Comment by dplz** [comment]
+1

**Comment by mliner** [comment]
+1

**Comment by acmarko** [comment]
+1

**Comment by pvelas** [comment]
+1

**Comment by evantahler** [comment]
Have you tried the `--debug` flag?  That will print out the request query being sent to ES, and then the JSON that it is trying to write to disk.   You can then isolate the write command, try it manually, and see what happens. 

Also, note that the `--bulk` options have been removed.

**Comment by jcajkovic** [comment]
Hi we tried `--debug` option, we removed also `--bulk` option however it looks like the `--limit` option is ignored and we cannot see which records are not inserted from debug output

**Comment by jcajkovic** [comment]
we also think it can have something to do with the encoding of the data, basically the difference between ES stacks or file when we dump first to file and import form file. FYI we use ES Service from Amazon and migrating data from our installation of ES.

**Comment by haydenth** [comment]
So, I had this problem when I was taking from ES 1.5 and moving it to ES 2.3. The errors were related to how 2.3 was handling nested mappings in a way that is different from how 1.5 handled nesting mappings. I was able to use the --debug flag to see the queries and then just manually re-tried a set until I could find the error. Is it worth considering having the --debug flag also throw out the JSON that is returned from ES upon insertion? If so, I'd be happy to submit a PR for this.

**Comment by pvelas** [comment]
@haydenth You are right. I tried to migrate one small index to ES 2.3 and all records were inserted. So it looks like that in some cases mappings between 1.5 and 2.x versions are not compatible.

**Comment by evantahler** [comment]
Thanks @haydenth.  Sadly, converting index settings between ES versions seems out-of-scope for this project.

**Comment by evantahler** [comment]
@haydenth please submit that PR with the output!  Perhaps only on error?
