### ISSUE TITLE
--retry option for timeouts

### ISSUE THREAD

**Issue by bluepuma77** [taskrabbit/elasticsearch-dump#246]
We experience timeouts with Elastic and it would be great to have an option like `--retry=5` in addition to `--ignore-errors`. That would create a higher chance of copying all docs.

Sidenote: we have Elastic behind a proxy that creates a non-JSON response in case of timeout:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>"
```

It would be great if elasticdump could handle that, not sure if that would result in an error.

**Comment by evantahler** [comment]
That sounds like a great feature to add!  Since we are using the Scroll API we can recover from timed out reads like this.  

Please submit a pull request! Let me know if you need help getting started.

**Comment by xrl** [comment]
I'm downloading from a ES server in China through some flakey load balancers. Failure to gracefully recover from downloads was a show-stopper. The quick fix was to use https://github.com/FGRibreau/node-request-retry which worked as-advertised, a drop in replacement for the request library.

For the elasticsearch transport file:

```
var request = require('requestretry');
[[ SNIP ]]
    searchRequest = {
      "uri": uri,
      "method": "GET",
      "sort": [ "_doc" ],
      "body": JSON.stringify(searchBody),

      "maxAttempts": 5,
      "retryDelay": 10000,
      "retryStrategy": request.RetryStrategies.HTTPOrNetworkError,
    };
```

Those last three options set on the `searchRequest` could be fetched from a CLI argument.

I'll be happy to produce a pull request if the project is happy with bringing in the new dependency. Totally understand if that's not desirable.

**Comment by evantahler** [comment]
Oh! I like this!

Please submit a pull request.  Perhaps we include both libraries as requirements in `package.json` and if a `--retryAttempts` flag is provided, switch to this new one
