### ISSUE TITLE
Add a silent or less verbose option

### ISSUE THREAD

**Issue by i5513** [taskrabbit/elasticsearch-dump#247]
Hello,

- ElasticDump version: 2.4
- Elasticsearch version: 2.3
- Full command you are having issue with (with inputs and outputs)
elasticdump --all=true --input=http://localhost:9200/ --output=elasticsearch.json

Fri, 19 Aug 2016 11:16:52 GMT | sent 100 objects to destination file, wrote 100
Fri, 19 Aug 2016 11:16:52 GMT | got 100 objects from source elasticsearch (offset: 213200)
...

Maybe -q or -s could be added so, less output or only errors are produced

Regards,

**Comment by evantahler** [comment]
added `--quiet` in v2.4.1
