### ISSUE TITLE
Add middleware option to modify data between input and output

### ISSUE THREAD

**Issue by shaharmor** [taskrabbit/elasticsearch-dump#248]
- ElasticDump version - latest
- Elasticsearch version - latest

Today its possible to override the input/output, but i'm looking for a way to only modify the data itself, while keeping the input/output as elasticsearch.

**Comment by evantahler** [comment]
I'm sorry, but modifying data in-flight is not the purpose of this tool.  This is simply a backup/restore utility.  

That said, you can create your own input/output transports today (loading them with `--inputTransport` and `--outputTransport`.  If you want to copy and modify the elsasticsearch input transport to also manipulate the data, you can!   Also, if you dump your data to an intermediate file first, there are any number of tools to do your modifications at that point.
