### ISSUE TITLE
Prompt for password

### ISSUE THREAD

**Issue by michalsvec** [taskrabbit/elasticsearch-dump#250]
As you state in readme:
> If you need basic http auth, you can use it like this: --input=http://name:password@production.es.com:9200/my_index

but it's not very safe to insert password as it can be seen in history. 
Would it be possible to add an option to prompt for password for basic http auth? 

Thank you!

**Comment by evantahler** [comment]
I think transforming this tool from a non-interactive one into an interactive one seems a bit out of scope for this need.  There are a number of ways (depending on your shell) on how to ignore, skip, or overwrite history.  Here are some suggestions for bash: http://stackoverflow.com/questions/8473121/execute-command-without-keeping-it-in-history
