### ISSUE TITLE
Unable to transfer mapping and data from one server to another using elasticdump

### ISSUE THREAD

**Issue by adarshchacko** [taskrabbit/elasticsearch-dump#251]
- ElasticDump version : 2.2.0 (both production and staging server)
- Elasticsearch version: 2.1.1 (both production and staging server)

I tried to transfer mapping using the following command:
`elasticdump --input=http://localhost:9200/index --output=http://staging.com:9200/index --type=mapping`

The above-mentioned command was run on the production server. This is what I get every time:
```
Wed, 07 Sep 2016 17:40:51 GMT | starting dump
Wed, 07 Sep 2016 17:40:51 GMT | got 1 objects from source elasticsearch (offset: 0)
Wed, 07 Sep 2016 17:40:52 GMT | Error Emitted => connect ECONNREFUSED xx.xxx.xxx.xxx:9200
Wed, 07 Sep 2016 17:40:52 GMT | Total Writes: 0
Wed, 07 Sep 2016 17:40:52 GMT | dump ended with error (set phase)  => Error: connect ECONNREFUSED xx.xxx.xxx.xxx:9200
```

where _xx.xxx.xxx.xxx_ is the ip address of the staging server.

Where could I go wrong ? 

**N.B.:** I tried using production.com instead of localhost in the input part but I got an error message with the ip address of the production server.

**Comment by evantahler** [comment]
`ECONNREFUSED` is a networking error.  Can you curl the server from where you are running elastic dump?

**Comment by adarshchacko** [comment]
I did try running curl and it is able to get the opening page of the site.

Do I need to configure Elasticsearch to bind the relevant ip address as suggested in this link.
[https://www.digitalocean.com/community/tutorials/how-to-set-up-a-production-elasticsearch-cluster-on-ubuntu-14-04]

**Comment by evantahler** [comment]
If you are seeing your site, you aren't seeing Elasticsearch.  Having Elasticsearch bind to a public interface is pretty dangerous (as there is not auth/control), so you are usually required to have infrastructure solutions in place to keep your cluster safe (firewalls).  You might SSH into a certain server running ES to reach it, and open up ports on the destination end as well... or use the file transport to move files of your dump around.
