### ISSUE TITLE
Question: What's the quickest path to clone an ES instance?

### ISSUE THREAD

**Issue by MarkHerhold** [taskrabbit/elasticsearch-dump#252]
What command should I be running to clone one ES instance (all indexes, mappings, etc) to another instance. I tried copying index-by-index across two AWS ES instances and the indexes weren't created on the destination instance. 😕 

Thanks!

**Comment by evantahler** [comment]
1) Mapping (which will create the index)
2) Analyzer
3) data.

check out https://github.com/taskrabbit/elasticsearch-dump#multielasticdump, which can do it all.

**Comment by MarkHerhold** [comment]
@evantahler Thanks! I imported the analyzer before the mapping so I guess that's why I don't have indexes? I'll give it another go with the order you provided.

I'll also take a look at multielasticdump, thanks!

**Comment by meersjo** [comment]
This is not only worth documenting in the readme; I would go as far as to add --type=all to do it right from the get-go.

**Comment by evantahler** [comment]
@MarkHerhold that's a great feature request, let me know if you need help getting started on that pull request!

**Comment by meersjo** [comment]
Subtle :-)
