### ISSUE TITLE
If an index name in ElasticSearch begins with a "." the file is created as hidden in the output directory

### ISSUE THREAD

**Issue by flybd5** [taskrabbit/elasticsearch-dump#255]
In order to help us troubleshoot issues with this project, you **must** provide the following details:
- ElasticDump version
2.4.2
- Elasticsearch version
2.3 on AWS
- Full command you are having issue with (with inputs and outputs)
multielasticdump

If an index name in ElasticSearch begins with a "." the file is created as hidden in the output directory. Can that behavior be overriden?

**Comment by evantahler** [comment]
I'm updating your title to reflect the content of your question

**Comment by evantahler** [comment]
There are no defaults specific to `elasticdump` about the output file's name (or even if we output to a file), so I'll guess you are talking about `multielasticdump`, which does save out all indexes to disk.

The file being "hidden" is specific to your operating system, and then the setting you have enabled for your "finder" or "explorer".  Yes, on most "*nix" operating systems, the default would be to hide that file.

I personally don't think that modifying the default behavior of `multielasticdump` is a good idea in these circumstances.  The logs still say which files are created, and adding complexity to the tool in this way seems unnecessary.  

That said, you can certainly submit a pull request on this topic and we can ask for feedback from others!

**Comment by flybd5** [comment]
Sorry about the title, I was going to report something else but I decided to try multielasticdump first. I checked and the files are being hidden by the OS but they don't have an archive or hidden file attribute set. No big deal then.
