### ISSUE TITLE
Wrote 0 for --type=data, mappings being written successfully

### ISSUE THREAD

**Issue by abhilashbolla-innoplexus** [taskrabbit/elasticsearch-dump#261]
ElasticDump version: 2.44.0
Elasticsearch version of source machine: 2.3.0
Elasticsearch version of target machine: 2.3.3

-------------- Write successful for mapping--------------------------------------------------------------------
elasticdump --input=http://192.168.0.196:9200/publication_search --output=http://192.168.0.58:9200/test_index --type=mapping
Tue, 27 Sep 2016 05:02:45 GMT | starting dump
Tue, 27 Sep 2016 05:02:45 GMT | got 1 objects from source elasticsearch (offset: 0)
Tue, 27 Sep 2016 05:02:46 GMT | sent 1 objects to destination elasticsearch, wrote 1
Tue, 27 Sep 2016 05:02:46 GMT | got 0 objects from source elasticsearch (offset: 1)
Tue, 27 Sep 2016 05:02:46 GMT | Total Writes: 1
Tue, 27 Sep 2016 05:02:46 GMT | dump complete
-----------------------------------<<<<<>>>>>>----------------------------------------------------------------------------------

-------------------Unsuccessful while writing data-------------------------------------------------------------
elasticdump --input=http://192.168.0.196:9200/publication_search --output=http://192.168.0.58:9200/test_index --type=data --limit=5                     130 ↵
Tue, 27 Sep 2016 05:03:47 GMT | starting dump
Tue, 27 Sep 2016 05:03:47 GMT | got 5 objects from source elasticsearch (offset: 0)
Tue, 27 Sep 2016 05:05:47 GMT | sent 5 objects to destination elasticsearch, wrote 0
Tue, 27 Sep 2016 05:05:47 GMT | got 5 objects from source elasticsearch (offset: 5)
Tue, 27 Sep 2016 05:07:47 GMT | sent 5 objects to destination elasticsearch, wrote 0
Tue, 27 Sep 2016 05:07:47 GMT | got 5 objects from source elasticsearch (offset: 10)
Tue, 27 Sep 2016 05:09:47 GMT | sent 5 objects to destination elasticsearch, wrote 0
Tue, 27 Sep 2016 05:09:47 GMT | got 5 objects from source elasticsearch (offset: 15)
Tue, 27 Sep 2016 05:11:47 GMT | sent 5 objects to destination elasticsearch, wrote 0
Tue, 27 Sep 2016 05:11:47 GMT | got 5 objects from source elasticsearch (offset: 20)
------------------------------------<<<<<>>>>>>---------------------------------------------------------------------

[publication_search.json.tar.gz](https://github.com/taskrabbit/elasticsearch-dump/files/494633/publication_search.json.tar.gz)

**Comment by evantahler** [comment]
Your attachment seems to be the data from your `publication_search` index.  How did you dump this data out?

**Comment by abhilashbolla-innoplexus** [comment]
using elasticdump... It was successful..

**Comment by evantahler** [comment]
If is successful, then is there a problem?

**Comment by raffi-minassian** [comment]
Check if some of your documents contain a field named _id . If they do, the write fails silently and you will get the result you are seeing because _id is a reserved field and can not be in your document. At least, I've seen similar situations and that was the cause in my cases.

**Comment by sarathgalimelu** [comment]
@raffi-minassian Hey Raffi I have the same problem in migrating data from one server to another, I am seeing the below error
``` sent 100 objects to destination elasticsearch, wrote 0 ```
The source server data will have the _id. Is there a way how I can migate the data when there is _id field.? Thanks in advance

**Comment by sarathgalimelu** [comment]
Hello @evantahler Can you suggest a way how can i insert the data from one server to another consisting of _id fields in the data. I am running the elasticdump query as below.
``` 
elasticdump --bulk=true --all --input=http://staging.example.co:9200/ --type=data --limit=1 --output=http://localhost:9200/ 
```

**Comment by raffi-minassian** [comment]
Hi @sarathgalimelu . It's been a while since I had to deal with it so I don't recall all the details, but ultimately I ended up writing a script that went through every document and changed the `_id` to just `id` and with that I was able to get around this issue.

I wrote that script with nodejs . I could try to hunt for it if you need but it should be relatively simple to recreate as well.

**Comment by nameraj** [comment]
I am getting same issue too 
elasticdump --input=test.json --output=http://localhost:9200/test --type=data --limit 100

Tue, 07 Nov 2017 17:19:51 GMT | starting dump
Tue, 07 Nov 2017 17:19:51 GMT | got 1 objects from source file (offset: 0)
Tue, 07 Nov 2017 17:19:51 GMT | sent 1 objects to destination elasticsearch, wrote 0
Tue, 07 Nov 2017 17:19:51 GMT | got 0 objects from source file (offset: 1)
Tue, 07 Nov 2017 17:19:51 GMT | Total Writes: 0
Tue, 07 Nov 2017 17:19:51 GMT | dump complete

I don't have any _id field in my json file. any other way i can try ? Thank you

**Comment by Amit-A** [comment]
I've got the same issue

Fri, 24 Nov 2017 03:14:03 GMT | starting dump
Fri, 24 Nov 2017 03:14:03 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 24 Nov 2017 03:14:04 GMT | sent 100 objects to destination elasticsearch, wrote 0
Fri, 24 Nov 2017 03:14:05 GMT | got 100 objects from source elasticsearch (offset: 100)
Fri, 24 Nov 2017 03:14:06 GMT | sent 100 objects to destination elasticsearch, wrote 0
Fri, 24 Nov 2017 03:14:06 GMT | got 100 objects from source elasticsearch (offset: 200)
Fri, 24 Nov 2017 03:14:07 GMT | sent 100 objects to destination elasticsearch, wrote 0
Fri, 24 Nov 2017 03:14:07 GMT | got 100 objects from source elasticsearch (offset: 300)
Fri, 24 Nov 2017 03:14:07 GMT | sent 100 objects to destination elasticsearch, wrote 0
(...)

I do see an _id field in my json file...
