### ISSUE TITLE
Problem with copying an index with file buffer in middle

### ISSUE THREAD

**Issue by gossel-j** [taskrabbit/elasticsearch-dump#262]
- ElasticDump v2.4.2
- Elasticsearch v2.3.1
- `elasticdump --input="http://localhost:9200/my_index" --output='$' | gzip | tee "my_index.json.gz" | gunzip | elasticdump --input='$' --output="http://localhost:9200/my_index_new"`

Basically, we are doing an elasticsearch migration from 1.5 to 2.3.1, after upgrading elasticsearch to 2.3.1 we want to reindex our data with new mapping (old_mapping_index -> temp_new_mapping_index,  DELETE old_mapping_index, temp_new_mapping_index -> new_mapping_with_old_name).

For the first step, we want to save the data on the disk in case of any error.

We already tried like this and it's works :

```
elasticdump --input="http://localhost:9200/my_index" --output="my_index.json"
elasticdump --input="my_index.json" --output="http://localhost:9200/my_index_new"
```

There is 2 things we don't like in this method
- The file is not gzip on the disk
- We need to do 2 steps, and it's long time

So we thought we can use stdin and stdout and some pipe magic like so :
`elasticdump --input="http://localhost:9200/my_index" --output='$' | gzip | tee "my_index.json.gz" | gunzip | elasticdump --input='$' --output="http://localhost:9200/my_index_new"`

Our index contains around 1 000 000 entries and this happen :

```
Wed, 28 Sep 2016 12:03:49 GMT | got 117 objects from source file (offset: 106499)
Wed, 28 Sep 2016 12:03:49 GMT | sent 117 objects to destination elasticsearch, wrote 117
Wed, 28 Sep 2016 12:03:49 GMT | got 116 objects from source file (offset: 106616)
Wed, 28 Sep 2016 12:03:49 GMT | sent 116 objects to destination elasticsearch, wrote 116
Wed, 28 Sep 2016 12:03:49 GMT | got 66 objects from source file (offset: 106732)
Wed, 28 Sep 2016 12:03:49 GMT | sent 66 objects to destination elasticsearch, wrote 66
Wed, 28 Sep 2016 12:03:49 GMT | got 0 objects from source file (offset: 106798)
Wed, 28 Sep 2016 12:03:49 GMT | Total Writes: 106798
Wed, 28 Sep 2016 12:03:49 GMT | dump complete
```

I think that the first elasticdump write a little slower at some moment and the second elasticdump just think there is no more data (even if no EOF, sadly...)

After reading your code, I think that breaking the "stream pipe pattern" with a "strange get callback recursion ..." is the problem.

**Comment by evantahler** [comment]
Can you point out an example in the code that is the `callback recursion`?   The file writer should be streaming all the way though.

**Comment by gossel-j** [comment]
I'm talking about this part of the code (https://github.com/taskrabbit/elasticsearch-dump/blob/master/elasticdump.js#L135).

I think that it would be better to transform the readers and writers with stream and transform this linking part (elasticdump.js) to a stream to, then you will just need to `input.pipe(elasticdump).pipe(output)` and let the streaming concept of node flow the information.

**Comment by evantahler** [comment]
That would be very cool! Let me know if you need help getting started on your pull request for this.

**Comment by gossel-j** [comment]
I'll try to work on this when I have some time. I think it will be quite a huge PR

**Comment by evantahler** [comment]
Closing due to lack of progress
