### ISSUE TITLE
MultiElasticDump documentation on the main page specifies default offset: 100

### ISSUE THREAD

**Issue by adammichalik** [taskrabbit/elasticsearch-dump#264]
On the project main page in the [MultiElasticDump section](https://www.npmjs.com/package/elasticdump#multielasticdump) it's specified that the default value for `offset` is 100 while [in fact it's 0](https://github.com/taskrabbit/elasticsearch-dump/blob/master/bin/multielasticdump#L39).

**Comment by evantahler** [comment]
It's correected https://github.com/taskrabbit/elasticsearch-dump/commit/6aa5b77d130706b22e6f7d816870c92f6fb16d8d.   It will be fixed on NPM in the next version
