### ISSUE TITLE
elasticdump hangs when using --offset option

### ISSUE THREAD

**Issue by hamazaspavetisyan** [taskrabbit/elasticsearch-dump#265]
Hi!
I have an issue when using the --offset option.
Here is the output of elasticdump in my case

starting dump
Warning: offseting 6382740 rows.
Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.

These are only log lines, then the tool hangs. No items are added in ES output, elasticdump process is idle in the processes list.
I am using ES version 1.4 (AWS). ED version is 2.4.2
My command line is 
./node_modules/elasticdump/bin/elasticdump --input=https://xxxxxx.us-west-2.es.amazonaws.com/goods --output=https://yyyyyy.us-west-2.es.amazonaws.com/goods --type=data --limit=4000 --offset=6382740

Access to ES domain is opened, so I do not need AWS keys as an options.

**Comment by evantahler** [comment]
see https://github.com/taskrabbit/elasticsearch-dump/issues/234#issuecomment-228423196

Right now, the "offset" option only effects the writer... we are still reading in the first N (6382740 in your case) documents.  No one has updated this functionally yet to "skip" as part of the initial elasticsearch query.

**Comment by lifekent** [comment]
Is there any update on this? Experiencing the same problem.

**Comment by hamazaspavetisyan** [comment]
Hi!
Actually I do not remember how fixed it. As I remember I have used Amazon
embedded tools for this and amazon's console.

**Comment by lifekent** [comment]
@hamazaspavetisyan Thanks for the reply, but it's pretty clear now for me from the [#234](https://github.com/taskrabbit/elasticsearch-dump/issues/234#issuecomment-228423196).

**Comment by ferronrsmith** [comment]
If your query is using the following limit clause: “LIMIT 50000, 20”, it’s actually requesting elastic-search to go through 50,020 rows and throw away the first 50,000. This action can have a high cost an impact response time. Which is still limited by `max_result_window`. A better solution would be to limit your result use `--searchBody`

**Comment by anapsix** [comment]
when working with interrupted import into ES (at offset 1231139) from file previously created via `--output=index_data.json`, I found it more helpful to use sed for generating offsetted input file, and continuing as usual
```
sed -n '1231139,$ p' index_data.json > index_data_next_part.json
elasticdump --input=index_data_next_part.json --output=... 
```
