### ISSUE TITLE
How to install this in Mac?

### ISSUE THREAD

**Issue by keeyonghan** [taskrabbit/elasticsearch-dump#266]
This package was something I really wanted to have and I wanted to run this in my Mac for testing but found it very hard to install in Mac. Is it possible? If so, there is any documentation on this?

**Comment by evantahler** [comment]
just `npm install elasticdump `?  
Assuming you have node.js installed.

**Comment by keeyonghan** [comment]
I found the documentation I was looking for at https://gist.github.com/DanHerbert/9520689.
