### ISSUE TITLE
Read http auth password from file

### ISSUE THREAD

**Issue by tarrow** [taskrabbit/elasticsearch-dump#269]
It would be nice if you could specify your http credentials other than on the command line. This is important because on a multi-user machine including credentials in the command line leaks them to the other users (including non-root) since anyone can see the whole command in the process list.

I saw this was suggested in #250 but making the tool non interactive was unpopular. It seems (but I've not used it) that you can specify credentials for AWS using a file so I thought it would be good to allow reading from a file for http credentials as well.

I've already hacked this in for my own use and I'd be happy to submit a PR if this is a direction you'd be interested in going in.

**Comment by evantahler** [comment]
Actually, https://github.com/taskrabbit/elasticsearch-dump/issues/250 didn't want to make the tool *interactive*.  It is presently non-interactive.   Please share your pull request so we can discuss it!
