### ISSUE TITLE
Add possibility to remove the index contents while restoring

### ISSUE THREAD

**Issue by keezeek** [taskrabbit/elasticsearch-dump#270]
Could it be possible to add an option to remove the output index contents while running elasticdump with these parameters:
`elasticdump --input=/data/my_index_data.json --output=http://production.es.com:9200/my_index`

**Comment by evantahler** [comment]
the `--delete` option will remove data from `--input` (so you can `mv` rather than `cp`).   Can you explain in more detail what you are asking for?

**Comment by keezeek** [comment]
I'm thinking about an option for restoring the index contents from the dumped json file.
When the destination index already exists and has some documents the `--restore` option would remove the index contents and then apply those from json file.

**Comment by evantahler** [comment]
Wouldn't that be the same thing as running `curl -X DELETE http://ES:9200/index` before your restore?

**Comment by evantahler** [comment]
Closing due to lack of response
