### ISSUE TITLE
Wildcard in index name

### ISSUE THREAD

**Issue by celesteking** [taskrabbit/elasticsearch-dump#271]
dump v5.0.1 , elastic 5.0.2 

For massive operations, you have to support [multi index](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/multi-index.html) syntax. There's just no other way. `curator` does it already.

`./bin/elasticdump --bulk --limit 5000  --type data --input 'http://xx:9200/smtp-*-2016-*' --output http://xx:9200/`

**Comment by evantahler** [comment]
The goal of elasticdump is to create backup files per index.  You can use [MultiElasticdump](https://github.com/taskrabbit/elasticsearch-dump#multielasticdump) which is included in this package to do more than one index in parallel.

The case you describe would be: `./bin/multielasticdump --limit 5000 --type data --input 'http://xx:9200' --match 'smtp-*-2016-*' --output 'http://xx:9200'`

**Comment by celesteking** [comment]
Yeah, this use case should really be documented. Like: If you need multiindex syntax, use this binary/version.

**Comment by celesteking** [comment]
Also, it doesn't work:

```
$ ./bin/multielasticdump  --limit 500  --type data --input http://xx:9200 --match 'smtp-transaction-2016-10-*' --output http://xx:9200/ | tee -a log.txt
Wed, 07 Dec 2016 12:54:54 GMT | We are performing : dump
Wed, 07 Dec 2016 12:54:54 GMT | options: {"debug":true,"parallel":4,"match":"smtp-transaction-2016-10-*","input":"http://xx:9200","output":"http://xx:9200/","scrollTime":"10m","limit":500,"offset":0,"direction":"dump"}
/home/kopf/elasticsearch-dump/bin/multielasticdump:76
  if (!fs.existsSync(options.output)) { throw new Error('--output does not exist') }
                                        ^

Error: --output does not exist
    at Object.<anonymous> (/home/kopf/elasticsearch-dump/bin/multielasticdump:76:47)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

**Comment by evantahler** [comment]
If you want to add more to the readme about this use case, please send in a pull request!

Can you un-obfuscate your output URL?  `  if (!fs.existsSync(options.output)) { throw new Error('--output does not exist') }` indicates that elasticdump thinks your output is a file descriptor not another URL.  There may be something wrong here if that is the case https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/is-url.js

**Comment by evantahler** [comment]
Oh! It looks like multielasticdump **only** supports dumping to files.  You will need to dump locally to files and then to your new cluster with this tool.  My mistake!

**Comment by jveldboom** [comment]
Here's a quick python script that does what you're trying to do - copy indices mapping & data with a wildcard.

```python
import subprocess

host_input='https://input-host.com:9200'
host_output='https://output-host.com:9200'
es_index='skynet-*'

# Get list of indices
output = subprocess.check_output("curl -s -XGET "+host_input+"/_cat/indices/"+es_index+" | awk '{print $3}'", shell=True)

# Loop through list of indices
for index in output.splitlines():
	print "STARTING MAPPING: "+index
	subprocess.call("docker run --rm -i taskrabbit/elasticsearch-dump \
		--input="+host_input+"/"+index+" \
		--output="+host_output+"/"+index+" \
		--type=mapping", shell=True)

	print "STARTING DATA: "+index
	subprocess.call("docker run --rm -i taskrabbit/elasticsearch-dump \
		--input="+host_input+"/"+index+" \
		--output="+host_output+"/"+index+" \
		--type=data", shell=True)
```
