### ISSUE TITLE
Not working with 5.0

### ISSUE THREAD

**Issue by celesteking** [taskrabbit/elasticsearch-dump#272]
Any errors sent by the sever should be printed, don't hide them, that makes the illusion everything works well while it doesn't.

So now I'm trying to use it against 5.0 and I see it's just not compatible. 

`./bin/elasticdump --limit 2 --type data --input http://xx:9200/$IDX --output http://xx:9200/`

Here's what I see with tcpdump (as I said, no errors thrown by the app - BAD)
```
PUT /_bulk HTTP/1.1
host: xx:9200
content-length: 4863
Connection: close

{"index":{"_type":"xx","_id":"38D3D7AF-0356-4E0B-9AC2-717D245B27C2.1"}}
{ ...doc ...
}
{"index":{"_type":"xx","_id":"8442A3B7-E260-45B4-A926-2DD446195E67.1"}}
{ ...doc ...
}
```
```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 273

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: index is missing;2: index is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: index is missing;2: index is missing;"},"status":400}
```

Why index missing? What is going on?

**Comment by dmc2015** [comment]
@evantahler why was this closed?
