### ISSUE TITLE
Log is not disabled when using stdout

### ISSUE THREAD

**Issue by MOZGIII** [taskrabbit/elasticsearch-dump#274]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 3.0.1
- Elasticsearch version: 5.0
- Full command you are having issue with (with inputs and outputs): 
```shell
exec node_modules/.bin/elasticdump \
  "--input=${ELASTIC_URL}/.kibana" \
  "--output=${OUPUT_FILE}" \
  --type=data \
  --searchBody='{
    "query": {
      "terms": {
        "_type": [
          "dashboard",
          "search",
          "visualization"
        ]
      }
    }
  }'
```
Where `ELASTIC_URL=http://127.0.0.1:1234` and `OUPUT_FILE='$'`

- A data set you can share publicly which reproduces the problem: any default kibana index should render the same.

What I expect:
The results of the query printed to stdout without logs.

What I get:
The results of the query printed to stdout *with* logs among them.

Sample output:
```
Tue, 13 Dec 2016 21:58:16 GMT | discovered elasticsearch input major version: 5
{"_index":".kibana","_type":"search","_id":"redacted","_score":1,"_source":{"title":"redacted","description":"","hits":0,"columns":["sql","duration"], ...
```

**Comment by MOZGIII** [comment]
Here's a link to my project to see what's exactly going on https://github.com/MOZGIII/hopkibana

**Comment by evantahler** [comment]
great find!
Those new ES version log messages were added recently, and to the wrong output level.

Thanaks!

**Comment by evantahler** [comment]
fixed here https://github.com/taskrabbit/elasticsearch-dump/commit/c275994c0a2f9401cfdfec8bf86ffe19118fee63

**Comment by MOZGIII** [comment]
Nice. :tada:
