### ISSUE TITLE
Logging to stderr?

### ISSUE THREAD

**Issue by MOZGIII** [taskrabbit/elasticsearch-dump#275]
We could log to stderr while still using stdout for output.

**Comment by evantahler** [comment]
We would need to ensure that only errors are reported to STDERR, and not just regular logs. Many tools treat the existence of anything on STDERR as... and error

Is this something you want to tackle? Let me know if you need help getting started.

**Comment by MOZGIII** [comment]
I'd like to help with this, but I'm overloaded with the job right now, so, unfortunately, I pass.

**Comment by evantahler** [comment]
Then I'll close this request.  Please submit a pull request with this new feature if you get around to it!

**Comment by MOZGIII** [comment]
Okay. If someone else is reading this, feel free to implement this feature! :)
