### ISSUE TITLE
Hey, I'm trying to load a index but elasticdump shows 0 writes dump complete.

### ISSUE THREAD

**Issue by jainsaransh** [taskrabbit/elasticsearch-dump#277]
Please help me out with this problem i am working on it from past three days. i have installed x-pack too. so when i am trying to run elasticdump command for mapper, it gives "missing authentication token for rest request".

- ElasticDump version -- 3.0.2
- Elasticsearch version -- 5.1.1
- Full command you are having issue with (with inputs and outputs)
INPUT : elasticdump --input=http://localhost:9200/my_index/  --output=http://104.199.158.158:9200/my_index/ --type=data --limit=1000

OUTPUT : 
got 1000 objects from source elasticsearch (offset: 3000)
sent 1000 objects to destination elasticsearch, wrote 0
got 640 objects from source elasticsearch (offset: 4000)
sent 640 objects to destination elasticsearch, wrote 0
got 0 objects from source elasticsearch (offset: 4640)
Total Writes: 0
dump complete

**Comment by alekbarszczewski** [comment]
👍  I have same issue - "wrote" is always 0 and no documents are transfered...

**Comment by evantahler** [comment]
there is no support what-so-ever for x-pack in this tool.  Please add it if you can!

**Comment by evgf** [comment]
Works fine with ElasticSearch 5.1.1 and X-Pack.
Just make sure that you specified the username and password in the ElasticSearch URL:
`--input=http://localhost:9200/my_index --output=http://elastic:your_password@104.199.158.158:9200/my_index --limit 5000 --type=data`

**Comment by evantahler** [comment]
Ah! so x-pack uses basic web auth.  Handy!

**Comment by jainsaransh** [comment]
@evgf 
thanks it worked for me
