### ISSUE TITLE
get error ''JavaScript heap out of memory" when i import data from json file to elasticsearch

### ISSUE THREAD

**Issue by showmeall** [taskrabbit/elasticsearch-dump#278]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 3.0.2
- Elasticsearch version 2.4.0
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

detail error:
<--- Last few GCs --->

 1145104 ms: Mark-sweep 1389.2 (1434.0) -> 1389.1 (1434.0) MB, 975.4 / 0.0 ms [allocation failure] [scavenge might not succeed].
 1146280 ms: Mark-sweep 1389.2 (1434.0) -> 1389.1 (1434.0) MB, 1175.0 / 0.0 ms (+ 0.4 ms in 1 steps since start of marking, biggest step 0.4 ms) [allocation failure] [scavenge might not succeed].
 1147268 ms: Mark-sweep 1389.2 (1434.0) -> 1389.1 (1434.0) MB, 987.4 / 0.0 ms [allocation failure] [scavenge might not succeed].

<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0xdecf4c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]

**Comment by evantahler** [comment]
closing in favor of https://github.com/taskrabbit/elasticsearch-dump/issues/160#issuecomment-269743946
