### ISSUE TITLE
get 'dump ended with error (set phase)  => Error: read ECONNRESET' error,

### ISSUE THREAD

**Issue by showmeall** [taskrabbit/elasticsearch-dump#279]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 3.0.2
- Elasticsearch version 2.4.0
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

when i import data from json file to ES, get eorro, please help me .
Sun, 01 Jan 2017 09:19:38 GMT | Error Emitted => read ECONNRESET
Sun, 01 Jan 2017 09:19:38 GMT | Total Writes: 1918
Sun, 01 Jan 2017 09:19:38 GMT | dump ended with error (set phase)  => Error: read ECONNRESET

**Comment by showmeall** [comment]
i fund the problem, it due to elasticsearch limit , add config "http.max_content_length: 500mb" , it is working now

**Comment by xkcoding** [comment]
add `http.max_content_length: 500mb` to elasticsearch.yml ?? @showmeall
