### ISSUE TITLE
Feature Request : support exporting aliases

### ISSUE THREAD

**Issue by bondib** [taskrabbit/elasticsearch-dump#285]
This is required in order to correctly export full index configuration properly.

**Comment by AtzeDeVries** [comment]
same here, getting this error:

Fri, 03 Feb 2017 14:35:30 GMT | {}

/usr/lib/node_modules/elasticdump/elasticdump.js:79
    self.log("got " + data.length + " objects from source " + self.inputType +
                          ^
TypeError: Cannot read property 'length' of null
    at /usr/lib/node_modules/elasticdump/elasticdump.js:79:27
    at elasticsearch.get (/usr/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:23:9)
    at elasticdump.dump (/usr/lib/node_modules/elasticdump/elasticdump.js:77:14)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/bin/elasticdump:59:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by ferronrsmith** [comment]
Due to almost a year without response I am closing.
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by ferronrsmith** [comment]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Node.js version
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

**Comment by MaLub** [comment]
+1 for this feature. I've to manually generate any aliases.

**Comment by ferronrsmith** [comment]
There isn't enough details in the issue, hence the reason for the above comment. Either you use the full index name or provide a proper description and details as to what the issue is.

**Comment by MaLub** [comment]
Yes, would make your product greater ;) 

In our project we make intensive use of the alias feature from elastic.
(https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-aliases.html)
 
Would be very helpful if it's possible to dump it also. (maybe as another type)

**Comment by ferronrsmith** [comment]
@MaLub I have added support for alias export on the branch `feature/alias` feel free to test. The format is as follows

```bash
# if alias-filter is not present the glob pattern '*' will be used.
elasticdump --input=http://localhost:9200/index-name/alias-filter --output $ --type=alias
```

**Comment by MaLub** [comment]
@ferronrsmith cool :thanks.
Export of an alias works fine for me.
Import of this alias throws an error:

[devel bin]$ ./elasticdump --debug --input=alias.json --type=alias --output=http://localhost:9200
Thu, 19 Apr 2018 08:29:53 GMT | starting dump
Thu, 19 Apr 2018 08:29:53 GMT | got 1 objects from source file (offset: 0)
Thu, 19 Apr 2018 08:29:53 GMT [debug] | discovered elasticsearch output major version: 2
Thu, 19 Apr 2018 08:29:53 GMT | Error Emitted => unknown type option
Thu, 19 Apr 2018 08:29:53 GMT | Total Writes: 0
Thu, 19 Apr 2018 08:29:53 GMT | dump ended with error (set phase)  => Error: unknown type option

**Comment by ferronrsmith** [comment]
There is no import yet. I haven’t pushed that code as yet.

**Comment by MaLub** [comment]
Thank you, works!

**Comment by Moulick** [comment]
@ferronrsmith is there any plan to support exporting the alias(s) also ? That would be awesome
