### ISSUE TITLE
Question regarding scroll API

### ISSUE THREAD

**Issue by ChaosMTA** [taskrabbit/elasticsearch-dump#294]
I'm sorry if this is the wrong place or if this just annoys you all, I just had a question as the README doesn't offer a lot of explanation.

I have a large index that I need to backup and I want to use the scroll API to do it so it is speedy, how can I do this with elasticdump? The README says you support it but I'm not sure how to actually use it.

**Comment by evantahler** [comment]
The scroll API is what this toll uses under the hood.
