### ISSUE TITLE
Do delete work?

### ISSUE THREAD

**Issue by danielmotaleite** [taskrabbit/elasticsearch-dump#297]
Elasticsearch-dump 3.1.0
Elasticsearch 5.2.2

Command:  
./bin/elasticdump --httpAuthFile /tmp/auth.tmp   --format=human  --input=http://192.168.106.3:9200/logstash-*-nginx-access-live   --output=jumia.json  --searchBody ' {  "query": {  "bool": { "must": [ { "query_string": { "query": "create AND  mobapi", "analyze_wildcard": true } } ], "must_not": []  }  } } ' --limit 1000 --delete=true

I run this, i got about 380k events, all info is  perfect... but the delete didn't happen, i can still search for that same query in kibana and the 380k hits

So i'm doing something wrong or --delete is not working in this ES version or for file output?

Thanks for the help and for elasticsearch-dump

**Comment by datashaman** [comment]
Use `--delete`, not `--delete=true`. Please re-open if this is still an issue.
