### ISSUE TITLE
dumping mappings into pipe does'nt work fine

### ISSUE THREAD

**Issue by theundefined** [taskrabbit/elasticsearch-dump#300]
I'm trying to use elasticdump to backup purpose. Backup of data - works fine. But backup of mappings doesn't work like expected. When i do backup into file or another ES instance - it's ok. When i use as output $ and doesn't pipe it - it works fine. But when i'm using output $ and do any piping (gzip or even cat command) - it's trimmed

wrong:
```
# elasticdump --input=${url}/logstash-2017.02 --output=$ --type=mapping  |tail -c 10
:{"type":"# 
# elasticdump --input=${url}/logstash-2017.02 --output=$ --type=mapping |wc 
      0       1   65536
```
ok:
```
# elasticdump --input=${url}/logstash-2017.02 --output=$ --type=mapping  >x
# cat x |tail -c 10
"}}}}}}}}
# cat x |wc
      1       1  109980
```

- ElasticDump version 3.1.0
- Elasticsearch version 2.3.5

**Comment by ferronrsmith** [comment]
elasticdump returns data in **jsonl** format, If you need to count, pipe it to a formatter like jq, then call count. 
```bash
elasticdump --input=${url}/logstash-2017.02 --output=$ --type=mapping | jq . | |wc 
```

Closing this issue. This is an issue with elasticdump.
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by theundefined** [comment]
how can i reopen it? It's not problem with wc :-) I  used wc only to size in bytes. Look at end of output and last chars (tail -c).

**Comment by ferronrsmith** [comment]
actually it's correct. `tail -c 10` limits bytes not lines `tail -n 10`. In any this isn't an issue with `elasticdump`

**Comment by ferronrsmith** [comment]
```bash
$ elasticdump --input=http://localhost:9200/metrics-2017.07.28 --output $ --type=mapping | tail -c 10
# ng"}}}}}}

$ elasticdump --input=http://localhost:9200/metrics-2017.07.28 --output $ --type=mapping | tail -c 10 | wc
#  1       1      10
````
