### ISSUE TITLE
Enhancement: Custom Request Headers

### ISSUE THREAD

**Issue by glenselle** [taskrabbit/elasticsearch-dump#306]
I'm interested in submitting a PR to allow passing custom headers. `this.baseRequest` already adds a custom user agent header for the elasticsearch transport, but I need to add other custom headers to get through a proxy which sits in front of an ES instance. 

lib/transports/elasticsearch.js:14
```
  this.baseRequest = request.defaults({headers: { 'User-Agent': 'elasticdump' }})
```

Would you accept a PR if I made adding custom headers an option?

**Comment by evantahler** [comment]
of course! be sure to add a test for it.

**Comment by glenselle** [comment]
So it looks like I could either add the headers similarly to the way it's adding `maxSockets` 

```
if (options.maxSockets) {
    self.log('globally setting maxSockets=' + options.maxSockets)
    http.globalAgent.maxSockets = options.maxSockets
    https.globalAgent.maxSockets = options.maxSockets
  }
```

Or I could pass the options through to the input and output protos and have the elasticsearch transport add the header like it adds the user agent header. However, doing this is a little tricky since the file transport has no concept of headers. And the means of instantiating the transport protos is always the same -- no differentiation between file, elasticsearch or anything else. They're all passed the same args. If I change the args being passed (or change it to just an object so the proto function signature is consistent for all transports), that would break any external input or output transport. Unless, I only change the internal input/output proto instantiation and leave the external one alone with the same args. Hopefully that makes sense. Do you have a preference on how I tackle this?

**Comment by evantahler** [comment]
Closed by https://github.com/taskrabbit/elasticsearch-dump/pull/315
