### ISSUE TITLE
Error emitted : docker container install

### ISSUE THREAD

**Issue by pavithrachandrakasu** [taskrabbit/elasticsearch-dump#308]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version  latest
- Elasticsearch version 5.0
- Full command you are having issue with (with inputs and outputs)
sudo docker run --rm -ti -v /tmp/elastic_backup:/tmp/elastic_backup taskrabbit/elasticsearch-dump
Mon, 10 Apr 2017 15:30:39 GMT | Error Emitted => {"errors":["`input` is a required input","`output` is a required input"]}

- A data set you can share publicly which reproduces the problem

**Comment by martinpetrasch** [comment]
I solved this issue by changing the Dockerfile to something like this and build it locally:
```
FROM node:boron
RUN npm install elasticdump -g
CMD elasticdump -help
```
