### ISSUE TITLE
how to use fileds

### ISSUE THREAD

**Issue by fanyoujian** [taskrabbit/elasticsearch-dump#310]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump 2.4.2
- Elasticsearch 2.3.3

./elasticdump --input=http://127.0.0.1:9200/domain6 --output=query1.json --debug=true --limit=1 --offset=0 --searchBody='{"query":{"range":{"id":{"lte":"80"}}},"fields": ["id"], "_source": true}' --sourceOnly=true

this result:
{"id":31,"host":"4yt.net","cname":null,"ename":null}

but I want only this id ,how to change?

**Comment by fanyoujian** [comment]
this question had Ok.

**Comment by datashaman** [comment]
"_source": "id" or "_source": "_id", can't remember which.

**Comment by datashaman** [comment]
fields says which fields are queried, not returned. source says which fields are returned.
