### ISSUE TITLE
why elasticdump has not size ？

### ISSUE THREAD

**Issue by fanyoujian** [taskrabbit/elasticsearch-dump#311]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump 2.4.2
- Elasticsearch 2.3.3

How to limit the total number of acquisitions？For example, I would like to get the first 100 data，how to use it?

**Comment by marcelopm** [comment]
:+1:

**Comment by evantahler** [comment]
closed by https://github.com/taskrabbit/elasticsearch-dump/pull/363
