### ISSUE TITLE
--delete should not to delete data, that not indexed

### ISSUE THREAD

**Issue by darky** [taskrabbit/elasticsearch-dump#314]
- ElasticDump version: 3.1.0
- Elasticsearch version: 5.1.1
- Full command you are having issue with (with inputs and outputs)

`elasticdump --input=http://localhost:9200/test1 --output=http://localhost:9200/test2 --type=data --delete`

- A data set you can share publicly which reproduces the problem

Index **test1** mapping: 

```
{"properties":{"test":{"type":"float"}}}
```

Index **test2** mapping:

```
{"properties":{"test":{"type":"boolean"}}}
```

Put some data with `float` values in index **test1** and try to move it in index **test2**
Data will not be moved, because incorrect mapping errors occured.
But data will be removed from index **test1**
**DATA WILL BE LOSED!!!**

**Comment by ferronrsmith** [comment]
After reviewing the code-base I see the issue here. input & output operations are independent.
So while output was successful. input was not. 

Advice stream first, then ensure that all the data was indexed properly then delete.
