### ISSUE TITLE
Ability to deactivate `refresh` call

### ISSUE THREAD

**Issue by darky** [taskrabbit/elasticsearch-dump#318]
- ElasticDump version: 5.1.1
- Elasticsearch version: 3.2.0
- Full command you are having issue with (with inputs and outputs)

Any, where data reindexed

- A data set you can share publicly which reproduces the problem

TL;DR: Need option `--noRefresh`, which cause not calling `reindex` method: https://github.com/taskrabbit/elasticsearch-dump/blob/9064b44c95adaaba4c650f5e906ebe9ebf514bf3/lib/transports/elasticsearch.js#L458-L470

More info:
I notice, that before get new batch of data, Elastic "refresh" command calls 
I understand, that you want to get fresh data and guarantee relevance of data.
But on big data and when many-many writes per second it slows down reindex process **more than 10 times** and, worse than that, **destroy your system** via high CPU usage, poor indexing speed, shard conflicts and other bad side effects.
When I reindex millions of data, no need call "refresh" on each get. My prior is speed and stability, not relevance. Especially, I will be reindex again, when first ended, but data will be much less. And when data will be little, I want to use "refresh" for getting last relevance.

**Comment by evantahler** [comment]
Great idea!  Please send in a pull request for this option.

**Comment by darky** [comment]
Will be available in `>3.2.0`, thanks!
