### ISSUE TITLE
Why do you ignore the _index in the dump

### ISSUE THREAD

**Issue by alrooney** [taskrabbit/elasticsearch-dump#322]
someone commented this out:

https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L385

which causes the resulting bulk upload to not have _index set.  This means that this does not work with aliases which span multiple indexes.  Is there a reason why this was commented out?  Why not make this a command-line option instead?

**Comment by datashaman** [comment]
:+1:  any specific reason it was removed, @evantahler ? It should still do the correct thing if it is used.

**Comment by evantahler** [comment]
From the comment `Not setting _index should use the one defined in URL.`, so this indicates that we want to allow folks to change the index name as part of the dump, and use the index as defined in the URL to elasticdump.  If this was enabled, you wouldn't be able to move `index` to `index-backup` on the same server, for example

**Comment by ferronrsmith** [comment]
Please re-open if you do not feel the question has been answered sufficiently.
