### ISSUE TITLE
--transform shall try value as file first

### ISSUE THREAD

**Issue by darkclad** [taskrabbit/elasticsearch-dump#324]
For complex transformations it is better to have transform read javascript file.
Suggested fix:

4 var fs=require('fs')
...
83:   if (fs.existsSync(transform)) {   transform = fs.readFileSync(transform, 'utf8')  }

**Comment by datashaman** [comment]
I suggest using the '@' prefix like curl does.

**Comment by evantahler** [comment]
closing in favor of https://github.com/taskrabbit/elasticsearch-dump/pull/325

**Comment by datashaman** [comment]
thanks, it should be passing soon-soon. just fixing a few small problems. :)
