### ISSUE TITLE
Syntax Error Ln 54 elasticdump

### ISSUE THREAD

**Issue by ghostnc** [taskrabbit/elasticsearch-dump#327]
I'm getting a consistent error whenever I run the `elasticdump` command

```
/usr/local/lib/node_modules/elasticdump/bin/elasticdump:52
for (var i of jsonParsedOpts) {
           ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

- NPM 1.3.10
- Nodejs v0.10.25
- ElasticDump version 3.3.0
- Elasticsearch 1.5.0 (seperate server)
- Doing a simple `elasticdump` command

**Comment by datashaman** [comment]
The utility is tested against nodejs versions 4 and 6.

0.10.* is quite old now.

Consider upgrading or using nvm if you need to support multiple versions of node.

**Comment by datashaman** [comment]
Also, it seems that 3.* Is not suitable for ES 1.5. Check the README file.
