### ISSUE TITLE
How to import Kibana Visualization and Dashboard usign elasticdump

### ISSUE THREAD

**Issue by Git-Rajkumar** [taskrabbit/elasticsearch-dump#329]
I have import  Kibana Visualization and Dashboard using elasticdump,  please refer this link

  https://discuss.elastic.co/t/how-to-import-kibana-visualization-and-dashboard/87128

**Comment by datashaman** [comment]
Hi, As discussed after your post on that thread, did you have any success dumping mappings and data, and then importing mapping before data?

It seems from that thread that using elasticdump for your purposes will cause issues.

Please close this issue if your problem is resolved.
