### ISSUE TITLE
Invalid JSON issue caused by Proxy settings

### ISSUE THREAD

**Issue by antonsar** [taskrabbit/elasticsearch-dump#331]
Hello, 

This is my first time using this tool so I am hoping I'm missing something obvious.

After reading the docs, I installed and tested this on my existing indices.  I immediately got an error when trying something simple like this:

./elasticdump   --input=http://localhost:9200/my_index/   --output=./my_output

> Thu, 01 Jun 2017 23:02:45 GMT | starting dump
> Thu, 01 Jun 2017 23:02:45 GMT | Error Emitted => Invalid protocol: web-proxy.bla.bla.com:
> Thu, 01 Jun 2017 23:02:45 GMT | Total Writes: 0
> Thu, 01 Jun 2017 23:02:45 GMT | dump ended with error (get phase) => Error: Invalid protocol: web-proxy.bla.bla.com:

This error went away after I set/export  HTTP_PROXY env

However now I am getting a syntax error because the result is not a valid JSON. 

When I hit http://localhost:9200/my_index/ it returned valid JSON to me .  However this tool seems to be rerouted somewhere and instead of getting JSON it seems to get an HTML page. 

> Thu, 01 Jun 2017 23:15:30 GMT | starting dump
> undefined:1
> < HTML >< HEAD > 
> ^
> 

When I tweaked my Proxy settings to an auto proxy, it gave me the same syntax error regarding JSON validation but the line that it shows is actually a line directly from the auto proxy script.. 

> [ant@localhost bin]$ ./elasticdump   --input=http://localhost:9200/my_index/   --output=./my_index_mapping.json  
> Thu, 01 Jun 2017 21:57:42 GMT | starting dump
> undefined:1
> //////////////////////////////////////////////////////////////////////
> ^
> 
> SyntaxError: Unexpected token / in JSON at position 0
>     at Object.parse (native)
>     at Request._callback (/home/ant/node_modules/elasticdump/lib/transports/elasticsearch.js:52:21)
>     at Request.self.callback (/home/ant/node_modules/request/request.js:188:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (/home/ant/node_modules/request/request.js:1171:10)
>     at emitOne (events.js:96:13)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (/home/ant/node_modules/request/request.js:1091:12)
>     at IncomingMessage.g (events.js:292:16)

I am baffled as to why it ended up downloading the proxy though.  Especially since I could hit it via browser, wget, curl just fine. 

Any ideas as to what I may have done wrong ? 

Thank you!!

**Comment by antonsar** [comment]
I figured it out!!! of course right after I made this post... but hopefully this will be helpful to others out there. 

I found that if I have already configured proxy in npm via npm config set proxy.  I need to wipe out my HTTP_PROXY, sets it to ""

If the HTTP_PROXY is set, then it will ended up downloading it for some reason.  This could be a bug with the tool maybe

**Comment by datashaman** [comment]
I think the application did the correct thing here, it threw an error when then the input was not the expected JSON, yes?

**Comment by alecrobins** [comment]
Thanks @antonsar. Setting `HTTP_PROXY=""` worked for me 👌

**Comment by AydinChavez** [comment]
just a side node: Setting HTTP_PROXY to an empty value didn't work for me, I had to unset it completely via unset command
