### ISSUE TITLE
Password contains @

### ISSUE THREAD

**Issue by ajvs** [taskrabbit/elasticsearch-dump#335]
- ElasticDump version: 3.3.1
- Elasticsearch version: 5.2.0
- Command:
elasticdump --input=https://name:passwordwithat@#123@url.com:9200/index --output http://localhost:9203/dev --type mapping

I'm having trouble when my input url needs basic authentication and the credentials contains '@'. Is there a way to escape the first @?
If it can't be escaped, can you provide a workaround? 

*I can't make --headers work. If you could provide the syntax for that it would be great.

Thanks!

**Comment by evantahler** [comment]
does `--input="https://name:passwordwithat@#123@url.com:9200/index"` not work?  what shell are you using?

**Comment by ajvs** [comment]
It doesn't. I think anything after the first @ becomes the url. I'm on windows 10.

C:\>elasticdump --input=https://name:@pass!#@word@this.url:9200/test --output=http://localhost:9200/test --type=mapping
Sat, 01 Jul 2017 01:44:35 GMT | starting dump
Sat, 01 Jul 2017 01:44:51 GMT | Error Emitted => getaddrinfo ENOTFOUND pass pass:443
Sat, 01 Jul 2017 01:44:51 GMT | Total Writes: 0
Sat, 01 Jul 2017 01:44:51 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND pass pass:443

**Comment by datashaman** [comment]
Probably need to escape the @ somehow in the password.

**Comment by datashaman** [comment]
https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls#6718568

says that is needs to be urlencoded.

**Comment by datashaman** [comment]
it's not possible to cleanly or safely urlencode the whole input URL, because I can't tell where names and passwords begin for certain, which is why urlencoding is required.

It must be done by the user of the app (or we use an input array for the parts, which sounds worse).

Install something like [urlencode-cli](https://github.com/yassh/urlencode-cli) to use like this:

    --input=https://$(urlencode name):$(urlencode password)@host:9200/test

You could add an alias of `u` in bash:

    alias u=urlencode
