### ISSUE TITLE
Import from file silently ignores data

### ISSUE THREAD

**Issue by prismec** [taskrabbit/elasticsearch-dump#339]
- ElasticDump version -> 3.3.1
- Elasticsearch version -> 5
- Full command you are having issue with (with inputs and outputs) -> elasticdump --input=metrics-2017.07.28-errors.json --output=http://localhost:9200/metrics-2017.07.28
- A data set you can share publicly which reproduces the problem ->
[metrics-2017.07.28-errors.json.txt](https://github.com/taskrabbit/elasticsearch-dump/files/1214129/metrics-2017.07.28-errors.json.txt)

Data is silently ignored - not everything is imported. Dump was created using elasticdump. 

```
$ cat metrics-2017.07.28-errors.json | wc -l
     865
$ elasticdump --input=metrics-2017.07.28-errors.json --output=http://localhost:9200/xxx
Thu, 10 Aug 2017 08:24:36 GMT | starting dump
Thu, 10 Aug 2017 08:24:36 GMT | got 100 objects from source file (offset: 0)
Thu, 10 Aug 2017 08:24:36 GMT | sent 100 objects to destination elasticsearch, wrote 100
Thu, 10 Aug 2017 08:24:36 GMT | got 255 objects from source file (offset: 100)
Thu, 10 Aug 2017 08:24:36 GMT | sent 255 objects to destination elasticsearch, wrote 255
Thu, 10 Aug 2017 08:24:36 GMT | got 256 objects from source file (offset: 355)
Thu, 10 Aug 2017 08:24:36 GMT | sent 256 objects to destination elasticsearch, wrote 256
Thu, 10 Aug 2017 08:24:36 GMT | got 255 objects from source file (offset: 611)
Thu, 10 Aug 2017 08:24:36 GMT | got 0 objects from source file (offset: 611)
Thu, 10 Aug 2017 08:24:36 GMT | Total Writes: 611
Thu, 10 Aug 2017 08:24:36 GMT | dump complete
```

**Comment by datashaman** [comment]
This one has me stumped! There are a few issues here:

* Why is it getting 255 and 256 objects from the source file, when the limit is 100?
* Why is it not writing the one batch of objects? The last full batch is unwritten, leaving the destination short of 255 objects.

As far as I can tell, the server receives the call to put those documents in using the bulk API. Things get hazy and difficult to follow inside those transport modules though.

I need to examine this more.
