### ISSUE TITLE
dump a very big index as json file

### ISSUE THREAD

**Issue by mikolaje** [taskrabbit/elasticsearch-dump#340]
- ElasticDump version  3.3.1
- Elasticsearch version  5.2.2

Hi ,I have a question ,if I want to dump a very large index (about 10 million rows  and about 30GB in storage)
I m using the command as below:

```
elasticdump \
  --input=http://elastic:changeme@localhost:9200/my_index \
  --output=/data/data.json \
  --type=data \
  --limit=2000 \
  --quiet=true

```
### The question is it would take a very long time to run and it was stuck in the end.how should I do if I want to dump it as a big Json File?

 My server configuration is 1CPU 2G RAM

Thank you very much

**Comment by ferronrsmith** [comment]
If the file stuck at the end. Usually you can wait until the server exits.

**Comment by ferronrsmith** [comment]
Closing this issue. 
Please re-open if you do not feel the question has been answered sufficiently.
