### ISSUE TITLE
 Error Emitted => getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by dalekurt** [taskrabbit/elasticsearch-dump#342]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: v3.3.1
- Elasticsearch version: 2.3

I have a number of index within my ElasticSearch cluster and have written a bash script to migrate the analyzer, data and mapping for each. with the following: 

`docker run --rm -ti taskrabbit/elasticsearch-dump --awsAccessKeyId=XMYACCESSKEYID --awsSecretAccessKey=YMYSECRETACCESSKEY --input=https://search-myproject-prod-xxxxxxxxxxxxxxxxx.us-west-2.es.amazonaws.com/myindex --output=http://myprivateserver:9200 --type=analyzer`

Log message

Analyzer for myindex
Fri, 08 Sep 2017 13:59:11 GMT | starting dump
Fri, 08 Sep 2017 13:59:16 GMT | Error Emitted => getaddrinfo EAI_AGAIN https://search-myproject-prod-xxxxxxxxxxxxxxxxx.us-west-2.es.amazonaws.com:443
Fri, 08 Sep 2017 13:59:16 GMT | Total Writes: 0
Fri, 08 Sep 2017 13:59:16 GMT | dump ended with error (get phase) => Error: getaddrinfo EAI_AGAIN https://search-myproject-prod-xxxxxxxxxxxxxxxxx.us-west-2.es.amazonaws.com:443

I'm having this issue which seems to be with the URL but I'm not sure. Have I done something wrong?

**Comment by datashaman** [comment]
According to the manpage for _getaddrinfo_ EAI_AGAIN means the following:
```
The name server returned a temporary failure indication.  Try again later.
```
I would suggest trying to manually browse to either of those URL endpoints to see if there's an issue with retrieving them generally.

**Comment by like-inspur** [comment]
I use elasticsearch dump in kubernetes, also brings error like this:
W1212 18:27:02.811096  284172 cmd.go:392] log is DEPRECATED and will be removed in a future version. Use logs instead.
Tue, 12 Dec 2017 10:23:48 GMT | starting dump
Tue, 12 Dec 2017 10:23:53 GMT | Error Emitted => getaddrinfo EAI_AGAIN elasticsearch:9200
Tue, 12 Dec 2017 10:23:53 GMT | Total Writes: 0
Tue, 12 Dec 2017 10:23:53 GMT | dump ended with error (get phase) => Error: getaddrinfo EAI_AGAIN elasticsearch:9200

**Comment by ferronrsmith** [comment]
`docker run --net=host --rm taskrabbit/elasticsearch-dump`

Use the `--net=host` and see if the issue still persist

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
