### ISSUE TITLE
elasticsearch support aggs query???

### ISSUE THREAD

**Issue by fanyoujian** [taskrabbit/elasticsearch-dump#345]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

**Comment by ferronrsmith** [comment]
Closing this issue. 
Please re-open if you do not feel the question has been answered sufficiently.
