### ISSUE TITLE
index.mapping.total_fields.limit setting is not preserved

### ISSUE THREAD

**Issue by cRUSHr2012** [taskrabbit/elasticsearch-dump#351]
elasticdump  : version: 3.3.1
Elasticsearch version : source  5.5.1.1 (1 node) destination 5.6.2.1 (3 nodes)

Exporting the **--type=analyzer** in a file, exports the **index.mapping.total_fields.limit** setting.
However, importing the file in the destination elasticsearch does not preserve the setting. Also does not work when source and destination are both ES instances.
This leads to :
`java.lang.IllegalArgumentException: Limit of total fields [1000] in index [products-whole-07] has been exceeded`
when migrating large mappings.

How to reproduce :
Add **mapping.total_fields.limit** setting:
```
[root@elas-01 ~]# curl -XPUT 'localhost:9200/products-7/_settings' -H 'Content-Type: application/json' -d'
{
  "index" : {
    "mapping" : {
     "total_fields" : {
       "limit" : "9000"
                       }
                }
             }
}'
```

Check (on source ES):
**[root@elas-01 ~]# curl -XGET 'localhost:9200/products-7/_settings?pretty'**
```
{
  "products-7" : {
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "9000"
          }
...
```
Export to file command:
`elasticdump  --input=http://elas-01:9200/products-7 --output=$ --limit=999 --type=analyzer > products_analyzer.json `
The **products_analyzer.json** file contains the setting:
```
...
"{\"attributes-whole-07\":{\"settings\":{\"index\":{\"mapping\":{\"total_fields\":{\"limit\":\"9000\"}},
...
```

Import file to ES command:
`elasticdump --input=products_analyzer.json --output=http://es-01:9200/products-7 --type=analyzer `
Verification (on destinaton ES):
[root@es-01 ~]# curl -XGET 'localhost:9200/products-7/_settings?pretty'
(**index.mapping.total_fields.limit**  is missing)
```
{
  "produts-7" : {
    "settings" : {
      "index" : {
        "creation_date" : "1507120679468",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "iWqjWxADTSWrhe-pSWwIUg",
        "version" : {
          "created" : "5060299"
        },
        "provided_name" : "products-7"
      }
    }
  }
}
```

**Comment by tim-ledsam** [comment]
I think this may be related [to the issue (352) I just raised](https://github.com/taskrabbit/elasticsearch-dump/issues/352) - were there any other values in your settings (e.g. an `analysis` field alongside your `mappings` one)?

**Comment by cRUSHr2012** [comment]
In my case https://github.com/taskrabbit/elasticsearch-dump/issues/351 <https://github.com/taskrabbit/elasticsearch-dump/issues/351> the analyzers / filters are preserved.
You can try to dump the —type=index in to a file and the examine it’s contents. Then try to import from that file. 

M. Bogdan
bogdangm@gmail.com

**Comment by tim-ledsam** [comment]
Ah, sorry, I deleted my comment, as, on replicating your above instructions, it did work, so it wasn't  relevant - it's not the same thing. (For reference, the comment was looking at linking this to the issue in issue 352).

However, I can replicate the issue you've posted above with my own indexes.

**Comment by ferronrsmith** [comment]
The output returns the full settings `--analyzer`, but the input only accepts the analyzer port of the settings. 

It's actually working as expected.
