### ISSUE TITLE
Type=analyzer not copying properly to remote servers

### ISSUE THREAD

**Issue by tim-ledsam** [taskrabbit/elasticsearch-dump#352]
I'm trying to use elasticdump to copy data between two clusters (let's call them `dev.db.com` and `live.db.com`). However, the `--type=analyzer` command is succeeding, but failing to copy anything across.

**Issue**

I'm running the following command:

```elasticdump --input=http://dev.db.com/some_index --output=http://live.db.com/some_index --type=analyzer```

On data that looks a little like this (when I run `curl -GET http://dev.db.com/some_index/_settings`):

```
{
    "some_index": {
        "settings" : {
            "index": {
                "creation_date": "timestamp", 
                "number_of_shards": "5", 
                "number_of_replicas": "1",
                "uuid": "uuid",
                "version": {"created":"5010199"},
                "provided_name":"some_index"
                "analysis": {
                    "filter": {
                        // A few filters
                    },
                    "analyzer": {
                         // A few analyzers
                    }
                },
                // More metadata
            },
        }
    }
}
``` 

When run, the action succeeds, but I get an index with the barest minimum of info. Running the same `curl` on the new remote index gives:

```
{
    "some_index": {
        "settings": { 
            "index": {   
                "creation_date": "timestamp", 
                "number_of_shards": "5", 
                "number_of_replicas": "1",
                "uuid": "uuid",
                "version": {"created":"5010199"},
                "provided_name":"some_index"
            }
        }
    }
}
```

**Investigation**

This works **absolutely fine** when I run it:

* local -> local
* dev -> local
* live -> local

It also is perfectly happy running with `--type=data`, regardless of input or output destination.

However, whenever I try to run it with `--type=analyzer` to a remote host, I get the above.

I'm going to see if I can install elasticdump on the `dev.db.com` server next, to see if it's an issue with the server, or whether it's genuinely to do with the remote destination - I'll update this post with any findings.

**Other**

A few extra bits of info, as requested:

- I'm using elasticdump 3.3.0 (though rolling back via 3.1.0, 3.0.0, and variable 2.x versions hasn't helped)
- All elasticsearch instances are v5.1.1 (local, dev & live)

**Comment by AfonsoTsukamoto** [comment]
Hi, 

This is also happening to me but I think in my case is because of aws elasticsearch.

AWS ES 2.3 does not support the close api, so this [line](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L291) fails.
Not sure why I don't see an error when I set output to the new index with type=analyzer though.

**Comment by gstamp** [comment]
Can reproduce problem on Elasticcloud with ES 2.4

**Comment by ferronrsmith** [comment]
`--analyzer` on output dumps all the settings for an index. On input it only takes the `analyzers`. Maybe we should add `--settings` so that's it's more aligned with the expectations of the output

**Comment by ferronrsmith** [comment]
Related to #351
