### ISSUE TITLE
Error while executing elasticdump

### ISSUE THREAD

**Issue by ameygat** [taskrabbit/elasticsearch-dump#361]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
3.3.1

- Elasticsearch version
```
"version" : {
    "number" : "2.4.1",
```

- Full command you are having issue with (with inputs and outputs)
```
$ elasticdump

/usr/local/lib/node_modules/elasticdump/bin/elasticdump:52
for (var i of jsonParsedOpts) {
           ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```
- A data set you can share publicly which reproduces the problem

**Comment by mgenelins** [comment]
Hey ameygat,

What OS are you running this on that you received the error? What version of java?

-matt

**Comment by ferronrsmith** [comment]
should be using node >= v4

**Comment by ameygat** [comment]
Node --version
v0.10.25

**Comment by ferronrsmith** [comment]
That's your problem. http://node.green/#ES2015-syntax-for--of-loops

for.of is only supported in 0.12.x+
