### ISSUE TITLE
Accept self-signed SSL/cert errors

### ISSUE THREAD

**Issue by aliostad** [taskrabbit/elasticsearch-dump#365]
I had issues running this with self-signed SSL and I managed to get it working with the trick below. Would be useful to add to the docs.

Essentially need to add `NODE_TLS_REJECT_UNAUTHORIZED=0` to the command line as below:

``` bash
$ NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input="https://localhost:9200" --output myfile
```

**Comment by ferronrsmith** [comment]
A section has been added to the README.md file, thanks.
