### ISSUE TITLE
Getting issue during aws signature generation

### ISSUE THREAD

**Issue by arijitkc** [taskrabbit/elasticsearch-dump#367]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 3.3.1
- Elasticsearch version :5.5
- Full command you are having issue with (with inputs and outputs)
elasticdump --input=https://xxx/index1:443 --output=https://yyy/index1:443 --type=data --awsChain
- A data set you can share publicly which reproduces the problem
Fri, 01 Dec 2017 11:35:22 GMT | starting dump
Fri, 01 Dec 2017 11:35:25 GMT | Error Emitted => {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/%3A443/_search\nfrom=0&scroll=10m\ncontent-length:74\ncontent-type:application/x-www-form-urlencoded; charset=utf-8\nhost:"}
Fri, 01 Dec 2017 11:35:25 GMT | Total Writes: 0
Fri, 01 Dec 2017 11:35:25 GMT | dump ended with error (get phase) => Error: {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'GET\n/"}

**Comment by ferronrsmith** [comment]
Closing this issue.
