### ISSUE TITLE
'multielasticdump@3.3.1' very slow comparing to'@1.1.4 --all' option

### ISSUE THREAD

**Issue by edudar** [taskrabbit/elasticsearch-dump#372]
- ElasticDump version: 3.3.1
- Elasticsearch version: 5.6.3
- Full command you are having issue with (with inputs and outputs)
```
multielasticdump --direction=dump --input=http://localhost:9202/ --output=elasticsearch --noRefresh
multielasticdump --direction=load --input=elasticsearch --output=http://localhost:9202/ --noRefresh
```

It's less of an issue but rather an inconvenience. I'm migrating from ES 1.7.3 to 5.6.3 and as result, I have to migrate from elasticdump 1.1.4 to 3.3.1. `--all` option has been dropped because it was buggy and `multielasticdump` is recommended but there is a catch. 

We use Elasticsearch for integration tests and we need to restore data often and fast. `elasticdump@1.1.4` restores 500+ documents in about 4 seconds and a second for `/_all` (settings and mapping) manually. `multielasticdump@3.3.1` takes 40-45 seconds to restore the same data. This renders it unusable for such scenario now.

**Comment by edudar** [comment]
Performance degradation with dumping info is even worse but much less of an issue as we do it just once at the very beginning. It's 1 second with `@1.1.4` vs 45 seconds with `@3.3.1`

**Comment by ferronrsmith** [comment]
Providing sample data would help to get this issue resolved

**Comment by edudar** [comment]
No sample data unfortunately but here’s the idea. Elasticsearch is fast enough so it does not make much difference for it to return 50 documents or 500. It basically takes a second for a query (request+response+write). When 3.3.1 switched to sequential queries on index-by-index manner, we had 40-45 queries to run. If each of them takes about a second - here’s the difference between 1 query and 40 queries and 1 second and 40 seconds.

I went with custom Elasticsearch REST call to get/load all data at once and jq for JSON processing and it works lightning fast, pretty much like 1.1.4 was.

**Comment by ferronrsmith** [comment]
Yea I think you're right. The problem here seems to be that `multielasticdump` which runs everything sequentially instead of in parallel.  I have tested running this in parallel vs sequential and while it's tempting to run everything in parallel for large loads this can be problematic, especially in cases where heap is low (2GB) and data-load/through-put is high (1-5M records * N streams, 2 GB mem).

**Comment by ferronrsmith** [comment]
I don't think we will ever accomplish the raw speed of @1.1.4 simply because now we perform more requests. I have mechanism to reduce the pause intervals that will help with performance, but there is still the limiting factor of multiple requests.
