### ISSUE TITLE
Can elasticsearch-dump specify _type?

### ISSUE THREAD

**Issue by YeeP79** [taskrabbit/elasticsearch-dump#373]
With the changes that are coming where only one _type will be allowed per index, we are trying to come up with a way to separate our indices that have multiple types into different indices. If this tool could specify which type you wanted to pull from a specific index, and which type you wanted to place it in, it could be used to migrate the current data you have into the new format that elasticsearch is pushing. 

Any thoughts on this would be much appreciated, and I apologize ahead of time for putting this in "Issues" as I wasn't sure where else I could get your attention.

Thank you for the tool, I have used it several times to migrate data across our network.

**Comment by ferronrsmith** [comment]
You can use the `--input-index` flag to only return a single index.

```bash
elasticdump --input http://localhost:9200 --input-index=myindex/indexType --type data --output dump.json --headers='{"Content-Type": "application/json"}'
```
or 

```bash
elasticdump --input http://localhost:9200 --input-index=myindex/indexType --type data --output http://localhost:9600 --output-index=oindex/indexType --headers='{"Content-Type": "application/json"}'
```

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by songlong** [comment]
when different types of between input and output, it will happener error:

{ _index: 'attack_detail_201711',
  _type: 'attack_detail_201711',
  _id: 'AV94Yx6hsgwu10szvdbj',
  status: 400,
  error: 
   { type: 'illegal_argument_exception',
     reason: 'Rejecting mapping update to [attack_detail_201711] as the final mapping would have more than 1 type: [attack_detail, attack_detail_201711]' } }

elasticdump --input=http://10.203.39.100:9200 --input-index=attack_detail_201711/attack_detail_201711 --output=http://10.203.39.100:9201 --output-index=attack_detail_201711/attack_detail --type=data --limit=20 --headers='{"Content-Type": "application/json"}'

**Comment by ferronrsmith** [comment]
> Indices created in Elasticsearch 6.0.0 or later may only contain a single mapping type. Indices created in 5.x with multiple mapping types will continue to function as before in Elasticsearch 6.x. Mapping types will be completely removed in Elasticsearch 7.0.0.


https://www.elastic.co/guide/en/elasticsearch/reference/6.2/removal-of-types.html

**Comment by songlong** [comment]
After creating new mapping, it can not assign new type when dump data to new indices if old es and new es has different type. 
param --output-index can not efficient.

**Comment by songlong** [comment]
elasticsearch.prototype.setData = function (data, limit, offset, callback) {
  data.forEach(function (elem) {
    var actionMeta = { index: {} }
    // actionMeta._index = elem._index; // Not setting _index should use the one defined in URL.
    actionMeta.index._type = elem._type
    actionMeta.index._id = elem._id

elem._type should call outpu-index type param not input index

**Comment by ferronrsmith** [comment]
@songlong this has been resolved in the latest release

**Comment by willzhang** [comment]
> You can use the `--input-index` flag to only return a single index.
> 
> ```shell
> elasticdump --input http://localhost:9200 --input-index=myindex/indexType --type data --output dump.json --headers='{"Content-Type": "application/json"}'
> ```
> 
> or
> 
> ```shell
> elasticdump --input http://localhost:9200 --input-index=myindex/indexType --type data --output http://localhost:9600 --output-index=oindex/indexType --headers='{"Content-Type": "application/json"}'
> ```

should i migrate json with --type mapping ?
