### ISSUE TITLE
Easticdump, Dumps exactly half of the documents.

### ISSUE THREAD

**Issue by TalZiv** [taskrabbit/elasticsearch-dump#375]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version :  elasticdump@3.3.1
- Elasticsearch version : 5.4.3
- Full command:  elasticdump --limit 1000 --input=http://X.X.X.X:9200/$index --output=/root/els_backup_temp/$index'_data.json' --type=data

The dump is only dumping exactly HALF of the documents shown by cerebro, is cerebro showing the wrong data? or elasticdump is failing, please see the output of _stats below.

![image](https://user-images.githubusercontent.com/22313897/34326810-6ed9d542-e8be-11e7-8dc1-9f868680ffba.png)

The _stats shows the number elasticdump shows : 

> {
>   "_shards": {
>     "total": 24,
>     "successful": 8,
>     "failed": 0
>   },
>   "_all": {
>     "primaries": {
>       "docs": {
>         **"count": 806966,**
>         "deleted": 0
>       },
>       "store": {
>         "size": "1.1gb",
>         "size_in_bytes": 1264553218,
>         "throttle_time": "0s",
>         "throttle_time_in_millis": 0
>       },
>       "indexing": {
>         **"index_total": 403483,**

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
