### ISSUE TITLE
final mapping would have more than 1 type error

### ISSUE THREAD

**Issue by tvb** [taskrabbit/elasticsearch-dump#377]
Hi,

How can I dump ES 2.x to ES6.0. Getting the following error:
```
{ _index: 'cwl-2017.11.26',
  _type: 'production-imports-vertx',
  _id: 'y82mimABZ_ORcC3Sqg39',
  status: 400,
  error:
   { type: 'illegal_argument_exception',
     reason: 'Rejecting mapping update to [cwl-2017.11.26] as the final mapping would have more than 1 type: [acceptance-data-vertx, production-imports-vertx]' } }
```

**Comment by ferronrsmith** [comment]
> Indices created in Elasticsearch 6.0.0 or later may only contain a single mapping type. Indices created in 5.x with multiple mapping types will continue to function as before in Elasticsearch 6.x. Mapping types will be completely removed in Elasticsearch 7.0.0.

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html

**Comment by ferronrsmith** [comment]
First step is to come up with a migration plan. Then you will need to dump each type to a separate index.
You can review the docs for more info or check the steps outlines in #373

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
