### ISSUE TITLE
elastic dump not working

### ISSUE THREAD

**Issue by foxiiit** [taskrabbit/elasticsearch-dump#381]
Hi 
I did install elasticsearch v 5.5.1. after some time the database becomes full .. decided to export indexes using elasticdump I did install node and elastidump using 
`npm install elasticdump`

when i try to export the data using 
 
` elasticdump --input=http://localhost:9200/ciscoasa-2017.08.25 --output=/home/hello/ll.json --type=data --debug`
nothing happen even when i use the debug option any ideas 
I did use also 
`/node_modules/.bin# ./elasticdump --help`

nothing .. is there any log for elasticdump 
thx

**Comment by ferronrsmith** [comment]
Going to need more information.

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
