### ISSUE TITLE
Content type header lost with AWS

### ISSUE THREAD

**Issue by atiro** [taskrabbit/elasticsearch-dump#382]
With ES6 refusing requests that do not have a Content-Type: application/json header, the aws4signer should be setting that header, as currently it seems to only be setting this:

  (lib/aws4signer.js, line 51)
` esRequest.headers = { 'host': urlObj.hostname } `

and ignoring all the other headers passed in on the command line. This then defaults to application/x-www-form-urlencoded Content-Type which is rejected by Es6.

Works with:

 ` esRequest.headers = { 'host': urlObj.hostname, 'content-type': 'application/json' }`

- ElasticDump version: 4.1.2
- Elasticsearch version: 6.0.1 (running on AWS)

**Comment by ferronrsmith** [comment]
`elasticdump-next` has been deprecated and the changes merged here. Can you try using ElasticDump version: 3.3.2 ?

**Comment by ferronrsmith** [comment]
Also have you tried using the head flag ? 

`--headers='{"Content-Type": "application/json"}'`

**Comment by atiro** [comment]
Hi @ferronrsmith same in elasticdump, and command line headers arguments are ignored. The aws4signer is only setting the host header, I'm not sure why it drops everything else. That wouldn't have been an issue before ES6, but the change to enforce application/json content-type only now breaks requests that don't send it.
