### ISSUE TITLE
Offset tied to batch size

### ISSUE THREAD

**Issue by kert-io** [taskrabbit/elasticsearch-dump#383]
Goal:  a job terminated early, so I need to restart from the last offset.  When I execute I get the following

```

 --type=data --limit=100 --offset=222300
Fri, 26 Jan 2018 18:59:36 GMT | starting dump
Fri, 26 Jan 2018 18:59:36 GMT | Warning: offseting 222300 rows.
Fri, 26 Jan 2018 18:59:36 GMT |   * Using an offset doesn't guarantee that the offset rows have already been written, please refer to the HELP text.
Fri, 26 Jan 2018 18:59:39 GMT | Error Emitted => {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Batch size is too large, size must be less than or equal to: [10000] but was [222400]. Scroll batch sizes cost as much memory as result windows so they are controlled by the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"eng-sysmon-2018.01","node":"bxDFQE5vTS6P4yZJIodJBg","reason":{"type":"query_phase_execution_exception","reason":"Batch size is too large, size must be less than or equal to: [10000] but was [222400]. Scroll batch sizes cost as much memory as result windows so they are controlled by the [index.max_result_window] index level setting."}}],"caused_by":{"type":"query_phase_execution_exception","reason":"Batch size is too large, size must be less than or equal to: [10000] but was [222400]. Scroll batch sizes cost as much memory as result windows so they are controlled by the [index.max_result_window] index level setting."}},"status":500}
Fri, 26 Jan 2018 18:59:39 GMT | Total Writes: 0
```

Why is offset associated with batch size?  I suspect this is some internal usage of the term.  But With large datasets, it seems this fails as the batch size limit is set to 10000.  Is there a workaround?

- ElasticDump version 3.0
- Elasticsearch version - 5.0
- Node.js version . - 4.2.6
- Full command you are having issue with (with inputs and outputs)
elasticdump --input=https://....com/eng-sysmon-2018.01 --output=https://....com/eng-sysmon-2018.02 --type=data --limit=100 --offset=222300

**Comment by ferronrsmith** [comment]
The reason you're seeing the issue is because you have crossed the `max_result_window` which is by default set to 10,000. Offsetting beyond this point requires a change to the index setting.

Please see for more info : https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html
