### ISSUE TITLE
ElasticDump issue introduced in 3.3.2 ?

### ISSUE THREAD

**Issue by FLavalliere** [taskrabbit/elasticsearch-dump#385]
- ElasticDump version (3.3.2+)
- Elasticsearch version (1.5)
- Node.js version (v8.9.4)
- Full command you are having issue with (with inputs and outputs)

/usr/lib/node_modules/elasticdump/bin/elasticdump --input=https://search-xxxxxxxx.us-east-1.es.amazonaws.com --output=./testData-3-2.data --type=data

Wed, 31 Jan 2018 14:45:27 GMT | starting dump
Wed, 31 Jan 2018 14:45:28 GMT | got 100 objects from source elasticsearch (offset: 0)
Wed, 31 Jan 2018 14:45:28 GMT | sent 100 objects to destination file, wrote 100
Wed, 31 Jan 2018 14:45:28 GMT | Error Emitted => {"error":"ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; ","status":400}
Wed, 31 Jan 2018 14:45:28 GMT | Total Writes: 100
Wed, 31 Jan 2018 14:45:28 GMT | dump ended with error (get phase) => Error: {"error":"ElasticsearchIllegalArgumentException[Failed to decode scrollId]; nested: IOException[Bad Base64 input character decimal 123 in array position 0]; ","status":400}

Using - ElasticDump version (3.3.1) it is working

/usr/lib/node_modules/elasticdump/bin/elasticdump --input=https://search-xxxxxxxx.us-east-1.es.amazonaws.com --output=./testData3-1.conf --type=data

Wed, 31 Jan 2018 14:45:40 GMT | starting dump
Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 0)
Wed, 31 Jan 2018 14:45:40 GMT | sent 100 objects to destination file, wrote 100

Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 100)
Wed, 31 Jan 2018 14:45:40 GMT | sent 100 objects to destination file, wrote 100
Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 200)
Wed, 31 Jan 2018 14:45:40 GMT | sent 100 objects to destination file, wrote 100
Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 300)
Wed, 31 Jan 2018 14:45:40 GMT | sent 100 objects to destination file, wrote 100
Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 400)
Wed, 31 Jan 2018 14:45:40 GMT | sent 100 objects to destination file, wrote 100
Wed, 31 Jan 2018 14:45:40 GMT | got 100 objects from source elasticsearch (offset: 500)
...

**Comment by gus4no** [comment]
Yes, I'm having the same issue.

**Comment by ferronrsmith** [comment]
We needed to support a newer version of elasticsearch. ES 1.5 as already reached EOL and our test harness doesn't support versions lower than 2.3.x. I will look into it, but at some point support for old versions will be broken.

**Comment by vijaya89** [comment]
I am seeing this issue again . 

./elasticdump \
--input elasticsearch 1.5 \
--output opensearch 2.3  \
--output-index test-index \
--searchBody "{\"query\":{\"match\":{\"test\": \"test\"}}}" \

**Comment by ferronrsmith** [comment]
@vijaya89 just remember to put all flags  passed. This issue occurs when the aws auth flags are passed.
