### ISSUE TITLE
Size param ignored

### ISSUE THREAD

**Issue by wolli2710** [taskrabbit/elasticsearch-dump#394]
- ElasticDump version 3.3.1
- Elasticsearch version 2.4.0
- Node.js version v8.9.4
- Input: elasticdump --input=http://user:pwd@server:port/myindex --output=my.data.json --type=data --size=20 --limit=10
- Output the whole index

The Inpput command is not writing out just 20 objects it's writing out the whole index. Am I using it wrong?

**Comment by ferronrsmith** [comment]
I think you misinterpret what the size parameter is. It's the size of the bulk request. As in, how many records get returned.

To limit the size of the payload from ES. You need to use the `--searchBody` option

```
elasticdump --input=http://user:pwd@server:port/myindex --output=my.data.json --type=data 
--searchBody '{"size":10,"from":10}'
```

**Comment by wolli2710** [comment]
Ok thx for clarifying!
