### ISSUE TITLE
[Query] avoid data transfer to client while copying data from one index to another

### ISSUE THREAD

**Issue by siddharth-verma-guavus** [taskrabbit/elasticsearch-dump#398]
elasticdump \
  --input=http://192.168.133.174:6775/blacklist7lakh \
  --output=http://192.168.133.174:6775/blacklist7lakh_simple_migrated
  --type=analyzer

elasticdump \
  --input=http://192.168.133.174:6775/blacklist7lakh \
  --output=http://192.168.133.174:6775/blacklist7lakh_simple_migrated
  --type=analyzer

elasticdump \
  --input=http://192.168.133.174:6775/blacklist7lakh \
  --output=http://192.168.133.174:6775/blacklist7lakh_simple_migrated
  --type=analyzer

I was checking the dstat output, and it showed significant data transfer to client machine.

Is there a way to import export data on the server side itself, to avoid network traffic, as done in [elasticsearch-inout-plugin](https://github.com/crate/elasticsearch-inout-plugin) and [elasticsearch-knapsack](https://github.com/jprante/elasticsearch-knapsack). Both those projects don't have support for 5.6 ES, and have been dormant for quite a long time.

**Comment by evantahler** [comment]
This tool uses the HTTP interface, to be the most portable. If you want to avoid network transfer, run elasticdump on a machine inside your firewall, on a private NIc interface.

**Comment by ferronrsmith** [comment]
You can export the data to a file on the data server and then import the file on the client server to reduce traffic, but no traffic. elasticsearch-inout-plugin and elasticsearch-knapsack both use the ES client library, to say there is no network traffic is rather incorrect.

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
