### ISSUE TITLE
Output to stdout contain logging information

### ISSUE THREAD

**Issue by T3rm1** [taskrabbit/elasticsearch-dump#399]
With version 3.3.6 the output to stdout (--output=$) contains logging information like these:

    Mon, 05 Mar 2018 14:57:03 GMT | starting dump
    Mon, 05 Mar 2018 14:57:03 GMT | got 100 objects from source elasticsearch (offset: 0)    

    ...
 
    Mon, 05 Mar 2018 14:57:03 GMT | sent 78 objects to destination file, wrote 78
    Mon, 05 Mar 2018 14:57:03 GMT | got 0 objects from source elasticsearch (offset: 178)

It's not possible to import this file. The documentation says that logging information is stripped from the output.

**Comment by ferronrsmith** [comment]
````
--toLog
                    When using a custom outputTransport, should log lines
                    be appended to the output stream?
                    (default: true, except for `$`)
```

```bash
elasticdump --input=http://localhost:9200 --input-index=sample_index/dataRecord --toLog=false --output=$ | gzip > m.json.gz

```

**Comment by ferronrsmith** [comment]
I'll add an update that disables this when the output is set to `$`. It's enabled by default

**Comment by T3rm1** [comment]
Yeah, I noticed toLog but didn't find it useful because I don't use a custom outputTransport.

**Comment by ferronrsmith** [comment]
ok pushed `3.3.7` with toLog disabled by default when output is `$`
