### ISSUE TITLE
Piping through gzip with high compression, loses documents

### ISSUE THREAD

**Issue by LordMike** [taskrabbit/elasticsearch-dump#404]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version `3.3.7`
- Elasticsearch version `5.6.8`
- Node.js version `v4.2.6`
-------

Hi,

I've tried dumping very large indexes, which required me to pipe the data through a compression scheme to avoid running out of disk space. I was pleased to find that `elasticdump` could output to the console using `$` as an output - but I then discovered we were losing documents.

I've found it happens when I instruct gzip to apply its best compression, as shown here. In these four commands, I expect them all to end up with 1.000.868 documents.

```
elasticdump --limit=10000 --type=data --input=http://localhost:9200/twitter/tweet --output=test-plain
elasticdump --limit=10000 --type=data --input=http://localhost:9200/twitter/tweet --output=$ > test-stdio
elasticdump --limit=10000 --type=data --input=http://localhost:9200/twitter/tweet --output=$ | gzip -9c > test-gz-9.gz
elasticdump --limit=10000 --type=data --input=http://localhost:9200/twitter/tweet --output=$ | gzip -c > test-gz-nrml.gz
```

The results are:
```
$ wc -l test-stdio test-plain
  1000868 test-stdio
  1000868 test-plain

$ zcat test-gz-nrml.gz | wc -l
1000868

$ zcat test-gz-9.gz | wc -l
799590
```

.. we're missing 201.278 documents from the `gzip -9` version. I can only assume that this is a timing thing, in the the "regular" gzip can read data so fast that it gets everything, while "gzip -9" is just that slower, that 200.000 documents aren't processed. I suspect the "regular" gzip will miss documents as well, if my computer were slower.

Is it possible that elasticdump is not flushing something, or somehow avoiding writing out its output?

For test data, I simply added 1M documents with the same data. The contents shouldn't matter - and presumably it should reproduce on much smaller indexes.

----

To test out the speed/timing theory, I dumped the index 4 times with "gzip -9", and got these document counts: `803719`, `761920`, `778691`, `777659`. Running the regular gzip 4 times consistently gets all documents.

**Comment by ferronrsmith** [comment]
replicated this issue. it's a race condition. I'll be pushing a fix for this soon
