### ISSUE TITLE
default is nodejs in ubuntu 16.04 instead if node

### ISSUE THREAD

**Issue by larrycai** [taskrabbit/elasticsearch-dump#407]
Small issue, when I run `elasticdump` in ubuntu 16.04, it reports error for `node`, and it is fine if I changed it to `nodejs`

- ElasticDump version: `3.3.7`
- Elasticsearch version: `6.2.1`
- Node.js version `v4.2.6`
- Full command you are having issue with (with inputs and outputs)

<pre>
$ elasticdump
/usr/bin/env: ‘node’: No such file or directory
</pre>

And I just changed `#!/usr/bin/env node` to `#!/usr/bin/env nodejs`

Will be good to state somewhere so make less trouble for none nodejs user.

- A data set you can share publicly which reproduces the problem

Doesn't matter

**Comment by ferronrsmith** [comment]
node.js 8 or higher is supported. We dropped support for older versions since **v3.3.2**

**Comment by ferronrsmith** [comment]
You could have used a symlink ... ```ln -s /usr/bin/nodejs /usr/bin/node```
