### ISSUE TITLE
Big integer issue

### ISSUE THREAD

**Issue by V-ctor** [taskrabbit/elasticsearch-dump#415]
It seems that elasticdump cut of big integer value.
If I have in source field
```
{
 "content_id": 1726275868403174266,
}
```
after copy
I get
```
{
  "content_id": 1726275868403174200
}
```
I guess this is JavaScript int/long restriction.

- ElasticDump 3.3.7
- Elasticsearch 2.4
- Node.js version v9.11.1
- Full command 
`
./node_modules/.bin/elasticdump \
  --input=http://192.168.50.222:9205/newsng_2018_03_v1 \
  --output=http://192.168.50.222:9205/test2_newsng_2018_03_v1 \
  --type=analyzer \
  --size=50
./node_modules/.bin/elasticdump \
  --input=http://192.168.50.222:9205/newsng_2018_03_v1 \
  --output=http://192.168.50.222:9205/test2_newsng_2018_03_v1 \
  --type=mapping \
  --size=50
./node_modules/.bin/elasticdump \
  --input=http://192.168.50.222:9205/newsng_2018_03_v1 \
  --output=http://192.168.50.222:9205/test2_newsng_2018_03_v1 \
  --type=data \
  --size=100
`
- A data set see above

**Comment by V-ctor** [comment]
Yes I did. My steps:
1. I tried with curl it returned `17262758684031742**66**`
2. Then tried to export in json file and got `17262758684031742**00**`

I'm not proficient with JS but I noticed that another nodejs software has the same issue (Insomnia, ES web plugin).
I'll try to prepare usefull dataset later.

**Comment by V-ctor** [comment]
So are there any plans to fix it?
Here
https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint
there is advice to use 3-d party json parse libs.

**Comment by ferronrsmith** [comment]
You can try using https://www.npmjs.com/package/json-bigint. It will patch JSON.parse to allow big int parsing...

**Comment by ferronrsmith** [comment]
Someone already submitted an old PR for this. I will have a look, add a few tests and push something for you to test. https://github.com/taskrabbit/elasticsearch-dump/pull/360

**Comment by V-ctor** [comment]
It would be great!

**Comment by ferronrsmith** [comment]
@evantahle that's a better field name.

**Comment by V-ctor** [comment]
But why we can not use any big int library (BigInteger.js ?) to store value instead strings? If you guess that it could be slower then probably it should be turned on by additional key like `--support-big-int`.
I'm not sure that every user knows list of fields with big int, and wants to explore data source to find it, but could agree for some extra time delay for properly working.

**Comment by ferronrsmith** [comment]
Yea, but it's very aggressive. It would convert all numeric fields to big integer. Event an ID field. e.g. "121212". If you have a string mapping then this would fail, which isn't great.

**Comment by V-ctor** [comment]
That's why I suggested additional key :-)
