### ISSUE TITLE
Quiet option outputs all logs to stdout

### ISSUE THREAD

**Issue by jchannon** [taskrabbit/elasticsearch-dump#416]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : 3.3.7
- Elasticsearch version : 6.2.2
- Node.js version *(note that nodejs v8+ is required for this tool)* : 8.4.0
- Full command you are having issue with (with inputs and outputs) : 
- A data set you can share publicly which reproduces the problem

```

#!/usr/bin/env bash

if [ "$#" -lt 2 ]; then
    echo "Please pass an input url and a output file name"
    exit 1
fi

inputurl=$1
outputfilename=$2
filter=$3

if [ -z "$filter" ]; then
    filter='{"query": { "match_all": {} }, "stored_fields": ["*"], "_source": true }'
    echo No filter specified, using defaut "${filter}"
fi

# Filter Example
# '{"query":{"bool":{"must":{"wildcard":{"@log_name.keyword":"*vcb-testing-1*"}},"filter":{"range":{"@timestamp":{"gte":"2018-03-08T13:00:00.000000+00:00","lte":"2018-03-08T14:00:00.000000+00:00"}}}}}}'

elasticdump --input "${inputurl}" --output "${outputfilename}"".mapping.json" --type=mapping --searchBody "${filter}" --limit 5000 --quiet=true

elasticdump --input "${inputurl}" --output "${outputfilename}"".analyzer.json" --type=analyzer --searchBody "${filter}" --limit 5000 --quiet=true

elasticdump --input "${inputurl}" --output "${outputfilename}"".data.json" --type=data --searchBody "${filter}" --limit 5000 --debug --quiet=true
```

This script works fine but when run I get all the logs outputted to stdout as well as the files specified.

How can I get it to dump without all the data to stdout?

**Comment by ferronrsmith** [comment]
I think you're mixing up 2 different issues. https://github.com/taskrabbit/elasticsearch-dump/issues/399 the output was being written to stdout when output was set to `$`, which is bad if your piping to a file.

This issue is different.

**Comment by jchannon** [comment]
Changed the title. I'm unaware of 399, just spotted stdout dump as well as file

**Comment by ferronrsmith** [comment]
I can't replicate the issue you're having. I ran the script provided on my data-set and it works perfectly.

ElasticDump version : 3.3.8
Elasticsearch version : 6.2.0
Node.js version (note that nodejs v8+ is required for this tool) : 8.11.1

**Comment by jchannon** [comment]
My point is that the tool works but just that it dumps to file as I want
but when the tool is run I can see all the logs whizz by in my terminal

**Comment by ferronrsmith** [comment]
I'm not seeing that behavior https://asciinema.org/a/kR3tHTtn51Ouy6TrG9sCa905C

**Comment by jchannon** [comment]
Updated to 3.3.8 and I still see a wall of text in my terminal

**Comment by ferronrsmith** [comment]
I don't really know what you're seeing. Take a screenshot and send a dataset. I can't fix something if I can't replicate it.

**Comment by jchannon** [comment]
Here's a gif of me executing the script ![ux](https://user-images.githubusercontent.com/105126/38571791-65ea5f72-3ce9-11e8-85f5-4c3fe40c7c93.gif)

**Comment by jchannon** [comment]
Looks like its a debug message of the results it found:

![screen shot 2018-04-10 at 18 05 33](https://user-images.githubusercontent.com/105126/38571963-cb92c4d6-3ce9-11e8-818f-7ab575cb3c00.png)

**Comment by ferronrsmith** [comment]
**debug** & error messages cannot be disabled or turned off.

**Comment by jchannon** [comment]
You might want to look at making debug messages an option then

**Comment by ferronrsmith** [comment]
I'll add a `--silence` flag

1. `silence` - only errors
1. `quiet` - not verbose

**Comment by jchannon** [comment]
Sounds good, thanks

**Comment by ferronrsmith** [comment]
ok added

**Comment by ferronrsmith** [comment]
this flag was actually unnecessary , you had `--debug` in your script which was causing the issue.
