### ISSUE TITLE
AWS Elasticsearch requests fails on first scroll request

### ISSUE THREAD

**Issue by jeff-hager-dev** [taskrabbit/elasticsearch-dump#422]
## Enviroment Info
- Elasticsearch Command: 2.3
- Elasticdump version 1.7
- Node version: v8.10.0
- Full command: See below
- Unfortunately I am not able to provide a data set at this time but it appears to be more of an issue of signing the requests for AWS then the data output. What data I get from the first request has been correct.

## Error Info:

When trying to interact with AWS elasticsearch service the first call goes through just fine and retreives the data. When the second call pass is made to get the next group it fails. The errors are different depending on the arguments I use.

### Example 1 command: 
```
elasticdump --limit=300 --type=data --input=https://elasticsearch-url.com/the-index 
--output=./output-file.json --awsAccessKeyId="some-access-key" 
--awsSecretAccessKey="super-secret"
```

Error Message: 
```
The request signature we calculated does not match the signature you provided. Check your AWS 
Secret Access Key and signing method. Consult the service documentation for details.
```

### Example 2 command: 
```
elasticdump --limit=300 --type=data --input=https://elasticsearch-url.com/the-index
 --output=./output-file.json --awsChain
```

Error Message:  
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: {"message":null}
```

Here the request is returning a `400: Bad Request` causing the  error to be tossed.

I have been debugging this for about a day now, so any help would be greatly appreicated!

**Comment by ferronrsmith** [comment]
Have you tried using a later version ?

**Comment by ferronrsmith** [comment]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version
- Node.js version *(note that nodejs v8+ is required for this tool)*
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.

**Comment by jeff-hager-dev** [comment]
I apologize for the delayed response. I ran back through my tests and I did provide the wrong verision number. I provide the version of `aws4` that was being used by `elasticdump` and not the version of `elasticdump`.  

I am still having the same issue and working to provide a data set, but like I mentioned before the issue isn't with data but with how the scroll requests are being signed when interacting with AWS. As soon as I have something set up I will update and re-open

**Comment by rcmorano** [comment]
Aloha!

I was also having this problem and it seems latest commit does not fix it.

I've sent a [PR](https://github.com/taskrabbit/elasticsearch-dump/pull/432) that fixes it as [AWS doc](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html#es_version_5_5) suggests: moving scroll_id to the request body.

**Comment by ferronrsmith** [comment]
I think you're reading the document incorrectly. Different versions of ES has different requirements.

**Comment by rcmorano** [comment]
To be exact, it does mention it just to avoid problems when '=' are part of the 'scroll_id', but the fact is that it worked when I moved the id to the request body.

**Comment by ferronrsmith** [comment]
yea but this breaks the behavior in certain versions of AWS. I merge your PR and tomorrow another issue opens up with an issue.

**Comment by ferronrsmith** [comment]
merged
