### ISSUE TITLE
Multi-index "--delete" not happening

### ISSUE THREAD

**Issue by MattiDeGrauwe** [taskrabbit/elasticsearch-dump#423]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
root@kibana:~# elasticdump --version
3.3.7

- Elasticsearch version
6.2.3

- Full command you are having issue with (with inputs and outputs)

root@kibana:~# elasticdump --input=http://192.1.2.3:9200/blue* --output=data/my_index.json --type=data --searchBody='{"query": {"range" : {"@timestamp" : {"lte": "now"}}}}' --delete
Thu, 12 Apr 2018 16:42:59 GMT | starting dump
Thu, 12 Apr 2018 16:42:59 GMT | got 100 objects from source elasticsearch (offset: 0)
Thu, 12 Apr 2018 16:42:59 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 100)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 200)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 300)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 400)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 500)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 600)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 700)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:00 GMT | got 100 objects from source elasticsearch (offset: 800)
Thu, 12 Apr 2018 16:43:00 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 900)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1000)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1100)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1200)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1300)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1400)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1500)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1600)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1700)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:01 GMT | got 100 objects from source elasticsearch (offset: 1800)
Thu, 12 Apr 2018 16:43:01 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:02 GMT | got 100 objects from source elasticsearch (offset: 1900)
Thu, 12 Apr 2018 16:43:02 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:02 GMT | got 100 objects from source elasticsearch (offset: 2000)
Thu, 12 Apr 2018 16:43:02 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:02 GMT | got 100 objects from source elasticsearch (offset: 2100)
Thu, 12 Apr 2018 16:43:02 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:02 GMT | got 100 objects from source elasticsearch (offset: 2200)
Thu, 12 Apr 2018 16:43:02 GMT | sent 100 objects to destination file, wrote 100
Thu, 12 Apr 2018 16:43:02 GMT | got 94 objects from source elasticsearch (offset: 2300)
Thu, 12 Apr 2018 16:43:02 GMT | sent 94 objects to destination file, wrote 94
Thu, 12 Apr 2018 16:43:02 GMT | got 0 objects from source elasticsearch (offset: 2394)
Thu, 12 Apr 2018 16:43:02 GMT | Total Writes: 2394
Thu, 12 Apr 2018 16:43:02 GMT | dump complete

With my command, I'm trying to dump multiple indices (eg. blue.haproxy, blue.apache, blue.nginx etc). 
The dump itself to the file happens but with the data is not deleted in elasticsearch with this method.

Any suggestions?

**Comment by MattiDeGrauwe** [comment]
Thanks for you response!

I think the record you're looking for is the folllowing:

Fri, 13 Apr 2018 12:24:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Y9h-sGIB8LgAzPnCJqbS

It says "deleteUrl" but the data remains afterwards

**Comment by ferronrsmith** [comment]
I'm not able to replicate the behavior locally. Is it possible to provided a sanitized sample data-set. 10 records should be fine.

**Comment by ferronrsmith** [comment]
Also can you try running a normal curl against the endpoint and see what happens ?

```bash
curl -XDELETE http://192.1.2.3:9200/blue.*/blue.syslog/Y9h-sGIB8LgAzPnCJqbS
```

**Comment by MattiDeGrauwe** [comment]
root@kibana:~# elasticdump --input=http://192.1.2.3:9200/blue.* --output=data/my_index.json --type=data --searchBody='{"query": {"bool" : {"must" : {"term" : { "environment" : "blue" }},"filter": {"range" : {"@timestamp" : {"gte": "now-12m"}}}}}}' --delete --debug
Fri, 13 Apr 2018 12:34:43 GMT | starting dump
Fri, 13 Apr 2018 12:34:43 GMT [debug] | discovered elasticsearch input major version: 6
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.apache-access/Ha39vmIBrU8jaY13Nz6a
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Zq31vmIBrU8jaY133j0M
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Z631vmIBrU8jaY133j0X
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/aa31vmIBrU8jaY133j0m
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/da31vmIBrU8jaY138T3y
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/e631vmIBrU8jaY13_T3E
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/aq31vmIBrU8jaY133j0u
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/bK31vmIBrU8jaY135j0K
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/d631vmIBrU8jaY139T3h
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Yq31vmIBrU8jaY133T3X
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/c631vmIBrU8jaY137T3z
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/f632vmIBrU8jaY13BT2k
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Y631vmIBrU8jaY133T3o
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/Za31vmIBrU8jaY133j0E
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/ea31vmIBrU8jaY13-T3U
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/sq34vmIBrU8jaY13_j3V
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/ZK31vmIBrU8jaY133T37
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/aK31vmIBrU8jaY133j0f
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/a631vmIBrU8jaY134j0e
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/ba31vmIBrU8jaY136T37
Fri, 13 Apr 2018 12:34:43 GMT [debug] | deleteUrl: http://192.1.2.3:9200/blue.*/blue.syslog/fa32vmIBrU8jaY13AT20
Fri, 13 Apr 2018 12:34:43 GMT | got 21 objects from source elasticsearch (offset: 0)
Fri, 13 Apr 2018 12:34:43 GMT | sent 21 objects to destination file, wrote 21
Fri, 13 Apr 2018 12:34:43 GMT | got 0 objects from source elasticsearch (offset: 21)
Fri, 13 Apr 2018 12:34:43 GMT | Total Writes: 21
Fri, 13 Apr 2018 12:34:43 GMT | dump complete

curl -XDELETE http://192.1.2.3:9200/blue.*/blue.syslog/Y9h-sGIB8LgAzPnCJqbS 

root@kibana:~# curl -XDELETE http://192.1.2.3:9200/blue.*/blue.syslog/Y9h-sGIB8LgAzPnCJqbS
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"blue.*","index_uuid":"_na_","index":"blue.*"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"blue.*","index_uuid":"_na_","index":"blue.*"},"status":404}

It does not find that index, but it does copy

**Comment by ferronrsmith** [comment]
ok I think I see the problem now. Let me do some more tests

**Comment by ferronrsmith** [comment]
I'll push a patch and you can test.

**Comment by ferronrsmith** [comment]
@MattiDeGrauwe I've added a fix to the `bug/wildcard-delete`, is this something you can test ? Thanks

**Comment by MattiDeGrauwe** [comment]
Hi ferronrsmith,
I just tested your update. It works like a charm now! Thank you for inserting the proper update.

**Comment by ferronrsmith** [comment]
awesome thanks, I will merge and create a new release
