### ISSUE TITLE
Re-importing multiple indices JSON

### ISSUE THREAD

**Issue by MattiDeGrauwe** [taskrabbit/elasticsearch-dump#425]
The wildcard works perfect now (was necessary for elasticsearch 6.0).
The problem I'm encountering now is that my JSON exists out of multiple indices.

Is it possible to re-import (and recreate) the indices in elasticsearch?
eg:

```
root@kibana:~/github/elasticsearch-dump/bin# ./elasticdump --input=my_index.json --output=http://192.1.2.3:9200/
root@kibana:~/github/elasticsearch-dump/bin# ./elasticdump --input=my_index.json --output=http://192.1.2.3:9200/*
```

Both don't work at this exact moment, is this already implemented?

Kind regards

**Comment by ferronrsmith** [comment]
We don't support multi output.

**Comment by ferronrsmith** [comment]
After reviewing this. I see what you mean, I have a fix for this. Will be pushing shortly for you to test.

**Comment by ferronrsmith** [comment]
you can test the `feature/index` branch

**Comment by MattiDeGrauwe** [comment]
Again, it works 👍  I think a lot of people will be using this feature since the parent-child structure was removed from elasticsearch. Thanks!

**Comment by MattiDeGrauwe** [comment]
Another thing I encountered is the following:
whenever I used the --delete param and the file already existed, the data was still deleted.

My suggestion here is to check for the --output file BEFORE the deletion of all the data?
Kind regards

**Comment by ferronrsmith** [comment]
`feature/pre-check` contains the check for the existence of the file before proceeding. Can you test and let me know if this is what you were talking ? Thanks

**Comment by ferronrsmith** [comment]
i.e the branch is based off master. so it won't contain this fix.

**Comment by MattiDeGrauwe** [comment]
root@kibana:~/github/elasticsearch-dump/bin# ./elasticdump --input=http://192.1.2.3:9200/* --output=my_index.json --type=data --searchBody='{"query": {"bool" : {"must" : {"term" : { "environment" : "blue" }},"filter": {"range" : {"@timestamp" : {"gte": "now-6h"}}}}}}' --delete --debug
/root/github/elasticsearch-dump/bin/elasticdump:92
    throw new Error('File `' + options.output + '` already exists, quitting');
    ^

Error: File `my_index.json` already exists, quitting
    at Object.<anonymous> (/root/github/elasticsearch-dump/bin/elasticdump:92:11)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js

Perfect, no lines were deleted before the check!

**Comment by ferronrsmith** [comment]
ok great. I'll merge these 2 PRs and cut a new release. Thanks for all the testing :+1:
