### ISSUE TITLE
Ignores the size parameter

### ISSUE THREAD

**Issue by aarjan** [taskrabbit/elasticsearch-dump#430]
elasticdump --input=http://localhost:5005/dl-server-2017 --output=dam.json --type=data --searchBody '{"size":3}'
Tue, 24 Apr 2018 10:06:37 GMT | starting dump
Tue, 24 Apr 2018 10:06:38 GMT | got 100 objects from source elasticsearch (offset: 0)
Tue, 24 Apr 2018 10:06:38 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:38 GMT | got 100 objects from source elasticsearch (offset: 100)
Tue, 24 Apr 2018 10:06:38 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:38 GMT | got 100 objects from source elasticsearch (offset: 200)
Tue, 24 Apr 2018 10:06:38 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:39 GMT | got 100 objects from source elasticsearch (offset: 300)
Tue, 24 Apr 2018 10:06:39 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:39 GMT | got 100 objects from source elasticsearch (offset: 400)
Tue, 24 Apr 2018 10:06:39 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:39 GMT | got 100 objects from source elasticsearch (offset: 500)
Tue, 24 Apr 2018 10:06:39 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:39 GMT | got 100 objects from source elasticsearch (offset: 600)
Tue, 24 Apr 2018 10:06:39 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:40 GMT | got 100 objects from source elasticsearch (offset: 700)
Tue, 24 Apr 2018 10:06:40 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:41 GMT | got 100 objects from source elasticsearch (offset: 800)
Tue, 24 Apr 2018 10:06:41 GMT | sent 100 objects to destination file, wrote 100
Tue, 24 Apr 2018 10:06:41 GMT | got 100 objects from source elasticsearch (offset: 900)
Tue, 24 Apr 2018 10:06:41 GMT | sent 100 objects to destination file, wrote 100

- ElasticDump : 3.3.12
- Elasticsearch : 5.3.2
- Node.js version : v9.11.1

I tested with version 3.3.0, same problem.

**Comment by ferronrsmith** [comment]
have you tried using the `--size` ?

```bash
elasticdump --input=http://localhost:5005/dl-server-2017 --output=dam.json --type=data --size 3
```
