### ISSUE TITLE
Error when restore data from json file to local ES

### ISSUE THREAD

**Issue by UCSBGauchos** [taskrabbit/elasticsearch-dump#434]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
latest
- Elasticsearch version
5.1.1
- Node.js version *(note that nodejs v8+ is required for this tool)*
v9.5.0
- Full command you are having issue with (with inputs and outputs)
docker run --net=host --rm -ti -v /tmp:/tmp taskrabbit/elasticsearch-dump:latest --input=/tmp/catalog_tag_index.json --output=http://127.0.0.1:9200/catalog_tag_index --type=data --limit=1000
Mon, 21 May 2018 15:28:20 GMT | starting dump
Mon, 21 May 2018 15:28:20 GMT | got 1000 objects from source file (offset: 0)
Mon, 21 May 2018 15:28:20 GMT | Error Emitted => connect ECONNREFUSED 127.0.0.1:9200
Mon, 21 May 2018 15:28:20 GMT | Total Writes: 0
Mon, 21 May 2018 15:28:20 GMT | dump ended with error (set phase)  => Error: connect ECONNREFUSED 127.0.0.1:9200

BTW curl http://127.0.0.1:9200 works

**Comment by ferronrsmith** [comment]
using the command above I am unable to replicate the issue

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
