### ISSUE TITLE
feature request| importing multiple mapping definition

### ISSUE THREAD

**Issue by levineran** [taskrabbit/elasticsearch-dump#435]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.2.4
- Elasticsearch version 3.3.14
- Node.js version *(note that nodejs v8+ is required for this tool)*
10

Hi,
I try to clone a development server.
I tried to clone all the docs, but unfortunately, it creates a dynamic mapping. 
The solution for me is to clone the mappings first. unfortunately as far as I know it is only possible with one index at-a-time. I want to import them all.

1. Is there any solution for that? 
2. Or it's a new feature.
3. By the way, shouldn't elastic-dump detect which docs I import, and if the index's mapping doesn't exist create it?

**Comment by ferronrsmith** [comment]
Have you tried using multi-elasticdump ?

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
