### ISSUE TITLE
Syntax error when running elasticdump

### ISSUE THREAD

**Issue by john717** [taskrabbit/elasticsearch-dump#441]
When I try to run **elasticdump --help**, I'm getting the following syntax error:

> >elasticdump --help
> 
> Microsoft (R) Windows Script Host Version 5.8
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> elasticdump.js(16, 30) Microsoft JScript compilation error: Syntax error

ElasticDump version - 3.3.14
ElasticSearch version - 5.6.3
Node.js version - 10.3.0

**Comment by ferronrsmith** [comment]
You need an actual shell 🐚, to run elasticdump on Windows. Git for Windows is packaged with bash, but cmd isn’t supported.
