### ISSUE TITLE
Programatic APIs

### ISSUE THREAD

**Issue by danm** [taskrabbit/elasticsearch-dump#442]
Wondering if there are any docs for using this module in a Node script using import or require.

I'd like to programmatically run an aggregation script which receives all data from a single index using elasticsearch-dump and then I can edit and import the aggregated data. Similar to rollup but without Xpack

**Comment by evantahler** [comment]
That's a good idea, and not too hard!  Notice how the (https://github.com/taskrabbit/elasticsearch-dump/blob/master/bin/elasticdump#L96 makes use of `new Elasticdump(options.input, options.output, options)`.

We would probably just need to export that object, and perhaps move the defaults in.

**Comment by ferronrsmith** [comment]
There isn't that much stopping you from doing this now. `elasticdump.js` is already the main.

```javascript
const Elasticdump = require('elasticsearch-dump');

const options = {outout,input};

 const dumper = new Elasticdump(options.input, options.output, options)
 dumper.on('log', function (message) { log('log', message) })
 dumper.on('debug', function (message) { log('debug', message) })
 dumper.on('error', (error) => { console.log('error', 'Error Emitted => ' + (error.message || JSON.stringify(error))) })
```

**Comment by evisong** [comment]
> There isn't that much stopping you from doing this now. `elasticdump.js` is already the main.
> 
> ```js
> const Elasticdump = require('elasticsearch-dump');
> 
> const options = {outout,input};
> 
>  const dumper = new Elasticdump(options.input, options.output, options)
>  dumper.on('log', function (message) { log('log', message) })
>  dumper.on('debug', function (message) { log('debug', message) })
>  dumper.on('error', (error) => { console.log('error', 'Error Emitted => ' + (error.message || JSON.stringify(error))) })
> ```

Hi, @ferronrsmith,

Your suggestion is awesome! I've followed this way to write a custom dumper, the input is ES and the output is S3.

However I find the program often ends too early, it exits before the uploading to S3 gets completed, without any error prompted.

Below is my code:

```js
import Elasticdump from 'elasticdump';

export const handler = async () => {
  const options = buildElasticdumpOptions({
    limit: 300,
    concurrency: 5,
    scrollTime: '30m',
    debug: true,
    toLog: true,
    input: 'http://es.example.com/my-index',
    searchBody: JSON.parse('{ ... }'),
    output: 's3://my_bucket/out.json',
    s3Region: REGION
  });
  const dumper = new Elasticdump(options);
  dumper.on('log', message => console.log('[dumper] %s', message));
  dumper.on('debug', message => console.debug('[dumper] %s', message));
  dumper.on('error', error => console.error('[dumper] Error emitted: %s', error.message || JSON.stringify(error)));

  // Converting the callback to a Promise
  let resultSize;
  try {
    resultSize = await new Promise((resolve, reject) => {
      dumper.dump((error, totalWrites) => {
        if (error) {
          reject(error);
        } else {
          resolve(totalWrites);
        }
      });
    });
    console.log('[dumper] resultSize %d', resultSize);
  } catch (err) {
    console.error('[dumper] %o', err);
  }

  return { output, resultSize };
};

function buildElasticdumpOptions(options) {
  const defaults = {
    size: -1,
    limit: 100,
    // ... as it's not exported,
    // copied from https://github.com/elasticsearch-dump/elasticsearch-dump/blob/4e51ae6fc72e2beb217b5f6d31e4379b278b7db5/bin/elasticdump#L13-L144
    // Btw, is it possible to export it in NPM package?
  };
  return { ...defaults, ...options };
}
```

When executing `handler()`, the log looks like this:

```plain
INFO [dumper] starting dump
DEBUG [dumper] discovered elasticsearch input major version: 6
DEBUG [dumper] lastScrollId: ...
DEBUG [dumper] Total Search Results: 464
INFO [dumper] got 300 objects from source elasticsearch (offset: 0)
INFO [dumper] sent 300 objects to destination s3, wrote 300
DEBUG [dumper] lastScrollId: ...
DEBUG [dumper] scrollRequest: {"uri":"http://es.example.com/_search/scroll","method":"POST","body":"{\"scroll\":\"30m\",\"scroll_id\":\"...\"}"}
DEBUG [dumper] body: "{\"_scroll_id\":\"....==\" ...}"
DEBUG [dumper] lastScrollId: ...
INFO [dumper] got 164 objects from source elasticsearch (offset: 300)
INFO [dumper] sent 164 objects to destination s3, wrote 164
INFO [dumper] got 0 objects from source elasticsearch (offset: 464)
INFO [dumper] Total Writes: 464
INFO [dumper] dump complete
INFO [dumper] resultSize 464
```

The result is correct but there is no `out.json` on S3. I had a hard time debugging this until I manually append a timer to postpone the program's termination:

```diff
 import Elasticdump from 'elasticdump';
+import { setTimeout } from 'node:timers/promises';
     // ...
     console.log('[dumper] resultSize %d', resultSize);
   } catch (err) {
     console.error('[dumper] %o', err);
   }
+  await setTimeout(1000);
   return { output, resultSize };
 };
```

This time, the `out.json` can be found on S3, and the log looks right:

```diff
 INFO [dumper] starting dump
 ...
 INFO [dumper] Total Writes: 464
 INFO [dumper] dump complete
 INFO [dumper] resultSize 464
+INFO [dumper] Uploaded out.json
```

Of cause, this timer is just a temporary workaround.

Could you advise what might be the root cause? 

Thanks.

**Comment by ferronrsmith** [comment]
The problem is with the s3 transport and how it works. It closes the stream just before the `finish` event is called, which causes that issue you're having. The solution would be to add emitters or call the callback after `finish` is called.

https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/transports/s3.js#L86

**Comment by evisong** [comment]
> The problem is with the s3 transport and how it works. It closes the stream just before the `finish` event is called, which causes that issue you're having. The solution would be to add emitters or call the callback after `finish` is called.
> 
> https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/transports/s3.js#L86
> 
> Timers would actually help, since it's added to the eventLoop and would be invoked after `finish` is called

Yes, you're right. Do you think is there any possible fix in `elasticdump`, or should the fix happen in `s3-stream-upload`?

Btw, I also find instead of `await setTimeout(1000)`, an `await setTimeout(0)`, `await setTimeout(10)` won't help, so I guess eventLoop may not be the only issue.

**Comment by ferronrsmith** [comment]
The fix can be done in transport, i'll push a PR and you can test

**Comment by evisong** [comment]
FYI, at last I've added a polling to check whether the upload is finished successfully:

```js
async function validateS3Upload(s3Client, key, interval = 1000, loopCount = 1) {
  if (loopCount === 0) {
    return;
  }
  // FIXME: https://github.com/elasticsearch-dump/elasticsearch-dump/issues/442#issuecomment-1463813176
  await setTimeout(interval);

  const command = new HeadObjectCommand({ Bucket: S3_BUCKET, Key: key });
  let output;

  try {
    output = await s3Client.send(command);
  } catch (error) {
    if (error instanceof NotFound && loopCount > 1) {
      console.warn('S3 object not found, revalidating in %d ms', interval);
      output = await validateS3Upload(s3Client, key, interval, loopCount - 1);
    } else {
      throw error;
    }
  }

  return output;
}
```

**Comment by ferronrsmith** [comment]
nice, thanks for sharing this.
