### ISSUE TITLE
AWS authorization is getting expired for the next request

### ISSUE THREAD

**Issue by mohanrao** [taskrabbit/elasticsearch-dump#445]
AWS authorization seems getting expired for next request

- ElasticDump version
3.3.7
- Elasticsearch version
6.2
- Node.js version *(note that nodejs v8+ is required for this tool)*
v8.11.1
- Full command you are having issue with (with inputs and outputs)
elasticdump --input=https://xxxxxx.us-east-1.es.amazonaws.com --input-index=aaa_index --output=https://yyyy.us-east-1.es.amazonaws.com --output-index=aaa_index --awsAccessKeyId=<awskey> --awsSecretAccessKey=<awsaccesskey> --type=data

Seems the authorization is getting cached one time . For AWS does it need to be regenerated every time

Fri, 08 Jun 2018 06:21:34 GMT | starting dump
Fri, 08 Jun 2018 06:21:38 GMT | got 100 objects from source elasticsearch (offset: 0)
Fri, 08 Jun 2018 06:21:46 GMT | sent 100 objects to destination elasticsearch, wrote 100
Fri, 08 Jun 2018 06:21:47 GMT | Error Emitted => {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
Fri, 08 Jun 2018 06:21:47 GMT | Total Writes: 100
Fri, 08 Jun 2018 06:21:47 GMT | dump ended with error (get phase) => Error: {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

**Comment by ferronrsmith** [comment]
Each time AWS is queried the header is signed. No caching is performed. Error above doesn't reflect expiration, seems the signature between client/host does not match. Try signing into aws first then using the profile mechanism to see if that works, then retry using the key+secret.
