### ISSUE TITLE
Error when dumping empty dataset

### ISSUE THREAD

**Issue by sanggonlee** [taskrabbit/elasticsearch-dump#448]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
3.3.1
- Elasticsearch version
6.3.0
- Node.js version *(note that nodejs v8+ is required for this tool)*
8.11.3
- Full command you are having issue with (with inputs and outputs)
`elasticdump --input=http://localhost:9201 --input-index=empty --output=http://localhost:9202 --output-input=empty --type=data --headers='{"User-Agent": "elasticdump", "Content-Type": "application/json"}'`
- A data set you can share publicly which reproduces the problem
Basically I was trying to dump from an empty index (the index called `empty` is literally an empty index

I'm getting the following error when trying to dump an empty dataset.
I would have expected it would do nothing, not printing out to standard error.
`dump ended with error (get phase) => Error: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse request body"}],"type":"illegal_argument_exception","reason":"Failed to parse request body","caused_by":{"type":"json_parse_exception","reason":"Unrecognized token 'DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAFBFjk3RWNaQXppVFA2cm9vZE5qcVpaVVEAAAAAAAABRBY5N0VjWkF6aVRQNnJvb2ROanFaWlVRAAAAAAAAAUIWOTdFY1pBemlUUDZyb29kTmpxWlpVUQAAAAAAAAFDFjk3RWNaQXppVFA2cm9vZE5qcVpaVVEAAAAAAAABRRY5N0VjWkF6aVRQNnJvb2ROanFaWlVR': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@589a3a5e; line: 1, column: 457]"}},"status":400}`

**Comment by ferronrsmith** [comment]
What is `--output-input=empty`, shouldn't this be `output-index` or simply `--output=http://localhost:9202/empty` ?

**Comment by sanggonlee** [comment]
@ferronrsmith That was a copy-and-paste mistake. With the `output-input` corrected to `output-index` I'm getting the same error.

**Comment by ferronrsmith** [comment]
Is it possible to provide a dataset ?

**Comment by ferronrsmith** [comment]
You should upgrade to a later version. Any version before v3.3.2 doesn't have ES 6 support.
