### ISSUE TITLE
Non escaped output of --type=settings and --type=analyzer 

### ISSUE THREAD

**Issue by PavelNovotny** [taskrabbit/elasticsearch-dump#449]
Hello,
is it possible to get non escaped output using elasticsearch-dump, for example:

./node_modules/elasticdump/bin/elasticdump \
  --input=http://10.199.160.137:9200/order_index \
  --output=/Users/pavelnovotny/WebstormProjects/elasticdump-play/data/order_index_settings.json \
  --type=settings

writes something like that:
"{\"order_index-else5_20180614_e2e_cisteni\":{\"settings\":{\"index\":{\"number_of_shards\":\"20\",\"provided_name\":\"order_index .... etc..

I would like to have an ordinary JSON, like that:
{"order_index-else5_20180614_e2e_cisteni":{"settings":{"index":{"number_of_shards":"20","provided_name":"order_index

I know that it depends on elastic api itself, but perhaps some use of --transform option would help. Is there any ready to use scripts (for output and input)?

Thank you in advance
Pavel

**Comment by ferronrsmith** [comment]
u can always use the **stdout** then pipe it to another program. The example below shows me using [jq](https://stedolan.github.io/jq/manual/).

```bash
./node_modules/elasticdump/bin/elasticdump
--input=http://10.199.160.137:9200/order_index
--output=$
--type=settings | jq -c 'fromjson' > /Users/pavelnovotny/WebstormProjects/elasticdump-play/data/order_index_settings.json
# note I used jq -c (-c compresses the output, remove this flag if this is not needed)
```

**Comment by PavelNovotny** [comment]
Nice. Piping looks more transparent then my  transform I've already made via reading/writing exported files. Thanks.
