### ISSUE TITLE
[Query] How do I directly do a multielasticdump on multiple indexes?

### ISSUE THREAD

**Issue by bluefangs** [taskrabbit/elasticsearch-dump#451]
- ElasticDump version : 3.3.15
- Elasticsearch version: 6.2.4
- Node.js version: 6.12 

I came accross this tool recently as I was required to move multiple indexes from one ES instance to another.
My indexes are named as : `test-index-1, test-index-2` etc.

Going by the documentation, I will be able to move one index at a time using this command:
```
elasticdump --input=http://localhost:9200/test-index-1 --output=http://localhost:9800/test-index-1 --limit=10000
elasticdump --input=http://localhost:9200/test-index-2 --output=http://localhost:9800/test-index-2 --limit=10000
...
...
```

How do I use wild cards to get all test-index-* to be copied over? I'm looking at multielasticdump but am not able to get a hang of how to do it. Do i necessarily have to dump it to a file first and then read it off the file and onto the second instance?

Thanks.

**Comment by ferronrsmith** [comment]
You can't move multiple indices using the default elasticdump tool. Check the [MultiElasticDump](https://github.com/taskrabbit/elasticsearch-dump#multielasticdump) section.

**Comment by ferronrsmith** [comment]
Closing this issue.
Please re-open if you do not feel the question has been answered sufficiently.
