### ISSUE TITLE
How do I authenticate for elasticsearch instances that use X-pack? I tried using basic authentication in --headers with no luck. Can you help?

### ISSUE THREAD

**Issue by omkarghalsasi** [taskrabbit/elasticsearch-dump#452]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version : Latest
- Elasticsearch version : 5.6.2
- Node.js version *(note that nodejs v8+ is required for this tool)* 8.11
- Full command you are having issue with (with inputs and outputs) 
$user = "usrname"
$pass = "pass"
$pair = "${user}:${pass}"

Build Authentication Header
$bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
$base64 = [System.Convert]::ToBase64String($bytes)
$basicAuthValue = "Basic $base64"
elasticdump --input=http://elastic-dev/xyz-logs-2018.06.20 --output=http://elastic-prod/mytest --headers $headers

**Comment by ferronrsmith** [comment]
It's very important that you read the docs before creating an issue.

If you need basic http auth, you can use it like this: --input=http://name:password@production.es.com:9200/my_index
