### ISSUE TITLE
Elasticdump Fails to copy data

### ISSUE THREAD

**Issue by tarpanpathak** [taskrabbit/elasticsearch-dump#453]
Hi, 
Just encountered an issue that is preventing us from migration Elasticsearch data between two clusters. Here are some environment details. 

- ElasticDump version: *3.3.15*
- Elasticsearch version: *2.4.3*
- Node.js version *(note that nodejs v8+ is required for this tool)*: *v10.0.0* 
- Full command you are having issue with (with inputs and outputs): 
```sh 
elasticdump \
> --input=http://es.test-tld/index \
> --output=http://es.test-tld/index \
> --type=data
```
- Error: 
```sh
Thu, 21 Jun 2018 06:31:39 GMT | starting dump
Thu, 21 Jun 2018 06:31:40 GMT | Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"},"status":400}
Thu, 21 Jun 2018 06:31:40 GMT | Total Writes: 0
Thu, 21 Jun 2018 06:31:40 GMT | dump ended with error (get phase) => Error: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: scrollId is missing;"},"status":400}
````
- A data set you can share publicly which reproduces the problem
Please create/use a small index with the following details. Once created, try copying this index between two Elasticsearch clusters running version *2.4.3* to see the error above.   
```
health status index            pri rep docs.count docs.deleted store.size pri.store.size 
green  open   test-index       5   1          0            0      1.5kb           795b
```

**Note**: copying data of `type=analyzer` and `type=mapping` works successfully.

**Comment by ferronrsmith** [comment]
I wasn't able to replicate this issue. What's the version of **output** cluster ?

**Comment by droloff** [comment]
We copy from :

```
version":{
"number": "6.0.1",
"build_hash": "d951bbf",
"build_date": "2017-12-07T01:43:54.348Z",
"build_snapshot": false,
"lucene_version": "7.0.1",
"minimum_wire_compatibility_version": "5.6.0",
"minimum_index_compatibility_version": "5.0.0"
},
```
to 

```
"version":{
"number": "6.2.2",
"build_hash": "10b1edd",
"build_date": "2018-02-28T15:42:08.616107Z",
"build_snapshot": false,
"lucene_version": "7.2.1",
"minimum_wire_compatibility_version": "5.6.0",
"minimum_index_compatibility_version": "5.0.0"
},
```
I'm not sure, if the problem is different behavior of the cluster. It looks like the body will not sent by calling  a http-GET. We are using a http-proxy, the aws-loadbalancer and a zuul application to get to our es-cluster. A lot of stages that need to handle the body of a get-request. 

Ok - It is Zuul who drops the body.
see: spring-cloud/spring-cloud-netflix#1964

But a GET could have a body, but should not. I've never understand why es does this.
Does it make sense to wrap the fix in a if (self.ESversion > 2 ) ?

**Comment by ferronrsmith** [comment]
I submit a fix. Can you test 3.3.16 and let me know ? Thanks

**Comment by tarpanpathak** [comment]
Thx for the quick fix @ferronrsmith. I've upgrade to and tried using version `3.3.16`. FYI, the `mapping` copy continue to work but the `data` copy is now throwing an SSL error: 
```
Thu, 21 Jun 2018 16:39:17 GMT | starting dump
Thu, 21 Jun 2018 16:39:18 GMT | got 0 objects from source elasticsearch (offset: 0)
Thu, 21 Jun 2018 16:39:18 GMT | Error Emitted => unable to verify the first certificate
Thu, 21 Jun 2018 16:39:18 GMT | Total Writes: 0
Thu, 21 Jun 2018 16:39:18 GMT | dump ended with error (set phase)  => Error: unable to verify the first certificate```

From the above, do you think I have an incorrect (source/destination) URI?

**Comment by ferronrsmith** [comment]
That's very strange. try using :

NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump \
> --input=http://es.test-tld/index \
> --output=http://es.test-tld/index \
> --type=data

**Comment by tarpanpathak** [comment]
Just tried that and got a different error this time: 
```
Thu, 21 Jun 2018 19:01:38 GMT | starting dump
Thu, 21 Jun 2018 19:01:38 GMT | got 0 objects from source elasticsearch (offset: 0)
undefined:1
default backend - 404
^

SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:57:21)
    at Request.self.callback (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:275:13)
```

**Comment by ferronrsmith** [comment]
This only happens when the data returned is not valid JSON.

**Comment by tarpanpathak** [comment]
I see. Just tried the copy using v`3.3.17` and getting the following error: 

```
Thu, 21 Jun 2018 20:44:28 GMT | starting dump
Thu, 21 Jun 2018 20:44:28 GMT | got 0 objects from source elasticsearch (offset: 0)
/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:27
    throw new Error('failed to parse json (message: "' + e.message + '") - source: ' + JSON.stringify(str))
    ^

Error: failed to parse json (message: "Unexpected token d in JSON at position 0") - source: "default backend - 404"
    at Object.parse (/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:27:11)
    at Request._callback (/usr/local/lib/node_modules/elasticdump/lib/transports/elasticsearch.js:57:27)
    at Request.self.callback (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elasticdump/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:275:13)
```

Let me understand this is a bit better, I'm hoping you can help. Here's my next question: if I go to the ES (search) endpoints using http/https directly, I get a valid response in `plain text` versus in JSON. Is it possible for me to modify `elasticdump` to handle this use-case? Also, the copy is working as expected for you correct?

**Comment by ferronrsmith** [comment]
There error seems plane. The backend is returning a 404.  `default backend - 404`. That's not an elasticdump issue. Format isn't the problem, the data returned must be valid json.

**Comment by tarpanpathak** [comment]
Found the problem. It was related to an invalid SSL certificate. After fixing this, all the copies are successfully going through.

**Comment by droloff** [comment]
@ferronrsmith I tested you fix and it works like expected. perfekt !! ... Thanks

**Comment by cristianchan** [comment]
Hi @tarpanpathak  how do you fix the SSL certificate I am having the same issue with one ES using Nginx
