### ISSUE TITLE
Error Emitted => connect EHOSTUNREACH

### ISSUE THREAD

**Issue by manuchitturi** [taskrabbit/elasticsearch-dump#457]
- ElasticDump version 3.315
- Elasticsearch version 2.x
- Node.js version v8

when i am trying to dump data, i ended up with below error

Error Emitted => connect EHOSTUNREACH

Some one please help me.

**Comment by manuchitturi** [comment]
it was working fine for 7 to 8 hours, after that it was throwing error
    std_err: 'Fri, 22 Jun 2018 10:39:54 GMT | Error Emitted => connect EHOSTUNREACH
      x.x.x.x:9200

**Comment by ferronrsmith** [comment]
EHOSTUNREACH - no route to host. Try running the query directly against the instance to see if it's working.

**Comment by manuchitturi** [comment]
its working fine.
Please help me in this...

Remaining buffer does not end with '\n'. Download corrupted?
Error Emitted => connect EHOSTUNREACH

**Comment by ferronrsmith** [comment]
It's hard to help you when there isn't enough information. What's the command ? Did you pipe the stream into another program ?

**Comment by manuchitturi** [comment]
Hi @ferronrsmith .I fixed  this error by adding max socket to command.
For testing, i limited using max sockets to 5. Please help till what number i can increase.?

**Comment by ferronrsmith** [comment]
That’s really dependent on your workload. Benchmark to see where your system bottoms out or just leave it to the default Infinity. It’s really up to you

**Comment by manuchitturi** [comment]
@ferronrsmith I didn't really understand one thing . why am i getting Error Emitted => connect EHOSTUNREACH error after my process is running for almost 8 hours , and it is continuing after that. I am able to perform ssh , curl.Please help me in resolving this error.

**Comment by ferronrsmith** [comment]
You have to monitor the network traffic to see why it’s closing. It’s hard to say what exactly is causing the issue.
