### ISSUE TITLE
how to set elastic authentication?

### ISSUE THREAD

**Issue by phypor** [taskrabbit/elasticsearch-dump#461]
{"root_cause":[{"type":"security_exception","reason":"missing authentication token for REST request [/test/test/_mapping]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication token for REST request [/hwqclog/report_detail/_mapping]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}

**Comment by phypor** [comment]
./elasticdump \
  --input=http://a:9200/test \
  --output=http://b:9200/test \
  --type=mapping

**Comment by ferronrsmith** [comment]
Helps to read the docs :


If you need basic http auth, you can use it like this: --input=http://name:password@production.es.com:9200/my_index
