### ISSUE TITLE
use elastic http auth should  urlencode 

### ISSUE THREAD

**Issue by phypor** [taskrabbit/elasticsearch-dump#463]
auth name : elastic
auth pwd : test#elastic

./elasticdump   --input=http://a:9200/test   --output=http://elastic:test#elastic@b:9200/test   --type=mapping

tell me "elastic:80" error.

but I change "#" to "%23" (urlencode)
./elasticdump   --input=http://a:9200/test   --output=http://elastic:test%23elastic@b:9200/test   --type=mapping
it runs normally

**Comment by ferronrsmith** [comment]
the base of the url isn't  urlencoded.
