### ISSUE TITLE
Out of memory when exporting large data

### ISSUE THREAD

**Issue by vinnytroia** [taskrabbit/elasticsearch-dump#466]
Elasticsearch version - latest
Elasticdump - latest

I am trying to dump a 1.2TB elasticsearch index. Everything is fine until the EXACT same spot in the index EVERy time. I've done this at least 5 times now. 

I've tried changing the limit from 10000 to 5000 with no difference. The machine i'm using has 16gb of ram and 4gb swap. No difference. 

here is the error

Wed, 25 Jul 2018 08:22:46 GMT | got 5000 objects from source elasticsearch (offset: 1615000)

<--- Last few GCs --->

[2002:0x349cb20]  2563272 ms: Scavenge 1132.3 (1415.8) -> 1124.6 (1416.3) MB, 3.4 / 0.0 ms  (average mu = 0.144, current mu = 0.121) allocation failure
[2002:0x349cb20]  2563320 ms: Scavenge 1132.3 (1416.3) -> 1124.6 (1417.3) MB, 3.8 / 0.0 ms  (average mu = 0.144, current mu = 0.121) allocation failure
[2002:0x349cb20]  2563400 ms: Scavenge 1137.5 (1422.5) -> 1130.3 (1423.0) MB, 3.6 / 0.0 ms  (average mu = 0.144, current mu = 0.121) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2d436f81e589 <JSObject>
    0: builtin exit frame: stringify(this=0x2d436f807809 <Object map = 0x23ce68082ba1>,0x3816804022e1 <undefined>,0x3816804022e1 <undefined>,0x2acdff38c5f1 <Object map = 0x23ce680f1f39>,0x2d436f807809 <Object map = 0x23ce68082ba1>)

    1: arguments adaptor frame: 1->3
    2: stringify [0x1a269710d301] [/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:~33] [pc=0x15b77fcdb885](this=0x39e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x89375c [node]
 3: v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe616b2 [node]
 6: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 7: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
 9: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
10: v8::internal::IncrementalStringBuilder::Extend() [node]
11: v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [node]
12: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
13: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
14: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
15: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
16: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
17: v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
18: v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) [node]
19: 0x15b77fc89efd
Aborted

is there a way to solve this?

**Comment by ferronrsmith** [comment]
Even streams have buffers (back-pressure) and after a while when they can get exhausted by a slow consumer. Try using NODE_OPTIONS=--max_old_space_size=8192 // increase heap to 8GB

**Comment by tholu** [comment]
@ferronrsmith Setting the `NODE_OPTIONS` did not work for me, it just lead to a different error much earlier:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write ENOBUFS
    at _errnoException (util.js:992:11)
    at Socket._writeGeneric (net.js:764:25)
    at Socket._writev (net.js:778:8)
    at doWrite (_stream_writable.js:395:12)
    at clearBuffer (_stream_writable.js:501:5)
    at onwrite (_stream_writable.js:449:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:876:12)
```

It's a much smaller index (~80GB) and I'm gzipping the file output. Any idea on how to generally do larger exports? Is there an easy way to split into smaller chunks?

**Comment by ferronrsmith** [comment]
To split in smaller chunks you can use searchBody to limit the amount of data that comes back. I'm working on a feature to split the files during export. Hopefully that fixes this issue. Will keep you posted.

**Comment by wxf4150** [comment]
https://github.com/wxf4150/esdump

speedup 83 times; and output gziped to 1/10 size

**Comment by tholu** [comment]
@wxf4150 Why is it so much faster?

**Comment by wxf4150** [comment]
@tholu 
> @wxf4150 Why is it so much faster?

- esdump write in golang .
- when export,  esdump never decode/encode the res.hits.source to and json object, it only save the res.hits.source bytes to gzip stream directly.  
-  nodejs(elasticsearch-dump) may  decode/encode all "elasticsearch respose body" to json object when export.

note:  res.hits.source is the document body from elasticsearch respose body
my outputfile is gziped and the   format is below:

document1RawBytes**Len**(4byte)+document1RawBytes
document2RawBytes**Len**(4byte)+document2RawBytes
...
...

sorry my bad english

**Comment by tholu** [comment]
@wxf4150 Very interesting! Are you planning to add tests etc.?

**Comment by wxf4150** [comment]
@tholu 
maybe later.
