### ISSUE TITLE
Elasticdump --noRefresh parameter doesn't seem to apply

### ISSUE THREAD

**Issue by admlko** [taskrabbit/elasticsearch-dump#467]
- ElasticDump version: 3.3.19
- Elasticsearch version: 6.2.2
- Node.js version: 8.11.3

Hi

I am running this command:
./node_modules/elasticdump/bin/elasticdump --input=/tmp/firewall-2018.06.25.json --output=http://localhost:9200/firewall-2018.06.25 --limit=5000 --noRefresh

The noRefresh option doesn't seem to work. I can still see the data as quickly as I could without the noRefresh option.
I put a debug print in the code (approx. line 663 inside the else-clause in file lib/transport/elasticsearch.js) where the refresh gets called and it prints, so it really executes the refresh even though --noRefresh is set.

**Comment by ferronrsmith** [comment]
Think you might be mixing up the option with `refresh_interval`. `noRefresh` only disables the refresh that occurs when elastic-dump is re-indexing your data. It does not modify elasticsearch `refresh_interval`. If this is set to the default `30s`, ES will refresh regardless.

i.e. If you're indexing a large data-set you should disable refresh entirely. That way it improves through-put.

https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html

**Comment by ferronrsmith** [comment]
Think you might be mixing up the option with refresh_interval. noRefresh only disables the refresh that occurs when elastic-dump is re-indexing your data. It does not modify elasticsearch refresh_interval. If this is set to the default 30s, ES will refresh regardless.

i.e. If you're indexing a large data-set you should disable refresh entirely. That way it improves through-put.

In case you were looking auth the right thing. Did you try :

./node_modules/elasticdump/bin/elasticdump --input=/tmp/firewall-2018.06.25.json --output=http://localhost:9200/firewall-2018.06.25 --limit=5000 --noRefresh=true

https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html
