### ISSUE TITLE
Copying data from 1 ES cluster to an another is failing when limit greater or  equal to 6000

### ISSUE THREAD

**Issue by Lord-Y** [taskrabbit/elasticsearch-dump#472]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 3.4.0
- Elasticsearch version: 5.5.2
- Node.js version v8.11.4

Hi all,
Copying data from 1 ES cluster to an another is failing when limit greater than 6000:
```
OLD_ES5=10.X.X.X
NEW_ES5=10.X.X.X
INDEX=my_index
elasticdump \
  --input=http://$OLD_ES5:9200/$INDEX \
  --output=http://$NEW_ES5:9200/$INDEX \
  --type=analyzer
elasticdump \
  --input=http://$OLD_ES5:9200/$INDEX \
  --output=http://$NEW_ES5:9200/$INDEX \
  --type=mapping
elasticdump \
  --input=http://$OLD_ES5:9200/$INDEX \
  --output=http://$NEW_ES5:9200/$INDEX \
  --type=data \
  --limit=10000 \
  --noRefresh

Fri, 07 Sep 2018 14:31:12 GMT | starting dump
Fri, 07 Sep 2018 14:31:24 GMT | got 10000 objects from source elasticsearch (offset: 0)
Fri, 07 Sep 2018 14:31:29 GMT | Error Emitted => failed to parse json (message: "Unexpected end of JSON input") - source: ""
Fri, 07 Sep 2018 14:31:29 GMT | Total Writes: 0
Fri, 07 Sep 2018 14:31:29 GMT | dump ended with error (set phase)  => Error: failed to parse json (message: "Unexpected end of JSON input") - source: ""
```

With a limit a 6000 it's failing after some import:
```
Fri, 07 Sep 2018 14:35:06 GMT | starting dump
Fri, 07 Sep 2018 14:35:11 GMT | got 6000 objects from source elasticsearch (offset: 0)
Fri, 07 Sep 2018 14:37:00 GMT | sent 6000 objects to destination elasticsearch, wrote 6000
Fri, 07 Sep 2018 14:37:06 GMT | got 6000 objects from source elasticsearch (offset: 6000)
Fri, 07 Sep 2018 14:38:49 GMT | sent 6000 objects to destination elasticsearch, wrote 6000
Fri, 07 Sep 2018 14:38:56 GMT | got 6000 objects from source elasticsearch (offset: 12000)
Fri, 07 Sep 2018 14:40:46 GMT | sent 6000 objects to destination elasticsearch, wrote 6000
Fri, 07 Sep 2018 14:40:53 GMT | got 6000 objects from source elasticsearch (offset: 18000)
Fri, 07 Sep 2018 14:40:56 GMT | Error Emitted => failed to parse json (message: "Unexpected end of JSON input") - source: ""
Fri, 07 Sep 2018 14:40:56 GMT | Total Writes: 18000
Fri, 07 Sep 2018 14:40:56 GMT | dump ended with error (set phase)  => Error: failed to parse json (message: "Unexpected end of JSON input") - source: ""
```

**Comment by ferronrsmith** [comment]
turn on debugging. There isn't enough information to help you.

**Comment by Lord-Y** [comment]
@ferronrsmith The nodeJS is out of memory:

Mon, 10 Sep 2018 08:52:25 GMT | starting dump
Mon, 10 Sep 2018 08:52:25 GMT [debug] | discovered elasticsearch input major version: 5
Mon, 10 Sep 2018 08:52:37 GMT | got 10000 objects from source elasticsearch (offset: 0)
Mon, 10 Sep 2018 08:52:37 GMT [debug] | discovered elasticsearch output major version: 5

<--- Last few GCs --->

[7501:0x30a5780]    17304 ms: Mark-sweep 979.2 (1278.2) -> 978.9 (1284.7) MB, 502.0 / 0.0 ms  allocation failure GC in old space requested
[7501:0x30a5780]    17820 ms: Mark-sweep 978.9 (1284.7) -> 978.9 (1237.2) MB, 516.3 / 0.0 ms  last resort GC in old space requested
[7501:0x30a5780]    18323 ms: Mark-sweep 978.9 (1237.2) -> 978.9 (1225.2) MB, 502.2 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xd93e825879 <JSObject>
    1: createWriteReq(aka createWriteReq) [net.js:797] [bytecode=0x174743ed1c61 offset=111](this=0x35a100a022d1 <undefined>,req=0xd82e6004389 <WriteWrap map = 0x2e446ccf45b9>,handle=0x31adacc06109 <TTY map = 0x1d8d3cac13f1>,data=0xd82e6004239 <Very long string[178294702]>,encoding=0xd93e834ba1 <String[4]: utf8>)
    2: _writeGeneric [net.js:760] [bytecode=0x174743ed0ae1 offset=395](this=0x31adacc1...

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8c21ec [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [node]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
10: int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
11: void node::StreamBase::JSMethod<node::LibuvStreamWrap, &(int node::StreamBase::WriteString<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&))>(v8::FunctionCallbackInfo<v8::Value> const&) [node]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
13: 0xad712c [node]
14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
15: 0x537cec842fd
Aborted
```

On my VM I have plenty of memory (30Go of ram)

**Comment by Lord-Y** [comment]
As the full command line is:
`node /usr/bin/elasticdump`
I called it with:
`node --max-old-space-size=8192 /usr/bin/elasticdump`

but at the end, the import failed with:

`Mon, 10 Sep 2018 09:12:14 GMT | Error Emitted => failed to parse json (message: "Unexpected end of JSON input") - source: ""
Mon, 10 Sep 2018 09:12:14 GMT | Total Writes: 0
Mon, 10 Sep 2018 09:12:14 GMT | dump ended with error (set phase)  => Error: failed to parse json (message: "Unexpected end of JSON input") - source: ""
`

**Comment by ferronrsmith** [comment]
Try increasing `max-old-space-size`. Seems your heap can't handle the amount of objects you're adding.
