### ISSUE TITLE
Migration a large data volume around 200 GB.

### ISSUE THREAD

**Issue by guielebo** [taskrabbit/elasticsearch-dump#481]
- ElasticDump version 4.0.3
- Elasticsearch version 2.3.4
- Node.js 8.10.0 version *(note that nodejs v8+ is required for this tool)*
- Full command you are having issue with (with inputs and outputs)

multielasticdump \  --direction=load  --input=dump \  --output=http://localhost:9200 \

I need a help 😕 

I'm doing a migration to the Azure VM and I have a large data volume around 200 GB.

I can not stop the service that fills the old index, and due to the large mass of data the migration estimate has around 5 days.

I'm going to have a data gap because I create my dump 2 days ago, is there a way to just migrate the difference from the index to the new one after the migration ends?

Tks 😃

**Comment by ferronrsmith** [comment]
It all depends on how your data is indexed. Usually for me I add metadata attributes to my records such as @uat/@iat so I can filter a subset based on time, but I'm not sure how the data is segmented to allow that.

There's a `--searchBody` flag that allows your to enter a query into ES.
