### ISSUE TITLE
s3 output doesn't write newlines between events

### ISSUE THREAD

**Issue by hilt86** [taskrabbit/elasticsearch-dump#487]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 4.10
- Elasticsearch version 6.3.2
- using Docker
- using options necessary to output to s3 bucket and --s3RecordKey events.
- https://s3.amazonaws.com/www.elasticsearch-dump.com/elastic_2018-11-07+00%3A31%3A12_output.jsonl

Expected behavior : elasticdump writes json lines to a file on s3 - what really happens is all "json lines" are on a single line...

**Comment by ferronrsmith** [comment]
Pushed a new release
