### ISSUE TITLE
S3 uplaod

### ISSUE THREAD

**Issue by abhi-dwivedi** [taskrabbit/elasticsearch-dump#488]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version  --
- Elasticsearch version --  5.3
- Node.js version *(note that nodejs v8+ is required for this tool)*  -- 11.1
- Full command you are having issue with (with inputs and outputs):
 107      56  9 10:30 ?        00:06:12 node /usr/local/bin/elasticdump --input=http://elasticsearch:9200/logstash-* --output=/root/logs/logstash.json --type=data

So i have 1.1 TB data with multiple indexes i want that data directly export to S3 . Could you please share the command.

Regards
Abhinav D

**Comment by ferronrsmith** [comment]
Refer to : https://github.com/taskrabbit/elasticsearch-dump/issues/473

or read the documentaion.

**Comment by ferronrsmith** [comment]
```bash
# Export ES data to S3
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --s3Bucket "${bucket_name}" \ 
  --awsAccessKeyId "${access_key_id}" \ 
  --awsSecretAccessKey "${access_key_secret}" \
  --s3RecordKey "${file_name}"  
```

**Comment by abhi-dwivedi** [comment]
@ferronrsmith 

Thanks for answering.

I have used elasticdump for my logstash-* index and its amount more than 700GB data . And it take so much time to restore the data in JSON file . in EBS volume .

Is there a way we can expedite it .

**Comment by ferronrsmith** [comment]
Have your tried splitting the files and loading them into ES concurrently

**Comment by abhi-dwivedi** [comment]
@ferronrsmith 

Actually i wanted to upload the json file in S3 and then use athena aws service for archive logs

**Comment by ferronrsmith** [comment]
We had to make some changes due to collisions with existing features.

It should be : 

elasticdump --input=http://elasticsearch:9200/logstash-2018.01.03 --s3Bucket "xyz" --s3AccessKeyId "" --s3SecretAccessKey "*" --s3RecordKey "logstash.json" --type=data

**Comment by ferronrsmith** [comment]
Haven't added support for that as yet.

**Comment by manugarri** [comment]
Got it, so right now this feature is not useable since it only writes a huge text file in s3. Unfortunately I dont know node.js so I cant really help (just complain :D). Thanks anyways.

**Comment by ferronrsmith** [comment]
You can use file transport to segment the files by size then push those manually to s3. Same process, just 1 more step.

**Comment by manugarri** [comment]
that is what I am doing right now yeah. it doubles the amount of transfer though.
