### ISSUE TITLE
分片问题

### ISSUE THREAD

**Issue by liqitian3344** [taskrabbit/elasticsearch-dump#490]
备份数据时怎么指定分片数量呢？

**Comment by ferronrsmith** [comment]
Very important that you read the documentation. Next time please translate the issue.

```bash
elasticdump \
  --input=http://production.es.com:9200/my_index \
  --output=/data/my_index.json \
  --fileSize=10mb
```

**Comment by liqitian3344** [comment]
![image](https://user-images.githubusercontent.com/29157770/48456122-d2d6d380-e7f8-11e8-9bb2-a0f740cc3612.png)
我用的是下面这种方式备份数据
elasticdump \
  --input=http://production.es.com:9200/ \
  --output=output=http://staging.es.com:9200/ \
  --limit=500
  --type=true
但是备份下来的分片（上图位置箭头）数不对，我要把它指定为三个 我应该怎么做呢？

**Comment by ferronrsmith** [comment]
That's unrelated to `elasticdump`. To shrink and index you need to re-index and reduce the shard count.
