### ISSUE TITLE
Feature request: multielasticdump with aliases

### ISSUE THREAD

**Issue by MaitreDede** [taskrabbit/elasticsearch-dump#494]
Hi,
It would be cool to have multielasticdump dump/load aliases.

In my use case, my ES mappings changes as the project evolves, and I use aliases when upgrading mappins. When using multielasticdump, it dumps the indexes, not the aliases, so I have to recreate them by hand, or rename indices to their alias name before loading into target cluster.

**Comment by ferronrsmith** [comment]
You can always submit a PR. It's a very simple feature to add. We already support dumping aliases in elasticdump. Adding to multielasticdump is even simpler.
