### ISSUE TITLE
How to set track_scores?

### ISSUE THREAD

**Issue by LordMike** [taskrabbit/elasticsearch-dump#495]
I'd very much like to disable scoring in my dumps, and I assume that unless the documents are intended to be sorted or if they don't include the result wrapper (the one with the score in it), scores aren't all that interesting at all.

So maybe the option should be set always, or most of the time? :)

For ref, in `uri search` (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html), there is a `track_scores` option that can be disabled.

**Comment by ferronrsmith** [comment]
use `--params` to set additional params on the URL.
