### ISSUE TITLE
how do I use multielasticdump to move multiple indexes from one cluster to another cluster directly？

### ISSUE THREAD

**Issue by wkcaeser** [taskrabbit/elasticsearch-dump#501]
- ElasticDump version:  4.1.2
- Elasticsearch version: 2.4.6
- Node.js version *(note that nodejs v8+ is required for this tool)* : v6.14.3
- Full command you are having issue with (with inputs and outputs)：
```
node --max-old-space-size=4096 /usr/bin/multielasticdump \
  --input=http://172.16.13.14:9200 \
  --output=/data/dump \
  --direction=dump \
  --noRefresh \
  --limit=20000

node --max-old-space-size=4096 /usr/bin/multielasticdump \
  --input=/data/dump \
  --output=http://192.168.3.41:9200 \
  ----direction=load \
  --noRefresh \
  --limit=20000
```
- A data set you can share publicly which reproduces the problem

Can I move the indexes directly? 
Do I necessarily have to dump it to a file first and then read it off the file and onto the second instance?

**Comment by ferronrsmith** [comment]
for `multielasticdump` no, and the truth is, you don't want that. because if something goes wrong and you don't have a copy you're screwed. 


i.e You can always write a script to iterate over a list of indices in bash. Shouldn't be too hard
