### ISSUE TITLE
'not_x_content_exception' when send data from file to es-6.5.2

### ISSUE THREAD

**Issue by andersonVSA** [taskrabbit/elasticsearch-dump#502]
Hi! I'm getting this error when send data to es6 cluster:

- elasticdump --version 4.1.2

- Elasticsearch 6.5.2
- node -v v11.3.0
- elasticdump --output=http://127.0.0.1:9200 --input=teste2.json --output-index=my_index/_doc --type=data  --headers='{"Content-Type": "application/json"}'
Thu, 20 Dec 2018 16:07:55 GMT | starting dump
Thu, 20 Dec 2018 16:07:55 GMT | got 1 objects from source file (offset: 0)
{ _index: 'myindex',
  _type: '_doc',
  _id: 'dhdfzGcBR9NC_ALElHLX',
  status: 400,
  error:
   { type: 'mapper_parsing_exception',
     reason: 'failed to parse',
     caused_by:
      { type: 'not_x_content_exception',
        reason:
         'Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes' } } }

my jsondata:
{"uri": "features/search.feature", "id": "google-search", "keyword": "Feature", "name": "Google Search", "description": "", "line": 1, "elements": [{"id": "google-search;search-for-existing-result-in-google", "keyword": "Scenario", "name": "Search for existing result in google", "description": "", "line": 2, "type": "scenario", "before": [{"match": {"location": "capybara-3.12.0/lib/capybara/cucumber.rb:14"}, "result": {"status": "passed", "duration": 22113}}, {"match": {"location": "capybara-3.12.0/lib/capybara/cucumber.rb:22"}, "result": {"status": "passed", "duration": 10699}}], "steps": [{"keyword": "Given ", "name": "I opened chrome browser", "line": 3, "match": {"location": "features/step_definitions/google_steps.rb:1"}, "result": {"status": "passed", "duration": 23040}}, {"keyword": "When ", "name": "I visit google site", "line": 4, "match": {"location": "features/step_definitions/google_steps.rb:4"}, "result": {"status": "passed", "duration": 1473574226}}, {"keyword": "Then ", "name": "I should see results", "line": 5, "match": {"location": "features/step_definitions/google_steps.rb:8"}, "result": {"status": "pending", "error_message": "TODO (Cucumber::Pending)\n./features/step_definitions/google_steps.rb:9:in `\"I should see results\"'\nfeatures/search.feature:5:in `Then I should see results'", "duration": 194027}}], "after": [{"match": {"location": "capybara-3.12.0/lib/capybara/cucumber.rb:10"}, "result": {"status": "passed", "duration": 46859338}}]}], "project_name": "higia-ex", "version": "1.2.3", "revision": "100", "build_number": "305", "build_tag": "higia-ex-305-22-12-2018"}

**Comment by ferronrsmith** [comment]
The data isn't in the correct format for import

Your data should look something like this going in...

```json
{"_index":"bigint_index","_type":"seeds","_id":"0","_score":1,"_source":{"key":1726275868403174266,"_uuid":"0"}}
```
