### ISSUE TITLE
import indices from AWS S3 bucket

### ISSUE THREAD

**Issue by alegma** [taskrabbit/elasticsearch-dump#503]
Hi,

I can backup indices to S3 bucket but is it possible to restore indices from S3 to my cluster using elasticdump?

**Comment by ferronrsmith** [comment]
not at this time. The s3 upload was needed by someone (@hilt86) and he kindly "lend" me a bucket for development. I'll be away for the holidays for a couple weeks, but you can feel free to submit a PR if you'd like or a **bucket** to help anyone who want to attempt this issue

**Comment by ferronrsmith** [comment]
Closing this. If someone needs this badly, share a bucket, send me the credentials and I'll gladly implement.
