### ISSUE TITLE
ECONNREFUSED problem

### ISSUE THREAD

**Issue by kgeographer** [taskrabbit/elasticsearch-dump#516]
I'm trying to input to a remote server from my local dev machine. I have sudo, and connect to the server routinely with an ssh private key. I can dump the files locally, copy them over and restored them, creating a copy of the index, but I'd like to get this on a script. I've tried with and without a loginname@ or user:password@ prefix to the ip, also with and without the --key option. There is no password associated with the key. I've opened port 9200 on the server, and confirmed:
```
To                         Action      From
--                         ------      ----
9200                       ALLOW       Anywhere
9200/tcp                   ALLOW       Anywhere
9200 (v6)                  ALLOW       Anywhere (v6)
9200/tcp (v6)              ALLOW       Anywhere (v6)
```
I must be missing something basic here -- thanks!

- ElasticDump version **4.4.0**
- Elasticsearch version **6.1.1 local, 6.4.1 remote**
- Node.js version **v11.10.0**

- Full command you are having issue with (with inputs and outputs)
elasticdump --input=http://localhost:9200/my-index --output=http://138.197.200.44:9200/my-index --type=mapping --input-key ~/.ssh/id_rsa

- A data set you can share publicly which reproduces the problem
not sure this is applicable

**Comment by ferronrsmith** [comment]
It never hurts reading the documentation.

`input-key` is a parameter for **TLS X509 authentication**. Try port-forwarding ssh `ssh -L ${PORT}:0.0.0.0:${PORT}`, then do whatever.

**Comment by kgeographer** [comment]
I _have_ read the documentation. Snide remarks like that are offensive, but I guess that's what you were after. In the documentation, --key references a private key file, nothing about TLS X509, which _is_ referred to above, for the --tlsAuth option. Perhaps the several lines below that all refer to tlsAuth, but that is not apparent.

**Comment by ferronrsmith** [comment]
```markdown
--tlsAuth
                    **Enable TLS X509 client authentication**
--cert, --input-cert, --output-cert
                    Client certificate file. Use --cert if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--key, --input-key, --output-key
                    Private key file. Use --key if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--pass, --input-pass, --output-pass
                    Pass phrase for the private key. Use --pass if source and destination are identical.
                    Otherwise, use the one prefixed with --input or --output as needed.
--ca, --input-ca, --output-ca
                    CA certificate. Use --ca if source and destination are identical.
```

The options above are all related to `TLS X509`

```javascript
  /// Code snippet
    if (this.parent.options.tlsAuth) {
      Object.assign(defaultOptions,
        this.applySSL([`${options.type}-cert`, `${options.type}-key`, `${options.type}-pass`, `${options.type}-ca`]))

      Object.assign(defaultOptions, this.applySSL(['cert', 'key', 'pass', 'ca']))
}
```
