### ISSUE TITLE
Docker builds not working

### ISSUE THREAD

**Issue by ferronrsmith** [taskrabbit/elasticsearch-dump#519]
@evantahler The docker builds are no longer working. Think this might be related to a recent change by docker. Is it possible for you to reconfigure the auto build or share the repository with me so I can manage it. Thanks !

**Comment by evantahler** [comment]
Ah, it looks like some one who works at TaskRabbit (I left a few years ago) will need to be the ones who link the [Docker repo](https://cloud.docker.com/u/taskrabbit/repository/docker/taskrabbit/elasticsearch-dump) to this project.  I don't have access any more :/

@bleonard can you click the buttons perhaps?

**Comment by ferronrsmith** [comment]
I guess folks can build it themselves. Not a high priority.

**Comment by ferronrsmith** [comment]
@bleonard any update on this ? Is this something that can be fixed ? Thanks

**Comment by ferronrsmith** [comment]
@evantahler I'm currently maintaining this project "crippled", I'm unable to create a new docker build due to limited access and @bleonard doesn't seem to be responding. The docker image doesn't match up 1:1 with the nom package, which confuses users.

**Comment by ferronrsmith** [comment]
Actually nvm. I'll add a deprecation notice for docker.

**Comment by evantahler** [comment]
Actually, I think I've finally got though to Docker support to add you to the team!  I'll need to know the email address associated with your https://hub.docker.com/u/ferronrsmith account

**Comment by ferronrsmith** [comment]
ferronrsmith@gmail.com (other folks please do not spam :+1:)

**Comment by evantahler** [comment]
Got it! Above comment annonomized :D

**Comment by ferronrsmith** [comment]
Thanks !
