### ISSUE TITLE
"Validation Failed: 1: type is missing;"

### ISSUE THREAD

**Issue by EdwardC996** [taskrabbit/elasticsearch-dump#520]
- ElasticDump 4.6.0
- Elasticsearch 6.5.1
- Node.js version 11.6.0

`abc@abc-Aspire-E5-471G:~/node_modules/elasticdump/bin$ ./elasticdump \`
`--input=/home/abc/userData.json \`
`--output=http://localhost:9200/users \--type=data`
`Wed, 27 Feb 2019 13:09:39 GMT | starting dump`
`Wed, 27 Feb 2019 13:09:39 GMT | got 1 objects from source file (offset: 0)`
`Wed, 27 Feb 2019 13:09:39 GMT | Error Emitted => `
`{"error":{"root_cause":`
`[{"type":"action_request_validation_exception",`
`"reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception",`
`"reason":"Validation Failed: 1: type is missing;"},"status":400}`
`Wed, 27 Feb 2019 13:09:39 GMT | Total Writes: 0`
`Wed, 27 Feb 2019 13:09:39 GMT | dump ended with error (set phase)  => `
`Error: {"error":{"root_cause":`
`[{"type":"action_request_validation_exception",`
`"reason":"Validation Failed: 1: type is missing;"}],"type":"action_request_validation_exception",`
`"reason":"Validation Failed: 1: type is missing;"},"status":400}`

here is my mapping file example users.json:
`{
    "mappings" : {
        "user" : {
            "properties" : {
                "id" : {
                    "type" : "long"
                },
                "name" : {
                    "type" : "text"
                },
                "hobby" : {
                    "type" : "text"
                }
            }
        }
    }
}`

here is my data example userData.json:
`[
{"id":"67785", "name":"abcd", "hobby":"abcde"},
{"id":"67784", "name":"abc", "hobby":"abcd"},
{"id":"67783", "name":"ab", "hobby":"abc"}
]`

**Comment by EdwardC996** [comment]
How can I solve this problem?

**Comment by ferronrsmith** [comment]
```json
{"_index":"users","_type":"seeds","_id":"67785","_score":1,"_source":{"id":"67785", "name":"abcd", "hobby":"abcde"}}
{"_index":"users","_type":"seeds","_id":"67784","_score":1,"_source":{"id":"67784", "name":"abcd", "hobby":"abcd"}}
{"_index":"users","_type":"seeds","_id":"67784","_score":1,"_source":{"id":"67783", "name":"ab","hobby":"abc"}}
```

> **NB: Format needs to be JSONL**
