### ISSUE TITLE
Option to copy rather than dump?

### ISSUE THREAD

**Issue by dprski33** [taskrabbit/elasticsearch-dump#521]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 3.1.0
- Elasticsearch version: 2.3.2
- Node.js version *(note that nodejs v8+ is required for this tool)*: v10.13.0
- Full command you are having issue with (with inputs and outputs): n/a
- A data set you can share publicly which reproduces the problem: n/a

Is there a way to perform an 'copy' operation when the input host and output host are the same?
Am I incorrect is assuming that when running this from my localhost creates temp files on my machine?
`elasticdump --input=host1:9200/index1 --output=host1:9200/index2`

**Comment by ferronrsmith** [comment]
copy/dump/move/re-index.. Different name for the same thing. Your assumption is incorrect. 
All data is streams, elasticdump has what are call transports. The transports are responsible for directing where input/output goes. So in essence the above command is valid.


There's an example section of the README. Check it out, thanks. https://github.com/taskrabbit/elasticsearch-dump


```bash
# copies index1 data to index2
elasticdump --input=host1:9200/index1 --output=host1:9200/index2
```

**Comment by dprski33** [comment]
So should it be faster to run that command or this one?
`ssh host1 && elasticdump --input=localhost:9200/index1 --output=localhost:9200/index2`

**Comment by ferronrsmith** [comment]
The first command you’re connecting running esdump on the box, the second I assume your sshing then running it ? Shouldn’t be different once you’re connected

**Comment by dprski33** [comment]
from my local, i.e.: running esdump locally, took about 2.5 hours:
`elasticdump --input=host1:9200/index1 --output=host1:9200/index2`
sshing to the es host then running esdump on that host took about 1.3 hours:
`ssh host1 && elasticdump --input=localhost:9200/index1 --output=localhost:9200/index2`
It seems that running locally vs running on the host does make a difference.
My question is about the apparent bottleneck here.  I guess the best answer is to just run the esdump operation on the ES host itself rather than from remote.

**Comment by ferronrsmith** [comment]
It would, but that’s a network issue, not a elasticdump issue
