### ISSUE TITLE
FEATURE REQUEST : Allow restoring multiple index mappings

### ISSUE THREAD

**Issue by johntmyers** [taskrabbit/elasticsearch-dump#524]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 4.3
- Elasticsearch version: 5.6.5
- Node.js version *(note that nodejs v8+ is required for this tool)*: 8.12

I'm using the latest Docker build.

Backup and restore of ES mappings does not have parity among backup vs restore.

For backup, you can specify just the ES URL as the input, i.e. http://localhost:9200 and if the output is a JSON file, you'll get an object where the top level keys are the name of the indices.

However, when restoring from json to ES you *must* provide an index as the output. This is where things get weird. The resulting index you restored to, will contain mappings for *EVERY* doc type that was in the backup json file, regardless of which indices various types belonged to.

So I created 2 indices and 2 unique mappings, one for each index:

```python
In [2]: es = elasticsearch.Elasticsearch(port=9201)

In [4]: es.indices.create('indi-1')
Out[4]: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'indi-1'}

In [5]: es.indices.create('indi-2')
Out[5]: {'acknowledged': True, 'shards_acknowledged': True, 'index': 'indi-2'}

In [6]: mapping1 = {
   ...:     'properties': {
   ...:         'ip': {'type': 'ip'}
   ...:         }}

In [7]: mapping1
Out[7]: {'properties': {'ip': {'type': 'ip'}}}

In [8]: es.indices.put_mapping('doc', mapping1, index='indi-1')
Out[8]: {'acknowledged': True}

In [9]: mapping2 = {'properties': {'another-ip': {'type': 'ip'}}}

In [10]: es.indices.put_mapping('doc', mapping2, index='indi-2')
Out[10]: {'acknowledged': True}
```

Then I backed up all indices, which is "normal" functionality:

`docker run -it --net my_net -v $(pwd)/es_dump_test:/tmp/es_dump_test/ taskrabbit/elasticsearch-dump --input=http://elastic2:9200 --output=/tmp/es_dump_test/mappings.json --type mapping`

And here's my mappings:

```json
{"indi-2":{"mappings":{"doc":{"properties":{"another-ip":{"type":"ip"}}}}},"indi-1":{"mappings":{"doc":{"properties":{"ip":{"type":"ip"}}}}}}
```

Then, flush ES...

So now, I _cannot_ restore these mappings in the *same way* I backed them up.

```
docker run -it --net my_net -v $(pwd)/es_dump_test:/tmp/es_dump_test/ taskrabbit/elasticsearch-dump --output=http://elastic2:9200 --input=/tmp/es_dump_test/mappings.json --type mapping

Wed, 06 Mar 2019 22:30:42 GMT | starting dump
Wed, 06 Mar 2019 22:30:42 GMT | got 1 objects from source file (offset: 0)
Wed, 06 Mar 2019 22:30:42 GMT | Error Emitted => {"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"}
Wed, 06 Mar 2019 22:30:42 GMT | Total Writes: 0
Wed, 06 Mar 2019 22:30:42 GMT | dump ended with error (set phase)  => [object Object]
```

Ok, so I want to restore my first index...

`docker run -it --net my_net -v $(pwd)/es_dump_test:/tmp/es_dump_test/ taskrabbit/elasticsearch-dump --output=http://elastic2:9200/indi-1 --input=/tmp/es_dump_test/mappings.json --type mapping`

When I dump my mappings...

```
{
    "indi-1": {
        "mappings": {
            "doc": {
                "properties": {
                    "another-ip": {
                        "type": "ip"
                    },
                    "ip": {
                        "type": "ip"
                    }
                }
            }
        }
    }
}
```

Both field mappings for the same doc appear in this index. Had I chosen different doc names, there would be two types of docs under "mappings".

**Comment by ferronrsmith** [comment]
The problem is you're doing a global dump of mappings (multiple index mapping backup), then trying to do a specific index restoration. It wasn't designed for that, hence why you're having issues.

**Comment by johntmyers** [comment]
There isn’t a global restore option. So what’s the point of a global
backup? And even then, you’re ignoring the fact that doing an
index-specific restore off of a global backup still applies every mapping
for every doc type for every index to the one specific index named in the
restore.

**Comment by ferronrsmith** [comment]
It would because it’s iterating the global mapping over a single index. 
feel free to submit a PR
