### ISSUE TITLE
Can I use elasticdump backup if es has an account password on x-pack

### ISSUE THREAD

**Issue by 18601762542** [taskrabbit/elasticsearch-dump#526]
Can I use elasticdump backup if es has an account password on x-pack

**Comment by recepkabatas** [comment]
Hello I have the same issue i want to use elasticdump with https
i'm using open distro for Elasticsearch it's new plugin for Elasticsearch developed by Amazon 
it's like searchguard. 
`elasticdump --limit=10000  --input=Desktop/file.json   --output=https://localhost:9200   --type=date`
but there is no response on terminal line it's just blank...

 if there is any parametters for authentication info that i can give into elasticdump scirpt .could you please share with us it'd be great !

what i'm looking is i want to sent my elasticsearch json file which i took lately from elasticdump from another elasticsearch server

**Comment by recepkabatas** [comment]
`elasticdump --limit=10000 --input=Desktop/file.json --output=https://localhost:9200 --type=data`
script is this previous script is my mistake 'date' ==> 'data'

**Comment by ferronrsmith** [comment]
The issue is very vague. What type of authentication is it ? (user/saml/ldap).

1. If you need basic http auth, you can use it like this: 
`--input=http://name:password@production.es.com:9200/my_index`
1. TLS X509 client authentication (Check the docs)

**Comment by recepkabatas** [comment]
> The issue is very vague. What type of authentication is it ? (user/saml/ldap).
> 
> 1. If you need basic http auth, you can use it like this:
>    `--input=http://name:password@production.es.com:9200/my_index`
> 2. TLS X509 client authentication (Check the docs)
i fixed the error for me with ;
`NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input=Desktop/file.json   --output=https://name:password@production.es.com:9200 --type=data
`
the key was `NODE_TLS_REJECT_UNAUTHORIZED=0`. i added this code then it works 👍 
thank you ! @ferronrsmith
