### ISSUE TITLE
multielasticdump gives error while using AWS ES input and output

### ISSUE THREAD

**Issue by gmidha** [taskrabbit/elasticsearch-dump#527]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version -- 4.6.0
- Elasticsearch version -- 1.5
- Node.js version *(note that nodejs v8+ is required for this tool)* -- 10.15.3
- Full command you are having issue with (with inputs and outputs) --
./multielasticdump --input=https://search-dvtl-es-events-qastg-vownak2ik3diukjox36kehtt7q.us-east-1.es.amazonaws.com --output=https://search-dvtl-es-events-qastg23-bhocymvtxubvfgyqefcthikxma.us-east-1.es.amazonaws.com

output: 
Thu, 28 Mar 2019 19:04:29 GMT | We are performing : dump
Thu, 28 Mar 2019 19:04:29 GMT | options: {"debug":true,"parallel":8,"match":"^.*$","input":"https://search-dvtl-es-events-qastg-vownak2ik3diukjox36kehtt7q.us-east-1.es.amazonaws.com","output":"https://search-dvtl-es-events-qastg23-bhocymvtxubvfgyqefcthikxma.us-east-1.es.amazonaws.com","scrollTime":"10m","timeout":null,"limit":100,"offset":0,"direction":"dump","support-big-int":false,"ignoreAnalyzer":false,"ignoreData":false,"ignoreMapping":false,"ignoreAlias":true,"ignoreType":[],"interval":1000,"prefix":"","suffix":"","transform":null,"searchBody":null}
/root/node_modules/elasticdump/bin/multielasticdump:93
  if (!fs.existsSync(options.output)) { throw new Error('--output does not exist') }
                                        ^

Error: --output does not exist
    at Object.<anonymous> (/root/node_modules/elasticdump/bin/multielasticdump:93:47)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Same input and output works with elasticdump. It would be great if you can help and provide me with a workaround.

**Comment by ferronrsmith** [comment]
Please read the documentation.

https://github.com/taskrabbit/elasticsearch-dump#multielasticdump


> **If the --direction is dump, which is the default, --input MUST be a URL for the base location of an ElasticSearch server (i.e. http://localhost:9200) and --output MUST be a directory.**

> **For loading files that you have dumped from multi-elasticsearch, --direction should be set to load, --input MUST be a directory of a multielasticsearch dump and --output MUST be a Elasticsearch server URL.**

**Comment by gmidha** [comment]
is it possible to use multielasticdump for copying the indices from one AWS ES to another.

**Comment by ferronrsmith** [comment]
You can dump it to a folder then push it to the destination server.
