### ISSUE TITLE
"Transform" option seems to be ignored

### ISSUE THREAD

**Issue by LeaderOne** [taskrabbit/elasticsearch-dump#530]
- ElasticDump version: *4.6.1*
- Elasticsearch version: *1.5*
- Node.js version: *8.15*
- Full command you are having issue with (with inputs and outputs)
`multielasticdump --input=https://my-es.us-east-1.es.amazonaws.com --output=. --transform='console.log("*********************HELLO WORLD!********************************");'`
- A data set you can share publicly which reproduces the problem: Anything

I'm trying to use elasticdump to copy data in preparation for an upgrade from ES 1.5 to ES6.  ES 1.5 supported multiple `_type` values in the same index.  ES 5 and later do not.  So I thought to use the `--transform` option.  

The `--transform` option in multielasticdump and elasticdump seems to be ignored.  If I run with `--debug`, I can see that my script or module is recognized as the transform, but the transform never runs.

I reverse-engineered the script in `bin/elasticdump` and was able to force the script to run by copying and pasting it into a node project, then hard-coding the transform (on line 
49), but no other method seems to work, either with elasticdump or multielasticdump.  

There has to be something very, very simple that I am doing wrong.  Any idea what it is?

**Comment by ferronrsmith** [comment]
You're using the wrong quotes (That's your first issue)

In any case the transform is only available during **load**, not **dump**
