### ISSUE TITLE
FEATURE REQUEST: Allowing S3-like endpoints

### ISSUE THREAD

**Issue by fnzv** [taskrabbit/elasticsearch-dump#532]
- ElasticDump version: any
- Elasticsearch version: 5.x / 6.x

Is it possible to plan for S3-like endpoints support?
Example:
--s3Endpoint {my custom s3 like server endpoint}

So anyone using emulated endpoints and/or any s3 compatible storage can use your software

**Comment by ferronrsmith** [comment]
There is no plans to add this functionality.
