### ISSUE TITLE
moving mapping to an elasticsearch 7 instance

### ISSUE THREAD

**Issue by albanm** [taskrabbit/elasticsearch-dump#539]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version -> 5.1.0
- Elasticsearch version -> 6.4.2 as input and 7.0.0 as output
- Node.js version *(note that nodejs v8+ is required for this tool)* -> 11
- Full command you are having issue with (with inputs and outputs) -> elasticdump --input=http://localhost:9200/$DUMPINDEX --output=http://$TARGET/$DUMPINDEX --type=mapping
- A data set you can share publicly which reproduces the problem -> no need for data

Hello,

When moving an index's mapping from a cluster to a newer cluster with elasticsearch 7 I have the following error :+1: 

Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}

This is due to a well documented breaking change in ES 7 that can be avoided by using the include_type_name parameter, cf https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-put-mapping.html

**Comment by ferronrsmith** [comment]
1. elasticdump doesn't support Elasticsearch 7 (as yet, there is an open PR)
1. Even when we do support it, you'll still need to convert the mapping using a transform.

Feel free to test the PR if you want.

**Comment by ferronrsmith** [comment]
pushed a new release. Let me know if you have any issues.

**Comment by albanm** [comment]
Ok, I did not think about using transform. I actully pushed the updated index definition by another mean thant elasticdump. But I am currently pushing the data with the _type info removed using elasticdump:

```
elasticdump --input=http://es1/my-index --output=http://es2/my-index --transform="delete doc._type;" --type=data
```

It seems to be working.

Thanks
