### ISSUE TITLE
Cannot get multielasticdump to work with custom certificates

### ISSUE THREAD

**Issue by admlko** [taskrabbit/elasticsearch-dump#540]
- ElasticDump version: latest
- Elasticsearch version: 6.6.x
- Node.js version *(note that nodejs v8+ is required for this tool)*: 8.12

I'm trying to add support for custom certificates to multielasticdump, but I cannot seem to grasp it.
It works fine with elasticdump, but not with multielasticdump (using exactly the same certs).
The error is the usual one, unable to verify the first certificate.
Here's my modified version of multielasticdump:

```
# truncated for brevity multi-elasticdump
```

Would be nice to get this working :)

**Comment by ferronrsmith** [comment]
Next time submit a PR 🙂

**Comment by admlko** [comment]
Right, but it still has an issue that it does not work for one reason or another, and I cannot figure it out by myself.
So is it okay to submit a PR even though it is not working? :)

**Comment by ferronrsmith** [comment]
Yup, easier to review

**Comment by ferronrsmith** [comment]
What flags you need in multi-elasticdump ?

**Comment by admlko** [comment]
Thanks for your comments, I will create a PR next time!

I need to pass client cert, client key and CA cert for reading from SSL secured Elasticsearch. I just added the same flags elasticdump supports while at it.

**Comment by ferronrsmith** [comment]
It's good when u fill out the section that asks what command are you running. Because we do support aliases etc. I don't necessarily want to add the full set of options to multielastic.

**Comment by admlko** [comment]
Sorry, I didn't understand.
What I did was that I added: tlsAuth, cert, key, pass, ca, input-cert, input-key, input-pass, input-ca, output-cert, output-key, output-pass and output-ca.

I understand that not all the options are necessary or needed with multielasticdump, but SSL support is definitely useful :)

**Comment by admlko** [comment]
I added a PR for this with explanation of the issue.

**Comment by asbjornu** [comment]
The associated PR is #542 for anyone else ending up here from Google.
