### ISSUE TITLE
Error with _timestamp when dumping from one instance to another

### ISSUE THREAD

**Issue by justinmchase** [taskrabbit/elasticsearch-dump#541]
I am encountering an error related to a `_timestamp` field which I'm not sure how to resolve. It seems like old data that has been migrated along but is now causing issues when trying to copy it. How can I resolve this?

# Versions
```sh
$ npx elasticdump --version
6.0.0
$ node -v
v8.15.0
```

Version | Env
-- | --
5.6.9 | prod
5.6.14 | local

## Command
```
  npx elasticdump \
    --input=$PROD_ES_URL \
    --output=$LOCAL_ES_URL \
    --type=mapping
```

## Example Data
If I dump to a file as output instead then I get this, essentially:
```
{
	"example": {
		"mappings": {
			"teams": {
				"_timestamp": {
					"enabled": true
				},
				"properties": {
					"exampleId": {
						"type": "string"
					}
				}
			}
		}
	}
}
```

## Error
```
Thu, 02 May 2019 21:16:43 GMT | Error Emitted => {"root_cause":[{"type":"illegal_argument_exception","reason":"[_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents."}],"type":"illegal_argument_exception","reason":"[_timestamp] is removed in 5.0. As a replacement, you can use an ingest pipeline to add a field with the current timestamp to your documents."}
Thu, 02 May 2019 21:16:43 GMT | Total Writes: 0
Thu, 02 May 2019 21:16:43 GMT | dump ended with error (set phase)  => [object Object]
```

**Comment by ferronrsmith** [comment]
ES 5.0 deprecated `_timestamp` & `_ttl`. as written here. https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L22


You can use the transform property to remove the field. 
`--transform="delete doc.example.mappings.teams._timestamp;`

**Comment by justinmchase** [comment]
Thanks @ferronrsmith 

If `teams` is actually variable, how can I handle that?

**Comment by justinmchase** [comment]
Is the syntax just javascript being eval'd?

**Comment by justinmchase** [comment]
For posterity I solved this by dumping to a file, running it through jq and then pushing into the next machine from the cleaned data.

```

npx elasticdump \
  --input=$PROD_ES_URL \
  --output=mapping.json \
  --type=mapping

cat mapping.json | jq -r '."collection-field".mappings[]|=with_entries(select(.key|test("_timestamp")|not))' > cleaned.mapping.json

npx elasticdump \
  --input=cleaned.mapping.json \
  --output=$LOCAL_ES_URL \
  --type=mapping
```

**Comment by ferronrsmith** [comment]
> Is the syntax just javascript being eval'd?

Yes it being eval'd 

https://github.com/taskrabbit/elasticsearch-dump/blob/master/elasticdump.js#L57
