### ISSUE TITLE
Is incremental sync supported or not?

### ISSUE THREAD

**Issue by Roshans007** [taskrabbit/elasticsearch-dump#543]
Just wanted to check if `elasticsearch-dump` supports incremental sync or not?

Because my use-case is I have a production ES cluster running which has around 1 TB of data. 
I want to replicate this cluster.

The first time it will take a lot of time to sync but later on, if I try to sync will that sync be incremental or will it take the same amount of time it took for the first sync?

**Comment by ferronrsmith** [comment]
Your question ? no
does ES supports incremental syncs ? no.

Fairly simple to achieve this by adding a timestamp to your data-set on upsert, but if you don't have it then, no
