### ISSUE TITLE
elasticsearch  bulk outofmemory

### ISSUE THREAD

**Issue by mingminghao** [taskrabbit/elasticsearch-dump#545]
- ElasticDump version 5.0.0
- Elasticsearch 6.4.0
- Node.js v8

![image](https://user-images.githubusercontent.com/39397546/57755688-1668b680-7724-11e9-9de5-6097758fce50.png)

**Comment by ferronrsmith** [comment]
The error isn't from elasticdump, it's from Elasticsearch. You need to increase the memory allocated to the heap.

https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
