### ISSUE TITLE
Unable to import template

### ISSUE THREAD

**Issue by badeball** [taskrabbit/elasticsearch-dump#546]
- ElasticDump version: 6.0.0
- Elasticsearch version: 6.3.2
- Node.js version: 11.13.0

Trying to import a template (content doesn't matter) as shown below.

```
$ elasticdump --input=template.json --output=http://localhost:9200 --type=template
Wed, 15 May 2019 13:19:26 GMT | starting dump
Wed, 15 May 2019 13:19:26 GMT | got 1 objects from source file (offset: 0)
Wed, 15 May 2019 13:19:26 GMT | Error Emitted => failed to parse json (message: "Unexpected token o in JSON at position 1") - source: {}
Wed, 15 May 2019 13:19:26 GMT | Total Writes: 0
Wed, 15 May 2019 13:19:26 GMT | dump ended with error (set phase)  => Error: failed to parse json (message: "Unexpected token o in JSON at position 1") - source: {}
```

It seems like the content is attempted to be parsed twice, because [parse](https://github.com/taskrabbit/elasticsearch-dump/blob/v6.0.0/lib/jsonparser.js#L23-L32) is invoked with the actual object.

Is this supposed to work?

**Comment by ferronrsmith** [comment]
That's a conditional statement. There isn't enough information in the issue to help you and I don't know what you are importing, if it's even valid.

Examples of templates can be found here : https://github.com/taskrabbit/elasticsearch-dump/tree/master/test/test-resources

**Comment by badeball** [comment]
I'm sorry for the ambiguity. The error presents itself even if I import a template contaning only `{}`.

**Comment by ferronrsmith** [comment]
The template needs to be a string `"{}"`.
