### ISSUE TITLE
Error getaddrinfo EAI_AGAIN running docker and using --net=host

### ISSUE THREAD

**Issue by FeTaka** [taskrabbit/elasticsearch-dump#547]
- ElasticDump version: 6.0.1
- Elasticsearch version: 7.0.0
- Node.js version: 8.10
- Command: 
`docker run -v $HOME/data:/data/ --net=host --rm -ti taskrabbit/elasticsearch-dump \
--input="https://$USER:$PWD@$path.aws.found.io:xxxx" \
--input-index=index \
--searchBody='{"query": { "bool": { "must": [{ "term" : { "field" : x } },{ "range": { "date": {"gte": "now-1d"}}}]}}}' \
--limit 100 --output ./data/mydata.json`

And the output is:
`Fri, 31 May 2019 01:48:22 GMT | starting dump
Fri, 31 May 2019 01:48:43 GMT | Error Emitted => getaddrinfo EAI_AGAIN xxxxx xxxxx:443
Fri, 31 May 2019 01:48:43 GMT | Total Writes: 0
Fri, 31 May 2019 01:48:43 GMT | dump ended with error (get phase) => Error: getaddrinfo EAI_AGAIN xxxxx xxxxx:443`

Also, when I don't use the container and run the elasticdump locally to the same inputs, it throws a similar error, but instead of "EAI_AGAIN", it says "ENOTFOUND"

**Comment by ferronrsmith** [comment]
If it failed both places, then I'm not sure what to say. EAI_AGAIN/ENOTFOUND. Can you try curling the URL before and see what the results are ?

- EAI_AGAIN is a DNS lookup timed out error
- ENOTFOUND site not found.

**Comment by FeTaka** [comment]
I am so sorry, I decided to change the password to one without special characters... and indeed it was the password that was messing up with the command. I will close this issue.
Again, sorry for the trouble.

**Comment by ferronrsmith** [comment]
It was no trouble at all. Thanks for using elasticdump 🙂

**Comment by ashaik65** [comment]
@FeTaka  how you solve this issue because i am also facing same issue  
Tue, 23 Aug 2022 09:31:56 GMT | starting dump
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Error Emitted => getaddrinfo ENOTFOUND http
Tue, 23 Aug 2022 09:32:16 GMT | Total Writes: 0
Tue, 23 Aug 2022 09:32:16 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND http
