### ISSUE TITLE
version compatibility of elastic dump

### ISSUE THREAD

**Issue by sritoleti** [taskrabbit/elasticsearch-dump#548]
Hello Team,

Can I please know if elastic dump's backup/restore is version compatible w.r.t elastic search ?

Example: Does bumping up and downgrading the Elastic search has any impact on the data while using elastic dump ?

Please advise.

**Comment by ferronrsmith** [comment]
Raw data no.

But mappings/templates/settings might be different. but this is mainly an ES issue which can be rectified easily.

**Comment by sritoleti** [comment]
Sure, I am looking for backup/restore of data for now.
Thank you very much for your quick response.
