### ISSUE TITLE
Coredump related to --support-big-int

### ISSUE THREAD

**Issue by jclosure** [taskrabbit/elasticsearch-dump#556]
When running with _--support-big-int_, sometimes getting a core dump related to GC compaction.  Here's the operative fn call:

`v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double)`

If I turn off _--support-big-int_, no issues with the same dataset.

- Full stacktrace
```
Thu, 20 Jun 2019 01:30:55 GMT | sent 10000 objects to destination elasticsearch, wrote 10000
Thu, 20 Jun 2019 01:31:09 GMT | got 10000 objects from source elasticsearch (offset: 50000)
Thu, 20 Jun 2019 01:31:13 GMT | sent 10000 objects to destination elasticsearch, wrote 10000

<--- Last few GCs --->
io[110236:0x34a3950]   120935 ms: Mark-sweep 1395.5 (1430.2) -> 1394.5 (1431.7) MB, 561.8 / 0.0 ms  (+ 0.0 ms in 59 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 570 ms) (average mu = 0.116, current mu = 0.014) allocatio[110236:0x34a3950]   121974 ms: Mark-sweep 1397.5 (1431.7) -> 1396.4 (1433.2) MB, 1032.1 / 0.0 ms  (+ 0.0 ms in 48 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1038 ms) (average mu = 0.049, current mu = 0.006) allocat

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10fdb31dbe1d]
    1: StubFrame [pc: 0x10fdb31dd1df]
Security context: 0x375c1d19e6e1 <JSObject>
    2: N(aka N) [0x61bec51c5c9] [/usr/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:~1] [pc=0x10fdb3260cf3](this=0x2e2502e826f1 <undefined>)
    3: O(aka O) [0x61bec51c709] [/usr/lib/node_modules/elasticdump/node_modules/lossless-json/dist/lossless-json.js:~1] [pc=0x10fdb323f4c8](this=0x2e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dbaa0 node::Abort() [node]
 2: 0x8dbaec  [node]
 3: 0xad83de v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad8614 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec5c42  [node]
 6: 0xec5d48 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xed1e22 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xed2754 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xed53c1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xe9e844 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x113dfae v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0x10fdb31dbe1d
(core dumped) elasticdump
```

- ElasticDump version
6.1.0

- Elasticsearch version
input ES ver: 5.1.1
output ES ver:  7.1.1

- Node.js version *(note that nodejs v8+ is required for this tool)*
v10.14.0

- Full command you are having issue with (with inputs and outputs)
```
elasticdump --params="$PARAMS" --input="$SOURCE_URI/$INDEX" --output="$DEST_URI/$INDEX" --type=data --ignore-errors --noRefresh --support-big-int=true --limit=10000
```

I'm working on trying to prepare a publishable dataset that triggers this.  It's pretty sensitive data, so it may take a little time.  Hopefully, the error is obvious to more knowledgeable eyes.

**Comment by ferronrsmith** [comment]
This is really a node issue. The limit is too high and the big-int library is doing too much.

Try bumping the `max-old-space-size`

NODE_OPTIONS="--max-old-space-size=4096"

FYI: There is no version `6.4.1`

**Comment by jclosure** [comment]
Sry, I meant elasticdump 6.1.0.  Corrected above.

Yeah exporting NODE_OPTIONS="--max-old-space-size=4096" was the first thing I tried.  

Doesn't resolve the issue.

**Comment by jclosure** [comment]
Also what about --maxSockets impact?  Recommendation?

**Comment by ferronrsmith** [comment]
That's totally dependent on you. You can set it to `Infinity`, but I wouldn't recommend anything over `100`. All these though need to be benchmarked, since it depends on how much request Elasticsearch can actually handle.

Adjusting `limit` relative `max-old-space-size` is hard, since it also dependent on the amount of properties you have. Through as much memory as you can at it, if that doesn't fix the issue then decrease the limit in increments of `1000`.

**Comment by jclosure** [comment]
Reducing the --limit and bumping up max-old-space-size works.  Stabilizes copying the same dataset with --support-big-int.  Wonder if it's possible to put a guard at the framework-level to prevent this behavior.  Would probably be ugly and not fully comprehensive.  In any case, it's clearly possible to overflow the heap when pushing elasticdump too hard.

Thanks for the help. 🙏

**Comment by jclosure** [comment]
Been documented with lossless-json. 

https://github.com/angular/angular-cli/issues/12645
