### ISSUE TITLE
elasticdump fails with scrollId not found

### ISSUE THREAD

**Issue by soniagupta9** [taskrabbit/elasticsearch-dump#559]
- ElasticDump version: 6.1.0
- Elasticsearch version: 6.2.4
- Index size : 50GB
- Command ran : elasticdump --input=http://localhost:8080/api/v1/namespaces/td-platform/services/https:elasticsearch-logging:9200/proxy/mlengine-6.2.4-2019.06.21 --output=test.json --type=data --limit 10000 --debug` 
- Output: 
Mon, 24 Jun 2019 03:30:32 GMT | starting dump
Mon, 24 Jun 2019 03:30:32 GMT [debug] | cannot discover elasticsearch input major version, assuming: 5
Mon, 24 Jun 2019 03:30:36 GMT | got 10000 objects from source elasticsearch (offset: 0)
Mon, 24 Jun 2019 03:30:36 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 24 Jun 2019 03:30:36 GMT [debug] | scrollRequest: {"uri":"http://localhost:8080/api/v1/namespaces/td-platform/services/https:elasticsearch-logging:9200/_search/scroll","method":"POST","body":"{\"scroll\":\"10m\",\"scroll_id\":\"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAPxlFmZSLXc2a3pBUkg2bnl0eEV3Wk5iSWcAAAAAAAC9fhZJRFFManBtSFI0eUo2V3AyV1QtZktRAAAAAAAA3ggWU0tXR3lHSi1STUtjREtMb3dlTXVFQQAAAAAAAPxmFmZSLXc2a3pBUkg2bnl0eEV3Wk5iSWcAAAAAAAD8ZBZmUi13Nmt6QVJINm55dHhFd1pOYkln\"}"}
Mon, 24 Jun 2019 03:30:36 GMT [debug] | body: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"the server could not find the requested resource\",\"reason\":\"NotFound\",\"details\":{},\"code\":404}\n"
Mon, 24 Jun 2019 03:30:36 GMT | Error Emitted => {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

Mon, 24 Jun 2019 03:30:36 GMT | Total Writes: 10000
Mon, 24 Jun 2019 03:30:36 GMT | dump ended with error (get phase) => Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

**Comment by ferronrsmith** [comment]
This all depends on how long elasticdump is taking to process those 10,000 records. The `scrollTime` might be insufficient. Try bumping this value. 

Also if you're dumping a 50GB index I highly recommend using the `fileSize` parameter to segment the data into smaller chunks.

**Comment by soniagupta9** [comment]
I tried with following combinations: 
`elasticdump --input=http://localhost:8080/api/v1/namespaces/td-platform/services/https:elasticsearch-logging:9200/proxy/mlengine-6.2.4-2019.06.21 --output=test2.json --type=data --debug --scrollTime=100m --fileSize=1mb`
`elasticdump --input=http://localhost:8080/api/v1/namespaces/td-platform/services/https:elasticsearch-logging:9200/proxy/mlengine-6.2.4-2019.06.21 --output=test2.json --type=data --limit 10000 --debug --scrollTime=30m --fileSize=30mb`
`elasticdump --input=http://localhost:8080/api/v1/namespaces/td-platform/services/https:elasticsearch-logging:9200/proxy/mlengine-6.2.4-2019.06.21 --output=test2.json --type=data --debug --scrollTime=30m --fileSize=30mb`

**Comment by ferronrsmith** [comment]
I used the same version of elastic that you're using and I was able to dump the data.

My guess is, your proxy is doing something weird. Try using curl to access the individual endpoints.

````
 [debug] | cannot discover elasticsearch input major version, assuming: 5
```

The above warning shouldn't exists if elasticdump was able to query the version endpoint. Usually it should return this :

```json
{
  "name" : "WfNEzH5",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "JsVtr_2KQNaKxeE9xK8PRQ",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by soniagupta9** [comment]
curl works fine ( with proxy urls) Not sure why elasticdump doesnt work

**Comment by ferronrsmith** [comment]
I don't know what the proxy is doing, so I don't know. Could be multiple redirects or something. Not enough info to know exactly what the issue is
