### ISSUE TITLE
Restoring data skips last few records from the input JSON

### ISSUE THREAD

**Issue by silverrajat88** [taskrabbit/elasticsearch-dump#562]
I had a total of 3911 records in my input JSON, while restoring only the first 3898 records got indexed leaving/skipping out the last 13 records.

It was only when I added a **--limit=200** option, that I managed to restore all the documents.
Ideally, it should be work fine without manipulating the limit option.

**Some Details**

- ElasticDump version = **6.2.2**
- Elasticsearch version = **7.2.0**
- Node.js version *(note that nodejs v8+ is required for this tool)* **12.4**
- Full command you are having issue with (with inputs and outputs)

`elasticdump --input=${ES_DATA_PATH}/venue-1_index.json --output=http://${ES_HOST}/venue-1 --type=data
`

**Comment by ferronrsmith** [comment]
Without the data, it's hard to replicate the issue. If it something you can share either here or via email please feel to send it. There are several reasons this might happen, but I rather not speculate. Easier to test with the data present.

**Comment by ferronrsmith** [comment]
I haven't gotten a response from you. Closing this issue.
Please comment if you have more information/data to test.
