### ISSUE TITLE
using [from] is not allowed in a scroll context

### ISSUE THREAD

**Issue by altomni** [taskrabbit/elasticsearch-dump#563]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: newest docker image
- Elasticsearch version: 6.7

sudo docker run --rm --network host -ti taskrabbit/elasticsearch-dump --input=http://XXXX:9200/XXXX --output=http://YYY:9201/YYY --type=data --size=2000000 --offset 1000000

With this error:
| dump ended with error (get phase) => Error: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}

**Comment by ferronrsmith** [comment]
`from` has been removed from ES since v5, but it was silently ignored. In v6 it fails if the offset it present. https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html#_scroll.

One way to alleviate this is to ensure your data fields that allow segmentation (UAT/IAT). I'll add a note to the README so that people can be aware of this.

**Comment by Pam996** [comment]
Hi  is there any methods or workaround for dumping part of data on ES version6 and higher ?

**Comment by ferronrsmith** [comment]
You can pass the scrollId if you want to continue from where a job failed. But if you want to offset then the best option is to use the searchbody with a query to return a subset that can be dumped. Ideally data should have some kind of sequence that allows filtering, if not then you're out of luck.

**Comment by Pam996** [comment]
Thanks so much, I will try it later.

**Comment by eherot** [comment]
@ferronrsmith Could you say a little more about how `scrollId` is used in this context? Can I just take the `(offset: NNN)` value in the output and pass it to `--scrollId`?

**Comment by ferronrsmith** [comment]
@eherot You can't offset in scroll anymore. The scrollId can be used to start from the point you last were in case the system should crash etc

**Comment by jetervaz** [comment]
How is it possible to restart a job that had a connection failure, when the last output from `elasticdump` is this?
```Thu, 30 Mar 2023 00:51:31 GMT | got 100 objects from source elasticsearch (offset: 12000)
Thu, 30 Mar 2023 00:51:31 GMT | sent 100 objects to destination file, wrote 100```

It only has an `offset` value, no `scrollId` - how should we continue a job? Shouldn't `elasticdump` maybe share the `scrollId`?

**Comment by ferronrsmith** [comment]
You can pass the scrollId, given that the scrollTime has not elapsed. Check the docs
