### ISSUE TITLE
how to create a field in transform script

### ISSUE THREAD

**Issue by firatoltulu** [taskrabbit/elasticsearch-dump#564]
Hi,

I want to exporting data  on es (1.7.1 )  i using with parameter

elasticdump --input=http://localhost:9200/ --input-index=yap/instance --output=instance.json --type=data --size=1000 --transform='ts'

i want to create a field to type then i write a script the following 

module.exports = function (doc, options) {
    // do something to doc
    doc["type"] = "instance";
};

but isn't working,  i need some information how it is work?

**Comment by ferronrsmith** [comment]
There's a section on [Module Transform](https://github.com/taskrabbit/elasticsearch-dump#module-transform) in the README
