### ISSUE TITLE
docker: Error response from daemon: failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by leiguorui** [taskrabbit/elasticsearch-dump#567]
ElasticDump version: latest

Elasticsearch version: 6.7.2

Command:
docker run --rm -ti taskrabbit/elasticsearch-dump   --input=<ELASTICSEARCH_URL>   --output=<ELASTICSEARCH_URL>   --type=mapping

Error:
docker: Error response from daemon: failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown.

**Comment by ferronrsmith** [comment]
This is a docker daemon issue.

Check that the daemon is started: `docker info`
Check that you can retrieve the version: `docker version`

Google the issue, a lot of results is returned concerning the above results.

**Comment by miland1990** [comment]
service docker restart
my bot became alive)
