### ISSUE TITLE
Using properties as field name cause error

### ISSUE THREAD

**Issue by gokhansengun** [taskrabbit/elasticsearch-dump#570]
- ElasticDump version: 6.2.2
- Elasticsearch version: 7.2.0
- Node.js version v10.16.0

When `properties` is used as a field name in the index, elasticsearch-dump fails to dump/restore the index mapping. It produces below error.

```
Tue, 23 Jul 2019 21:51:51 GMT | starting dump
Tue, 23 Jul 2019 21:51:51 GMT | got 1 objects from source elasticsearch (offset: 0)
Tue, 23 Jul 2019 21:51:51 GMT | got 0 objects from source elasticsearch (offset: 1)
Tue, 23 Jul 2019 21:51:52 GMT | Error Emitted => {"root_cause":[{"type":"mapper_parsing_exception","reason":"No type specified for field [properties]"}],"type":"mapper_parsing_exception","reason":"No type specified for field [properties]"}
```

Reproduction

1. Download problematic mapping

    ```
    curl -o /tmp/example_mapping https://gist.githubusercontent.com/gokhansengun/d61e2c22e4110687086ad5fb3dded09a/raw/277f83443883e7b1464e5c287c71f81ffac818f5/example_mapping
    ```

1. Create the mapping

    ```
    curl -XPUT http://ES_HOST/test_index?pretty -H "content-type: application/json" -d @/tmp/example_mapping
    ```

1. Try to clone mapping from source ES to the target ES. I used Docker but same result with non-containerized artifact.

    ```
    ES_TEST_INDEX=test_index
    docker run --rm -ti taskrabbit/elasticsearch-dump:v6.2.2 \
      --input=http://${SOURCE_ES_HOST}:${SOURCE_ES_PORT}/${ES_TEST_INDEX} \
      --output=http://${TARGET_ES_HOST}:${TARGET_ES_PORT}/${ES_TEST_INDEX} \
      --type=mapping
    ```

**Comment by ferronrsmith** [comment]
> ES 7.x.x & higher no longer supports type property. all templates prior to ES 6.0 has to be upgraded to remove the type property.

There is no support for moving mapping/templates between ES versions. Export modify and re-import

**Comment by ferronrsmith** [comment]
Also, the data in the gist is invalid.

**Comment by gokhansengun** [comment]
Ok, thanks for the quick response. Problem is also seen in ES 6.x.x. It goes away when the field named properties is removed or renamed to props. How do you explain this part?

I am not aware of ES’s poor support on types in ES 7.x.x. I just know they drop support for having multiple types in the index.

**Comment by ferronrsmith** [comment]
* ES dropped support for types. I haven't experienced the issue so I can relate. Provide replication steps. Source ES => Target ES etc. ES 6.8.x dropped type support anyway

**Comment by ferronrsmith** [comment]
Seems like an ES restriction on field names. There seems to be side-effect or bug when mapping is supplied to ES on index creation.

If I create the index, then submit the mapping it fails.

```json
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [mappings : {properties={productId={type=long}, name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, properties={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, propertyValue={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Root mapping definition has unsupported parameters:  [mappings : {properties={productId={type=long}, name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, properties={properties={name={type=text, fields={keyword={ignore_above=256, type=keyword}}}, propertyValue={type=text, fields={keyword={ignore_above=256, type=keyword}}}, id={type=long}}}}}]"
  },
  "status": 400
}

```
