### ISSUE TITLE
searchBody 没作用？

### ISSUE THREAD

**Issue by gaofeng0** [taskrabbit/elasticsearch-dump#571]
windows 10执行
elasticdump --input=http://192.168.2.116:9200/serverdata/Biz \ --output=E:\\elasticdump\\query.json \--searchBody '{\"query\":{\"term\":{\"fileId\": \"34QF24341IX2S7VR\"}}}'

**Comment by ferronrsmith** [comment]
You should ensure the `searchBody` is properly escaped

elasticdump --input=http://192.168.2.116:9200/serverdata/Biz \ --output=E:\elasticdump\query.json --searchBody="{\"query\":{\"term\":{\"fileId\": \"34QF24341IX2S7VR\"}}}"
