### ISSUE TITLE
Dump Documentations with Multitenancy 

### ISSUE THREAD

**Issue by wenjun666** [taskrabbit/elasticsearch-dump#572]
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.3.3
- Elasticsearch version 6.1.2
- Node.js version *(note that nodejs v8+ is required for this tool)*
- Full command you are having issue with (with inputs and outputs)
- A data set you can share publicly which reproduces the problem

I have multiple tenants using search Guard. I want to export all documentations from one tenant and import to another. Currently, the export part works fine withe following command:

NODE_TLS_REJECT_UNAUTHORIZED=0 ./elasticdump --input=https://username:password@url:port/.kibana/doc --output= test_elasticdump.json --headers {“sgtenant”: “source_tenant”}

But I have issue when trying to import with the following command:

NODE_TLS_REJECT_UNAUTHORIZED=0 ./elasticdump --output=https://username:password@url:port/.kibana/doc --input=test_elasticdump.json --headers '{"sgtenant": "dest_tenant"}'

Mon, 29 Jul 2019 19:03:27 GMT | starting dump
Mon, 29 Jul 2019 19:03:27 GMT | got 1 objects from source file (offset: 0)
Mon, 29 Jul 2019 19:03:27 GMT | got 0 objects from source file (offset: 1)
{ _index: '.kibana',
  _type: 'doc',
  _id: 'index-pattern:xxxxxxxx-68fb-11e8-a5b1-fdc5a150c826',
  status: 404,
  error:
   { type: 'shard_not_found_exception',
     reason:
      'expected aID [xxxxxx79T7eeSCNg3JrICA] with term [1] but found [7]',
     index_uuid: 'xxxxxxUNT1SBDBJj-nJ5JQ',
     shard: '0',
     index: '.kibana' } }

I make sure the cluster and all the shards are in healthy state.
Thank you.

**Comment by ferronrsmith** [comment]
Need sample data to replicate the issue

**Comment by wenjun666** [comment]
Sorry for the late response, here is one entry I try to import:

{"_index":".kibana_1102994236_devtoolsdev","_type":"doc","_id":"search:0d723040-311d-11e8-ab4b-bf57c73693c4","_score":1,"_source":{"type":"search","updated_at":"2018-06-05T20:10:00.010Z","search":{"title":"Dome Prod Jira Unique Users","description":"","hits":0,"columns":["user"],"sort":["@timestamp","desc"],"version":1,"kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"fad02310-68f9-11e8-a5b1-fdc5a150c826\",\"highlightAll\":true,\"version\":true,\"query\":{\"language\":\"lucene\",\"query\":\"\"},\"filter\":[{\"$state\":{\"store\":\"appState\"},\"meta\":{\"alias\":null,\"disabled\":false,\"index\":\"7f508220-30fa-11e8-ab4b-bf57c73693c4\",\"key\":\"app\",\"negate\":false,\"params\":{\"query\":\"jira\",\"type\":\"phrase\"},\"type\":\"phrase\",\"value\":\"jira\"},\"query\":{\"match\":{\"app\":{\"query\":\"jira\",\"type\":\"phrase\"}}}},{\"$state\":{\"store\":\"appState\"},\"meta\":{\"alias\":null,\"disabled\":false,\"index\":\"7f508220-30fa-11e8-ab4b-bf57c73693c4\",\"key\":\"environment\",\"negate\":false,\"params\":{\"query\":\"dome\",\"type\":\"phrase\"},\"type\":\"phrase\",\"value\":\"dome\"},\"query\":{\"match\":{\"environment\":{\"query\":\"dome\",\"type\":\"phrase\"}}}},{\"$state\":{\"store\":\"appState\"},\"meta\":{\"alias\":null,\"disabled\":false,\"index\":\"7f508220-30fa-11e8-ab4b-bf57c73693c4\",\"key\":\"instance\",\"negate\":false,\"params\":{\"query\":\"production\",\"type\":\"phrase\"},\"type\":\"phrase\",\"value\":\"production\"},\"query\":{\"match\":{\"instance\":{\"query\":\"production\",\"type\":\"phrase\"}}}},{\"$state\":{\"store\":\"appState\"},\"meta\":{\"alias\":null,\"disabled\":false,\"index\":\"7f508220-30fa-11e8-ab4b-bf57c73693c4\",\"key\":\"document_type\",\"negate\":false,\"params\":{\"query\":\"jira-access\",\"type\":\"phrase\"},\"type\":\"phrase\",\"value\":\"jira-access\"},\"query\":{\"match\":{\"document_type\":{\"query\":\"jira-access\",\"type\":\"phrase\"}}}},{\"meta\":{\"index\":\"4cb57dc0-30fa-11e8-ab4b-bf57c73693c4\",\"negate\":false,\"disabled\":false,\"alias\":null,\"type\":\"exists\",\"key\":\"user\",\"value\":\"exists\"},\"exists\":{\"field\":\"user\"},\"$state\":{\"store\":\"appState\"}},{\"meta\":{\"index\":\"4cb57dc0-30fa-11e8-ab4b-bf57c73693c4\",\"negate\":true,\"disabled\":false,\"alias\":null,\"type\":\"phrase\",\"key\":\"user\",\"value\":\"-\",\"params\":{\"query\":\"-\",\"type\":\"phrase\"}},\"query\":{\"match\":{\"user\":{\"query\":\"-\",\"type\":\"phrase\"}}},\"$state\":{\"store\":\"appState\"}}]}"}}}}

**Comment by ferronrsmith** [comment]
Wasn't able to replicate the issue. Worked for me ... This usually means the issue is ES related and not the library
