### ISSUE TITLE
[BUG]  Large index: es_rejected_execution_exception

### ISSUE THREAD

**Issue by ex0ns** [taskrabbit/elasticsearch-dump#574]
**Context**

- ElasticDump version:  6.3.3
- Elasticsearch version: 5.6.10
- Node.js version *(note that nodejs v8+ is required for this tool)*: v10.16.1
- Full command you are having issue with (with inputs and outputs):

```bash
 elasticdump --quiet --limit 10 --noRefresh --retryAttempts 10--retryDelay 10000 --input=backup/data.json-1 --output=http://localhost:9200/restored_2 --type=data
````
Output:

```
{ _index: 'restored_2',
  _type: 'message',
  _id: '8173f2c0-3703-11e9-b05a-005056b5ef2d',
  status: 429,
  error:
   { type: 'es_rejected_execution_exception',
     reason:
      'rejected execution of org.elasticsearch.transport.TransportService$7@37bbee0c on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@222f0016[Running, pool size = 8, active threads = 8, queued tasks = 200, completed tasks = 195686]]' } }
```
- A data-set you can share publicly which reproduces the problem: unfortunately, this only happens on large dataset ( > 20go).

**Describe the bug**

When restoring a large index with elasticdump, I reach the limitation of the transport, and I'm rejected by ES with a es_rejected_execution_exception, I try to tune the parameters given to Elasticdump (retry, limit and so on), but was not able to overcome this issue, do you have any idea of what I could try (without updating the server's config) to import large indices (even if it requires more time).

**Additional context**

The machine is running Ubuntu 16.04LTS and it elasticdump works well when restoring smaller indices. Currently I splitted the file by chunck of 15go (my indices are 200Go or more) and I don't think that splitting the file in even smaller pieces would solve this issue

**Comment by ferronrsmith** [comment]
Seems a typical fast producer, slow producer problem. Can you try version 6.0.2 or lower. I'll work on adding throttling support to the producer.

**Comment by ex0ns** [comment]
I tried with the version 6.0.2 of ElasticDump and it seems to be working like a charm :smile: 
Can I ask what changes made in version above 6.0.2 caused this issue ?

Thank you !

**Comment by ferronrsmith** [comment]
We added a performance improvement that sends more concurrent request to ES, but that seems to be causing issues with slow consumers.

I've added `--concurrency` flag that can limit the amount of concurrent requests sent to a transport. That's in v `6.4.0` (released)

**Comment by ex0ns** [comment]
Hello, sorry to re-open the issue, but I wanted to let you know that I tested this morning with the `--concurrency` option set to 1 and it fails with the same message  (`es_rejected_execution_exception`):

```
elasticdump --quiet --limit 10 --concurrency 1 --noRefresh --retryAttempts 10--retryDelay 10000 --input=backup/data.json-1 --output=http://localhost:9200/restored_2 --type=data
```

I re-tried with 6.0.2 and it worked (slowly).

**Comment by ferronrsmith** [comment]
Yea right, it still a bit too fast. It needs a back-off window

**Comment by ferronrsmith** [comment]
I've added support for fine-grain throttling. Let me know if it works for you.

These are the new options. (more information can be found in the README)

  carryoverConcurrencyCount: false,
  intervalCap: Infinity,
  concurrencyInterval: 0

**Comment by ferronrsmith** [comment]
Ok pushed a new release

**Comment by ex0ns** [comment]
Hello,

I finally had the time to perform some test, and I think we still have to issues (related to #580 with the data lost). I backed up a index containing 183,156 documents 

I tried to restore it with different settings and each of them gave me the above error message, here is the result of my tests:

```
Original: 183,156 messages                                                                
--concurrency 1 --intervalCap 50 : 138,441 messages                                
--concurrency 1 --intervalCap 20 : 170,652 messages                                
--concurrency 1 --intervalCap 20 --concurrencyInterval 5000 : 173,797 messages
--concurrency 1 --intervalCap 1 --concurrencyInterval 5000 : 179,027 messages  
```

Is there something I did not understand with those concurrency settings ? 
I found really strange that the last one, with both `concurrency` and `intervalCap` set to 1 still produces an `es_rejected_execution_exception` on the elastic side...

For reference, I also restored the index using version `6.0.2` and got the expected result: of 183,156 messages.

I unfortunately can't share the file with you, but I'm willing to perform some test if you need more information regarding this issue.

**Comment by ex0ns** [comment]
All those options make a lot more sense now, thanks for the clarification.
Adding a `throttleInterval` helped a lot with this issue:
` --concurrency 1 --intercalCap 500 --concurrencyInterval 5000 --throttleInterval 1` I didn't get any `es_rejected_execution_exception` error whereas without the `--throttleInterval` set, I got one.

Thanks again !
