### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jeroen-80** [taskrabbit/elasticsearch-dump#578]
Running node v10.16.2 (lts). Large uploads fail after some time:
```
<--- Last few GCs --->
n [11519:0x43b0230]  3487974 ms: Mark-sweep 1399.3 (1416.6) -> 1399.3 (1417.1) MB, 854.7 / 0.0 ms  (+ 20.3 ms in 3 steps since start of marking, biggest step 19.8 ms, walltime since start of marking 884 ms) (average mu = 0.133, current mu = 0.028) allocatio[11519:0x43b0230]  3488810 ms: Mark-sweep 1399.6 (1417.1) -> 1399.6 (1417.6) MB, 808.2 / 0.0 ms  (+ 21.2 ms in 2 steps since start of marking, biggest step 20.9 ms, walltime since start of marking 836 ms) (average mu = 0.083, current mu = 0.030) allocatio

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x36aabce1e6e9 <JSObject>
    0: builtin exit frame: parse(this=0x36aabce11a21 <Object map = 0x1e8656e842a9>,0x29eae1f02201 <Very long string[99592176]>,0x36aabce11a21 <Object map = 0x1e8656e842a9>)

    1: parse [0x394077622011] [/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:~23] [pc=0x3122061160ab](this=0x39407761e771 <Object map = 0x166985b6d601>,str=0x29eae1f02201 <Very long string[99592176]>,configs=0x39...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa060 node::Abort() [node]
 2: 0x8fa0ac  [node]
 3: 0xaff7ee v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xaffa24 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef3f32  [node]
 6: 0xef4038 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00112 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf00a44 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf036b1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xed888c  [node]
11: 0xed8a27 v8::internal::Factory::NewJSObject(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::PretenureFlag) [node]
12: 0xfc3c06 v8::internal::JsonParser<true>::ParseJsonObject() [node]
13: 0xfc4a60 v8::internal::JsonParser<true>::ParseJsonValue() [node]
14: 0xfc3fac v8::internal::JsonParser<true>::ParseJsonObject() [node]
15: 0xfc4a60 v8::internal::JsonParser<true>::ParseJsonValue() [node]
16: 0xfc3fac v8::internal::JsonParser<true>::ParseJsonObject() [node]
17: 0xfc4a60 v8::internal::JsonParser<true>::ParseJsonValue() [node]
18: 0xfc4ef5 v8::internal::JsonParser<true>::ParseJsonArray() [node]
19: 0xfc4a70 v8::internal::JsonParser<true>::ParseJsonValue() [node]
20: 0xfc41f3 v8::internal::JsonParser<true>::ParseJsonObject() [node]
21: 0xfc4a60 v8::internal::JsonParser<true>::ParseJsonValue() [node]
22: 0xfc4ad4 v8::internal::JsonParser<true>::ParseJson() [node]
23: 0xbd40f8 v8::internal::Builtin_JsonParse(int, v8::internal::Object**, v8::internal::Isolate*) [node]
24: 0x31220575bf7d
```
Running latest elasticdump. Never seen this before, while always using latest node lts, elasticdump and elasticsearch (now: 7.3.0).

More than enough RAM available. No errors in error log elastic.

**Comment by ferronrsmith** [comment]
Please read the docs

In v 6.1.0 a concurrent processing logic was introduced that process more data in parallel, hence the more memory requirement. 

You can throttle the consumer with the new `--concurrency/concurrencyInterval` flags or you can use v6.0.2 or lower to get the old behaviour. 

You can also use the `max-old-space-size` node flag to provide a higher memory head room

**Comment by jeroen-80** [comment]
Switching back to an older version is not an option.

What settings would you recommend for ```--concurrency/concurrencyInterval``` to disable concurrency? Same error with ```--concurrency=0```.

How to apply ```max-old-space-size```? If I change the first line of elasticdump to e.g. ```#!/usr/bin/env node --max-old-space-size=4096```, elasticdump is unworkable slow.

**Comment by ferronrsmith** [comment]
NODE_OPTIONS="--max-old-space-size=8192" elasticdump  --concurrency can't be set to 0, lowest value is 1.

```
NODE_OPTIONS="--max-old-space-size=8192" elasticdump --concurrency=5 --carryoverConcurrencyCount=true --concurrencyInterval 10000 - intervalCap 5
```

concurrency - the amount of items that can be queued at once
carryoverConcurrencyCount - whether the count should carry over into another interval
concurrencyInterval - the specific interval in which to process the items
intervalCap - how many items to process in a given interval


All the options are there for you to scale to your hearts content, provided that both Elasticsearch and elasticdump is properly configured.

**Comment by atykhonov** [comment]
For sorry `NODE_OPTIONS="--max-old-space-size=8096" elasticdump --concurrency=1 --carryoverConcurrencyCount=true^C-concurrencyInterval=10000 --intervalCap=5` doesn't work for me. Yes, indeed `NODE_OPTIONS="--max-old-space-size=8096` makes the difference, i.e. the command fails later, but anyway it fails. After 28800 offset the command fails with "JavaScript heap out of memory" error. Is there any way to work around it? Please help.

**Comment by ferronrsmith** [comment]
Use `--fileSize` to segment the data.

**Comment by zhang8473** [comment]
Your v 6.1.0 new concurrent processing logic always results in this FATAL error, no matter how I set size, concurrencyInterval, intervalCap, and throttleInterval. The GC seems not working. The space-size just delay the FATAL error, it does not solve the problem.

---
Fri, 11 Oct 2019 19:03:58 GMT | sent 1000 objects to destination elasticsearch, wrote 1000
<--- Last few GCs --->
[1:0x55f498d16d20] 18802433 ms: Scavenge 7800.8 (16541.2) -> 7800.7 (16541.7) MB, 65.2 / 0.0 ms (average mu = 0.917, current mu = 0.892) allocation failure
[1:0x55f498d16d20] 18802510 ms: Scavenge 7801.6 (16541.7) -> 7801.6 (16541.7) MB, 69.0 / 0.0 ms (average mu = 0.917, current mu = 0.892) allocation failure
[1:0x55f498d16d20] 18802578 ms: Scavenge 7801.6 (16541.7) -> 7801.6 (16541.7) MB, 61.3 / 0.0 ms (average mu = 0.917, current mu = 0.892) allocation failure
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x0da3c5c1e6e9 <JSObject>
0: builtin exit frame: parse(this=0x0da3c5c11a21 <Object map = 0x1a6e805842a9>,0x366bf2182201 <Very long string[741049]>,0x0da3c5c11a21 <Object map = 0x1a6e805842a9>)
1: parse [0x121cf7bb3259] [/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:~24] [pc=0xa1ca87aa95b](this=0x121cf7baf539 <Object map = 0x2ee5277a7249>,str=0x366bf2182201 <Very long string[741049]>,configs=0x3dc5795...
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory

**Comment by ferronrsmith** [comment]
That's a very old version. Seems your reading/exporting too much data (beyond node allowable limit). Also there isn't enough information in your comment to ascertain or aid.

**Comment by zhang8473** [comment]
I am using taskrabbit/elasticsearch-dump:latest docker image. My node has enough memory (8 cores/64GB).

**Comment by ferronrsmith** [comment]
This has nothing to do with concurrency, this is purely a memory issue. That file is too large to buffer, you need to segment the dataset into smaller chunks. Use the `--fileSize` param.

Maybe `--fileSize=1gb`, it's all dependent on what your system can handle.

**Comment by ferronrsmith** [comment]
Then you can use `cat *.segments > mylargefile.jsonl`

**Comment by zhang8473** [comment]
I am not dumping anything to a file. I am copying from one ES to another ES. There is nothing to do with file.

**Comment by ferronrsmith** [comment]
You're transferring too much data. You need to adjust the **--limit**. Also benchmark your settings.

**Comment by niglesiasbrc** [comment]
I can confirm this error also.
Using:
- node v12.13.0
- elasticdump 6.15.2

Tried in a 32 GB box with:
- --limit 50
- --fileSize 10mb
- NODE_OPTS="--max-old-space-size=8096"

Importing from an elasticsearch server, dumping to files.

While monitoring I can see that node's memory usage keeps growing until the error occurs, always around the same offset no matter what _--limit_ or _--fileSize_ I use.

**Comment by WGriffing** [comment]
This issue is a bit old now, but I was having the same problem. 

Upgrading from elasticdump v6.12.1 to v6.27.1 fixed it for me.

If it matters, I am running node v12.7.0.

Just wanted to drop a note here in case anyone else is in the same boat.

**Comment by zapcity** [comment]
Still getting the same issue when using:

elasticdump \
  --s3AccessKeyId blah \
  --s3SecretAccessKey blah \
  --input=http://elastic_ip:9200/some_index \
  --output "s3://some_s3/blah.json" \
  --limit "5000"

$ npm list -g
/home/ec2-user/.nvm/versions/node/v16.19.0/lib
├── corepack@0.15.1
├── elasticdump@6.97.0
└── npm@9.4.2

I originally set limit=10,000 and I estimated that it would take me 7.5 hrs to dump 32GB index to s3. If I set limit=5,000 it takes 15 hrs. I have hundreds of these 32 GB indexes to process. I cannot set limit=100 and wait years to do this operation.

How can we get elasticdump to segment the data so it writes a file to s3 after X number of records read? So instead of one huge file, it writes several; after each file dump it flushes memory and continues. It seems we can't do that and it stores all data in memory and writes one huge file at the end, I tried a EC2 with 64 GB of RAM and still not working.

**Comment by zapcity** [comment]
Even when using a 64 GB RAM EC2 instance with `export NODE_OPTIONS="--max-old-space-size=16384" `
it gets same problem. Now using Logstash which dumps chunks of data specified by `size_file`. This is what elasticdump should be capable of doing to possibly circumvent these fatal errors.
