### ISSUE TITLE
[BUG] SyntaxError: Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by tuandmcn** [taskrabbit/elasticsearch-dump#581]
I am using 

- ElasticDump 4.7.0
- Elasticsearch version 6.4.2
When i run command 
elasticdump --input=http://10.x.x.x:9200/hs --output=http://10.x.x.y:9200/hs--searchBody='{"query":{"range":{"NGAY_TAO":{"gte":"2019-08-21","lte":"2019-08-23"}}}}'
I get an error: SyntaxError: Unexpected token ' in JSON at position 0
Can you help me?

**Comment by ferronrsmith** [comment]
The `--searchBody` takes JSON as a string, which means it needs to be properly escaped.

`--searchBody="{\"query\":{\"range\":{\"NGAY_TAO\":{\"gte\":\"2019-08-21\",\"lte\":\"2019-08-23\"}}}}"`

**Comment by tuandmcn** [comment]
I run it ok, thank you very much!
