### ISSUE TITLE
[BUG] c

### ISSUE THREAD

**Issue by jondavidchristopher** [taskrabbit/elasticsearch-dump#582]
- ElasticDump version: 6.7.0
- Elasticsearch version: 7.1
- Node.js version: v11.10.0
- Full command you are having issue with (with inputs and outputs):
elasticdump --input=http://localhost:9200/mls_ca_claw_members_development --output=https://search-spindrip-2pmei6ogk3hv4766dwskzf55f4.us-east-1.es.amazonaws.com/mls_ca_claw_members_production --awsAccessKeyId=[redacted] --awsSecretAccessKey=[redacted] --type=data

- A data-set you can share publicly which reproduces the problem
Attaching. It's a rather large dataset.

**Describe the bug**
I am getting the "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details." issue. 

**To Reproduce**
1. Run command
2. Error occurs

**Current behavior**
I can't seem to get past this error. I have checked my AWS key combos a dozen times and generated a half dozen new ones to try to get past the issue. 

**Expected behavior**
Records are dumped to aws es cluster

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jondavidchristopher** [comment]
[mls_ca_claw_members_development.txt](https://github.com/taskrabbit/elasticsearch-dump/files/3528674/mls_ca_claw_members_development.txt)

**Comment by jondavidchristopher** [comment]
☝️ dump of index above

**Comment by ferronrsmith** [comment]
Seems like an AWS issue that occurs sporadically. I don't have access to AWS so I can't properly debug this issue for you, sorry. All Signatures are generated by the `aws-sdk`

**Comment by ferronrsmith** [comment]
Think I found the bug, fixing.

**Comment by ferronrsmith** [comment]
This issue should be fixed in v6.7.3, sorry for the inconvenience.

**Comment by jondavidchristopher** [comment]
@ferronrsmith NO inconvenience! Thanks for solving this so quickly. Can you point me towards some ES documentation for your --type option?

**Comment by ferronrsmith** [comment]
type option really just maps different elastic objects. Not sure exactly what you're looking for. Have to be specific

```
--type
                    What are we exporting?
                    (default: data, options: [settings, analyzer, data, mapping, alias, template])
```

**Comment by jondavidchristopher** [comment]
@ferronrsmith I guess analyzer is throwing me off. Is this for custom analyzers?

**Comment by ferronrsmith** [comment]
That's correct https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html


data - data records
settings - ES settings 
analyser - data analyzers
mappings - generated/custom mappins
alias - self explanatory
template - es template (dynamic/static)

**Comment by jondavidchristopher** [comment]
@ferronrsmith I am now getting the following when attempting to push up the type of mapping. I was able to push up the type of data without issue:

```
Sat, 24 Aug 2019 04:36:52 GMT | starting dump
Sat, 24 Aug 2019 04:36:52 GMT | got 1 objects from source elasticsearch (offset: 0)
(node:16720) UnhandledPromiseRejectionWarning: #<Object>
(node:16720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Sat, 24 Aug 2019 04:36:53 GMT | got 0 objects from source elasticsearch (offset: 1)
Sat, 24 Aug 2019 04:36:53 GMT | Total Writes: 0
Sat, 24 Aug 2019 04:36:53 GMT | dump complete
```

**Comment by ferronrsmith** [comment]
Can u share the mapping so I can test ? Thanks

**Comment by jondavidchristopher** [comment]
[my_index_mapping.txt](https://github.com/taskrabbit/elasticsearch-dump/files/3537312/my_index_mapping.txt)

**Comment by jondavidchristopher** [comment]
@ferronrsmith my apologies. Attached above

**Comment by ferronrsmith** [comment]
I wrote the patch for this, but I haven't had enough sleep, so I'll get some and test it later

**Comment by ferronrsmith** [comment]
Try posting the full command next time 👍 . Makes replicating much easier

**Comment by jondavidchristopher** [comment]
Sorry about that. Here it is below for reference. Did you end up finding the issue?

elasticdump --input=http://localhost:9200/mls_ca_claw_members_development --output=https://search-spindrip-2pmei6ogk3hv4766dwskzf55f4.us-east-1.es.amazonaws.com/mls_ca_claw_members_production --awsAccessKeyId=[redacted] --awsSecretAccessKey=[redacted] --type=mapping

**Comment by ferronrsmith** [comment]
Yea I did, already submitted a pr, will merge in a few

**Comment by jondavidchristopher** [comment]
Awesome man! Thank you so much

**Comment by ferronrsmith** [comment]
pushed the release btw

**Comment by jondavidchristopher** [comment]
Awesome, thanks. Will check shortly
