### ISSUE TITLE
Elasticdump not proccessing data

### ISSUE THREAD

**Issue by rahul15111990** [taskrabbit/elasticsearch-dump#584]
Hi,
I installed elasticdump on Amazon Linux 2 using latest epel (yum install elasticdump). But when i use it for dump or restore dump it is showing error.
ElasticDump version:  2.2.0
Elasticsearch version : 7.3.0
Node.js version : v6.17.1
NPM version : 3.10.10

Error On dump : 
elasticdump  --input=http://localhost:9200/.kibana  --output=user27082019_index.json  --type=data
**Mon, 26 Aug 2019 12:16:56 GMT | starting dump
Mon, 26 Aug 2019 12:16:56 GMT | Error Emitted => {"error":"Content-Type header [] is not supported","status":406}
Mon, 26 Aug 2019 12:16:56 GMT | Total Writes: 0
Mon, 26 Aug 2019 12:16:56 GMT | dump ended with error (get phase) => Error: {"error":"Content-Type header [] is not supported","status":406}**

Error on restore : 
elasticdump  --input=user26082019_index.json  --output=http://localhost:9200/.kibana --type=data
**Mon, 26 Aug 2019 12:18:27 GMT | starting dump
Mon, 26 Aug 2019 12:18:27 GMT | got 100 objects from source file (offset: 0)
Mon, 26 Aug 2019 12:18:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Mon, 26 Aug 2019 12:18:28 GMT | got 131 objects from source file (offset: 100)
Mon, 26 Aug 2019 12:18:28 GMT | sent 131 objects to destination elasticsearch, wrote 0
Mon, 26 Aug 2019 12:18:28 GMT | got 58 objects from source file (offset: 231)
Mon, 26 Aug 2019 12:18:28 GMT | sent 58 objects to destination elasticsearch, wrote 0
Mon, 26 Aug 2019 12:18:28 GMT | got 0 objects from source file (offset: 289)
Mon, 26 Aug 2019 12:18:28 GMT | Total Writes: 0
Mon, 26 Aug 2019 12:18:28 GMT | dump complete**

Please help

**Comment by ferronrsmith** [comment]
You're using a very old version of elasticdump that doesn't have support for ES v7.

**Comment by rahul15111990** [comment]
In epel repo only this version available.Do you have any idea how to install latest version in Amazon Linux AMI 2.

**Comment by ferronrsmith** [comment]
No I have no knowledge Amazon services, sorry

**Comment by rahul15111990** [comment]
Thank you for quick response..
Do you have any idea how to install it's latest version on centos 7 ??

**Comment by rahul15111990** [comment]
I tried npm install elasticdump -g. But after installation when i tried anything with elasticdump command it's showing below error.

[root@analytics ~]# elasticdump --help
/usr/lib/node_modules/elasticdump/elasticdump.js:123
  async _loop (limit, offset, totalWrites) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/elasticdump/bin/elasticdump:6:21)

**Comment by rahul15111990** [comment]
Awesome thanks!
It's working when i update my node to v10.
Thanks a lot for help.
