### ISSUE TITLE
Backup data of elasticsearch:6.3.1 to s3

### ISSUE THREAD

**Issue by kiddingl** [taskrabbit/elasticsearch-dump#589]
###  I want to backup data of elasticsearch to s3 with elasticsearch-dump is  running on docker.
But some problems apear in docker logs.

**My command in shell：**
```
docker run -dit --name=es-backup --net=host taskrabbit/elasticsearch-dump --s3SSLEnabled "false" --s3Endpoint "s3.stafdfdgig.egehap.com" --s3AccessKeyId "EQfjdksfhkd3N82CS" --s3SecretAccessKey "NQNnruud2zkfhfjksdhfksffdsafdI9div97q" --input=http://127.0.0.1:9201/bank --output "s3://db-backup/es-backup/bank"
```
**My dokcer logs：**
![image](https://user-images.githubusercontent.com/36329336/64409816-37cb2500-d0bc-11e9-95a3-be8f0f0b1b39.png)

I can't slove the problem
**tips:**
The exactt s3 key secret endpiinot has been modified on github, I think it's insecure on open platform.

**Comment by ferronrsmith** [comment]
Seems to be having trouble parsing the response from s3 (which is xml). According to the `aws-sdk` forum, it might be a corrupted response. I'll add a retry option, but beyond that I can't do much

**Comment by ferronrsmith** [comment]
version 6.8.0 has been pushed to docker hub

**Comment by kiddingl** [comment]
> 版本6.8.1已被推送到docker hub
###I am trying v6.8.1
#### Run the shell command:
```
docker run -it --rm  --net=host taskrabbit/elasticsearch-dump:v6.8.1 --concurrency 1 --s3SSLEnabled="false" --s3Endpoint="s3.m" --s3AccessKeyId="sdjkghsdgkhaskdjghaskjd" --s3SecretAccessKey="fhsdlkfsadlfjsaldkfjalsdfkjl" --s3ForcePathStyle="true"  --input "http://127.0.0.1:9201" --output s3://db-backup/es-backup/es-all.json
```
The end of command resault:
![image](https://user-images.githubusercontent.com/36329336/64690053-1609dd80-d4c2-11e9-9dc4-4d6c2adf885c.png)
Know the file has been uploaded s3
#### Restore data from s3 to elasticsearch, running the shell command：
```
docker run -it --rm  --net=host taskrabbit/elasticsearch-dump:v6.8.1 --concurrency 1 --s3SSLEnabled="false" --s3Endpoint="s3.om" --s3AccessKeyId="gsdkghklskdghasklghklS" --s3SecretAccessKey="jsdhafkjsdhfkjsdhfkjsadfhkjds" --s3ForcePathStyle="true"  --output "http://127.0.0.1:9201" --input s3://db-backup/es-backup/es-all.json
```
The resault of command:
![image](https://user-images.githubusercontent.com/36329336/64690279-94ff1600-d4c2-11e9-924a-ba20827a1a0d.png)
Only 31083 objects were restored in elasticsearch and lost many data

**Comment by kiddingl** [comment]
@ferronrsmith
