### ISSUE TITLE
Does not work with self-signed HTTPS certificates

### ISSUE THREAD

**Issue by quasipedia** [taskrabbit/elasticsearch-dump#59]
I'm not sure if I am doing anything wrong, but it seems es-dump is not working with our setup, where ES is reachable via HTTPS through a self-signed certificate.

From the console:

```
--- ~ » curl -XGET https://our-internal-server/_cat/indices | tail 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5742  100  5742    0     0  10313      0 --:--:-- --:--:-- --:--:-- 10327
yellow logstash-2014.09.30 5 1    9645 0 337.2mb 337.2mb 
yellow logstash-2014.12.14 5 1   51324 0  33.1mb  33.1mb 
yellow logstash-2014.11.02 5 1   16900 0  56.6mb  56.6mb 
yellow logstash-2015.01.06 5 1   47712 0  58.6mb  58.6mb 
yellow logstash-2014.12.13 5 1   31839 0  35.8mb  35.8mb 
yellow logstash-2014.11.14 5 1   34022 0    79mb    79mb 
yellow logstash-2015.01.01 5 1   27092 0  32.8mb  32.8mb 
yellow logstash-2014.10.20 5 1   13366 0  40.7mb  40.7mb 
yellow logstash-2014.10.12 5 1   31878 0   1.3gb   1.3gb 
yellow logstash-2014.11.04 5 1   13078 0  22.8mb  22.8mb 
```
...which shows that the certificate works and indices are there. However:

```
--- ~ » .npm/elasticdump/0.7.7/package/bin/elasticdump --input='https://our-internal-server/kibana-int' --output=/tmp/my_index.json --type=data --debug
Wed, 07 Jan 2015 13:37:38 GMT | starting dump
Wed, 07 Jan 2015 13:37:38 GMT | SELF_SIGNED_CERT_IN_CHAIN
Wed, 07 Jan 2015 13:37:38 GMT | got 0 objects from source elasticsearch (offset: 0)
Wed, 07 Jan 2015 13:37:38 GMT | sent 0 objects to destination file, wrote 0
Wed, 07 Jan 2015 13:37:38 GMT | dump complete
```
I tried to explicitly specify the 443 port, to omit the `--type` and `--debug` parameters, to change the index, to specify `--all`, to set the output to `stdout`, and more...

...but to no avail.  If I am doing something wrong, I'm missing what that is...

[As visible from the command line, I am using v0.7.7, and I am running it on my local machine, a Fedora 21 64 bit installation].

**Comment by evantahler** [comment]
Under the hood, we use the [request](https://github.com/request/request) package for making the HTTP requests.  To use self signed certs, it looks like a few steps are required:

- supply the `strictSSL` option 
  - *If true, requires SSL certificates be valid. Note: to use your own certificate authority, you need to specify an agent that was created with that CA as an option.*
- provide a proxy certificate authority via the PEM file with the options:
```json
agentOptions: {
        ca: fs.readFileSync('ca.cert.pem')
    }
```
  - *It is possible to accept other certificates than those signed by generally allowed Certificate Authorities (CAs). This can be useful, for example, when using self-signed certificates. To allow a different certificate, you can specify the signing CA by adding the contents of the CA's certificate file to the agentOptions*

The `SELF_SIGNED_CERT_IN_CHAIN ` error you are seeing is indicative of `request` having an SSL issue, so I believe that this is the cause of your problem.  We use this tool over HTTPS with a valid cert, and I confirm that it does work OK.  

Please try out the options above (all of your changes should be within [this file](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js)) and let us know if it works.  If it does, we can try and sort out how to handle the command-line arguments that would be required.

**Comment by quasipedia** [comment]
@evantahler - Thank you for the prompt, informative answer. :)

Unluckily I am not a JS developer and I wanted to use elasticsearch-dump for a one-off operation, so both the time and skills I can throw at this are limited, as I could find a workaround to my contingent problem.

I am willing to test stuff to help improving elasticsearch-dump though, but I'd need stricter directions, especially given that the source is undocumented. Where/how should I modify the file? Is the call on line 83 the one of concern (I got to that idea because despite the object being called `searchRequest` it looks like it's a search that will match all entries).

As I said, I'd be happy to test stuff for you, but I need guidance.

**Comment by evantahler** [comment]
We'll leave this issue open until someone has the time to implement insecure HTTPS certificates.

**Comment by quasipedia** [comment]
Cool.  Just to be clear though: a self-signed certificate is not "insecure", it's just a certificate whose chain of trust does not relies on CA authorities.

In fact self-signed certificates is *the* most common way to secure back-end elasticsearch connections [at least according to the poll conducted by Elasticsearch itself during the webinair on Shield].

In my case I was able to get to a colleague with an account on the server and dump using http on localhost and bypassing Apache altogether, working around the problem.

**Comment by evantahler** [comment]
If you want to use a self-signed cert in node in general, you can add an environment variable to trigger node to be OK with it (which, by default, it is not).

You can either add this as an early ling of code in your `elasticsearch` "binary" `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` or set this when you launch the application, IE: 

```
NODE_TLS_REJECT_UNAUTHORIZED=0 elasticdump --input=http://production.es.com:9200/my_index --output=http://staging.es.com:9200/my_index --type=mapping
```

**Comment by letusfly85** [comment]
Is your example not a self-signed certificate???

```
http://production.es.com:9200/my_index
```

is not  self-signed certificate.

in correctly, is below right?
```
https://production.es.com:9200/my_index
```


On my machine,  self-signed certificate doesn't work yes....

**Comment by evantahler** [comment]
I believe that the hack above (ENV VARS) only works on some operating systems.  The *real* answer is to change the code per https://github.com/taskrabbit/elasticsearch-dump/issues/59#issuecomment-69057549.

Pull requests welcome!

**Comment by evgf** [comment]
In case someone faces the issue and needs a quick workaround.
Here is the Dockerfile that builds a Docker image ignoring the errors caused by the self-signed certificate (based on the original image from Evan):
`
FROM alpine:3.3
MAINTAINER evan@evantahler.com
RUN apk add --update nodejs
ENV NODE_TLS_REJECT_UNAUTHORIZED 0
RUN npm install elasticdump -g
ENTRYPOINT ["/usr/lib/node_modules/elasticdump/bin/elasticdump"]`

**Comment by evantahler** [comment]
You don't need to rebuild the docker file at all, you can pass environment variables in at runtime with ` -e NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by rjurney** [comment]
So glad you addressed this, or I couldn't use the tool!
