### ISSUE TITLE
How to import settings?

### ISSUE THREAD

**Issue by seanr** [taskrabbit/elasticsearch-dump#593]
From another issue, I see "Settings can only be added on index creation." So I tried this on the target environment:

curl -XDELETE 'https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/index-name

That seems to work (acknowledged: true returned), but then the settings import still errors out with the same error.

I'm a bit at a loss here, because --type=analyzer doesn't actually seem to copy over the analyzer info (which is how I found out about --type=settings) so then my mappings won't import either because of the missing analyzers. How can I get to a state where I can get that working, either with --type=settings, or some alternate method?

**Comment by ferronrsmith** [comment]
`--type=analyzer ` & `--type=settings` does the same thing on output. On input is where they differentiate. 

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the course url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by seanr** [comment]
Sorry, this wasn't really a bug report so much as a support request. My local machine is a Mac, but both environments in question are AWS. What I need is a way to get the analyzer stuff over from our prod to test servers. If this tool can't do that, I'm OK with that answer, but I'm looking for a way to get the test server to perfectly match what's in prod in anticipation of having to do something similar in the event that our planned change to prod doesn't go well. Not getting the analyzers and thus the mappings across is a blocker for me right now.

Here's what I've tried:

```
elasticdump \
  --input=https://vpc-searchprod-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --output=https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --type=analyzer
```
As mentioned elsewhere, doesn't add analyzer info to the settings:

```
curl -XGET 'https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted]/_settings?pretty' -w "\n"
```
Returns incomplete array.

```
curl -XDELETE 'https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted]?pretty' -w "\n"
```
Reports acknowledged: true.

```
elasticdump \
  --input=https://vpc-searchprod-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --output=https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --type=settings
```
Fails saying index still exists.

```
elasticdump \
  --input=https://vpc-searchprod-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --output=https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted] \
  --type=mapping
```
Fails due to missing analyzer.

I've redacted the URLs including the index name for obvious reasons as one of them is in production.

**Comment by seanr** [comment]
```
$ curl -XGET 'https://vpc-searchtest-[redacted].us-east-1.es.amazonaws.com/[redacted]/_settings?pretty' -w "\n"
{
  "[redacted]" : {
    "settings" : {
      "index" : {
        "creation_date" : "1546457841981",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "VSAHXOT-TlalRHHFEoiaMQ",
        "version" : {
          "created" : "5050299"
        },
        "provided_name" : "wcm-sites"
      }
    }
  }
}
```

While:
```
$ curl -XGET 'https://vpc-searchprod-[redacted].us-east-1.es.amazonaws.com/[redacted]/_settings?pretty' -w "\n"
{
  "[redacted]5" : {
    "settings" : {
      "index" : {
        "number_of_shards" : "5",
        "provided_name" : "[redacted]5",
        "creation_date" : "1536254897628",
        "analysis" : {
          "filter" : {
            "english_keywords" : {
              "keywords" : [
                [redacted]
              ],
              "type" : "keyword_marker"
            },
            "shingle" : {
              "max_shingle_size" : "3",
              "min_shingle_size" : "2",
              "type" : "shingle"
            },
            "english_stemmer" : {
              "type" : "stemmer",
              "language" : "english"
            },
            "english_possessive_stemmer" : {
              "type" : "stemmer",
              "language" : "possessive_english"
            },
            "english_stop" : {
              "type" : "stop",
              "stopwords" : "_english_"
            }
          },
          "analyzer" : {
            "reverse" : {
              "filter" : [
                "standard",
                "reverse"
              ],
              "type" : "custom",
              "tokenizer" : "standard"
            },
            "trigram" : {
              "filter" : [
                "standard",
                "shingle"
              ],
              "type" : "custom",
              "tokenizer" : "standard"
            },
            "wcm_english" : {
              "filter" : [
                "english_possessive_stemmer",
                "lowercase",
                "english_stop",
                "english_keywords",
                "english_stemmer"
              ],
              "tokenizer" : "standard"
            }
          }
        },
        "number_of_replicas" : "1",
        "uuid" : "ZL4tqLdQSwibqGRchRi4WA",
        "version" : {
          "created" : "5050299"
        }
      }
    }
  }
}
```

I need to get the first one to look like the second.

I will note that the second one has a number added to the tail end of [redacted] (5). Could that be tripping me up additionally? But anyway, it's not even gotten that far from what I've been reading in the issues here.

**Comment by ferronrsmith** [comment]
`--type=analyzer` & `--type=settings` does the same thing on output. Meaning, when you pull the data from an index using either option, the same output will be returned.


On insertion they are different. 

`analyzer` takes the analysis portion of the payload and submits it to ES.
`settings` take everything except the restricted fields and submits it to ES.

In both cases the index must not exist for this to work.

**Comment by seanr** [comment]
OK, that last point in your comment may be what's tripping me up. I figured out a way around it with a direct curl put for now.

**Comment by ferronrsmith** [comment]
Yea it’s a bit confusing l, but the thing is. Once data is indexed, the settings/analysers don’t matter. Which is why we ensure they are non-existent before.
