### ISSUE TITLE
Can't complete export of large data set from AWS Elasticsearch 5.5

### ISSUE THREAD

**Issue by pawoolley** [taskrabbit/elasticsearch-dump#596]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:
- OS: Ubuntu 18.04 LTS
- ElasticDump version: elasticsearch-dump Docker image v6.8.3
- Elasticsearch version: AWS Elasticsearch Service 5.5
- Node.js version: Don't know. Whatever comes with Docker image v6.8.3
- Full command you are having issue with (with inputs and outputs): `docker run -v "${env.WORKSPACE}/$sourceESCredentials:/root/.aws/credentials" -v "${env.WORKSPACE}:/tmp" --rm -i taskrabbit/elasticsearch-dump --searchBody='{"query":{"match":{...}}' --retryAttempts=3 --concurrency=1 --awsChain --type=data --debug=true --input=$sourceEnvDetails.esUrl/event --output=/tmp/data.json`
- A data-set you can share publicly which reproduces the problem: Sorry, but the data set is private.

**Describe the bug**
I'm trying to export a subset of data from an index in AWS Elasticsearch Service (ES is version 5.5), which contains ~153M documents.  Using a `searchBody` query, I'm limiting the overall export to ~500K documents.  The export starts off fine and runs for a bit, but after a few minutes of exporting and before exporting all the documents, it quits with the following type of error message:
```
Fri, 13 Sep 2019 14:54:15 GMT | sent 100 objects to destination file, wrote 100
Fri, 13 Sep 2019 14:54:25 GMT | Error Emitted => getaddrinfo ENOTFOUND <URL of the AWS ES logged here>
Fri, 13 Sep 2019 14:54:25 GMT | Total Writes: 209700
Fri, 13 Sep 2019 14:54:25 GMT | dump ended with error (get phase) => Error: getaddrinfo ENOTFOUND <URL of the AWS ES logged here>
```

**To Reproduce**
1. Have a large data set (~500,000 docs) in an index in AWS ES 5.5.
2. Using the Dockerised version of elasticsearch-dump, attempt to export it to a file.

**Current behavior**
The export quits before completing with a `ENOTFOUND` error.

**Expected behavior**
The export completes.

**Additional context**
I did wonder if I was hitting some sort of AWS service/rate limit, which is why I tried adding the `--retryAttempts=3` and `--concurrency=1` options to try and make things more resilient to errors and perhaps run a bit slower, but it didn't help and I don't see any clues from the available logging as to why these `ENOTFOUND` errors suddenly start showing up after the export seems to start off fine.

I get that this might be something to do with the use of AWS ES and not necessarily a bug with elasticsearch-dump, but at this point, from the logging available, I can't really tell or diagnose further.  Any clues/hints/tips gratefully received.

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
I don't use AWS so I can't say for sure if it's a rate limit issue, but it does seem like it.

Setting conccurency=1 doesn't exactly limit concurrency. There's more to it than that.

```bash
docker run -v "${env.WORKSPACE}/$sourceESCredentials:/root/.aws/credentials" -v "${env.WORKSPACE}:/tmp" --rm -i taskrabbit/elasticsearch-dump --searchBody='{"query":{"match":{...}}' --retryAttempts=3 --concurrency 1 --intervalCap 5 --concurrencyInterval 5000 --carryoverConcurrencyCount true --throttleInterval 1 --awsChain --type=data --debug=true --input=$sourceEnvDetails.esUrl/event --output=/tmp/data.json
```

Try running the above command. You should have better results. You can move the concurrency/intervalCap up/down based on your own benchmarking.

**Comment by pawoolley** [comment]
Thanks for the information, @ferronrsmith.  I do seem to be having better results using the command you suggested along with adjusting the `concurrency` and `intervalCap` values up/down.

I have a couple of questions about two of the parameters, which isn't clear from the docs:
- `throttleInterval`: What is the unit of delay?  Seconds, milliseconds?
- `carryoverConcurrencyCount`: Is this saying that if `true`, any incomplete requests from a `concurrencyInterval` will carry over in to the next interval, which will effectively reduce the number of new requests created in the next interval?  I.e. `new requests = intervalCap - <num of carried over requests>`.  And if `false`, new requests will be created in every `concurrencyInterval`, regardless of whether requests from the previous interval completed or not?

**Comment by ferronrsmith** [comment]
1. all units of time is milliseconds.
2. Yes & Yes.
