### ISSUE TITLE
[BUG] Problem with dumping index data

### ISSUE THREAD

**Issue by bbkgh** [taskrabbit/elasticsearch-dump#598]
**Context**
elasticdump version -> 6.9.1
Elasticsearch version -> 6.5.4
node -> v8.10.0

Command: 
elasticdump \     
  --input=http://username:password@localhost:9200/index_name \
  --output=/tmp/index_name.json \
  --type=data

I can't dump index data with above command. Command's output file is attached.

[elasticdump_output.txt](https://github.com/taskrabbit/elasticsearch-dump/files/3615027/elasticdump_output.txt)

But mapping of this index can be fetched:
elasticdump \     
  --input=http://username:password@localhost:9200/index_name \
  --output=/tmp/index_name.json \
  --type=mapping

**Comment by ferronrsmith** [comment]
A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.


There isn't enough information here to reproduce or move forward.
