### ISSUE TITLE
Specific versions of elasticdump

### ISSUE THREAD

**Issue by gerbdla** [taskrabbit/elasticsearch-dump#602]
My company needs to build specific versions of elasticdump available to build from a Dockerfile but we cannot use anything other than FROM taskrabbit/elasticsearch-dump:version 
in the file for security reasons.  It appears that when I add a version for instance
FROM taskrabbit/elasticsearch-dump:6.8.3 I get 
 failed to build: manifest for taskrabbit/elasticsearch-dump:6.8.3 not found: manifest unknown:

**Comment by ferronrsmith** [comment]
You should look at the tag names


https://cloud.docker.com/u/taskrabbit/repository/docker/taskrabbit/elasticsearch-dump


**FROM taskrabbit/elasticsearch-dump:v6.8.3**
