### ISSUE TITLE
[FEATURE]change ENTRYPOINT to CMD in dockerfile

### ISSUE THREAD

**Issue by kiddingl** [taskrabbit/elasticsearch-dump#603]
I hava many indexs, I want to run the docker in k8s and use elasticsearch-dump in more times. I cant't use elasticdump command and only use options if use ENTRYPOINT in dockerfile.

**Comment by ferronrsmith** [comment]
I can't remove the ENTRYPOINT since it would break the current flow. I did however allow it to be overridden easily.

**Comment by ferronrsmith** [comment]
You can always create your own Dockerfile
