### ISSUE TITLE
[BUG] multielasticdump: "Error: --input() does not exist"

### ISSUE THREAD

**Issue by seanr** [taskrabbit/elasticsearch-dump#605]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: latest updated minutes ago from NPM - 6.10.0

- Elasticsearch version: 5.6

- Node.js version: 10.16.3

- Full command you are having issue with:
`multielasticdump --direction=load --input=es_backup --output=http://localhost:32800`

- A data-set you can share publicly which reproduces the problem
LARGE local backup from AWS, cannot share.

**Describe the bug**

```
bash-3.2$ multielasticdump --direction=load --input=es_backup --output=http://localhost:32800
Fri, 20 Sep 2019 19:13:55 GMT | We are performing : load
Fri, 20 Sep 2019 19:13:55 GMT | options: {"debug":true,"parallel":8,"match":"^.*$","input":"es_backup","output":"http://localhost:32800","scrollTime":"10m","timeout":null,"limit":100,"offset":0,"direction":"load","support-big-int":false,"ignoreAnalyzer":false,"ignoreData":false,"ignoreMapping":false,"ignoreSettings":false,"ignoreTemplate":false,"ignoreAlias":true,"ignoreType":[],"interval":1000,"prefix":"","suffix":"","transform":null,"headers":null,"searchBody":null,"cert":null,"key":null,"pass":null,"ca":null,"tlsAuth":false,"input-cert":null,"input-key":null,"input-pass":null,"input-ca":null,"output-cert":null,"output-key":null,"output-pass":null,"output-ca":null,"concurrency":null,"carryoverConcurrencyCount":false,"intervalCap":null,"concurrencyInterval":0,"overwrite":false}
/usr/local/lib/node_modules/elasticdump/bin/multielasticdump:162
  if (!fs.existsSync(options.input)) { throw new Error('--input() does not exist') }
                                       ^

Error: --input() does not exist
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/bin/multielasticdump:162:46)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**To Reproduce**
1. `multielasticdump --direction=dump --input=https://vpc-searchprod-kks6rqngdaekvmrk2hwvtth5iu.us-east-1.es.amazonaws.com --output=elasticsearch` (works fine)
2. `multielasticdump --direction=load --input=es_backup --output=http://localhost:32800` (32800 is the port of my locally running ES in docker, can curl it locally)
3. See error

**Current behavior**
Blows up claiming a documented option doesn't exist.

**Expected behavior**
Imports.

**Additional context**
Moving an AWS backup to my local machine and then want to pull it into a docker container to demonstrate a full backup before we attempt to import to an AWS instance.

OS X Mojave locally, running commands in bash for sanity check (I usually use fish). Target docker environment is the bitnami elasticsearch image for 5.6, configured (automatically by lando: https://lando.dev/) to expose to localhost:32800.

**Comment by ferronrsmith** [comment]
input, as in the folder that your importing the data from does not exists. 

When the direction is `load`, input must be a directory
When the direction is `dump`, output must be a directory

**Comment by seanr** [comment]
I suggest this be reopened as a feature request to make the error more accurate, then. I hadn't realized I had the wrong directory in the input, and the error makes it seem like the --input _option_ doesn't exist, not the --input _value_.

**Comment by ferronrsmith** [comment]
Feel free to submit another issue. It’s a bug, that’s a feature request
