### ISSUE TITLE
[FEATURE] multielasticdump: full usage example in docs

### ISSUE THREAD

**Issue by seanr** [taskrabbit/elasticsearch-dump#611]
**Is your feature request related to a problem? Please describe.**
It appears as though a straight export and then import via multielasticdump without ignoreType trips on itself on import, apparently because settings and analyzer trip on each other (from what I could tell). The following on import will not work because the index will already exist:

1. `curl -XDELETE http://localhost:9200/*`
2. Verify via kibana no indexes remain (except `.kibana`)
3. `multielasticdump --direction=load --input=es_backup --output=http://localhost:9200 --match='[^.*$]'`

It appears to run into itself during the setup of each index (it throws index_already_exists_exception a couple times and then hangs). Looking at kibana afterward, you'll see a couple of the indexes got created until the point where the script hanged.

**Describe the solution you'd like**
A clear and concise usage example in the readme, and perhaps a better explanation of the ignoreType option and its apparent necessity.

**Describe alternatives you've considered**
This may actually be a bug? In that case, multielasticdump should choose settings over analyzer (if that is indeed the correct course of action to get the most complete restore) and continue on its merry way.

**Give some examples of implementations**
This worked for me to get the import completed:
`multielasticdump --direction=load --input=es_backup --output=http://localhost:9200 --match='[^.*$]' --ignoreType=analyzer`

**Comment by ferronrsmith** [comment]
I've said this already and this is very clear in Elasticsearch documents. settings & analysers are mutually exclusive. There is no point in importing analysers + settings. Analyzers are a subset of settings.

**Comment by seanr** [comment]
My point is that the multielasticdump without specifying ignoreType will attempt to do both, and the readme does not tell you that and unless someone found your specific comment on my other issue, how would they know that? There is at least one multielasticdump example in the issues where the person's code snippet didn't include that. I only figured it out because you had mentioned that before, but you cannot expect the average user new to your tool to find that, hence the documentation request.

You're going to get more bug reports without that, so I'm trying to save you future work.

**Comment by ferronrsmith** [comment]
I've ignored the `analyzer` type by default. ✅ 
I've also updated the docs with usage examples + notes on the types that are ignored by default.

It's easier to just submit a PR with docs changes. I can't see everything 👀. I'm only one person 😄.

Thanks for using elasticsearch-dump

**Comment by ferronrsmith** [comment]
So here's the challenge. Read the changes I've made. If they aren't adequate please submit a PR that breaks down multielasticdump and its options (with examples) for the average user. Thanks in advance 👍

**Comment by seanr** [comment]
OK, will do. Thanks. I apologize; I got thrown into this out of nowhere so I'm learning ES the same time I'm learning your tool. I've made crazy progress over the last couple weeks, but it's still just coming together. ;)

**Comment by ferronrsmith** [comment]
No problem 😉. I’m here to help.

**Comment by seanr** [comment]
From your edit to the readme:

`# NB: analyzer & alias types are ignored by default`

Is that actually the case? In my experience, alias was but analyzer was not.

**Comment by ferronrsmith** [comment]
That was added in v6.11.0.

**Comment by seanr** [comment]
OK, my latest pull from the other day didn't include that and looks like I'm a version behind again. :/
