### ISSUE TITLE
Multielasticdump compress support

### ISSUE THREAD

**Issue by peidong-hu** [taskrabbit/elasticsearch-dump#614]
**Is your feature request related to a problem? Please describe.**
the multielasticdump will dump all indices, and in my case, the size of data is huge. can we have option to compress the dump files in the dump folder?

**Describe the solution you'd like**
add option in multielasticdump to let the backup and restore process automatically zip/unzip the files.

**Comment by ferronrsmith** [comment]
no this isn't something that I'll be adding. This is something that can be handle pre/post.

**Comment by ferronrsmith** [comment]
added a `--fsCompress` flag.
