### ISSUE TITLE
Import to AWS ElasticSearch fails with "Request size exceeded 10485760 bytes"

### ISSUE THREAD

**Issue by pawoolley** [taskrabbit/elasticsearch-dump#616]
_This is perhaps somewhere between a bug and a feature request._

**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: **6.12.0**
- Elasticsearch version: **AWS ElasticSearch Service, ES v5.5**
- Node.js version: **not sure**
- Full command you are having issue with (with inputs and outputs):
`gzip -cd data.json.gz | docker run -v /home/ubuntu/.aws/credentials:/root/.aws/credentials --rm -i taskrabbit/elasticsearch-dump --retryAttempts=5 --retryDelay=5000 --concurrency=3 --intervalCap=50 --concurrencyInterval=5000 --carryoverConcurrencyCount=true --throttleInterval=1 --awsChain --type=data --input=$ --output=<AWS ES endpoint URL>`
- A data-set you can share publicly which reproduces the problem: **sorry, but dataset is private**

**Describe the bug**
Attempt to import data from a gzipped data file in to an AWS hosted ES instance.  Import fails with `"Request size exceeded 10485760 bytes"` message.

**To Reproduce**
1. Import data.
1. See error.

**Current behavior**
Import fails.  Logging shows:
```
Importing data to <AWS ES endpoint URL>
Fri, 04 Oct 2019 10:09:49 GMT | starting dump
Fri, 04 Oct 2019 10:09:49 GMT | got 100 objects from source file (offset: 0)
Fri, 04 Oct 2019 10:09:51 GMT | got 36766 objects from source file (offset: 0)
Fri, 04 Oct 2019 10:09:52 GMT | sent 100 objects to destination elasticsearch, wrote 100
Fri, 04 Oct 2019 10:09:52 GMT | got 0 objects from source file (offset: 100)
Fri, 04 Oct 2019 10:09:52 GMT | Error Emitted => {"Message":"Request size exceeded 10485760 bytes"}
Fri, 04 Oct 2019 10:09:52 GMT | Total Writes: 0
Fri, 04 Oct 2019 10:09:52 GMT | dump ended with error (get phase) => Error: {"Message":"Request size exceeded 10485760 bytes"}
Fri, 04 Oct 2019 10:09:52 GMT | Error Emitted => {"Message":"Request size exceeded 10485760 bytes"}
```

**Expected behavior**
Import succeeds.

**Additional context**
A quick Google for `"Request size exceeded 10485760 bytes"` turns up [this page](https://github.com/wagtail/wagtail/issues/4554) which says, *"This happens because the default value of the max_chunk_bytes keyword arg for bulk() is 100 megabytes, but Amazon only allows 10 megabytes per chunk (as evidenced by that error message)."*

Could this problem be worked around by using a lower value for `--limit`, or does one of the other options somehow allow the setting of `max_chunk_bytes` to a different value?  If not, could the ability to set `max_chunk_bytes` and/or other bulk insert properties be exposed as command line args?

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
The default value for limit is 100 records, If your records are large then use `--limit` to reduce the amount of items imported.

**Comment by ferronrsmith** [comment]
Seems the limit is determined based on the instance type : https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html
