### ISSUE TITLE
[BUG] elasticdump 6.12.1 does not seem to handle --limit argument when uploading to ES

### ISSUE THREAD

**Issue by lentils** [taskrabbit/elasticsearch-dump#617]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.12.1
- Elasticsearch version: v5.6.2
- Node.js version *(note that nodejs v8+ is required for this tool)*: v11.10.1
- Full command you are having issue with (with inputs and outputs): 
`elasticdump --input=/tmp/backups/backup.json --output=<ES_HOST>`
- A data-set you can share publicly which reproduces the problem: None currently. I don't think a dataset is relevant for this particular bug.

**Describe the bug**

Hello, I am having trouble with the `--limit` argument when *uploading* objects to ES. When I PUT objects using a local file as `--input` (with the ES index as `--output` destination), I'm seeing the payloads get progressively larger, eventually resulting in OOM of the JS VM or a timeout from the ES host:

```
elasticdump --limit=100 --input=/tmp/backups/backup.json --output=<ES_HOST>
Tue, 08 Oct 2019 02:14:27 GMT | got 100 objects from source file (offset: 0)
Tue, 08 Oct 2019 02:14:27 GMT | sent 100 objects to destination elasticsearch, wrote 100
Tue, 08 Oct 2019 02:14:27 GMT | got 1590 objects from source file (offset: 100)
Tue, 08 Oct 2019 02:14:30 GMT | sent 1590 objects to destination elasticsearch, wrote 1590
Tue, 08 Oct 2019 02:14:30 GMT | got 12376 objects from source file (offset: 1690)
Tue, 08 Oct 2019 02:14:54 GMT | sent 12376 objects to destination elasticsearch, wrote 12376
Tue, 08 Oct 2019 02:14:54 GMT | got 92735 objects from source file (offset: 14066)
...
```

Note that `--limit` is specified there, using the default 100.

Interestingly, I don't get the same behavior when writing objects *from* ES to a local file, only when I go from a file to ES.

Furthermore, `--limit` *is* configurable, but only for the first batch operation:

```
elasticdump --limit=1 --input=/tmp/backups/backup.json --output=<ES_HOST>
Wed, 09 Oct 2019 19:13:40 GMT | starting dump
Wed, 09 Oct 2019 19:13:40 GMT | got 1 objects from source file (offset: 0)
Wed, 09 Oct 2019 19:13:41 GMT | sent 1 objects to destination elasticsearch, wrote 1
Wed, 09 Oct 2019 19:13:41 GMT | got 10928 objects from source file (offset: 1)
^C
```

The previous version of `elasticdump` (`v6.11.2`) does not have this problem.

It seems to me that `limit` is not being handled properly with the latest release of `elasticdump` (`v6.12.1`), but *only* when `--output` is an ElasticSearch host. 

**To Reproduce**
- Try to upload any payload where `--input` is a file with objects of ~1000 or more and `--output` is an ES host
- Observe the batch size grow seemingly exponentially with each batch

**Current behavior**
`--limit` only works for the first batch. Subsequent batches seem to grow by an order of magnitude. 

**Expected behavior**
Each batch size should be roughly the same amount as what's specified by `--limit` (I am aware of the "fuzziness" when streaming, that part is fine). Here's what I get for the exact same data on the previous `elasticdump` version (`6.11.2`):

```
elasticdump --limit=100 --input=/tmp/backups/backup.json --output=<ES_HOST>
Wed, 09 Oct 2019 19:25:27 GMT | starting dump
Wed, 09 Oct 2019 19:25:28 GMT | got 100 objects from source file (offset: 0)
Wed, 09 Oct 2019 19:25:29 GMT | sent 100 objects to destination elasticsearch, wrote 100
Wed, 09 Oct 2019 19:25:29 GMT | got 109 objects from source file (offset: 100)
Wed, 09 Oct 2019 19:25:30 GMT | sent 109 objects to destination elasticsearch, wrote 109
Wed, 09 Oct 2019 19:25:30 GMT | got 105 objects from source file (offset: 209)
Wed, 09 Oct 2019 19:25:32 GMT | sent 105 objects to destination elasticsearch, wrote 105
Wed, 09 Oct 2019 19:25:32 GMT | got 112 objects from source file (offset: 314)
Wed, 09 Oct 2019 19:25:33 GMT | sent 112 objects to destination elasticsearch, wrote 112
Wed, 09 Oct 2019 19:25:33 GMT | got 107 objects from source file (offset: 426)
Wed, 09 Oct 2019 19:25:34 GMT | sent 107 objects to destination elasticsearch, wrote 107
Wed, 09 Oct 2019 19:25:34 GMT | got 110 objects from source file (offset: 533)
^C
```

**Screenshots**
None

**Additional context**
I see that there's been some refactoring since the previous version (eg https://github.com/taskrabbit/elasticsearch-dump/commit/e866759c0a6c7819fa9aaba3856759b9fac011d4). Specifically, I see some references to limits and counter updates in `lib/transport/base.js`. Is it possible a bug was introduced during refactoring?

**Comment by ferronrsmith** [comment]
taken care of in the latest release.
