### ISSUE TITLE
ssl_assert_hostname option

### ISSUE THREAD

**Issue by seperman** [taskrabbit/elasticsearch-dump#619]
**Is your feature request related to a problem? Please describe.**
I'm doing port forwarding hence the https validation fails with `Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames`.

**Describe the solution you'd like**
Many http request libraries come with an option to ignore SSL validation errors.
Example: `ssl_assert_hostname=false` but it should be true by default.

**Describe alternatives you've considered**
I'm currently using some custom code to do it since I can't use this tool.

**Comment by ferronrsmith** [comment]
have you tried `NODE_TLS_REJECT_UNAUTHORIZED=0`
