### ISSUE TITLE
Running the test suite copies all data from local ES indexes to /tmp/out.json

### ISSUE THREAD

**Issue by davidjairala** [taskrabbit/elasticsearch-dump#62]
This causes the rest of the tests (when trying to read from the out.json file) to fail because of timeouts.

Proposal: lets make it so the all to `"all es to file"` test limits the number of rows it copies.

**Comment by evantahler** [comment]
You got it!
https://github.com/taskrabbit/elasticsearch-dump/commit/a1572dde62629ca0a3e0c0692a7cc61985f05d79
