### ISSUE TITLE
use docker to run elasticsearch-dump, throw error no such file or directory

### ISSUE THREAD

**Issue by GrayGraySmall** [taskrabbit/elasticsearch-dump#625]
**ElasticSearch version:**6.7.0
**ElasticDump version:** latest

I use the comand
 `docker run --rm -ti taskrabbit/elasticsearch-dump --input ./my_data.json --output http://127.0.0.1:9200/my_index --type=data`
to import  my data to my local index，but the comand throw an error：

`Tue, 15 Oct 2019 09:33:19 GMT | starting dump
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'vendor_assignrule.json'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)`

and the comand in the same directory  with my_data.json

**Comment by ferronrsmith** [comment]
You're referencing a file that's outside the container inside the container. This is really a docker issue. Short version is you need a volume.

docker run -v **$PWD:/host** --rm -ti taskrabbit/elasticsearch-dump --input **/host/my_data.json** --output http://127.0.0.1:9200/my_index --type=data
