### ISSUE TITLE
ATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vivekyad4v** [taskrabbit/elasticsearch-dump#626]
**Context**
- ElasticDump version - docker - "taskrabbit/elasticsearch-dump:latest"
- Elasticsearch version - 6.8
- Node.js version *docker - taskrabbit/elasticsearch-dump:latest*
- 
```
# Import data from S3 into ES (using s3urls)
docker run --rm -ti taskrabbit/elasticsearch-dump \
  --s3AccessKeyId "${AWS_ACCESS_KEY_ID}" \
  --s3SecretAccessKey "${AWS_SECRET_ACCESS_KEY}" \
  --input "s3://${S3_BUCKET_NAME}/${index}-${APPNAME}-${DATE}.json" \
  --output="${new_instance}/${index}" \
  --limit 500 \
  --concurrency 1 \
  --fileSize 100mb

```

Not sure if fileSize works with S3 but it created a single file in S3 & while restoring, I am getting below error -

```
<--- Last few GCs --->

[1:0x561f202d2fc0]   713220 ms: Mark-sweep 1393.7 (1422.8) -> 1393.7 (1422.8) MB, 1231.5 / 0.0 ms  (average mu = 0.079, current mu = 0.000) last resort GC inold space requested
[1:0x561f202d2fc0]   714456 ms: Mark-sweep 1393.7 (1422.8) -> 1393.7 (1422.8) MB, 1236.4 / 0.0 ms  (average mu = 0.041, current mu = 0.000) last resort GC inold space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c0868f9e6e9 <JSObject>
    0: builtin exit frame: stringify(this=0x3c0868f91a21 <Object map = 0x3684228842a9>,0x1b2b6cc026f1 <undefined>,0x1b2b6cc026f1 <undefined>,0x0127e01afbe1 <Very long string[2057824]>,0x3c0868f91a21 <Object map = 0x3684228842a9>)

    1: arguments adaptor frame: 1->3
    2: stringify [0x27e465be9599] [/usr/local/lib/node_modules/elasticdump/lib/jsonparser.js:~37] [pc=0xfd1ff1ee174](this=0x27e465...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 

```

**Comment by vivekyad4v** [comment]
@ferronrsmith - Please suggest. Quite similar to - https://github.com/taskrabbit/elasticsearch-dump/issues/578

**Comment by ferronrsmith** [comment]
You can try increasing the `--max-old-space-size=4096`. If you still get the error then the `--limit` is too high, beyond what can be handled

**Comment by vivekyad4v** [comment]
Didn't try "--max-old-space-size=4096" because using `node:12-alpine` as the base docker image for elasticdump executable solved the issue. It would be great if someone can update the Dockerhub image for latest node version as well.

Dockerfile - 

```
FROM node:12-alpine
LABEL maintainer="evan@evantahler.com"

RUN npm install elasticdump -g

ENTRYPOINT ["elasticdump"]
```
@ferronrsmith - Thanks a lot for your help!

**Comment by ferronrsmith** [comment]
yea node v12 has dynamic heap adjustment. I'll bump the **Dockerfile** since this seems to be a common issue. i.e This can still be a problem if the heap size is allocated slower than it's resized or if the box actually ran out of space.
