### ISSUE TITLE
[BUG] dump with option 'offset' report an action_request_validation_exception

### ISSUE THREAD

**Issue by GhostedProgramer** [taskrabbit/elasticsearch-dump#629]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version 6.14.1
- Elasticsearch version 6.5.4
- Node.js version *(note that nodejs v8+ is required for this tool)* 
- Full command you are having issue with (with inputs and outputs) elasticdump --input=http://118.31.158.220:9200/dcrelease --output=http://121.199.120.234:9200/dcrelease --type=data --offset=100
- A data-set you can share publicly which reproduces the problem

**Describe the bug**
Error Emitted => {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: using [from] is not allowed in a scroll context;"},"status":400}
**To Reproduce**

**Current behavior**
Describe what's happening now.

**Expected behavior**

**Screenshots**

**Additional context**

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
Offset isn't support in scroll queries since ES v6. 

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html#_scroll

**Comment by GhostedProgramer** [comment]
I know this, but could you please teach me how can I use another attribute to replace '--offset' to skip ahead from the input transport, I will be very grateful

**Comment by GhostedProgramer** [comment]
> 
> 
> Offset isn't supported in scroll queries since ES v6.
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html#_scroll

I know this, but could you please teach me how can I use another attribute to replace '--offset' to skip ahead from the input transport, I will be very grateful
