### ISSUE TITLE
[BUG] elasticdump v. 6.15.4 only supports Node.js 10+

### ISSUE THREAD

**Issue by PeledYuval** [taskrabbit/elasticsearch-dump#630]
- ElasticDump version: 6.15.4
- Elasticsearch version: irrelevant
- Node.js version: 8.15.0
- Full command you are having issue with: `elasticdump --output http://localhost:9200/someIndex --input=fileName`
- A data-set you can share publicly which reproduces the problem: irrelevant

**Describe the bug**
When running the simple command `elasticdump --output=... --input=...` on Node.js v8, I get the following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:214:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:9:28)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

**Additional context**
The problem is with this change:
https://github.com/taskrabbit/elasticsearch-dump/commit/ec1e96b65492f57bda4a6de927afc93014fd8918#diff-f60b04ac83f174b93b06625be32a86f5R9
It adds use of Node.js's built in stream.pipeline function that was only added to Node v10, as can be seen here:
https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback

I'm not sure if this is a bug since I couldn't find the minimal version of Node.js that elasticdump targets.
If elasticdump targets Node.js 10+ then I would add that to its readme.md and would bump the major version number to 7 since this is a breaking change.
If this is an unintentional bug then I would recommend running elasticdump's CI tests on the minimal targeted Node.js version to catch bugs like this.

**Comment by ferronrsmith** [comment]
That's an error my part.

**Comment by PeledYuval** [comment]
Thanks for the swift response and fix!

**Comment by JonnyJD** [comment]
It looks like the support of nodejs 8 was removed now with c9c66a64e316c4f7cf5c5e5b5b08dc5c2a23ecdc
so starting with elasticdump 6.32.0 nodejs 10 is required.

**Comment by MajPay** [comment]
Just crashed into this. Provisioned a VM with Ubuntu 18.04, nodejs and npm are installed via apt (version 8.10.0) and elasticdump is installed via npm. Results in this error.

So you have to: Either install a fixed version of elasticdump or a fixed version of nodejs.

In my case:
```npm i -g elasticdump@6.15.5```

**Comment by ferronrsmith** [comment]
I dropped support for node version lower than 10. Use 6.31.5 or lowered

**Comment by iTaybb** [comment]
Is it possible to unpublish/block versions greater than 6.31.5 for node v8?
currently, when using node v8, simply running `npm i elasticdump` results in a broken installation.

**Comment by ferronrsmith** [comment]
That's a function of the **npm cli** not **elasticdump**. They don't enforce engine restrictions, so there isn't much I can do.

> i.e. I did add a note to the README.md

**Comment by PeledYuval** [comment]
@ferronrsmith my small 2 cents on this issue are that changing minimal node version should change the package's major version to 7

**Comment by ferronrsmith** [comment]
I could have done this, but I didn't want to at the time.

**Comment by xdanx** [comment]
Please, can you at least add a warning in elasticdump if node version is too old so we don't search like crazy for this error?

**Comment by ferronrsmith** [comment]
yea sure! I'll do that now

**Comment by ferronrsmith** [comment]
Ok done, from v 6.67.0 onward. If the node version doesn't match the engine restrictions specified in the `package.json` `elasticsearch-dump` will quit with an error and inform the user the node version it too low.
