### ISSUE TITLE
require http

### ISSUE THREAD

**Issue by hackerman234** [taskrabbit/elasticsearch-dump#635]
```./elasticdump.js: line 1: syntax error near unexpected token `('
./elasticdump.js: line 1: `const http = require('http')'```

running the tool i get this error here is my command
```
./elasticdump.js \  --input=http://10.10.10.115:9200/quotes \  --output=quptes.json \  --type=data
```

**Comment by ferronrsmith** [comment]
`#!/usr/bin/env node` is line one, which means u must be running in a shell (i.e cmd doesn't count a real shell) or use the docker image

**Comment by hackerman234** [comment]
ah thanks!
