### ISSUE TITLE
Issue with running inside docker

### ISSUE THREAD

**Issue by ashwilson** [taskrabbit/elasticsearch-dump#636]
HI, 

I recevice the following error while trying to run against an elastic.co cluster (6.8.3):
`Sat, 09 Nov 2019 10:16:07 GMT | starting dump
(node:1) UnhandledPromiseRejectionWarning: Error: Pipeline failed
    at file.setupGet (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:44:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
I was using the instructions for docker as shown:
`docker run --rm -ti -v /data:/tmp taskrabbit/elasticsearch-dump \
  --input=https:/${USER}:${PWD}@${HOST}/${INDEX} \
  --output=/tmp/my_index_mapping.json \
  --type=data
`

Also, I got an error with the `input` option when using `https://`:
`Sat, 09 Nov 2019 10:23:58 GMT | starting dump
Sat, 09 Nov 2019 10:23:58 GMT | Error Emitted => Invalid URI "https:///"
Sat, 09 Nov 2019 10:23:58 GMT | Error Emitted => Invalid URI "https:///"
Sat, 09 Nov 2019 10:23:58 GMT | Total Writes: 0
Sat, 09 Nov 2019 10:23:58 GMT | dump ended with error (get phase) => Error: Invalid URI "https:///"
`

I have given the cluster user read privaleges (read, monitor, view_index_metadata) to the indexes; is there anything else required?

Thanks.

**Comment by ferronrsmith** [comment]
The url is invalid. http://

**Comment by ferronrsmith** [comment]
Also there isn’t enough information here. 
1. What version of elasticdump are you using ? 
1. What is the full command run in both cases ? 
1. Steps to replicate the issue must be provided

**Comment by ashwilson** [comment]
I used the docker command with my own variables in the readme as described in my original comment:
`taskrabbit/elasticsearch-dump           latest                   be995f1e7a2e        11 days ago         143MB`
```
docker run --rm -ti -v /data:/tmp taskrabbit/elasticsearch-dump \
  --input=https://${USER}:${PWD}@${HOST}/${INDEX} \
  --output=/tmp/my_index_mapping.json \
  --type=data
```

**Comment by ferronrsmith** [comment]
Explain to me how is it that someone would be able to replicate your issue from what you post ?

FYI : You need to ensure the basic auth is URL encoded to avoid issues.

> A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What was the url? What steps will reproduce the issue? What OS experience the problem? All these details will help to fix any potential bugs as soon as possible.

**Comment by ferronrsmith** [comment]
check https://github.com/taskrabbit/elasticsearch-dump/issues/335
