### ISSUE TITLE
[BUG]Request Entity Too Large

### ISSUE THREAD

**Issue by yufengnian** [taskrabbit/elasticsearch-dump#637]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version
- Elasticsearch version 5.4
- Node.js version v8.15.0

 elasticdump --input=http://localhost:9200/demo1 --output=http://romote:9200/demo1 --type=data --limit=2000

Wed, 13 Nov 2019 15:43:25 GMT | starting dump
Wed, 13 Nov 2019 15:43:26 GMT | got 2000 objects from source elasticsearch (offset: 0)
Wed, 13 Nov 2019 15:43:27 GMT | Error Emitted => <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty</center>
</body>
</html>

**Comment by ferronrsmith** [comment]
This is a Elasticsearch issue. You need to increase the `http.max_content_length` value

**Comment by yufengnian** [comment]
OK   thanks
