### ISSUE TITLE
[BUG] fileSize doesn't seem to have effect when output is S3

### ISSUE THREAD

**Issue by artdgn** [taskrabbit/elasticsearch-dump#638]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.15.7 (in docker)
- Elasticsearch version: 5.1
- Node.js version *(note that nodejs v8+ is required for this tool)*: running in docker
- Full command you are having issue with (with inputs and outputs): 
```
docker run --rm -it --net=host  \
    -v $(realpath ~)/.aws:/root/.aws \
    taskrabbit/elasticsearch-dump  \
    --input=http://localhost:9200/my-index \
    --output="s3://my-bucket/folder/index.json" \
    --type=data \
    --overwrite \
    --fileSize 10mb \
    --sourceOnly=true  \
    --maxSockets=50 \
    --limit=10000
```

**Describe the bug**
A clear and concise description of what the bug is:
As far as I can see from the documentation it looks like fileSize argument should split files when writing to S3. Instead it creates a single file (in my case multiple GBs).
When writing to disk the parameter works as expected.

**Comment by ferronrsmith** [comment]
```
--fileSize  supports file splitting.... (truncated for brevity)
```

This isn't a bug, it's not supported.

**Comment by artdgn** [comment]
@ferronrsmith Thanks for the super quick reply. Perhaps worth to reword the docs, because I've read it again, and it doesn't specify that file is strictly a file-system-local-disk file and not an S3 destination with a file path and file name.
