### ISSUE TITLE
[BUG] OOM when dumping large index to S3

### ISSUE THREAD

**Issue by artdgn** [taskrabbit/elasticsearch-dump#639]
Following up from https://github.com/taskrabbit/elasticsearch-dump/issues/638

**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.15.7 (in docker)
- Elasticsearch version: 5.1
- Node.js version *(note that nodejs v8+ is required for this tool)*: running in docker
- Full command you are having issue with (with inputs and outputs): 
```
docker run --rm -it --net=host  \
    -v $(realpath ~)/.aws:/root/.aws \
    taskrabbit/elasticsearch-dump  \
    --input=http://localhost:9200/my-index \
    --output="s3://my-bucket/folder/index.json" \
    --type=data \
    --overwrite \
    --sourceOnly=true  \
    --maxSockets=50 \
    --limit=10000
```

**Describe the bug**
A clear and concise description of what the bug is:
When specifying S3 as output for an index that's larger than the machine's memory - the machine runs out of memory and the process crushes.
The only workaround I've found is writing to disk and than uploading to S3. However, this should solve the problem only for sizes of indeces that fit on the local disk. Is there a truly streaming solution / workaround?

**Comment by ferronrsmith** [comment]
This isn't really a bug per say, this is just the natural limitation of the machine. You can use `NODE_OPTIONS="--max-old-space-size=16384` or use the PR I just added https://github.com/taskrabbit/elasticsearch-dump/pull/640, which adds stream split support to s3.

**Comment by ferronrsmith** [comment]
i.e. This will be merged soon, just requires a bit more testing.

**Comment by ferronrsmith** [comment]
elasticdump v6.16.0 now supports fileSize with s3

**Comment by artdgn** [comment]
Amazing turn around time @ferronrsmith , thanks! 
Tested on my use-case and seems to be working as expected :+1:
