### ISSUE TITLE
No help output

### ISSUE THREAD

**Issue by p-run** [taskrabbit/elasticsearch-dump#64]
Current:

<pre>
% elasticdump -h
Wed, 28 Jan 2015 00:39:04 GMT | starting dump
Wed, 28 Jan 2015 00:39:04 GMT | connect ECONNREFUSED
Wed, 28 Jan 2015 00:39:04 GMT | got 0 objects from source elasticsearch (offset: 0)
Wed, 28 Jan 2015 00:39:04 GMT | sent 0 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 00:39:04 GMT | dump complete

% elasticdump --help
Wed, 28 Jan 2015 00:39:17 GMT | starting dump
Wed, 28 Jan 2015 00:39:17 GMT | connect ECONNREFUSED
Wed, 28 Jan 2015 00:39:17 GMT | got 0 objects from source elasticsearch (offset: 0)
Wed, 28 Jan 2015 00:39:17 GMT | sent 0 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 00:39:17 GMT | dump complete
</pre>

Expected:

Some form of help output explaining usage and listing available options.

Also, the above output suggests that invalid options are simply ignored, which is probably not a good behavior.

Readme says `--input` and `--output` options are required, yet this does not seem to be the case. What is the default output?

**Comment by evantahler** [comment]
Good ideas! 

https://github.com/taskrabbit/elasticsearch-dump/pull/65

**Comment by evantahler** [comment]
Closing in favor of the pull request.
