### ISSUE TITLE
[BUG]Something Network error

### ISSUE THREAD

**Issue by shintaro-hz** [taskrabbit/elasticsearch-dump#642]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.16.0
- Elasticsearch version : From 6.4.2(ES in localnetwork) To 7.1.1(AWS ES behind proxy)
- Node.js version :v8.16.2

**Describe the bug**
[root@elasticdump ~]# elasticdump \ 
--input=http://172.XX.XXX.XXX:9200/index \
--output=https://XXXXXX.es.amazonaws.com/index

Wed, 27 Nov 2019 04:17:18 GMT | starting dump
Wed, 27 Nov 2019 04:17:18 GMT | got 100 objects from source elasticsearch (offset: 0)
Wed, 27 Nov 2019 04:17:38 GMT | Error Emitted => tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
Wed, 27 Nov 2019 04:17:38 GMT | Error Emitted => tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
Wed, 27 Nov 2019 04:17:38 GMT | Total Writes: 0
Wed, 27 Nov 2019 04:17:38 GMT | dump ended with error (get phase) => Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

**Current behavior**
I want to migrate index of ES in local to AWS ES. But It can not work well as shown above.

AWS ES needs proxy to resolve domain name but local ES does not need to.
So I set proxy and no proxy as shown bellow.

export http_proxy="http://ID:PW@IP:PORT"
export https_proxy="http://ID:PW@IP:PORT"

export no_proxy="127.0.0.1,localhost,IP for ES"
export NO_PROXY="$no_proxy"

I can get right responses from both ES local and AWS by curl command like this.
{
  "name" : "node3",
  "cluster_name" : "es-cluster",
  "cluster_uuid" : "n4GrebxNRSeCT8gUxMjG_g",
  "version" : {
    "number" : "6.4.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

I could migrate local to AWS the other day.

**Comment by ferronrsmith** [comment]
The error says it cannot connect to a socket on port 80. Not sure what the error is...

**Comment by shintaro-hz** [comment]
It might be that the domain name of AWS ES can not be resolved.
So please tell me how to set proxy for elasticdump.

**Comment by ferronrsmith** [comment]
This isn't an ES dump issue.

process.env.http_proxy = 'http://proxy.example.com:<port>';
