### ISSUE TITLE
[BUG]UnhandledPromiseRejectionWarning: Error: Pipeline failed

### ISSUE THREAD

**Issue by natee1992** [taskrabbit/elasticsearch-dump#643]
**
(node:1) UnhandledPromiseRejectionWarning: Error: Pipeline failed
    at file.setupGet (/usr/local/lib/node_modules/elasticdump/lib/transports/file.js:44:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**

- ElasticDump lastest
- Elasticsearch 7.1.1

**Comment by ferronrsmith** [comment]
There isn't any information in the issue and the promise is already handled in a try/catch block

**Comment by natee1992** [comment]
sorry,i got the problem,because when i import data to es,my test-es run in docker,so i need to import use docker network ,and i need to make a volume because es-dump also run in docker

**Comment by ferronrsmith** [comment]
👍🏾. No worries
