### ISSUE TITLE
restore setting and analyzer failed

### ISSUE THREAD

**Issue by GerryLon** [taskrabbit/elasticsearch-dump#646]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.16.0
- Elasticsearch version: 7.3.1
- Node.js version *(note that nodejs v8+ is required for this tool)*: v12.13.1
- Full command you are having issue with (with inputs and outputs)
    ```bash
   elasticdump \
		--limit 500 \
		--concurrency 10 \
		--input=2019-12-03-settings.json \
		--output=http://my-es.com \
		--type=settings

   elasticdump \
		--limit 500 \
		--concurrency 10 \
		--input=2019-12-03-analyzer.json \
		--output=http://my-es.com \
		--type=analyzer
   ```

- Error log
```

Tue, 03 Dec 2019 09:53:53 GMT | starting dump
Tue, 03 Dec 2019 09:53:53 GMT | got 1 objects from source file (offset: 0)
Tue, 03 Dec 2019 09:53:53 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, GET, HEAD]","status":405}
Tue, 03 Dec 2019 09:53:53 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, GET, HEAD]","status":405}
Tue, 03 Dec 2019 09:53:53 GMT | Total Writes: 0
Tue, 03 Dec 2019 09:53:53 GMT | dump ended with error (get phase) => Error: {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [DELETE, GET, HEAD]","status":405}
restore failed on log-2019-12-03-analyzer.json

Tue, 03 Dec 2019 09:55:11 GMT | starting dump
Tue, 03 Dec 2019 09:55:11 GMT | got 1 objects from source file (offset: 0)
Tue, 03 Dec 2019 09:55:11 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
Tue, 03 Dec 2019 09:55:11 GMT | Error Emitted => {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
Tue, 03 Dec 2019 09:55:11 GMT | Total Writes: 0
Tue, 03 Dec 2019 09:55:11 GMT | dump ended with error (get phase) => Error: {"error":"Incorrect HTTP method for uri [/] and method [PUT], allowed: [HEAD, GET, DELETE]","status":405}
restore failed on 2019-12-03-settings.json
```

**Please Note**:
- both **2019-12-03-settings.json** and **2019-12-03-analyzer.json** are exported by elasticdump, not written by hand(their format is correct).
- data, mapping, alias and template were imported successfully!

**Comment by ferronrsmith** [comment]
Need to see the output file, because I tested this and could not replicate the issue.

**Comment by ferronrsmith** [comment]
Can't reproduce the issue and there isn't much information provided. Please re-open when you have more info

**Comment by archfz** [comment]
I have this issue as well. Data in output file start like this `"{\".apm-custom-link\":{\"settings\":{\"index\":{\"routing\":{\"allo`

**Comment by archfz** [comment]
ELK_VERSION=7.11.2
node.js=14.16.0
ElasticDump=6.68.0

Trying to export what `filebeat setup` generates.

**Comment by ferronrsmith** [comment]
> I have this issue as well. Data in output file start like this `"{\".apm-custom-link\":{\"settings\":{\"index\":{\"routing\":{\"allo`

This doesn't really help in reproducing your issue.

**Comment by ferronrsmith** [comment]
> **NB: Exporting settings & analyzer is redundant. The both pull from the same endpoint. Restoring the settings will restore the analyzers.**

**Comment by archfz** [comment]
So basically what I did is that I export everything in kibana and use this tool to export mapping from elastic. But when I import back the indices are missing. I tought that I need to export/import the analyzer type to make it work. 

 I cant really provide a repo to reproduce but I could provide a list of steps to setup and reproduce.

**Comment by ferronrsmith** [comment]
Not repo, the mapping would suffice and the process. If you want to change names etc, that would help. As it stands there isn't enough info to say what the issue is.

**Comment by archfz** [comment]
OK here are the steps:
1. clone https://github.com/deviantony/docker-elk
2. create `elasticsearch/analyzers.json` from https://pastebin.com/pr0tYMxw
3. add the following in the `elasticsearch/Dockerfile`
   ```dockerfile

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash \
    && . ~/.bashrc \
    && nvm install 14.16.0 \
    && npm install elasticdump -g
ENV PATH="$PATH:/root/.nvm/versions/node/v14.16.0/bin"

COPY ./analyzers.json /analyzers.json

   ```
4. `docker-compose up -d --build`
5. `docker-compose exec elasticsearch bash`
6. `elasticdump --output http://elastic:changeme@localhost:9200 --input /analyzers.json --type analyzer`
7. Observe the issue.

**Comment by ferronrsmith** [comment]
The problem here is you did a dump of the entire index settings and then tried to import it using elasticdump, but it's actually in an incompatible format.

Settings/Analyzers are per index configurations. You're trying to apply a bulk setting. (which also has invalid data present)

**Comment by archfz** [comment]
Ok thanks for your time. I taught this would work to export and import all from one command. The project documentation should contain this limitation.

**Comment by archfz** [comment]
In any case do you know what is the easiest way to share between environment all kibana settings and elastic index settings and mappings (no data) (in context of elk).

**Comment by ferronrsmith** [comment]
you could use `multielasticdump` command to export all settings/mappings from one environment to the next then import it into another.

https://github.com/elasticsearch-dump/elasticsearch-dump#multielasticdump
