### ISSUE TITLE
[FEATURE] limit the multielasticdump index matching by time or if index has changed

### ISSUE THREAD

**Issue by gschaden** [taskrabbit/elasticsearch-dump#650]
I want to backup all my data from an elasticsearch cluster. My indices are organized in indices one per day in the form index-2019.12.09. 
It would be fine to just dump yesterdays dump, but it is possible that I get late logging data. So I do not know when "all" logging data is in place. So I could dump the last 2 or 3 days, but that consumes a lot of bandwidth. 
Actually I would like to export only changed indices. 

There is no easy way to get the last modification date of an index, maybe it is possible to store shard commit ids with the dump to be able to detect changes. For simple add only indices a document count comparison could be sufficient.

**Comment by ferronrsmith** [comment]
Unless you store some kind of `update_at` timestamp value inside the index, it's not possible. At least not that I'm aware of. Older versions of ES supported `_timestamp`, but that's now being deprecated, so the user has to manage this value.

It's possible to just wait until you know when all the data has been logged for the day to run the dump. (Not efficient, but it works)

**Comment by ferronrsmith** [comment]
closing this; it's not a feature that can easily be added to elastic dump.
