### ISSUE TITLE
[FEATURE] Quiet mode for MultiElasticDump

### ISSUE THREAD

**Issue by revelnode** [taskrabbit/elasticsearch-dump#652]
**Describe the solution you'd like**
Currently, the --quiet flag does not work on MultiElasticDump mode.  This would definitely be an asset for those wishing to log only errors, as we have over 100 million docs we export, and the log file each run runs about 5 MB in size every run, which is excessive when it contains no relevant info.

**Describe alternatives you've considered**
On windows I could port to `| Out-Null` however this would suppress errors.

**Give some examples of implementations**
`multielasticdump --direction=dump  --match='^.*_mainpc$' --input=http://my-eleasticsearch-cluster:9200  --output=D:\ES-BACKUP\Backup-files --limit 7500 --quiet`

**Comment by ferronrsmith** [comment]
added in `6.16.2`  https://github.com/taskrabbit/elasticsearch-dump/commit/e223330236008538675ce6cc29abd03a848a61b1
