### ISSUE TITLE
[BUG]--offset seems not work

### ISSUE THREAD

**Issue by codeboytj** [taskrabbit/elasticsearch-dump#658]
- ElasticDump version 6.16.2
- Elasticsearch version
- Node.js version: v8.11.2

I start dump by with a --offset option after last dump crash: 

```
elasticdump --input=foo --output=bar --type=data --offset=21690000 --limit=10000 --concurrency=5
```
but I get an ERROR:

```
 Mon, 20 Jan 2020 12:54:22 GMT | Error Emitted => {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Batch size is too large, size must be less than or equal to: [10000] but was [21700000]......
```

It seems like elasticdump want to dump 21700000 rows because I set offset as 21690000. But I just want to dump from 21690000 to 21700000, it just 10000 rows.

**Comment by ferronrsmith** [comment]
https://github.com/taskrabbit/elasticsearch-dump#notes

__if you are using Elasticsearch version 6.0.0 or higher the offset parameter is no longer allowed in the scrollContext__

**Comment by Moulde** [comment]
I have the exact same issue in ES 5.6 - i'm trying to continue a dump that crashed.
How is this not a bug? It seems like the limit value is not used, and instead it uses the offset + the specified limit as the size argument?

Last log before it failed
`got 10000 objects from source elasticsearch (offset: 1130000)`

Tried adding the "--offset 1130000" parameter to the dump command, but I also get the same error.

`Batch size is too large, size must be less than or equal to: [10000] but was [1140000]`

**Comment by ferronrsmith** [comment]
Try adjusting 'index.max_result_window', it defaults to 10k. Ideally offset shouldn't be used
