### ISSUE TITLE
Authenticate and authorize against Cognito-protected Elasticsearch cluster

### ISSUE THREAD

**Issue by dirkgomez** [taskrabbit/elasticsearch-dump#659]
I'm trying to dump an Elastic cluster index stored in AWS that is protected by Cognito and accessible via a VPC endpoint.

What is the correct way to allow elasticdump to authenticate and authorize in that scenario? I've tried the available aws options and AWS_PROFILE, to no avail. Error messages are either:

{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}
{"Message":"User: arn:aws:sts::12345678:assumed-role/GroupName/MyEmail is not authorized to perform: es:ESHttpGet"}
{"message":"The security token included in the request is expired"}

Elasticdump version: 6.18.0
Elasticsearch: 7.1 (AWS managed service)
Node: v13.6.0

**Comment by ferronrsmith** [comment]
I don't think authenticated via Cognito is supported. I don't use AWS services so I don't have much insight into this. All the AWS work done was either contributed or access provided for feature development.

If you submit a PR, I'll consider merging, thanks for using elasticsearch-dump

**Comment by dirkgomez** [comment]
Here's how I managed to get access:

- I created a role that allows for access to the elasticsearch cluster in question
- I ran aws sts assume-role to assume said role, it prints AccessKeyId, SecretAccessKey, SessionToken
- I took those as parameters for --awsAccessKeyId, --awsSecretAccessKey, --sessionToken

Thanks a lot!

**Comment by ferronrsmith** [comment]
Thanks for sharing. this will be helpful to someone else 👍

**Comment by AdSoNaTuRaL** [comment]
Useful for me, thanks @dirkgomez and @ferronrsmith
