### ISSUE TITLE
Where did my data go?

### ISSUE THREAD

**Issue by p-run** [taskrabbit/elasticsearch-dump#66]
I used:

<pre>
% zcat elasticsearch-dump.json.gz| elasticdump --input=\$ --output=http://localhost:9200/       
Wed, 28 Jan 2015 17:40:21 GMT | starting dump
Wed, 28 Jan 2015 17:40:22 GMT | got 9003 objects from source stdio (offset: 0)
Wed, 28 Jan 2015 17:41:38 GMT | sent 9003 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:41:39 GMT | got 9168 objects from source stdio (offset: 9003)
Wed, 28 Jan 2015 17:42:55 GMT | sent 9168 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:42:56 GMT | got 9319 objects from source stdio (offset: 18171)
Wed, 28 Jan 2015 17:44:14 GMT | sent 9319 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:44:15 GMT | got 9223 objects from source stdio (offset: 27490)
Wed, 28 Jan 2015 17:45:32 GMT | sent 9223 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:45:34 GMT | got 9084 objects from source stdio (offset: 36713)
Wed, 28 Jan 2015 17:46:50 GMT | sent 9084 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:46:52 GMT | got 9201 objects from source stdio (offset: 45797)
Wed, 28 Jan 2015 17:48:09 GMT | sent 9201 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:48:10 GMT | got 9039 objects from source stdio (offset: 54998)
Wed, 28 Jan 2015 17:49:26 GMT | sent 9039 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:49:27 GMT | got 9050 objects from source stdio (offset: 64037)
Wed, 28 Jan 2015 17:50:43 GMT | sent 9050 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:50:45 GMT | got 9176 objects from source stdio (offset: 73087)
Wed, 28 Jan 2015 17:52:01 GMT | sent 9176 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:52:02 GMT | got 9078 objects from source stdio (offset: 82263)
Wed, 28 Jan 2015 17:53:18 GMT | sent 9078 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:53:20 GMT | got 9127 objects from source stdio (offset: 91341)
Wed, 28 Jan 2015 17:54:36 GMT | sent 9127 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:54:37 GMT | got 9110 objects from source stdio (offset: 100468)
Wed, 28 Jan 2015 17:55:53 GMT | sent 9110 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:55:55 GMT | got 9105 objects from source stdio (offset: 109578)
Wed, 28 Jan 2015 17:57:11 GMT | sent 9105 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:57:12 GMT | got 9202 objects from source stdio (offset: 118683)
Wed, 28 Jan 2015 17:58:30 GMT | sent 9202 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:58:31 GMT | got 8902 objects from source stdio (offset: 127885)
Wed, 28 Jan 2015 17:59:46 GMT | sent 8902 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 17:59:47 GMT | got 8889 objects from source stdio (offset: 136787)
Wed, 28 Jan 2015 18:01:02 GMT | sent 8889 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:01:03 GMT | got 8882 objects from source stdio (offset: 145676)
Wed, 28 Jan 2015 18:02:17 GMT | sent 8882 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:02:19 GMT | got 8888 objects from source stdio (offset: 154558)
Wed, 28 Jan 2015 18:03:33 GMT | sent 8888 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:03:34 GMT | got 8864 objects from source stdio (offset: 163446)
Wed, 28 Jan 2015 18:04:49 GMT | sent 8864 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:04:50 GMT | got 8885 objects from source stdio (offset: 172310)
Wed, 28 Jan 2015 18:06:05 GMT | sent 8885 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:06:07 GMT | got 8920 objects from source stdio (offset: 181195)
Wed, 28 Jan 2015 18:07:22 GMT | sent 8920 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:07:23 GMT | got 8887 objects from source stdio (offset: 190115)
Wed, 28 Jan 2015 18:08:38 GMT | sent 8887 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:08:39 GMT | got 8844 objects from source stdio (offset: 199002)
Wed, 28 Jan 2015 18:09:54 GMT | sent 8844 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:09:55 GMT | got 8890 objects from source stdio (offset: 207846)
Wed, 28 Jan 2015 18:11:10 GMT | sent 8890 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:11:11 GMT | got 8886 objects from source stdio (offset: 216736)
Wed, 28 Jan 2015 18:12:25 GMT | sent 8886 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:12:26 GMT | got 8915 objects from source stdio (offset: 225622)
Wed, 28 Jan 2015 18:13:41 GMT | sent 8915 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:13:42 GMT | got 8911 objects from source stdio (offset: 234537)
Wed, 28 Jan 2015 18:14:57 GMT | sent 8911 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:14:58 GMT | got 8925 objects from source stdio (offset: 243448)
Wed, 28 Jan 2015 18:16:13 GMT | sent 8925 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:16:14 GMT | got 8961 objects from source stdio (offset: 252373)
Wed, 28 Jan 2015 18:17:30 GMT | sent 8961 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:17:31 GMT | got 8944 objects from source stdio (offset: 261334)
Wed, 28 Jan 2015 18:18:46 GMT | sent 8944 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:18:48 GMT | got 8944 objects from source stdio (offset: 270278)
Wed, 28 Jan 2015 18:20:03 GMT | sent 8944 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:20:04 GMT | got 8940 objects from source stdio (offset: 279222)
Wed, 28 Jan 2015 18:21:19 GMT | sent 8940 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:21:21 GMT | got 9016 objects from source stdio (offset: 288162)
Wed, 28 Jan 2015 18:22:36 GMT | sent 9016 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:22:38 GMT | got 8882 objects from source stdio (offset: 297178)
Wed, 28 Jan 2015 18:23:52 GMT | sent 8882 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:23:54 GMT | got 9508 objects from source stdio (offset: 306060)
Wed, 28 Jan 2015 18:25:14 GMT | sent 9508 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:25:15 GMT | got 9016 objects from source stdio (offset: 315568)
Wed, 28 Jan 2015 18:26:31 GMT | sent 9016 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:26:32 GMT | got 8903 objects from source stdio (offset: 324584)
Wed, 28 Jan 2015 18:27:47 GMT | sent 8903 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:27:48 GMT | got 8935 objects from source stdio (offset: 333487)
Wed, 28 Jan 2015 18:29:03 GMT | sent 8935 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:29:05 GMT | got 8993 objects from source stdio (offset: 342422)
Wed, 28 Jan 2015 18:30:20 GMT | sent 8993 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:30:22 GMT | got 8887 objects from source stdio (offset: 351415)
Wed, 28 Jan 2015 18:31:36 GMT | sent 8887 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:31:38 GMT | got 8930 objects from source stdio (offset: 360302)
Wed, 28 Jan 2015 18:32:53 GMT | sent 8930 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:32:54 GMT | got 8977 objects from source stdio (offset: 369232)
Wed, 28 Jan 2015 18:34:09 GMT | sent 8977 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:34:10 GMT | got 5932 objects from source stdio (offset: 378209)
Wed, 28 Jan 2015 18:35:00 GMT | sent 5932 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:35:01 GMT | got 8953 objects from source stdio (offset: 384141)
Wed, 28 Jan 2015 18:36:17 GMT | sent 8953 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:36:18 GMT | got 8965 objects from source stdio (offset: 393094)
Wed, 28 Jan 2015 18:37:33 GMT | sent 8965 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:37:34 GMT | got 8922 objects from source stdio (offset: 402059)
Wed, 28 Jan 2015 18:38:49 GMT | sent 8922 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:38:50 GMT | got 8947 objects from source stdio (offset: 410981)
Wed, 28 Jan 2015 18:40:06 GMT | sent 8947 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:40:07 GMT | got 8907 objects from source stdio (offset: 419928)
Wed, 28 Jan 2015 18:41:22 GMT | sent 8907 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:41:23 GMT | got 8891 objects from source stdio (offset: 428835)
Wed, 28 Jan 2015 18:42:38 GMT | sent 8891 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:42:39 GMT | got 9028 objects from source stdio (offset: 437726)
Wed, 28 Jan 2015 18:43:55 GMT | sent 9028 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:43:56 GMT | got 8968 objects from source stdio (offset: 446754)
Wed, 28 Jan 2015 18:45:11 GMT | sent 8968 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:45:12 GMT | got 8944 objects from source stdio (offset: 455722)
Wed, 28 Jan 2015 18:46:26 GMT | sent 8944 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:46:27 GMT | got 8929 objects from source stdio (offset: 464666)
Wed, 28 Jan 2015 18:47:42 GMT | sent 8929 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:47:43 GMT | got 8883 objects from source stdio (offset: 473595)
Wed, 28 Jan 2015 18:48:58 GMT | sent 8883 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:48:59 GMT | got 8929 objects from source stdio (offset: 482478)
Wed, 28 Jan 2015 18:50:14 GMT | sent 8929 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:50:16 GMT | got 9004 objects from source stdio (offset: 491407)
Wed, 28 Jan 2015 18:51:31 GMT | sent 9004 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:51:32 GMT | got 8995 objects from source stdio (offset: 500411)
Wed, 28 Jan 2015 18:52:48 GMT | sent 8995 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:52:49 GMT | got 3234 objects from source stdio (offset: 509406)
Wed, 28 Jan 2015 18:53:16 GMT | sent 3234 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:53:16 GMT | got 0 objects from source stdio (offset: 512640)
Wed, 28 Jan 2015 18:53:16 GMT | sent 0 objects to destination elasticsearch, wrote 0
Wed, 28 Jan 2015 18:53:16 GMT | dump complete
</pre>

Now when I try to see my indexes:

<pre>
% curl 'localhost:9200/_cat/indices?v'
health status index pri rep docs.count docs.deleted store.size pri.store.size 
</pre>

Where was the data loaded?

**Comment by evantahler** [comment]
notice how each line says "wrote 0".  That means it wrote 0 lines to your desintantison.  You need to provide an index, ie: `http://localhost:9200/some_index`.

**Comment by p-run** [comment]
Thanks, but, I have some follow-up questions then:

1. Why does elasticdump keep going when writes are failing?
2. Why does the entire process take over an hour for a ~350 mb file?
3. My dump file has multiple indexes as I dumped it with `elasticdump --input=http://localhost:9200/5000_\* --output=\$`. How do I load this file into the same indexes it came from?

**Comment by evantahler** [comment]
1) The tool will keep writing because it's very possible that certain transports want to allow for partial writes.  If you want, a pull request would be useful to default this to alert_and_crash rather than proceed, it's rare that a transport requires this.
2) You are still making that many HTTP requests (one per object), even if they are failing.  That takes time.
3) use the `--all` flag when you expect to manipulate more than one index/all indexes.  This is generally unsafe because it may clobber data in many/all indexes.

**Comment by p-run** [comment]
Regarding 1: The impression I am getting is loading a dump which was created without using --all=true without specifying a destination index is a usage error, in that this will never work. If my understanding is correct then elasticdump should detect this situation and abort the operation with a sensible error message.

Regarding 2: I see that there is a bulk flag, which by default is off. If bulk mode would work for me, why is it off by default? In which situations is bulk mode not going to work?

Regarding 3: elasticdump runs out of memory and dies when I ask it to dump all of my data:

<pre>
$ elasticdump  --input=http://localhost:9200/ --output=\$ --all=true |gzip > elasticsearch-dump.json.gz
FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory
ubuntu@staging:~$ Write failed: Broken pipe
</pre>

So this does not work at all.

I am still unclear how to load a dump which contains multiple indexes - does elasticdump produce dumps which it is then incapable of loading back into elasticsearch?
