### ISSUE TITLE
[FEATURE] Clear scroll is not implemented

### ISSUE THREAD

**Issue by StephaneBour** [taskrabbit/elasticsearch-dump#660]
Each scroll created by elasticdump is not destroyed. This is problematic when we wait for the limit on the nodes of "search.current_scroll".

It would remove the scroll at the end of the script

https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#_clear_scroll_api

**Comment by ferronrsmith** [comment]
`Search context are automatically removed when the scroll timeout has been exceeded.`

The default scrollTime is 10m, you can configure it to a much lower. Feel free to submit a PR if you're still not comfortable with the default limits and I'd be happy to merge it.

**Comment by StephaneBour** [comment]
Ok, thank you. I'm not comfortable with javascript but i will try.

**Comment by ferronrsmith** [comment]
You could try reducing the scrollTime, that usually fixes most users issues. If that doesn’t work then you can go ahead and implement the problem is, to implement scroll delete I’d need to keep track of all scroll IDs

**Comment by StephaneBour** [comment]
I especially think that it is cleaner to delete what is created by the application, rather than going to play on the parameters.

I started working on it.

**Comment by ferronrsmith** [comment]
the choice is ultimately yours at the end of the day, but seeing that Elastic provides the option then I think it's safe to use. Awaiting your PR. 

Happy coding
