### ISSUE TITLE
AWS auth failing due to missing service

### ISSUE THREAD

**Issue by mikepalfrey** [taskrabbit/elasticsearch-dump#661]
Hi all,

I've replicated this issue on the latest code from master.

I'm experiencing some issues using Elasticdump to create a dump of an index from AWS ES. My AWS Elasticsearch instance is secured using IAM roles, so I end up authenticating and then switching roles to the one used for the service.

Once done, I provide the following to Elasticdump:

`./elasticdump --input <INDEX_URL> --output index.json --awsAccessKeyId <AWS_ACCESS_KEY> --awsSecretAccessKey <AWS_SECRET> --sessionToken <AWS_SESSION_TOKEN>`

Upon running this I see the following error:

`Sun, 26 Jan 2020 14:27:17 GMT | Error Emitted => {"message":"Credential should be scoped to correct service: 'es'. "}
Sun, 26 Jan 2020 14:27:17 GMT | Error Emitted => {"message":"Credential should be scoped to correct service: 'es'. "}
Sun, 26 Jan 2020 14:27:17 GMT | Total Writes: 0
Sun, 26 Jan 2020 14:27:17 GMT | dump ended with error (get phase) => Error: {"message":"Credential should be scoped to correct service: 'es'. "}`

I can fix this through adding 'service' to the esRequest in aws4signer.js - e.g.

` esRequest.service = 'es';`

Following this, this then works and I'm able to successfully make the dump.

I'm happy to submit a pull request to resolve this, but before I do, I was wondering if this is an issue or if there's something I'm doing wrong...

Cheers,

Mike

**Comment by ferronrsmith** [comment]
I've added an `awsService` flag that allows `esRequest.service` to be set before signing.
