### ISSUE TITLE
[BUG] Dumping to S3

### ISSUE THREAD

**Issue by nitsugahcram** [taskrabbit/elasticsearch-dump#663]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version: 6.18.0
- Elasticsearch version: 6.X
- Node.js version *(note that nodejs v8+ is required for this tool)*: 6.18.0
- Full command you are having issue with (with inputs and outputs):
elasticdump \
  --s3AccessKeyId="xx" \
  --s3SecretAccessKey="xx/xx+wx" \
  --s3Region="us-west-2" \
  --input=http://10.0.1.136:9200/group_1_traces_2019-12_traces_12 \
  --output=s3://bucket/registry.json
- A data-set you can share publicly which reproduces the problem

**Describe the bug**
If I dump to file work perfectly but for S3 output I do not see anything at S3, I do not see anything at output too.
Wed, 29 Jan 2020 15:08:04 GMT | starting dump
Wed, 29 Jan 2020 15:08:05 GMT | got 100 objects from source elasticsearch (offset: 0)
Wed, 29 Jan 2020 15:08:05 GMT | sent 100 objects to destination s3, wrote 100
Wed, 29 Jan 2020 15:08:05 GMT | got 100 objects from source elasticsearch (offset: 100)
Wed, 29 Jan 2020 15:08:05 GMT | sent 100 objects to destination s3, wrote 100
Wed, 29 Jan 2020 15:08:05 GMT | got 100 objects from source elasticsearch (offset: 200)

**To Reproduce**
Exectue elastict dump for S3 storage.

**Comment by ferronrsmith** [comment]
There is enough information here to do anything. I've used the s3 transport with minio and I've not experienced any issues.

**Comment by nitsugahcram** [comment]
I could not provide sample data, since it's collected from elastics. If I dump to file work perfectly.  Are any debug or log, I could provide it? I am trying to debug, but not succeed where to set the break point.

**Comment by ferronrsmith** [comment]
Yes there is a debug flag

**Comment by nitsugahcram** [comment]
Ok, I hope this help, I tried previous but I do not get any clue. 
[debug.log.zip](https://github.com/taskrabbit/elasticsearch-dump/files/4134203/debug.log.zip)

**Comment by nitsugahcram** [comment]
It seem take time to upload it, thank you
