### ISSUE TITLE
Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true

### ISSUE THREAD

**Issue by tommyongib** [taskrabbit/elasticsearch-dump#669]
- ElasticDump version: 6.21.0
- Elasticsearch version:  dump data from 6.7.0 to 7.1.1
- Node.js version: v12.12.0
- Full command you are having issue with (with inputs and outputs)
```
  elasticdump \
    --input=<input_url v.6.7.0>/<index> \
    --output=<output_url v.7.1.1>/<index> \
    --type=mapping
```

- A data-set you can share publicly which reproduces the problem.
```json
{
  "mappings": {
    "_doc": {
      "properties": {
        "type": { "type": "keyword" }, 
        "name": { "type": "text" },
        "user_name": { "type": "keyword" },
        "email": { "type": "keyword" },
        "content": { "type": "text" },
        "tweeted_at": { "type": "date" }
      }
    }
  }
}
```

**Describe the bug**
```
Error Emitted =>
{
  "root_cause": [
    {
      "type": "illegal_argument_exception",
      "reason": "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
    }
  ],
  "type": "illegal_argument_exception",
  "reason": "Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."
}
```
For data with `_doc` type in mapping, to export to ElasticSearch 7.0 and above, the param `include_type_name` need to be included. There should be a way to specify this param, or even better a way to remove `_doc` so that the mapping is typeless.

Ref https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_typeless_apis_in_7_0

**Comment by ferronrsmith** [comment]
Have you actually thought about editing the export ? We don’t support upgrading from one version to another. All platform (elasticsearch) quirks have to be worked out by you
