### ISSUE TITLE
"Malformed scrollId" exception

### ISSUE THREAD

**Issue by p-run** [taskrabbit/elasticsearch-dump#67]
Originally reported in https://github.com/elasticsearch/elasticsearch/issues/9469, they told me to report the issue here, so here goes:

One elasticdump invocation yields the following:

<pre>
% elasticdump --input=http://localhost:9200/ --output=\$ 
Wed, 28 Jan 2015 18:07:28 GMT | {"error":"ElasticsearchIllegalArgumentException[Malformed scrollId []]","status":400}
[
]
</pre>

What is a scrollId and why is it malformed? Google is of no help in understanding this error message.

This exception seems like a low-level one. It should be caught by higher level code and converted to a more meaningful error message, like, say, "index was not specified".

Update: this issue seems to happen only when I am trying to dump an elasticsearch instance which has no data. It further looks like elasticdump is sending an empty scrollid to elasticsearch in this case.

**Comment by evantahler** [comment]
I was able to reproduce this: It only happens when you request a dump of the *whole* cluster (no index specified), and there is no data (which must be the case with no indexes created)

**Comment by evantahler** [comment]
We'll have some better error messaging here https://github.com/taskrabbit/elasticsearch-dump/pull/69

```
> ./bin/elasticdump --input http://localhost:9200/ --output ~/Desktop/out.json --all
Tue, 17 Feb 2015 06:43:58 GMT | starting dump
Tue, 17 Feb 2015 06:43:58 GMT | Unable to obtain scrollId; This tends to indicate an error with your index(es)
Tue, 17 Feb 2015 06:43:58 GMT | got 0 objects from source elasticsearch (offset: 0)
Tue, 17 Feb 2015 06:43:58 GMT | dump ended with error (get phase) => Error: Unable to obtain scrollId; This tends to indicate an error with your index(es)
```

**Comment by p-run** [comment]
So how am I meant to figure out what "an error with my index(es)" actually is from that message?

**Comment by evantahler** [comment]
See above, this only happens when you have *no* indexes.
