### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by roniez** [taskrabbit/elasticsearch-dump#670]
Is it possible to dump a frozen index with elasticdump?
i have not been able to see such support going thru the manual.

**Comment by ferronrsmith** [comment]
A frozen index is just a read-only index with throttled search, so it should be possible. It will be slow

**Comment by WeslyG** [comment]
If you try search in frozen indices just run 
```
elasticdump --params='{"ignore_throttled" : "false"}' --input=localhost:9200/indexName --output=myfile.json  --searchBody='{ searchBodyHere }'
```

Its works for me)
