### ISSUE TITLE
[FEATURE] Possibility to use search templates for --searchBody

### ISSUE THREAD

**Issue by mgorsk1** [taskrabbit/elasticsearch-dump#671]
**Is your feature request related to a problem? Please describe.**

Since we can define searchBody, it would be nice to use feature of Elasticsearch called Search Templates. With this we could simplify the searchBody by only passing necessary arguments.

More on the topic: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html

**Describe the solution you'd like**

--searchWithTemplate flag which would append /template string to source (if source is Elasticsearch index). curl http://localhost:9200/index_name/_search/**template**

Then --searchBody could contain only id of template and params (if defined in template). 

**Describe alternatives you've considered**

Alternatively I could paste whole query but this makes request unreadable for more complex queries.

**Give some examples of implementations**
Give some implementation example

Create search template:

POST _scripts/employees-search-filter
{
  "script": {
    "lang": "mustache",
    "source": {
      "query": {
        "bool": {
          "filter": [
            {
              "match_all": {}
            },
            {
              "range": {
                "DateOfJoining": {
                  "gte": "{{date_from}}",
                  "lt": "{{date_to}}",
                  "format": "strict_date_optional_time"
                }
              }
            }
          ]
        }
      }
    }
  }
}

Use search template (in Kibana):
GET employees-bulk-v2/_search/template
{
  "id": "employees-search-filter",
  "params": {
    "date_from": "2006-12-31T23:00:00.000Z",
    "date_to": "2007-12-31T23:00:00.000Z"
  }
}

**Additional context**

**Comment by ferronrsmith** [comment]
Nice-have feature, but very limit in usefulness in this tool. Feel free to submit a PR

**Comment by mgorsk1** [comment]
Cool, will do. Thanks !

**Comment by mgorsk1** [comment]
I have slightly changed the logic - instead of appending template to the search uri, I just render search query using _render/template API and then treat it as searchBody. This way we can still append "size" parameter to the query.
