### ISSUE TITLE
[BUG]export data out noraml end,Actually has some data no export.

### ISSUE THREAD

**Issue by 151608133** [taskrabbit/elasticsearch-dump#678]
**Context**
- ElasticDump 6.23
- Elasticsearch 5.5.1
- Node.js version 12.16
elasticdump --input=$esUrl \
  --input-index=$indexName \
  --limit=1000\
  --timeout=10000 \
  --output=$exportpath/$indexName/$indexName \
  --overwrite=true \
  --fileSize=300mb \
  --fsCompress 
**Describe the bug**
I am not very good at English，and I don't know if this is a bug. I can only go here for help.
I have some indices over 20G, over 1000W nums. I use this tools to export to another server. but export not complete.  This happens many times at another big index, I don't know how to resolve it.
please help me to resolve it. Thanks !

**Screenshots**
![image](https://user-images.githubusercontent.com/21124892/77840711-0c756800-71bd-11ea-80fc-e11a9a1c44cb.png)

![image](https://user-images.githubusercontent.com/21124892/77840726-257e1900-71bd-11ea-9ea3-9b3ff82331d5.png)

**Comment by ferronrsmith** [comment]
need more info

**Comment by 151608133** [comment]
I'm sorry, I do'nt know what do you need .  i export this index keep almost 4 hours ,but hav't export all data it auto stop with no error.
![image](https://user-images.githubusercontent.com/21124892/77850109-db1f8b00-7202-11ea-8cd8-2fadd469ff0a.png)

**Comment by ferronrsmith** [comment]
Did you check the database from ensure the data was missing ?

**Comment by 151608133** [comment]
every time i export compelete , i will query the index actully numbers and compare with export numbers. sometime i can export all but some time i can't. the picture above can be seen
the log . this morning i export 3900W over,there's not one left.This doesn't happen every time
.There is a situation where I open index every time before exporting

**Comment by 151608133** [comment]
last night this happend agin.
![image](https://user-images.githubusercontent.com/21124892/77976361-60a05980-732f-11ea-9e74-a26db27e7b70.png)
![image](https://user-images.githubusercontent.com/21124892/77976380-6c8c1b80-732f-11ea-8f7e-3fa55567e8f3.png)
this time the index only 590W ,but have 3000 not export.

**Comment by ferronrsmith** [comment]
that's strange, if you're using shards it might be a read issue o the ES end (if you're constantly updating data)

**Comment by 151608133** [comment]
This happens several times these days.Maybe it's a real bug.
![image](https://user-images.githubusercontent.com/21124892/78450777-9c327f00-76b3-11ea-9f48-95a92ae7b0d2.png)

**Comment by ferronrsmith** [comment]
If I can’t replicate the issue on my system then there is no point. I’ve never had missing data issue. I’m going to need more info and a data-set and even with that the conditions of your system might be different

**Comment by ferronrsmith** [comment]
Data is pulled using scrolls, if data is added/removed/changed constantly then the count can change, which isn't a bug. This is normal

**Comment by 151608133** [comment]
The index I operate has not been used for a long time. There is no data change operation. no one to add or remove data.

**Comment by ferronrsmith** [comment]
I'm going to need the data-set to actually test this, because I've not had this issue.

**Comment by 151608133** [comment]
![image](https://user-images.githubusercontent.com/21124892/78452393-a35e8a80-76bd-11ea-92fe-92aeb8f8cd0d.png)
It just happened again.This index hasn't been used for a year.
![image](https://user-images.githubusercontent.com/21124892/78452470-efa9ca80-76bd-11ea-90fd-c647a7d86d0b.png)
I'm sorry ,I'm not very familiar with ES.can you tell me how to query the info about you need.

**Comment by ferronrsmith** [comment]
http://localhost:9200/_cat/indices
