### ISSUE TITLE
[BUG]multielasticdump alias includeType

### ISSUE THREAD

**Issue by 66988230** [taskrabbit/elasticsearch-dump#679]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- elasticsearch-dump-6.23.0/bin/multielasticdump
- Elasticsearch 6.4.3
- Node.js v10.15.3

**Describe the bug**
./multielasticdump --direction=dump --match='^.*$' --input=${my_es_ip} --includeType='mapping,alias,settings' --output=${my_backup_dir}

I want to dump my_es_ip's all indexes(include mappings,settings and alias), mappings and settings are both dump ok, but alias always error 404:
"{\"error\":\"alias [xxxxxxxxx] missing\",\"status\":404}"
But all my indexes  had its alias. 

help!!!!! thinks!!!

**Comment by ferronrsmith** [comment]
the issue isn't really useful and doesn't help diagnose the issue. From what I see, you're pulling data from an index that doesn't exist
