### ISSUE TITLE
Unable to handle FilePath in Windows

### ISSUE THREAD

**Issue by tiansh** [taskrabbit/elasticsearch-dump#68]
```
elasticdump --input=http://localhost:9200/ --output=D:\1.json
````
This command line cause error when writing.
```
Wed, 04 Feb 2015 07:29:10 GMT | starting dump
Wed, 04 Feb 2015 07:29:11 GMT | got 2700 objects from source elasticsearch (offset: 0)
Wed, 04 Feb 2015 07:29:11 GMT | Invalid URI "d:/1.json/api/514"
Wed, 04 Feb 2015 07:29:11 GMT | dump ended with error
......
```

Both `D:\1.json` or `\\?\D:\1.json` cannot work.

( Maybe just add a notice in README is enough. )

**Comment by evantahler** [comment]
To clarify: Did none of those paths work, or did one of them eventually work?  
I don't have any windows computers to test on.

**Comment by tiansh** [comment]
WORK:

> --output=/1.json
> --output=\1.json
> --output=.\1.json

NOT WORK:

> --output=d:1.json
> --output=d:\1.json
> --output=\\?\d:\1.json

It seems that path contains ":" will not work.

**Comment by evantahler** [comment]
Ahh!

We use the ":" to determine that the argument is a URL vs file path.  As only windows references drives like that, I'm not going change the behavior here.   I feel that this is common knowledge, but if you want, please add that note to the readme in a separate Pull Request.
