### ISSUE TITLE
help!!! how i can dump indexes from one es to files, and then load in another es.

### ISSUE THREAD

**Issue by 66988230** [taskrabbit/elasticsearch-dump#680]
hi ,i have a problem, but I don't know how to solve. 

===1.  I dump all indexes in an dir, like this:
multielasticdump  --direction=dump --match='^.*$' --input=http://xxxx:9200 --includeType='settings,mapping' --output=./dir

dir/index_name.mapping.json  dir/index_name.settings.json

===2.  then,i want to load the dir to another es:
multielasticdump --direction=load  --input=./dir  --output=http://xxxx:9200
but it always error,"type":"resource_already_exists_exception"

i need to rebuild many indexes in two es cluster, and how i can rebuild those indexes in another ES? help!! thinks!

**Comment by ferronrsmith** [comment]
Resource already exists means the index is already present try change the index name to something unique. When you’re done loading the data use an alias to reference the old index name after deleting the target index with the conflicting name
