### ISSUE TITLE
[QUESTION (FEATURE)] How do you restore indices from compressed files?

### ISSUE THREAD

**Issue by exquisitus** [taskrabbit/elasticsearch-dump#681]
Thank you very much for your work on elasticsearch-dump. I use it to take nightly backups of my indices and save them compressed (with the --s3Compress option) to S3.

The question is about restoring the compressed backups from S3 (or from a file). Something like the following doesn't work for me with "Error Emitted: => Invalid JSON (Unexpected "\u001f" at position 0 in state STOP)"

> elasticdump
> --output=http://elasticsearch-client:9200/$(INDEX_NAME)-$(DATE)
> --input "s3://$(S3_BUCKET)/$(S3_PREFIX)/$(INDEX_NAME)-$(DATE).json.gz"

How do you do it? Is it possible to restore directly from a compressed S3 file?

Or do you use an intermediate step of downloading the .gz file and then restoring from there? In that case, can you restore directly from .gz with piping from gunzip to elasticdump with input=$ ?

**Comment by ferronrsmith** [comment]
The compressed file needs to be in a format that elssticsearch dump supports (jsonl) and must have the necessary formatting for each row

**Comment by exquisitus** [comment]
Sorry, I did not understand.

Is this not the case, when the compressed file is created with elasticsearch-dump itself, with the --s3Compress option? I have taken the backup with elasticdump, with the --s3Compress option, and  I can see that the compressed file looks like what you say (jsonl).

Do you mean I can play the compressed backup directly from S3 to elastic with the command I gave, and that the error is somehow only in my data?

How does elasticdump know the difference between compressed and uncompressed files? does it look at the file extension? If yes, is json.gz (which I am using) correct?

**Comment by ferronrsmith** [comment]
The `s3Compress ` flag is needed when you're decompressing the file. This signals to the transport that it should expect a gzip file.
