### ISSUE TITLE
Security warnings coming from deprecated dependency "optimist"

### ISSUE THREAD

**Issue by justinmchase** [taskrabbit/elasticsearch-dump#683]
**Context**
All versions of ElasticDump
(not related to elasticsearch or nodejs)

**Describe the bug**
This library depends on a deprecated package which has a dependency on an old version of a different package with a security vulnerability. It is triggering security warnings in my repo and there is no possible upgrade path for me to fix it.

Your bad dependency "optimist":
https://github.com/taskrabbit/elasticsearch-dump/blob/master/package.json#L40

Optimists bad dependency:
https://github.com/substack/node-optimist/blob/master/package.json#L8

**To Reproduce**
1. `npm i elasticdump`
2. `npm audit`

**Current behavior**
I now have a security warning

**Expected behavior**
I have no security warnings

**Screenshots**
<img width="576" alt="Screen Shot 2020-04-03 at 8 42 03 AM" src="https://user-images.githubusercontent.com/10974/78367030-0c8fb200-7587-11ea-85e3-be618b8755eb.png">

**Additional context**
Probably you'll need to switch to yargs or maybe just straight minimist.

**Comment by ferronrsmith** [comment]
`yargs` has too much dependencies and `minimist` doesn't have the help option.

**Comment by justinmchase** [comment]
Awesome thanks!

I see it was already patched https://github.com/taskrabbit/elasticsearch-dump/commit/9be27174e41ce1b12c58fd68a413a1889406f5cf
