### ISSUE TITLE
[Support URL query parameters]

### ISSUE THREAD

**Issue by adjokic** [taskrabbit/elasticsearch-dump#684]
**Is your feature request related to a problem? Please describe.**
I would like to be able to import data and specify a pipeline to be used, i.e. call http://elasticsearch.service.local:9200/my_index/_bulk?pipeline=data-preprocessor

**Describe the solution you'd like**
I would like to be able to pass in a series of query parameters; I actually expected the `--params` parameter to do this for me, but it seems that this is not the case.

**Describe alternatives you've considered**
N/A

**Give some examples of implementations**
N/A

**Additional context**
When setting `--params='{"pipeline":"data-preprocessor"}'`, I was expecting to see the following output when running in `--debug` mode:
Mon, 06 Apr 2020 17:39:28 GMT [debug] | thisUrl: http://elasticsearch.service.local:9200/my_index/_bulk?pipeline=data-preprocessor, payload.body: "{\"index\":{\"_index\" ...

but the actual output was:
Mon, 06 Apr 2020 17:39:28 GMT [debug] | thisUrl: http://elasticsearch.service.local:9200/my_index/_bulk, payload.body: "{\"index\":{\"_index\" ...

is there a way to currently pass in query parameters?

**Comment by ferronrsmith** [comment]
closed by https://github.com/taskrabbit/elasticsearch-dump/commit/00f62e99a4f7f74abf8a447388005e5fa262f468
