### ISSUE TITLE
Error 400 (Bad Request) when pulling data

### ISSUE THREAD

**Issue by erinfry6** [taskrabbit/elasticsearch-dump#686]
-ElasticDump version: 6.27.3
-Elasticsearch version: 7.4.2
-Node.js version: 13.7.0

I am trying to pull down all data from Elasticsearch for an index. It has 1509 documents. The command below successfully runs to acquire the mapping:
```
elasticdump \
  --input=https://my.url/my-index-2020-03 \
  --output=data/mapping.json \
  --type=mapping \
  --headers='{"Authorization": "Basic ..."}'
```
But then I try to actually download the data, with basically the same command, just changing type to 'data':
```
elasticdump \
  --input=https://my.url/my-index-2020-03 \
  --output=data/data.json \
  --type=data \
  --headers='{"Authorization": "Basic ..."}'
```

And I get this very vague error:
```
Tue, 14 Apr 2020 15:45:34 GMT | Error Emitted => <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>

Tue, 14 Apr 2020 15:45:34 GMT | Error Emitted => <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
```

I have tried:
- limiting records to 100
- running with --debug
- running on a different environment
- running with search body
- saving to a zipped file

But I have seen no change in error message.

Any help with this is greatly appreciated!

**Comment by ferronrsmith** [comment]
You haven't really provided any information to help diagnose the issue. the most I can say is the url/path to the Elasticsearch index is incorrect, but that's just based on the information provided

**Comment by erinfry6** [comment]
I don't think the URL is the issue since my first code chunk to acquire the mapping is working. What other information should I provide? I cannot provide access to my database, so the url and login information will remain hidden. 

If I am able to obtain mapping data, what other adjustments to the code do I need to obtain the actual data from documents themselves?

**Comment by ferronrsmith** [comment]
The error you sent refers to Google.com. Only the `type` change, which you did.


Are you sure this error is from the server and not google ?
<img width="493" alt="Screenshot 2020-04-14 at 2 04 02 PM" src="https://user-images.githubusercontent.com/159764/79258218-ce34a580-7e58-11ea-9b4f-ac9dfd3386c3.png">

**Comment by erinfry6** [comment]
Ah you're right - more information about hosting: the Elasticsearch instance is hosted in Kubernetes on Google Cloud.. I'm guessing that's what the error is about? It's just strange that I'm able to pull the mapping but not the data. Is the package known to work with Elasticsearch hosted on Google Cloud? Do I need to add any additional flags?

**Comment by ferronrsmith** [comment]
It’s a different URL so that might affect things

**Comment by ferronrsmith** [comment]
A simpler way to do basic auth is using `-`input=http://name:password@production.es.com:9200/my_index`. I'm not sure if this affects anything, but you can give it a try

**Comment by ferronrsmith** [comment]
Not sure if this is still needed, but a resolution was added, check #797
