### ISSUE TITLE
[BUG] `--toLog=false` shows log output in `stdout`

### ISSUE THREAD

**Issue by SoAG** [taskrabbit/elasticsearch-dump#688]
**Context**
In order to help us troubleshoot issues with this project, you **must** provide the following details:

- ElasticDump version  6.27.3 
- Elasticsearch version 2.4
- Node.js version v13.10.1
- Full command you are having issue with (with inputs and outputs)
```
bin/elasticdump --input http://elastic.local:9200/index/type --type data --sourceOnly --searchBody '{"query": {"match_all": {}}}' --limit 1 --toLog=false --output=$
```
- no special data needed

**Describe the bug**
`--toLog=false` option should lead to no logging out put ending up in `stdout`. But I keep getting this log line in the output.

```
Fri, 24 Apr 2020 13:33:33 GMT | lastScrollId: cXVlcnlUaGVuRmV0Y2g7NTsyNjU5OmZqa1k3ZkpzU3Z1QnMyaFlfTXF5WGc7MjY1ODpzNnY5YWtMSVJuR2N4bXlHcTZfVUJROzI2NTk6czZ2OWFrTElSbkdjeG15R3E2X1VCUTsyNjYwOmZqa1k3ZkpzU3Z1QnMy
aFlfTXF5WGc7MjY2MTpmamtZN2ZKc1N2dUJzMmhZX01xeVhnOzA7 
```

**To Reproduce**
Run against any dataset: 
`bin/elasticdump --input http://elastic.local:9200/index/type --type data --sourceOnly --searchBody '{"query": {"match_all": {}}}' --limit 1 --toLog=false --output=$`

**Current behavior**
Even though `--toLog=false` option is set log lines are output to `stdout` 

**Expected behavior**
No logs being sent to `stdout` when `--toLog=false` is set

**Additional context**
I think the issue lies with the [`elasticsearch`](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/elasticsearch.js#L258) transport using `this.parent.emit('log')` instead of `this.parent.log(message)`. The event emitted is being received here https://github.com/taskrabbit/elasticsearch-dump/blob/master/bin/elasticdump#L113 and thus logged ignoring the `--toLog=false` flag.

**Comment by ferronrsmith** [comment]
`toLog` - When using a custom outputTransport, should log lines be appended to the output stream?

It's doing what it suppose to do. What you're looking for is the `quiet` option

**Comment by SoAG** [comment]
Ah OK. Then I misunderstood 
> (default: true, except for `$`)
part. 

It sounds like if the output is `$` it would default to `false` and thus not show any log output in `stdout`. 

Will use the `quiet` option instead. Thanks

**Comment by ferronrsmith** [comment]
not exactly, because the `lastScrollId` is important in cases where the job stopped and you wanted to continue from the last point. So I logged that intentionally.
