### ISSUE TITLE
How to export from ElasticSearch to Minio - S3

### ISSUE THREAD

**Issue by sivakumarl** [taskrabbit/elasticsearch-dump#690]
Hi Team,
      Can you please help me to export the data minio - s3, using below configuration but by default the hostname is appending with bucket. How to stop appending bucket by default to host.

elasticdump \
  --s3AccessKeyId "${access_key_id}" \
  --s3SecretAccessKey "${access_key_secret}" \
  --s3Endpoint "http://minio.com:9000"
  --input=http://es.com:9200/my_index \
  --output "s3://elkdocs/myindex.json"

Error : 
{UnknownEndpoint: Inaccessible host: `elkdocs.minio.com`. This service may not be available in the `us-east-1 region`.}

Regards,
Siva Kumar.

**Comment by ferronrsmith** [comment]
You're missing 

```bash
--s3ForcePathStyle true
```

This is needed for S3 compatible backends

**Comment by sivakumarl** [comment]
Thank @ferronrsmith , its working.
