### ISSUE TITLE
[BUG] Concurrency options doesn't seem to get respected

### ISSUE THREAD

**Issue by yatishb** [taskrabbit/elasticsearch-dump#692]
**Context**
- ElasticDump: 6.27.3
- Elasticsearch version: Reproducible with version 2.4 and 7.1 
- Node.js version: v14.0.0
- `elasticdump --input=https://<es_index_url> --output=<file_name>.json --type=data --concurrency=10`

**Describe the bug**
I've been trying to alter the concurrency option on the command both when I'm trying to export data from an ES cluster to a file as well as when I'm reading from a file and importing to an ES cluster. In both cases, I'm not seeing the changes in the concurrency setting to have any effect and always create what looks like 5 concurrent threads

**Current behavior**
Not seeing any difference in the execution time of the tool with currency settings. Logs are always showing 5 concurrent requests which get executed at the same time.

**Expected behavior**
I would expect the number of concurrent requests made to respect the passed in argument

**Screenshots**
With concurrency 1:
<img width="1459" alt="elasticdump_concurrency1" src="https://user-images.githubusercontent.com/2919567/80579675-02a18780-8a3d-11ea-98b1-b2dcde31ce52.png">

With concurrency 10:
<img width="1459" alt="elasticdump_concurrency10" src="https://user-images.githubusercontent.com/2919567/80579704-0df4b300-8a3d-11ea-9790-4bc13a4e2df7.png">

During an import from a file with concurrency 10:
<img width="1459" alt="elasticdump_concurrency10_import" src="https://user-images.githubusercontent.com/2919567/80580980-00402d00-8a3f-11ea-8807-2c381a95891c.png">

**Comment by ferronrsmith** [comment]
Please read the docs. There are several flags that control concurrency. What is happening is you're reaching the `intervalCap (default:5)`. This limits the max requests that can be made during a concurrency interval.

**Comment by mfelician** [comment]
I think this issue is not related to limits

![image](https://user-images.githubusercontent.com/7103608/194307261-b9ac1b20-996a-4cee-9e1e-c3b4e53eaa7a.png)

**Comment by ferronrsmith** [comment]
Yea I know. This was removed years ago by me. Just didn't remember. It actually didn't make any sense. If you think about it, you will understand what I mean

**Comment by mfelician** [comment]
I did tests with manually breaking up the dataset to multiple parts and using "xargs" or "parallel" utility to run Elasticdump in parallel I can achieve 10x+ speed gain. 
Recent Elasticsearch versions support Sliced Scroll too (https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#slice-scroll) - but having support for this in Elasticsearch requires some work for sure.

**Comment by ferronrsmith** [comment]
1. A file is cursor based, unless you split the file into multiple parts before reading concurrency is a myth
2. It doesn't inside elasticdump. The effort is not worth the reward and this can easily be accomplished using bash
3. This was tagged as not working years ago. Don't remember in which issue, but you're right I'll remove it from the docs
4. This is probably the best option
5. slice-scroll to me is garbage and is actually hard to implement in a generic library as elasticdump.

Feel free to submit an PR, but I've long given up on implementing this inside elasticdump. Complexity isn't worth the reward.
