### ISSUE TITLE
[INFO NEEDED]

### ISSUE THREAD

**Issue by SowmyaM84** [taskrabbit/elasticsearch-dump#693]
When we are trying to use "Split files into multiple parts"
 using --fileSize the file name received are as follows: 
sample_filename.json.split-49
sample_filename.json.split-45
sample_filename.json.split-43

Is it possible to have filename as sample_filename-split-49.json ( so that file ends with .json extension)

**Comment by ferronrsmith** [comment]
nope, because that's an assumption that everybody reads from a json file. technically it's jsonl

**Comment by ferronrsmith** [comment]
resolved by https://github.com/taskrabbit/elasticsearch-dump/commit/dbf6d1ffd1cbe71a2de1ef92c1ddfd01fb068880
