### ISSUE TITLE
Export Import not working on Windows 7 

### ISSUE THREAD

**Issue by nithyanv** [taskrabbit/elasticsearch-dump#70]
I am trying to use the following commands with two separate cluster/node i.e they have different cluster.names in same machine. The index and mapping I am trying these commands with is the one elasticsearch provided in the initial documents. 

Localhost 9400 is running ES 1.4.0
Localhost 9200 is running ES 1.4.4

Operating system is windows 7. 
elasticsearch-dumb is installed globally. 

I am running these commands in cygwin.  

Mapping
>  elasticdump --input=localhost:9400/shakespeare --output=localhost:9200/shakespeare --type=mapping

> Thu, 26 Feb 2015 15:09:45 GMT | starting dump

Data
>  elasticdump --input=localhost:9400/shakespeare --output=localhost:9200/shakespeare --type=data

> Thu, 26 Feb 2015 15:08:38 GMT | starting dump

However, it makes no visible changes in mapping or indices of cluster/node running at localhost:9200.

**Comment by evantahler** [comment]
Is that the extent of the logs?  Do you have any further details?  I would expect this to work. 

Also, you may need to provide the full URL, ie:
```
elasticdump --input=http://localhost:9400/shakespeare --output=http://localhost:9200/shakespeare --type=mapping
```

**Comment by nithyanv** [comment]
I have tried this again with between ES 1.4.4 cluster/nodes running on Windows 7 and Linux. It worked perfectly as detailed. I was able to use this to export Kibana dasboards as well by exporting .kibana index. Possibly, the last time it was something to do with version difference between the two. Thank you.
