### ISSUE TITLE
Unhelpful/incorrect error message

### ISSUE THREAD

**Issue by p-run** [taskrabbit/elasticsearch-dump#72]
Fix for #67, as implemented in #69, added an error message which reads:

Tue, 17 Feb 2015 06:43:58 GMT | Unable to obtain scrollId; This tends to indicate an error with your index(es)

In actuality, this error only occurs (presumably) when the elasticsearch instance has no indexes, which is not exactly an error condition.

The message should be reworded to something like "Unable to obtain scrollId: elasticsearch instance has no indexes".

**Comment by evantahler** [comment]
That sounds fine to me! open a pull request with that content change!
