### ISSUE TITLE
Values from _timestamp field are not dumped

### ISSUE THREAD

**Issue by agorski** [taskrabbit/elasticsearch-dump#75]
_timestamp field (maybe other fields too?) is skipped by dumping

Example
input data:
{
      "_index" : "my-index",
      "_type" : "my-type",
      "_id" : "AUu8jVhY4Lq59mfN-hXL",
      "_score" : 1.0,
      "_source":{"id":5218198,"userId":123},
      "fields" : {
        "_timestamp" : 1424797554751
}
is copied as:
{
      "_index" : "my-index",
      "_type" : "my-type",
      "_id" : "AUu8jVhY4Lq59mfN-hXL",
      "_score" : 1.0,
      "_source":{"id":5218198,"userId":123}
}

**Comment by evantahler** [comment]
That is correct.  We store only the data which elasticsearch returns as a "hit".  It's common for folks to store `created_at` and `updated_at` within the source, and not rely on ElasticSearch's timestamps for when the data writen (vs. created).

That said, pull requests welcome!  (this might also be a setting in your particular elasticsearch index)
