### ISSUE TITLE
Writing to file is very slow

### ISSUE THREAD

**Issue by yusufcan141** [taskrabbit/elasticsearch-dump#76]
Hi,

I dump a very large index. It fetch the results fast but when it is writing them to file it writes them very slowly. Is there any limitation?

**Comment by evantahler** [comment]
Only the speed of you disk!    We also need to parse and un-parse JSON objects, which is CPU-intensive.

**Comment by wxf4150** [comment]
https://github.com/wxf4150/esdump

speedup 83 times
