### ISSUE TITLE
undefined "_index": ".kibana",

### ISSUE THREAD

**Issue by dkirrane** [taskrabbit/elasticsearch-dump#78]
I'm trying to import my Kibana 4 saved Queries, Visualizations and DashBoards.

When I try to import I get:
```
Mon, 30 Mar 2015 13:47:39 GMT | starting dump

undefined:1
"_index": ".kibana",
        ^
SyntaxError: Unexpected token :
    at Object.parse (native)
    at /usr/lib/node_modules/elasticdump/lib/transports/file.js:45:27
    at getLine (/usr/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:74:9)
    at LineReader.nextLine (/usr/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:93:9)
    at file.getLines (/usr/lib/node_modules/elasticdump/lib/transports/file.js:37:17)
    at /usr/lib/node_modules/elasticdump/lib/transports/file.js:51:12
    at getLine (/usr/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:74:9)
    at LineReader.nextLine (/usr/lib/node_modules/elasticdump/node_modules/line-reader/lib/line_reader.js:93:9)
    at file.getLines (/usr/lib/node_modules/elasticdump/lib/transports/file.js:37:17)
    at /usr/lib/node_modules/elasticdump/lib/transports/file.js:51:12
```

My export command:
```
elasticdump --input=http://135.60.151.232:9200/.kibana --output=$ --type=data --searchBody='{"filter": { "or": [ {"type": {"value": "dashboard"}}, {"type" : {"value":"visualization"}}] }}' > kibana-exported.json
```
My import command:
```
elasticdump --input=kibana.json --output=http://MyIp:9200/.kibana --type=data
```

When I browse to `http://MyIp:9200/.kibana` I can see this:
```
{".kibana":{"aliases":{},"mappings":{"config":{"properties":{"buildNum":{"type":"long"}}}},"settings":{"index":{"creation_date":"1427722524272","uuid":"QIa46E0zRImVekm0RRGvPg","number_of_replicas":"1","number_of_shards":"1","version":{"created":"1050099"}}},"warmers":{}}}
```

**Comment by evantahler** [comment]
That looks like a JSON parse error.  Can you share the data you saved in `kibana.json`?  Without seeing it, I don't think we'll be able to tell what went wrong.

Also, if you are just saving your output to disk, you can supply a file name and skip the step where you pipe the stdout to a file.   Give that a try and diff the files created.  Some clues might be there.

**Comment by dkirrane** [comment]
Sure. kibana.json attached.

**Comment by evantahler** [comment]
and can you share the one generated with the file output as well?

**Comment by dkirrane** [comment]
This is what gets exported by the elasticdump export command above:

https://gist.githubusercontent.com/dkirrane/06e0a07cb42a6e41f012/raw/753549e45dd2d15d0c0ec3463a89e35d5bc0f445/gistfile1.txt

**Comment by evantahler** [comment]
ok, the good news is that those files are identical (whew!).

The problem is that you have pretty-preinted your JSON.  The parser assumes that each line is a [fully-formed JSON object](https://github.com/taskrabbit/elasticsearch-dump/blob/master/lib/transports/file.js#L29-L56).  

Un-pretty print your JS, and you'll be fine.

If you are up for it, changing `file.prototype.getLines()` to be able to scan multiple lines would be a great pull request.
