### ISSUE TITLE
type=mapping does only create index, not mappings

### ISSUE THREAD

**Issue by tschubotz** [taskrabbit/elasticsearch-dump#79]
Hi,

When exporting and importing my index mapping from von ES instance to another one, only the index itself created and no mappings.
The issue appear when both (1) directly copying the mapping or (2) indirectly via a json file.

(1)
```elasticdump --input=https://myelasticsearchurl/myindex  --output=https://myelasticsearchurl/myindex      --type=mapping```

(2)
```elasticdump --input=https://myelasticsearchurl/myindex  --output=mapping.json --type=mapping```
```elasticdump --input=mapping.json  --output=https://myelasticsearchurl/myindex --type=mapping```

Anybody else experiencing this problem? Or am I missing something.

Best regards,
Tobias

**Comment by evantahler** [comment]
With version 2, can you confirm that your `mapping.json` actually contains any data?   Both method 1 and 2 should work.

**Comment by tschubotz** [comment]
Yep, the mapping.json contains the following:

```javascript
[
"{\"myindex\":{
    \"mappings\":{
      \"mydoctype\":{
        \"_boost\":{\"name\":\"boost\",\"null_value\":1.0},
        \"properties\":{
           \"cs\":{\"type\":\"long\"},
           \"csp\":{\"type\":\"long\"},
           \"css\":{\"type\":\"long\"},
           \"country\":{\"type\":\"string\",\"index\":\"not_analyzed\"},
           \"creator\":{\"type\":\"string\",\"index\":\"not_analyzed\"},
           \"text\":{\"type\":\"string\",\"analyzer\":\"snowball\"}
         }
       }
     }
   }
  }"
]```

So this is a list containing a string of the serialized index property dict. 
Is this how it is supposed to look like?

**Comment by evantahler** [comment]
Yep, that's right.  

I just re-tested with the latest version of ElasticDump (`0.12.0`) and ElasticSearch version `1.4.4`.  Both your version 1 and 2 work OK for me.  We also test this in the test suite  [here](https://github.com/taskrabbit/elasticsearch-dump/blob/master/test/test.js#L238-L266) and test against the latest version as provided by travis.

**Comment by tschubotz** [comment]
Okay, looks like the problem is on my side then. I'm using Elasitcsearch version ```1.4.2```. But this shouldn't make a difference, right?

Thanks for re-testing, though!

**Comment by evantahler** [comment]
Yeah, as long as you are on ES v1.0 or greater, I *think* elasticdump should work, as the APIs have been stable.

**Comment by tschubotz** [comment]
Found the problem:
I'm using a custom index analyzer. However, the mapping export does not copy all index settings, but only the properties (mappings).
Consequently, when trying to create the new mapping, the request fails, since the custom analyzer does not exist.

**Comment by ethurgood** [comment]
I ran into the same problem with custom analyzers. It would be fantastic if elasticdump could include the input index's settings along with the mappings when creating the output index.

**Comment by evantahler** [comment]
Pull requests are welcome!  

I would suggest that exporting (and importing) analyzers becomes a third `type` so we would have `--type mapping`, `--type data`, and  now `--type analyzer`

**Comment by ehartford** [comment]
I think all settings, not just analyzers.
curl -XGET 'http://localhost:9200/_all/_settings'

**Comment by evantahler** [comment]
sounds great... someone on this thread should submit this pull request :D

**Comment by ehartford** [comment]
I'll make a new bug to track the feature request, and implement when I have time.
