### ISSUE TITLE
we can export and import data between 2 versions of elasticsearch?

### ISSUE THREAD

**Issue by astrung** [taskrabbit/elasticsearch-dump#80]
Now,i have used version 1.4.4.But i want to upgrade my elasticsearch cluster to version 1.5.5,and i need to backup-export and import data to a new version of elasticsearch.This plugin can do that?

**Comment by evantahler** [comment]
Yep! We just make JSON files of your data, and use the normal APIs to POST data back in. 

That said, moving from versions 1.4.x to 1.5.x can be an in-line/rolling upgrade.  You don't need to do export and import necessarily.
