### ISSUE TITLE
Output file formats

### ISSUE THREAD

**Issue by gonrada** [taskrabbit/elasticsearch-dump#83]
Would it be possible to have a flag that would alter the output format?
Specifically I am needing my output in a file of newline delimited jsons so I can use the data with other tools.
While it isn't hard to massage the data into the desired format, it would be cool if the tool had this functionality.

**Comment by evantahler** [comment]
You can download the source and add a custom transport https://github.com/taskrabbit/elasticsearch-dump/tree/master/lib/transports.   If are willing to make your own, we can add a way to load in transports from outside of the project's codebase.

**Comment by gonrada** [comment]
Cool, from looking at the transports/file.js it does not look terrible complex to change what is there to fit my needs.

When you say add custom transport from outside, is what you are thinking having a flag where I would pass it the full path to my custom-transports-file.js ?

**Comment by evantahler** [comment]
@gonrada yep, that's the idea.

**Comment by pctj101** [comment]
+1 on this one :)

**Comment by evantahler** [comment]
This PR allows for custom transports.  Thoughts?

https://github.com/taskrabbit/elasticsearch-dump/pull/87/files

**Comment by gonrada** [comment]
Looks good. I will test this out later this week.

**Comment by evantahler** [comment]
well... I'm just going to merge this in... we can always make changes later!
