### ISSUE TITLE
Export index with parent-child relationship

### ISSUE THREAD

**Issue by JLVeiga** [taskrabbit/elasticsearch-dump#85]
I've tried to copy an index with a parent-child relationship. 

All data is dumped but does not have the relationship (no _parent field is found in the index), if I check the json I can't find the "_parent" field and it is necessary to maintain the relationship. 

I've tried back up all indices and back up the mapping and data separated.  

This is a known bug? 

Thanks in advance

**Comment by evantahler** [comment]
We've got no examples and no tests for parent-child relationships.  Please add them if you can!

**Comment by JLVeiga** [comment]
For example with this data.

curl -XPOST 'http://localhost:9200/manager_employee' -d '{
"mappings": {
"employee": {
"_parent": {
"type": "employee"
},
"properties": {
"name": {
"type": "string"
}
}
}
}
}'


curl -s -XPOST localhost:9200/_bulk --data-binary '
{ "index" : { "_index" : "manager_employee", "_type" : "employee", "_id" : "employee1" , _parent:"employee1"} }
{ "name" : "chris"}
{ "index" : { "_index" : "manager_employee", "_type" : "employee", "_id" : "employee2" , _parent:"employee1"} }
{ "name" : "joseph" }


Then I export to a file with this command:
elasticdump --input=http://localhost:9200/manager_employee --output=test.json --type=data

And I get
[
{"_index":"manager_employee","_type":"employee","_id":"employee1","_score":0,"_source":{"name":"chris"}}
,{"_index":"manager_employee","_type":"employee","_id":"employee2","_score":0,"_source":{"name":"joseph"}}
]

In the employee2 we don't get the parent field. 

This is the json from the index

{
"_index": "manager_employee",
"_type": "employee",
"_id": "employee2",
"_version": 1,
"_score": 1,
"_source": {
"name": "joseph"
},
"fields": {
"_parent": "employee1"
}
}

**Comment by evantahler** [comment]
This is a matter of the `--searchBody` query used when extracting data from ES.  I've updated the default query here https://github.com/taskrabbit/elasticsearch-dump/pull/86.

Closing in favor of the PR.
