### ISSUE TITLE
Does searchBody work?

### ISSUE THREAD

**Issue by ditesh** [taskrabbit/elasticsearch-dump#88]
It seems that it doesn't work as its not in the defaults variable.

**Comment by evantahler** [comment]
Whoops! That was recently removed here https://github.com/taskrabbit/elasticsearch-dump/commit/28cd38f1404bacf9e74fcaf6a65ad281042ed333.

Added back here: https://github.com/taskrabbit/elasticsearch-dump/commit/057865fdcdd511ae21a260837d3c83010afbd0e2
