### ISSUE TITLE
Add option to input/output line separated json

### ISSUE THREAD

**Issue by keras** [taskrabbit/elasticsearch-dump#91]
Please add support for line separated json files:

    { "_id": "1", .....}
    { "_id": "2", .....}
    { "_id": "3", .....}

Compared to current:

    [
    { "_id": "1", .....},
    { "_id": "2", .....},
    { "_id": "3", .....}
    ]

This would make it easier to use with stream processing tools like (grep, awk, sed, jq, ...)

**Comment by evantahler** [comment]
Sadly, that would not be valid JSON, so it won't be supported.

That said, you can write your own input and output transports and link them up! The new release has flags for `--inputTransport` where you can write your own file parser.

**Comment by evantahler** [comment]
solved by https://github.com/taskrabbit/elasticsearch-dump/pull/87
