### ISSUE TITLE
Exit code is 0 even when error occurs

### ISSUE THREAD

**Issue by ilyash-p** [taskrabbit/elasticsearch-dump#92]
I did mapping recovery. By mistake (apparently) did it to `http://.../` instead of `http://.../byindex`. No errors shown, exit code 0. In tcpdump I'm seeing this:

	HTTP/1.1 400 Bad Request
	Content-Type: application/json; charset=UTF-8
	Content-Length: 105

	{"error":"ActionRequestValidationException[Validation Failed: 1: mapping type is missing;]","status":400}

and the command does not work

**Comment by ilyash-p** [comment]
The request for the response above is

	PUT /censored/_mapping HTTP/1.1
	host: 127.0.0.1:9200
	content-length: 744
	Connection: keep-alive

**Comment by evantahler** [comment]
Good catch! will be solved by https://github.com/taskrabbit/elasticsearch-dump/pull/93
