### ISSUE TITLE
Wrong type guessing on bulk import

### ISSUE THREAD

**Issue by colegatron** [taskrabbit/elasticsearch-dump#95]
Not a error, but to clarify on doc: 

I tried this morning to bulk import all indexes from one cluster to a new one.
To avoid having to move all data into an intermediate file and then to the cluster I did:
```
$ elasticsearch-dump --all=true --bulk=true --input=http://fromhere:9200/ --output=http://tothere:9200/
```
It worked,  but we have some indexes with geoshape and geopoint field types that had been converted from:
```
"polygon" : { "tree_levels" : 10, "type" : "geo_shape" },
"center" : { "lat_lon" : true, "type" : "geo_point" },
```
to:
```
"polygon" : { "properties" : { "type" : { "type" : "string" }, "coordinates" : { "type" : "double" } } },
"center" : { "properties" : { "lon" : { "type" : "double" }, "lat" : { "type" : "double" } } },
```
If you first create the indexes mappings (one by one), then the --all=true --bulk=true --input=host1 --output=host2 will work fine.

It would be nice to be able to limit the number or rows to dump in a run. 
`$ elasticdump --limit=1000 --offset=350000 --maxrows=20000 --input=host1 --output=host2 --bulk=true_or_false`

By the way, congratulations, this is a great tool !!

**Comment by evantahler** [comment]
Yep, for this exact reason we have the mapping step, and recommend that you use that first.  I'll add a separate issue (https://github.com/taskrabbit/elasticsearch-dump/issues/96) to make a bulk-mapping option. 

Regarding the limit/offset, you can write a `--searchBody` query to sort and limit however you want

**Comment by colegatron** [comment]
I have a 220Gb json file with a Type backup and what I want to index into a new index is a subset, so --searchBody does not plays well there. 

Anyway, I should congratulate you for this cool tool. Thank you!
