### ISSUE TITLE
MappingParsingException

### ISSUE THREAD

**Issue by HenleyChiu** [taskrabbit/elasticsearch-dump#97]
I'm trying to dump a mapping from 1 server to another:
bin/elasticdump  --input=http://195.95.29.19:9200/new_articles2_percolator   --output=http://167.114.251.181:9200/new_articles2_percolator   --type=mapping

But I get this error:
```
Thu, 23 Jul 2015 21:42:40 GMT | starting dump
Thu, 23 Jul 2015 21:42:40 GMT | got 1 objects from source elasticsearch (offset: 0)
Thu, 23 Jul 2015 21:42:40 GMT | Error Emitted => "MapperParsingException[Analyzer [title_analyzer] not found for field [analyzed_title]]"
Thu, 23 Jul 2015 21:42:40 GMT | dump ended with error (set phase)  => MapperParsingException[Analyzer [title_analyzer] not found for field [analyzed_title]]
```

**Comment by evantahler** [comment]
Can you dump the mapping to a file and share what the contents are?

**Comment by evantahler** [comment]
I'm guessing you probably have an analyzer plugin on your source which isn't installed in your destination.

**Comment by evantahler** [comment]
closing due to lack of response
