### ISSUE TITLE
dump ended with error (set phase)  => Error: connect EADDRNOTAVAIL

### ISSUE THREAD

**Issue by HenleyChiu** [taskrabbit/elasticsearch-dump#98]
One of my dumps ended with this error:
dump ended with error (set phase)  => Error: connect EADDRNOTAVAIL

It was successfully writing for a minute before this error happened:

Thu, 23 Jul 2015 21:51:02 GMT | got 120 objects from source elasticsearch (offset: 45600)
Thu, 23 Jul 2015 21:51:03 GMT | sent 120 objects to destination elasticsearch, wrote 120
Thu, 23 Jul 2015 21:51:03 GMT | got 120 objects from source elasticsearch (offset: 45720)
Thu, 23 Jul 2015 21:51:04 GMT | sent 120 objects to destination elasticsearch, wrote 120
Thu, 23 Jul 2015 21:51:04 GMT | got 120 objects from source elasticsearch (offset: 45840)
Thu, 23 Jul 2015 21:51:04 GMT | sent 120 objects to destination elasticsearch, wrote 120
Thu, 23 Jul 2015 21:51:04 GMT | got 120 objects from source elasticsearch (offset: 45960)
Thu, 23 Jul 2015 21:51:04 GMT | Error Emitted => connect EADDRNOTAVAIL
Thu, 23 Jul 2015 21:51:04 GMT | dump ended with error (set phase)  => Error: connect EADDRNOTAVAIL
Thu, 23 Jul 2015 21:51:04 GMT | Total Writes: 45960

**Comment by evantahler** [comment]
This is a sign that the computer you are running elasticdump on cannot reach the cluster.  Perhaps bad networking, timeouts, internet outages, etc. Closing, as this is not an elsticdump issue.

**Comment by jmacleod** [comment]
Hey,

I just wanted to say I ran into this same issue and my machines had no problem talking to each other otherwise via elasticsearch.  They were right next to each other on the same network and like the original poster's description it was working for a few minutes before it stopped with the EADDRNOTAVAIL error.

I did some googling about for other people with the same issue and someone mentioned that all of my sockets might be getting used up.  I checked by running netstat and I could see the sockets in the TIME_WAIT state to localhost:9200 just exploding (>30k) as this ran and as soon as it stopped running they would drop back down to a sane number (< 300).

So I did some more research and since I am running linux I was able to just do:
cat /proc/sys/net/ipv4/tcp_tw_recycle
0
cat /proc/sys/net/ipv4/tcp_tw_reuse
0

echo 1 | sudo tee /proc/sys/net/ipv4/tcp_tw_recycle
echo 1 | sudo tee /proc/sys/net/ipv4/tcp_tw_reuse

cat /proc/sys/net/ipv4/tcp_tw_recycle
1
cat /proc/sys/net/ipv4/tcp_tw_reuse
1

This makes it so linux will take those sockets in the TIME_WAIT state an reuse them.  After that it worked like a charm.  

So even though I agree that this is not a problem with the elasticdump app, I think the aggressive way it uses sockets (maybe it is a node thing, I have no idea), can lead to this issue if your system can't quickly reuse the sockets. 

Just a little more info in case someone else doesn't have any other connection issues but is getting the same error.

Thanks.
Jared

**Comment by evantahler** [comment]
good debugging! 

While we only make one "request" at a time (we don't do any parallel loading with this tool so you can debug errors; and so you don't overload your cluster), node will "keep" sockets for a while after using them.

The default number of sockets the node process would open has changed between node versions.  It used to be 5 (node v0.8 I think) and is now `Infinity`.

You can modify this:
```
    http.globalAgent.maxSockets  = 123;
    https.globalAgent.maxSockets = 123;
```

**Comment by sunyonggang** [comment]
it really works, when i change my node version from 0.10.30 to 4.2.2 on Mac, it showed me: 
```
dump ended with error (set phase)  => Error: connect ECONNRESET 127.0.0.1:9200
```
so I can rollback node.js to v0.10.38 or use v4.2.2 with '--maxSockets=5'

but here is another problem, when i tried to use elasticsearch-dump to recover my data to ES, it can't work well, it can't write data to ES
```
[sunyonggang@localhost ~/mygithub/elasticsearch-dump]$ bin/elasticdump --bulk=ture --input=/Users/sunyonggang/esdata/bank.json --output=http://localhost:9200
Wed, 06 Jan 2016 06:33:28 GMT | starting dump
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 0)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 100)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 200)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 300)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 400)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 500)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 600)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 700)
Wed, 06 Jan 2016 06:33:28 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:28 GMT | got 100 objects from source file (offset: 800)
Wed, 06 Jan 2016 06:33:29 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:29 GMT | got 100 objects from source file (offset: 900)
Wed, 06 Jan 2016 06:33:29 GMT | sent 100 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:29 GMT | got 0 objects from source file (offset: 1000)
Wed, 06 Jan 2016 06:33:29 GMT | sent 0 objects to destination elasticsearch, wrote 0
Wed, 06 Jan 2016 06:33:29 GMT | Total Writes: 0
Wed, 06 Jan 2016 06:33:29 GMT | dump complete
```
if I change to '--output=http://localhost:9200/another_index',  it can work, but the index have changed to 'another_index', my bank.json has its index named 'bank'.
if I want to use 'bank' as an index, so what could i do next?

**Comment by sunyonggang** [comment]
ooooH, i found it, it's my mistake that i should use 'true' in '--bulk' instead of 'ture', the useful command should be:
```
 bin/elasticdump --bulk=true --input=/Users/sunyonggang/esdata/bank.json --output=http://localhost:9200
```
**should be true not ture**
😂😓

**Comment by unandhagopal** [comment]
I am new to elasticsearch, while exploring the bulk JSON files to Elasticsearch index getting below error

nandha@localhost:~$ elasticdump \
> --bulk=true \
> --input="/home/nandha/Desktop/accountss.json" \
> --output=http://localhost:9200/scb
Mon, 30 Jan 2017 13:39:46 GMT | starting dump
Mon, 30 Jan 2017 13:39:46 GMT | got 100 objects from source file (offset: 0)
Mon, 30 Jan 2017 13:39:46 GMT | sent 100 objects to destination elasticsearch, wrote 0
Mon, 30 Jan 2017 13:39:46 GMT | got 74 objects from source file (offset: 100)
Mon, 30 Jan 2017 13:39:46 GMT | sent 74 objects to destination elasticsearch, wrote 0
Mon, 30 Jan 2017 13:39:46 GMT | got 0 objects from source file (offset: 174)
Mon, 30 Jan 2017 13:39:46 GMT | Total Writes: 0
Mon, 30 Jan 2017 13:39:46 GMT | dump complete

using elsticdump to do this activity
Question
a) how could i can make sure the data got loaded into elasticsearch? (any specific command being used)
b) if not, what is the problem which the data is not loaded into elasticsearch
c) version used ;(you guys reference)
Desktop    elasticsearch-5.1.2.deb    Elasticsearch-Document~  kibana-5.1.2-linux-x86_64         Music     Templates

**Comment by kirantlr** [comment]
@unandhagopal ,
check if index created or not --> curl 'http://localhost:9200/_cat/indices?v'
You may need to set the parameter (--type=data) along with --input and --output

**Comment by naveen0314** [comment]
Hi, I have the same issue even after adding --type=data 

Elastic version :6.6.2
Easticdump version:2.2.0

 elasticdump --input=http://localhost:9200/sourceindex --output=http://nitels.com:9200/drindex --type=data -H 'Content-Type: application/json'
Tue, 26 Mar 2019 20:46:19 GMT | starting dump
Tue, 26 Mar 2019 20:46:19 GMT | Error Emitted => {"error":"Content-Type header [] is not supported","status":406}
Tue, 26 Mar 2019 20:46:19 GMT | Total Writes: 0
Tue, 26 Mar 2019 20:46:19 GMT | dump ended with error (get phase) => Error: {"error":"Content-Type header [] is not supported","status":406}

**Comment by ferronrsmith** [comment]
@naveen0314 versions lower that 3.x.x does not support ES 6.x
