### ISSUE TITLE
Cannot find imported data

### ISSUE THREAD

**Issue by krutchm** [taskrabbit/elasticsearch-dump#99]
I'm tying to use elasticdump to reindex data. So I set up mapping for test/type1 and reindex:

```
./bin/elasticdump --input=http://localhost:9200/supy/data --output=http://localhost:9200/test/type1 --type=data --bulk=true --limit 10000 --bulk-use-output-index-name=true 

starting dump
got 1098 objects from source elasticsearch (offset: 0)
sent 1098 objects to destination elasticsearch, wrote 1098
got 0 objects from source elasticsearch (offset: 1098) 
sent 0 objects to destination elasticsearch, wrote 0
dump complete
 Total Writes: 1098 
```

but then resulting index is empty

`get test/type1/_search `
```
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   }
}
```
if I not specify existing type (which I need to define mapping) all works.

**Comment by evantahler** [comment]
You are using a combination of options that confuse things.  Your GET is for a specific type, not an index.   In this query you are asking fox bulk data, and saying to use the existing index.   The tool probably tried to write to a new index called 'supy/data', which already exists, so you just overwrote existing data.  You can confirm this with document version.

If you need to export only a certain type of object, use `--searchBody`

**Comment by krutchm** [comment]
Sorry, I see that you didn't note options of command (you need to scroll my original message to the right):
--type=data --bulk=true --limit 10000 --bulk-use-output-index-name=true
last one specified to use destination index and type.
So it is not clear from your answer what does mean "The tool probably tried to write to a new index called 'supy/data'" since this is input. Why does it try to write to input?  I want it to write to /test/type1 which is output. As you advised I checked document version of source which is the same.
Trying to figure out answer through the code.

**Comment by evantahler** [comment]
Basically you can't just ask for a type of object, this tool works on entire `indexes`.
